Veins: veins::SimpleObstacleShadowing Class Reference
veins::SimpleObstacleShadowing Class Reference
Basic implementation of a SimpleObstacleShadowing.
#include <SimpleObstacleShadowing.h>
Public Member Functions
SimpleObstacleShadowing (cComponent *owner, ObstacleControl &obstacleControl, bool useTorus, const Coord &playgroundSize)
Initializes the analogue model.
void filterSignal (Signal *signal) override
Filters a specified Signal by adding an attenuation over time to the Signal.
bool neverIncreasesPower () override
If the model never increases the power level of any signal given to filterSignal, it returns true here.
Public Member Functions inherited from veins::AnalogueModel
AnalogueModel (cComponent *owner)
virtual ~AnalogueModel ()
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Attributes
ObstacleControl & obstacleControl
reference to global ObstacleControl instance
const bool useTorus
Information needed about the playground.
const Coord & playgroundSize
The size of the playground.
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Basic implementation of a SimpleObstacleShadowing.
Definition at line 45 of file SimpleObstacleShadowing.h.
Constructor & Destructor Documentation
SimpleObstacleShadowing()
SimpleObstacleShadowing::SimpleObstacleShadowing (cComponent * owner, ObstacleControl & obstacleControl, bool useTorus, const Coord & playgroundSize)
Initializes the analogue model.
myMove and playgroundSize need to be valid as long as this instance exists.
The constructor needs some specific knowledge in order to create its mapping properly:
Parameters
owner pointer to the cComponent that owns this AnalogueModel
obstacleControl the parent module
useTorus information about the playground the host is moving in
playgroundSize information about the playground the host is moving in
Definition at line 29 of file SimpleObstacleShadowing.cc.
     : AnalogueModel(owner)
     , obstacleControl(obstacleControl)
     , useTorus(useTorus)
     , playgroundSize(playgroundSize)
 {
     if (useTorus) throw cRuntimeError("SimpleObstacleShadowing does not work on torus-shaped playgrounds");
 }
References useTorus.
Member Function Documentation
filterSignal()
void SimpleObstacleShadowing::filterSignal (Signal * signal) override virtual
Filters a specified Signal by adding an attenuation over time to the Signal.
Implements veins::AnalogueModel.
Definition at line 38 of file SimpleObstacleShadowing.cc.
 {
     auto senderPos = signal->getSenderPoa().pos.getPositionAt();
     auto receiverPos = signal->getReceiverPoa().pos.getPositionAt();
     double factor = obstacleControl.calculateAttenuation(senderPos, receiverPos);
     EV_TRACE << "value is: " << factor << endl;
     *signal *= factor;
 }
References veins::ObstacleControl::calculateAttenuation(), veins::AntennaPosition::getPositionAt(), veins::Signal::getReceiverPoa(), veins::Signal::getSenderPoa(), obstacleControl, and veins::POA::pos.
neverIncreasesPower()
bool veins::SimpleObstacleShadowing::neverIncreasesPower () inline override virtual
If the model never increases the power level of any signal given to filterSignal, it returns true here.
This allows optimized signal handling.
Reimplemented from veins::AnalogueModel.
Definition at line 77 of file SimpleObstacleShadowing.h.
     {
         return true;
     }
Member Data Documentation
obstacleControl
ObstacleControl& veins::SimpleObstacleShadowing::obstacleControl protected
reference to global ObstacleControl instance
Definition at line 48 of file SimpleObstacleShadowing.h.
Referenced by filterSignal().
playgroundSize
const Coord& veins::SimpleObstacleShadowing::playgroundSize protected
The size of the playground.
Definition at line 54 of file SimpleObstacleShadowing.h.
useTorus
const bool veins::SimpleObstacleShadowing::useTorus protected
Information needed about the playground.
Definition at line 51 of file SimpleObstacleShadowing.h.
Referenced by SimpleObstacleShadowing().
The documentation for this class was generated from the following files:
SimpleObstacleShadowing.h
SimpleObstacleShadowing.cc