Veins: veins::DemoBaseApplLayer Class Reference
veins::DemoBaseApplLayer Class Reference
Demo application layer base class.
#include <DemoBaseApplLayer.h>
Public Types
enum DemoApplMessageKinds { SEND_BEACON_EVT , SEND_WSA_EVT }
Public Types inherited from veins::BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Public Member Functions
~DemoBaseApplLayer () override
void initialize (int stage) override
void finish () override
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Public Member Functions inherited from veins::BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
void initialize (int) override
Initialization of the module and some variables.
Public Member Functions inherited from veins::BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
void handleLowerMsg (cMessage *msg) override
handle messages from below and calls the onWSM, onBSM, and onWSA functions accordingly
void handleSelfMsg (cMessage *msg) override
handle self messages
virtual void populateWSM (BaseFrame1609_4 *wsm, LAddress::L2Type rcvId=LAddress::L2BROADCAST(), int serial=0)
sets all the necessary fields in the WSM, BSM, or WSA.
virtual void onWSM (BaseFrame1609_4 *wsm)
this function is called upon receiving a BaseFrame1609_4
virtual void onBSM (DemoSafetyMessage *bsm)
this function is called upon receiving a DemoSafetyMessage, also referred to as a beacon
virtual void onWSA (DemoServiceAdvertisment *wsa)
this function is called upon receiving a DemoServiceAdvertisement
virtual void handlePositionUpdate (cObject *obj)
this function is called every time the vehicle receives a position update signal
virtual void handleParkingUpdate (cObject *obj)
this function is called every time the vehicle parks or starts moving again
virtual void startService (Channel channel, int serviceId, std::string serviceDescription)
This will start the periodic advertising of the new service on the CCH.
virtual void stopService ()
stopping the service and advertising for it
virtual simtime_t computeAsynchronousSendingTime (simtime_t interval, ChannelType chantype)
compute a point in time that is guaranteed to be in the correct channel interval plus a random offset
virtual void sendDown (cMessage *msg)
overloaded for error handling and stats recording purposes
virtual void sendDelayedDown (cMessage *msg, simtime_t delay)
overloaded for error handling and stats recording purposes
virtual void checkAndTrackPacket (cMessage *msg)
helper function for error handling and stats recording purposes
Protected Member Functions inherited from veins::BaseApplLayer
void handleLowerControl (cMessage *msg) override
Handle control messages from lower layer.
void handleUpperMsg (cMessage *msg) override
Handle messages from upper layer.
void handleUpperControl (cMessage *msg) override
Handle control messages from upper layer.
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
Protected Member Functions inherited from veins::BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
TraCIMobility * mobility
TraCICommandInterface * traci
TraCICommandInterface::Vehicle * traciVehicle
AnnotationManager * annotations
DemoBaseApplLayerToMac1609_4Interface * mac
bool isParked
uint32_t beaconLengthBits
uint32_t beaconUserPriority
simtime_t beaconInterval
bool sendBeacons
uint32_t dataLengthBits
uint32_t dataUserPriority
bool dataOnSch
int currentOfferedServiceId
std::string currentServiceDescription
Channel currentServiceChannel
simtime_t wsaInterval
Coord curPosition
Coord curSpeed
LAddress::L2Type myId = 0
int mySCH
uint32_t generatedWSMs
uint32_t generatedWSAs
uint32_t generatedBSMs
uint32_t receivedWSMs
uint32_t receivedWSAs
uint32_t receivedBSMs
cMessage * sendBeaconEvt
cMessage * sendWSAEvt
Protected Attributes inherited from veins::BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from veins::BaseLayer
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
PassedMessage * passedMsg
The last message passed through this layer.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Public Attributes inherited from veins::BaseLayer
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Demo application layer base class.
Author
David Eckhoff
See also
DemoBaseApplLayer
Mac1609_4
PhyLayer80211p
Decider80211p
Definition at line 58 of file DemoBaseApplLayer.h.
Member Enumeration Documentation
DemoApplMessageKinds
enum veins::DemoBaseApplLayer::DemoApplMessageKinds
Enumerator
SEND_BEACON_EVT
SEND_WSA_EVT
Definition at line 67 of file DemoBaseApplLayer.h.
{
         SEND_BEACON_EVT,
         SEND_WSA_EVT
     };
Constructor & Destructor Documentation
~DemoBaseApplLayer()
DemoBaseApplLayer::~DemoBaseApplLayer () override
Definition at line 264 of file DemoBaseApplLayer.cc.
 {
     cancelAndDelete(sendBeaconEvt);
     cancelAndDelete(sendWSAEvt);
     findHost()->unsubscribe(BaseMobility::mobilityStateChangedSignal, this);
 }
References veins::BaseModule::findHost(), veins::BaseMobility::mobilityStateChangedSignal, sendBeaconEvt, and sendWSAEvt.
Member Function Documentation
checkAndTrackPacket()
void DemoBaseApplLayer::checkAndTrackPacket (cMessage * msg) protected virtual
helper function for error handling and stats recording purposes
Parameters
msg the message to be checked and tracked
Definition at line 304 of file DemoBaseApplLayer.cc.
 {
     if (dynamic_cast<DemoSafetyMessage*>(msg)) {
         EV_TRACE << "sending down a BSM" << std::endl;
         generatedBSMs++;
     }
     else if (dynamic_cast<DemoServiceAdvertisment*>(msg)) {
         EV_TRACE << "sending down a WSA" << std::endl;
         generatedWSAs++;
     }
     else if (dynamic_cast<BaseFrame1609_4*>(msg)) {
         EV_TRACE << "sending down a wsm" << std::endl;
         generatedWSMs++;
     }
 }
References generatedBSMs, generatedWSAs, and generatedWSMs.
Referenced by sendDelayedDown(), and sendDown().
computeAsynchronousSendingTime()
simtime_t DemoBaseApplLayer::computeAsynchronousSendingTime (simtime_t interval, ChannelType chantype) protected virtual
compute a point in time that is guaranteed to be in the correct channel interval plus a random offset
Parameters
interval the interval length of the periodic message
chantype the type of channel, either type_CCH or type_SCH
Definition at line 112 of file DemoBaseApplLayer.cc.
 {
     /*
      * avoid that periodic messages for one channel type are scheduled in the other channel interval
      * when alternate access is enabled in the MAC
      */
     simtime_t randomOffset = dblrand() * interval;
     simtime_t firstEvent;
     simtime_t switchingInterval = mac->getSwitchingInterval(); // usually 0.050s
     simtime_t nextCCH;
     /*
      * start event earliest in next CCH (or SCH) interval. For alignment, first find the next CCH interval
      * To find out next CCH, go back to start of current interval and add two or one intervals
      * depending on type of current interval
      */
     if (mac->isCurrentChannelCCH()) {
         nextCCH = simTime() - SimTime().setRaw(simTime().raw() % switchingInterval.raw()) + switchingInterval * 2;
     }
     else {
         nextCCH = simTime() - SimTime().setRaw(simTime().raw() % switchingInterval.raw()) + switchingInterval;
     }
     firstEvent = nextCCH + randomOffset;
     // check if firstEvent lies within the correct interval and, if not, move to previous interval
     if (firstEvent.raw() % (2 * switchingInterval.raw()) > switchingInterval.raw()) {
         // firstEvent is within a sch interval
         if (chan == ChannelType::control) firstEvent -= switchingInterval;
     }
     else {
         // firstEvent is within a cch interval, so adjust for SCH messages
         if (chan == ChannelType::service) firstEvent += switchingInterval;
     }
     return firstEvent;
 }
References veins::control, veins::DemoBaseApplLayerToMac1609_4Interface::getSwitchingInterval(), veins::DemoBaseApplLayerToMac1609_4Interface::isCurrentChannelCCH(), mac, and veins::service.
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), initialize(), and startService().
finish()
void DemoBaseApplLayer::finish () override
Definition at line 252 of file DemoBaseApplLayer.cc.
 {
     recordScalar("generatedWSMs", generatedWSMs);
     recordScalar("receivedWSMs", receivedWSMs);
     recordScalar("generatedBSMs", generatedBSMs);
     recordScalar("receivedBSMs", receivedBSMs);
     recordScalar("generatedWSAs", generatedWSAs);
     recordScalar("receivedWSAs", receivedWSAs);
 }
References generatedBSMs, generatedWSAs, generatedWSMs, receivedBSMs, receivedWSAs, and receivedWSMs.
Referenced by veins::MyVeinsApp::finish().
handleLowerMsg()
void DemoBaseApplLayer::handleLowerMsg (cMessage * msg) override protected virtual
handle messages from below and calls the onWSM, onBSM, and onWSA functions accordingly
Reimplemented from veins::BaseApplLayer.
Definition at line 206 of file DemoBaseApplLayer.cc.
 {
     BaseFrame1609_4* wsm = dynamic_cast<BaseFrame1609_4*>(msg);
     ASSERT(wsm);
     if (DemoSafetyMessage* bsm = dynamic_cast<DemoSafetyMessage*>(wsm)) {
         receivedBSMs++;
         onBSM(bsm);
     }
     else if (DemoServiceAdvertisment* wsa = dynamic_cast<DemoServiceAdvertisment*>(wsm)) {
         receivedWSAs++;
         onWSA(wsa);
     }
     else {
         receivedWSMs++;
         onWSM(wsm);
     }
     delete (msg);
 }
References onBSM(), onWSA(), onWSM(), receivedBSMs, receivedWSAs, and receivedWSMs.
handleParkingUpdate()
void DemoBaseApplLayer::handleParkingUpdate (cObject * obj) protected virtual
this function is called every time the vehicle parks or starts moving again
Definition at line 201 of file DemoBaseApplLayer.cc.
 {
     isParked = mobility->getParkingState();
 }
References veins::TraCIMobility::getParkingState(), isParked, and mobility.
Referenced by receiveSignal().
handlePositionUpdate()
void DemoBaseApplLayer::handlePositionUpdate (cObject * obj) protected virtual
this function is called every time the vehicle receives a position update signal
Reimplemented in veins::TraCIDemo11p, and veins::MyVeinsApp.
Definition at line 194 of file DemoBaseApplLayer.cc.
 {
     ChannelMobilityPtrType const mobility = check_and_cast<ChannelMobilityPtrType>(obj);
     curPosition = mobility->getPositionAt(simTime());
     curSpeed = mobility->getCurrentSpeed();
 }
References curPosition, curSpeed, veins::TraCIMobility::getCurrentSpeed(), veins::BaseMobility::getPositionAt(), and mobility.
Referenced by veins::MyVeinsApp::handlePositionUpdate(), veins::TraCIDemo11p::handlePositionUpdate(), and receiveSignal().
handleSelfMsg()
void DemoBaseApplLayer::handleSelfMsg (cMessage * msg) override protected virtual
handle self messages
Reimplemented from veins::BaseApplLayer.
Reimplemented in veins::TraCIDemo11p, and veins::MyVeinsApp.
Definition at line 228 of file DemoBaseApplLayer.cc.
 {
     switch (msg->getKind()) {
     case SEND_BEACON_EVT: {
         DemoSafetyMessage* bsm = new DemoSafetyMessage();
         populateWSM(bsm);
         sendDown(bsm);
         scheduleAt(simTime() + beaconInterval, sendBeaconEvt);
         break;
     }
     case SEND_WSA_EVT: {
         DemoServiceAdvertisment* wsa = new DemoServiceAdvertisment();
         populateWSM(wsa);
         sendDown(wsa);
         scheduleAt(simTime() + wsaInterval, sendWSAEvt);
         break;
     }
     default: {
         if (msg) EV_WARN << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
         break;
     }
     }
 }
References beaconInterval, populateWSM(), SEND_BEACON_EVT, SEND_WSA_EVT, sendBeaconEvt, sendDown(), sendWSAEvt, and wsaInterval.
Referenced by veins::MyVeinsApp::handleSelfMsg(), and veins::TraCIDemo11p::handleSelfMsg().
initialize()
void DemoBaseApplLayer::initialize (int stage) override
Definition at line 27 of file DemoBaseApplLayer.cc.
 {
     BaseApplLayer::initialize(stage);
     if (stage == 0) {
         // initialize pointers to other modules
         if (FindModule<TraCIMobility*>::findSubModule(getParentModule())) {
             mobility = TraCIMobilityAccess().get(getParentModule());
             traci = mobility->getCommandInterface();
             traciVehicle = mobility->getVehicleCommandInterface();
         }
         else {
             traci = nullptr;
             mobility = nullptr;
             traciVehicle = nullptr;
         }
         annotations = AnnotationManagerAccess().getIfExists();
         ASSERT(annotations);
         mac = FindModule<DemoBaseApplLayerToMac1609_4Interface*>::findSubModule(getParentModule());
         ASSERT(mac);
         // read parameters
         headerLength = par("headerLength");
         sendBeacons = par("sendBeacons").boolValue();
         beaconLengthBits = par("beaconLengthBits");
         beaconUserPriority = par("beaconUserPriority");
         beaconInterval = par("beaconInterval");
         dataLengthBits = par("dataLengthBits");
         dataOnSch = par("dataOnSch").boolValue();
         dataUserPriority = par("dataUserPriority");
         wsaInterval = par("wsaInterval").doubleValue();
         currentOfferedServiceId = -1;
         isParked = false;
         findHost()->subscribe(BaseMobility::mobilityStateChangedSignal, this);
         findHost()->subscribe(TraCIMobility::parkingStateChangedSignal, this);
         sendBeaconEvt = new cMessage("beacon evt", SEND_BEACON_EVT);
         sendWSAEvt = new cMessage("wsa evt", SEND_WSA_EVT);
         generatedBSMs = 0;
         generatedWSAs = 0;
         generatedWSMs = 0;
         receivedBSMs = 0;
         receivedWSAs = 0;
         receivedWSMs = 0;
     }
     else if (stage == 1) {
         // store MAC address for quick access
         myId = mac->getMACAddress();
         // simulate asynchronous channel access
         if (dataOnSch == true && !mac->isChannelSwitchingActive()) {
             dataOnSch = false;
             EV_ERROR << "App wants to send data on SCH but MAC doesn't use any SCH. Sending all data on CCH" << std::endl;
         }
         simtime_t firstBeacon = simTime();
         if (par("avoidBeaconSynchronization").boolValue() == true) {
             simtime_t randomOffset = dblrand() * beaconInterval;
             firstBeacon = simTime() + randomOffset;
             if (mac->isChannelSwitchingActive() == true) {
                 if (beaconInterval.raw() % (mac->getSwitchingInterval().raw() * 2)) {
                     EV_ERROR << "The beacon interval (" << beaconInterval << ") is smaller than or not a multiple of  one synchronization interval (" << 2 * mac->getSwitchingInterval() << "). This means that beacons are generated during SCH intervals" << std::endl;
                 }
                 firstBeacon = computeAsynchronousSendingTime(beaconInterval, ChannelType::control);
             }
             if (sendBeacons) {
                 scheduleAt(firstBeacon, sendBeaconEvt);
             }
         }
     }
 }
References annotations, beaconInterval, beaconLengthBits, beaconUserPriority, computeAsynchronousSendingTime(), veins::control, currentOfferedServiceId, dataLengthBits, dataOnSch, dataUserPriority, veins::BaseModule::findHost(), veins::FindModule< T >::findSubModule(), generatedBSMs, generatedWSAs, generatedWSMs, veins::TraCIMobilityAccess::get(), veins::TraCIMobility::getCommandInterface(), veins::AnnotationManagerAccess::getIfExists(), veins::DemoBaseApplLayerToMac1609_4Interface::getMACAddress(), veins::DemoBaseApplLayerToMac1609_4Interface::getSwitchingInterval(), veins::TraCIMobility::getVehicleCommandInterface(), veins::BaseApplLayer::headerLength, veins::BaseApplLayer::initialize(), veins::DemoBaseApplLayerToMac1609_4Interface::isChannelSwitchingActive(), isParked, mac, mobility, veins::BaseMobility::mobilityStateChangedSignal, myId, veins::TraCIMobility::parkingStateChangedSignal, receivedBSMs, receivedWSAs, receivedWSMs, SEND_BEACON_EVT, SEND_WSA_EVT, sendBeaconEvt, sendBeacons, sendWSAEvt, traci, traciVehicle, and wsaInterval.
Referenced by veins::MyVeinsApp::initialize(), and veins::TraCIDemo11p::initialize().
onBSM()
virtual void veins::DemoBaseApplLayer::onBSM (DemoSafetyMessage * bsm) inline protected virtual
this function is called upon receiving a DemoSafetyMessage, also referred to as a beacon
Reimplemented in veins::MyVeinsApp.
Definition at line 86 of file DemoBaseApplLayer.h.
 {};
Referenced by handleLowerMsg().
onWSA()
virtual void veins::DemoBaseApplLayer::onWSA (DemoServiceAdvertisment * wsa) inline protected virtual
this function is called upon receiving a DemoServiceAdvertisement
Reimplemented in veins::TraCIDemoRSU11p, veins::TraCIDemo11p, and veins::MyVeinsApp.
Definition at line 89 of file DemoBaseApplLayer.h.
 {};
Referenced by handleLowerMsg().
onWSM()
virtual void veins::DemoBaseApplLayer::onWSM (BaseFrame1609_4 * wsm) inline protected virtual
this function is called upon receiving a BaseFrame1609_4
Reimplemented in veins::TraCIDemoRSU11p, veins::TraCIDemo11p, and veins::MyVeinsApp.
Definition at line 83 of file DemoBaseApplLayer.h.
 {};
Referenced by handleLowerMsg().
populateWSM()
void DemoBaseApplLayer::populateWSM (BaseFrame1609_4 * wsm, LAddress::L2Type rcvId = LAddress::L2BROADCAST(), int serial = 0) protected virtual
sets all the necessary fields in the WSM, BSM, or WSA.
Definition at line 154 of file DemoBaseApplLayer.cc.
 {
     wsm->setRecipientAddress(rcvId);
     wsm->setBitLength(headerLength);
     if (DemoSafetyMessage* bsm = dynamic_cast<DemoSafetyMessage*>(wsm)) {
         bsm->setSenderPos(curPosition);
         bsm->setSenderSpeed(curSpeed);
         bsm->setPsid(-1);
         bsm->setChannelNumber(static_cast<int>(Channel::cch));
         bsm->addBitLength(beaconLengthBits);
         wsm->setUserPriority(beaconUserPriority);
     }
     else if (DemoServiceAdvertisment* wsa = dynamic_cast<DemoServiceAdvertisment*>(wsm)) {
         wsa->setChannelNumber(static_cast<int>(Channel::cch));
         wsa->setTargetChannel(static_cast<int>(currentServiceChannel));
         wsa->setPsid(currentOfferedServiceId);
         wsa->setServiceDescription(currentServiceDescription.c_str());
     }
     else {
         if (dataOnSch)
             wsm->setChannelNumber(static_cast<int>(Channel::sch1)); // will be rewritten at Mac1609_4 to actual Service Channel. This is just so no controlInfo is needed
         else
             wsm->setChannelNumber(static_cast<int>(Channel::cch));
         wsm->addBitLength(dataLengthBits);
         wsm->setUserPriority(dataUserPriority);
     }
 }
References beaconLengthBits, beaconUserPriority, veins::cch, curPosition, currentOfferedServiceId, currentServiceChannel, currentServiceDescription, curSpeed, dataLengthBits, dataOnSch, dataUserPriority, veins::BaseApplLayer::headerLength, and veins::sch1.
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), and handleSelfMsg().
receiveSignal()
void DemoBaseApplLayer::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override
Definition at line 183 of file DemoBaseApplLayer.cc.
 {
     Enter_Method_Silent();
     if (signalID == BaseMobility::mobilityStateChangedSignal) {
         handlePositionUpdate(obj);
     }
     else if (signalID == TraCIMobility::parkingStateChangedSignal) {
         handleParkingUpdate(obj);
     }
 }
References handleParkingUpdate(), handlePositionUpdate(), veins::BaseMobility::mobilityStateChangedSignal, and veins::TraCIMobility::parkingStateChangedSignal.
sendDelayedDown()
void DemoBaseApplLayer::sendDelayedDown (cMessage * msg, simtime_t delay) protected virtual
overloaded for error handling and stats recording purposes
Parameters
msg the message to be sent. Must be a WSM/BSM/WSA
delay the delay for the message
Definition at line 298 of file DemoBaseApplLayer.cc.
 {
     checkAndTrackPacket(msg);
     BaseApplLayer::sendDelayedDown(msg, delay);
 }
References checkAndTrackPacket(), and veins::BaseApplLayer::sendDelayedDown().
Referenced by veins::TraCIDemoRSU11p::onWSM().
sendDown()
void DemoBaseApplLayer::sendDown (cMessage * msg) protected virtual
overloaded for error handling and stats recording purposes
Parameters
msg the message to be sent. Must be a WSM/BSM/WSA
Definition at line 292 of file DemoBaseApplLayer.cc.
 {
     checkAndTrackPacket(msg);
     BaseApplLayer::sendDown(msg);
 }
References checkAndTrackPacket(), and veins::BaseLayer::sendDown().
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), handleSelfMsg(), and veins::TraCIDemo11p::handleSelfMsg().
startService()
void DemoBaseApplLayer::startService (Channel channel, int serviceId, std::string serviceDescription) protected virtual
This will start the periodic advertising of the new service on the CCH.
Parameters
channel the channel on which the service is provided
serviceId a service ID to be used with the service
serviceDescription a literal description of the service
Definition at line 271 of file DemoBaseApplLayer.cc.
 {
     if (sendWSAEvt->isScheduled()) {
         throw cRuntimeError("Starting service although another service was already started");
     }
     mac->changeServiceChannel(channel);
     currentOfferedServiceId = serviceId;
     currentServiceChannel = channel;
     currentServiceDescription = serviceDescription;
     simtime_t wsaTime = computeAsynchronousSendingTime(wsaInterval, ChannelType::control);
     scheduleAt(wsaTime, sendWSAEvt);
 }
References veins::DemoBaseApplLayerToMac1609_4Interface::changeServiceChannel(), computeAsynchronousSendingTime(), veins::control, currentOfferedServiceId, currentServiceChannel, currentServiceDescription, mac, sendWSAEvt, and wsaInterval.
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), and veins::TraCIDemo11p::onWSA().
stopService()
void DemoBaseApplLayer::stopService () protected virtual
stopping the service and advertising for it
Definition at line 286 of file DemoBaseApplLayer.cc.
 {
     cancelEvent(sendWSAEvt);
     currentOfferedServiceId = -1;
 }
References currentOfferedServiceId, and sendWSAEvt.
Referenced by veins::TraCIDemo11p::handleSelfMsg(), and veins::TraCIDemo11p::onWSA().
Member Data Documentation
annotations
AnnotationManager* veins::DemoBaseApplLayer::annotations protected
Definition at line 143 of file DemoBaseApplLayer.h.
Referenced by initialize().
beaconInterval
simtime_t veins::DemoBaseApplLayer::beaconInterval protected
Definition at line 152 of file DemoBaseApplLayer.h.
Referenced by handleSelfMsg(), and initialize().
beaconLengthBits
uint32_t veins::DemoBaseApplLayer::beaconLengthBits protected
Definition at line 150 of file DemoBaseApplLayer.h.
Referenced by initialize(), and populateWSM().
beaconUserPriority
uint32_t veins::DemoBaseApplLayer::beaconUserPriority protected
Definition at line 151 of file DemoBaseApplLayer.h.
Referenced by initialize(), and populateWSM().
curPosition
Coord veins::DemoBaseApplLayer::curPosition protected
Definition at line 167 of file DemoBaseApplLayer.h.
Referenced by handlePositionUpdate(), and populateWSM().
currentOfferedServiceId
int veins::DemoBaseApplLayer::currentOfferedServiceId protected
Definition at line 161 of file DemoBaseApplLayer.h.
Referenced by initialize(), veins::TraCIDemo11p::onWSA(), populateWSM(), startService(), and stopService().
currentServiceChannel
Channel veins::DemoBaseApplLayer::currentServiceChannel protected
Definition at line 163 of file DemoBaseApplLayer.h.
Referenced by populateWSM(), and startService().
currentServiceDescription
std::string veins::DemoBaseApplLayer::currentServiceDescription protected
Definition at line 162 of file DemoBaseApplLayer.h.
Referenced by populateWSM(), and startService().
curSpeed
Coord veins::DemoBaseApplLayer::curSpeed protected
Definition at line 168 of file DemoBaseApplLayer.h.
Referenced by handlePositionUpdate(), and populateWSM().
dataLengthBits
uint32_t veins::DemoBaseApplLayer::dataLengthBits protected
Definition at line 156 of file DemoBaseApplLayer.h.
Referenced by initialize(), and populateWSM().
dataOnSch
bool veins::DemoBaseApplLayer::dataOnSch protected
Definition at line 158 of file DemoBaseApplLayer.h.
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), initialize(), and populateWSM().
dataUserPriority
uint32_t veins::DemoBaseApplLayer::dataUserPriority protected
Definition at line 157 of file DemoBaseApplLayer.h.
Referenced by initialize(), and populateWSM().
generatedBSMs
uint32_t veins::DemoBaseApplLayer::generatedBSMs protected
Definition at line 175 of file DemoBaseApplLayer.h.
Referenced by checkAndTrackPacket(), finish(), and initialize().
generatedWSAs
uint32_t veins::DemoBaseApplLayer::generatedWSAs protected
Definition at line 174 of file DemoBaseApplLayer.h.
Referenced by checkAndTrackPacket(), finish(), and initialize().
generatedWSMs
uint32_t veins::DemoBaseApplLayer::generatedWSMs protected
Definition at line 173 of file DemoBaseApplLayer.h.
Referenced by checkAndTrackPacket(), finish(), and initialize().
isParked
bool veins::DemoBaseApplLayer::isParked protected
Definition at line 147 of file DemoBaseApplLayer.h.
Referenced by handleParkingUpdate(), and initialize().
mac
DemoBaseApplLayerToMac1609_4Interface* veins::DemoBaseApplLayer::mac protected
Definition at line 144 of file DemoBaseApplLayer.h.
Referenced by computeAsynchronousSendingTime(), initialize(), veins::TraCIDemo11p::onWSA(), veins::TraCIDemoRSU11p::onWSA(), and startService().
mobility
TraCIMobility* veins::DemoBaseApplLayer::mobility protected
Definition at line 139 of file DemoBaseApplLayer.h.
Referenced by handleParkingUpdate(), handlePositionUpdate(), veins::TraCIDemo11p::handlePositionUpdate(), initialize(), and veins::TraCIDemo11p::onWSM().
myId
LAddress::L2Type veins::DemoBaseApplLayer::myId = 0 protected
Definition at line 169 of file DemoBaseApplLayer.h.
Referenced by initialize(), and veins::TraCIDemo11p::onWSM().
mySCH
int veins::DemoBaseApplLayer::mySCH protected
Definition at line 170 of file DemoBaseApplLayer.h.
receivedBSMs
uint32_t veins::DemoBaseApplLayer::receivedBSMs protected
Definition at line 178 of file DemoBaseApplLayer.h.
Referenced by finish(), handleLowerMsg(), and initialize().
receivedWSAs
uint32_t veins::DemoBaseApplLayer::receivedWSAs protected
Definition at line 177 of file DemoBaseApplLayer.h.
Referenced by finish(), handleLowerMsg(), and initialize().
receivedWSMs
uint32_t veins::DemoBaseApplLayer::receivedWSMs protected
Definition at line 176 of file DemoBaseApplLayer.h.
Referenced by finish(), handleLowerMsg(), and initialize().
sendBeaconEvt
cMessage* veins::DemoBaseApplLayer::sendBeaconEvt protected
Definition at line 181 of file DemoBaseApplLayer.h.
Referenced by handleSelfMsg(), initialize(), and ~DemoBaseApplLayer().
sendBeacons
bool veins::DemoBaseApplLayer::sendBeacons protected
Definition at line 153 of file DemoBaseApplLayer.h.
Referenced by initialize().
sendWSAEvt
cMessage* veins::DemoBaseApplLayer::sendWSAEvt protected
Definition at line 182 of file DemoBaseApplLayer.h.
Referenced by handleSelfMsg(), initialize(), startService(), stopService(), and ~DemoBaseApplLayer().
traci
TraCICommandInterface* veins::DemoBaseApplLayer::traci protected
Definition at line 140 of file DemoBaseApplLayer.h.
Referenced by initialize().
traciVehicle
TraCICommandInterface::Vehicle* veins::DemoBaseApplLayer::traciVehicle protected
Definition at line 141 of file DemoBaseApplLayer.h.
Referenced by initialize(), and veins::TraCIDemo11p::onWSM().
wsaInterval
simtime_t veins::DemoBaseApplLayer::wsaInterval protected
Definition at line 164 of file DemoBaseApplLayer.h.
Referenced by handleSelfMsg(), initialize(), and startService().
The documentation for this class was generated from the following files:
DemoBaseApplLayer.h
DemoBaseApplLayer.cc