Veins: veins::PhyToMacControlInfo Class Reference
veins::PhyToMacControlInfo Class Reference
Controlinfo for packets which are send from Physical layer to the MAC layer.
#include <PhyToMacControlInfo.h>
Public Member Functions
PhyToMacControlInfo (DeciderResult *result)
Initializes the PhyToMacControlInfo with the passed DeciderResult.
~PhyToMacControlInfo () override
Clean up the DeciderResult.
DeciderResult * getDeciderResult () const
Returns the result of the evaluation of the Decider.
void setSourceAddress (LAddress::L2Type sourceAddress)
Sets address of the packet's sender.
LAddress::L2Type getSourceAddress () const
Returns address of the packet's sender.
Static Public Member Functions
static cObject *const setControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult)
Attaches a "control info" structure (object) to the message pMsg.
static DeciderResult *const getDeciderResult (cMessage *const pMsg)
extracts the decider result from message "control info".
static DeciderResult *const getDeciderResultFromControlInfo (cObject *const pCtrlInfo)
extracts the decider result from message "control info".
Protected Attributes
DeciderResult * result
The result of the decider evaluation.
LAddress::L2Type sourceAddress
Detailed Description
Controlinfo for packets which are send from Physical layer to the MAC layer.
The ControlInfo contains the the DeciderResult of the Decider.
Definition at line 42 of file PhyToMacControlInfo.h.
Constructor & Destructor Documentation
PhyToMacControlInfo()
veins::PhyToMacControlInfo::PhyToMacControlInfo (DeciderResult * result) inline
Initializes the PhyToMacControlInfo with the passed DeciderResult.
NOTE: PhyToMacControlInfo takes ownership of the passed DeciderResult!
Definition at line 56 of file PhyToMacControlInfo.h.
         : result(result)
     {
     }
~PhyToMacControlInfo()
veins::PhyToMacControlInfo::~PhyToMacControlInfo () inline override
Clean up the DeciderResult.
Definition at line 64 of file PhyToMacControlInfo.h.
     {
         if (result) delete result;
     }
Member Function Documentation
getDeciderResult() [1/2]
DeciderResult* veins::PhyToMacControlInfo::getDeciderResult () const inline
Returns the result of the evaluation of the Decider.
Definition at line 72 of file PhyToMacControlInfo.h.
     {
         return result;
     }
Referenced by getDeciderResultFromControlInfo(), and veins::Mac1609_4::handleLowerMsg().
getDeciderResult() [2/2]
static DeciderResult* const veins::PhyToMacControlInfo::getDeciderResult (cMessage *const pMsg) inline static
extracts the decider result from message "control info".
Definition at line 116 of file PhyToMacControlInfo.h.
     {
         return getDeciderResultFromControlInfo(pMsg->getControlInfo());
     }
getDeciderResultFromControlInfo()
static DeciderResult* const veins::PhyToMacControlInfo::getDeciderResultFromControlInfo (cObject *const pCtrlInfo) inline static
extracts the decider result from message "control info".
Definition at line 123 of file PhyToMacControlInfo.h.
     {
         PhyToMacControlInfo* const cCtrlInfo = dynamic_cast<PhyToMacControlInfo* const>(pCtrlInfo);
         if (cCtrlInfo) return cCtrlInfo->getDeciderResult();
         return nullptr;
     }
References getDeciderResult().
getSourceAddress()
LAddress::L2Type veins::PhyToMacControlInfo::getSourceAddress () const inline
Returns address of the packet's sender.
Definition at line 88 of file PhyToMacControlInfo.h.
     {
         return sourceAddress;
     }
setControlInfo()
static cObject* const veins::PhyToMacControlInfo::setControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult) inline static
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the decider result.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pDeciderResult The decider results.
Definition at line 106 of file PhyToMacControlInfo.h.
     {
         PhyToMacControlInfo* const cCtrlInfo = new PhyToMacControlInfo(pDeciderResult);
         pMsg->setControlInfo(cCtrlInfo);
         return cCtrlInfo;
     }
Referenced by veins::BasePhyLayer::sendUp().
setSourceAddress()
void veins::PhyToMacControlInfo::setSourceAddress (LAddress::L2Type sourceAddress) inline
Sets address of the packet's sender.
Definition at line 80 of file PhyToMacControlInfo.h.
     {
         this->sourceAddress = sourceAddress;
     }
Member Data Documentation
result
DeciderResult* veins::PhyToMacControlInfo::result protected
The result of the decider evaluation.
Definition at line 45 of file PhyToMacControlInfo.h.
sourceAddress
LAddress::L2Type veins::PhyToMacControlInfo::sourceAddress protected
Deprecated:
The sender MAC address.
Definition at line 48 of file PhyToMacControlInfo.h.
The documentation for this class was generated from the following file:
PhyToMacControlInfo.h