Veins: veins::TraCIScenarioManager Class Reference
veins::TraCIScenarioManager Class Reference
Creates and moves nodes controlled by a TraCI server.
#include <TraCIScenarioManager.h>
Public Member Functions
TraCIScenarioManager ()
~TraCIScenarioManager () override
int numInitStages () const override
void initialize (int stage) override
void preNetworkFinish ()
void finish () override
void handleMessage (cMessage *msg) override
virtual void handleSelfMsg (cMessage *msg)
bool isConnected () const
TraCICommandInterface * getCommandInterface () const
TraCIConnection * getConnection () const
bool getAutoShutdownTriggered ()
const std::map< std::string, cModule * > & getManagedHosts ()
bool isUsable () const
Predicate indicating a successful connection to the TraCI server.
Static Public Attributes
static const simsignal_t traciInitializedSignal = registerSignal("org_car2x_veins_modules_mobility_traciInitialized")
static const simsignal_t traciModulePreInitSignal = registerSignal("org_car2x_veins_modules_mobility_traciModulePreInit")
static const simsignal_t traciModuleAddedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleAdded")
static const simsignal_t traciModuleRemovedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleRemoved")
static const simsignal_t traciTimestepBeginSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepBegin")
static const simsignal_t traciTimestepEndSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepEnd")
Protected Types
typedef std::map< std::string, std::string > TypeMapping
Protected Member Functions
void executeOneTimestep ()
read and execute all commands for the next timestep
virtual void init_traci ()
virtual void preInitializeModule (cModule *mod, const std::string &nodeId, const Coord &position, const std::string &road_id, double speed, Heading heading, VehicleSignalSet signals)
virtual void updateModulePosition (cModule *mod, const Coord &p, const std::string &edge, double speed, Heading heading, VehicleSignalSet signals)
void addModule (std::string nodeId, std::string type, std::string name, std::string displayString, const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan, VehicleSignalSet signals={VehicleSignal::undefined}, double length=0, double height=0, double width=0)
cModule * getManagedModule (std::string nodeId)
returns a pointer to the managed module named moduleName, or 0 if no module can be found
void deleteManagedModule (std::string nodeId)
bool isModuleUnequipped (std::string nodeId)
returns true if this vehicle is Unequipped
void subscribeToVehicleVariables (std::string vehicleId)
void unsubscribeFromVehicleVariables (std::string vehicleId)
void processSimSubscription (std::string objectId, TraCIBuffer &buf)
void processVehicleSubscription (std::string objectId, TraCIBuffer &buf)
void processSubcriptionResult (TraCIBuffer &buf)
void subscribeToTrafficLightVariables (std::string tlId)
void unsubscribeFromTrafficLightVariables (std::string tlId)
void processTrafficLightSubscription (std::string objectId, TraCIBuffer &buf)
void parseModuleTypes ()
parses the vector of module types in ini file
TypeMapping parseMappings (std::string parameter, std::string parameterName, bool allowEmpty=false)
transforms a list of mappings of an omnetpp.ini parameter in a list
virtual int getPortNumber () const
void lifecycleEvent (SimulationLifecycleEventType eventType, cObject *details) override
void listenerRemoved () override
Protected Attributes
bool traciInitialized = false
Flag indicating whether the init_traci routine has been run.
simtime_t connectAt
when to connect to TraCI server (must be the initial timestep of the server)
simtime_t firstStepAt
when to start synchronizing with the TraCI server (-1: immediately after connecting)
simtime_t updateInterval
time interval of hosts' position updates
TypeMapping moduleType
module type to be used in the simulation for each managed vehicle
TypeMapping moduleName
module name to be used in the simulation for each managed vehicle
TypeMapping moduleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::string host
int port
std::string trafficLightModuleType
module type to be used in the simulation for each managed traffic light
std::string trafficLightModuleName
module name to be used in the simulation for each managed traffic light
std::string trafficLightModuleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::vector< std::string > trafficLightModuleIds
list of traffic light module ids that is subscribed to (whitelist)
bool autoShutdown
Shutdown module as soon as no more vehicles are in the simulation.
double penetrationRate
bool ignoreGuiCommands
whether to ignore all TraCI commands that only make sense when the server has a graphical user interface
TraCIRegionOfInterest roi
Can return whether a given position lies within the simulation's region of interest.
double areaSum
AnnotationManager * annotations
std::unique_ptr< TraCIConnection > connection
std::unique_ptr< TraCICommandInterface > commandIfc
size_t nextNodeVectorIndex
next OMNeT++ module vector index to use
std::map< std::string, cModule * > hosts
vector of all hosts managed by us
std::set< std::string > unEquippedHosts
std::set< std::string > subscribedVehicles
all vehicles we have already subscribed to
std::map< std::string, cModule * > trafficLights
vector of all traffic lights managed by us
uint32_t activeVehicleCount
number of vehicles, be it parking or driving
uint32_t parkingVehicleCount
number of parking vehicles, derived from parking start/end events
uint32_t drivingVehicleCount
number of driving, as reported by sumo
bool autoShutdownTriggered
cMessage * connectAndStartTrigger
self-message scheduled for when to connect to TraCI server and start running
cMessage * executeOneTimestepTrigger
self-message scheduled for when to next call executeOneTimestep
BaseWorldUtility * world
std::map< const BaseMobility *, const MobileHostObstacle * > vehicleObstacles
VehicleObstacleControl * vehicleObstacleControl
Detailed Description
Creates and moves nodes controlled by a TraCI server.
If the server is a SUMO road traffic simulation, you can use the TraCIScenarioManagerLaunchd module and sumo-launchd.py script instead.
All nodes created thus must have a TraCIMobility submodule.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff, Falko Dressler, Zheng Yao, Tobias Mayer, Alvaro Torres Cortes, Luca Bedogni
See also
TraCIMobility
TraCIScenarioManagerLaunchd
Definition at line 67 of file TraCIScenarioManager.h.
Member Typedef Documentation
TypeMapping
typedef std::map<std::string, std::string> veins::TraCIScenarioManager::TypeMapping protected
Definition at line 129 of file TraCIScenarioManager.h.
Constructor & Destructor Documentation
TraCIScenarioManager()
TraCIScenarioManager::TraCIScenarioManager ()
Definition at line 55 of file TraCIScenarioManager.cc.
     : connection(nullptr)
     , commandIfc(nullptr)
     , connectAndStartTrigger(nullptr)
     , executeOneTimestepTrigger(nullptr)
     , world(nullptr)
 {
 }
~TraCIScenarioManager()
TraCIScenarioManager::~TraCIScenarioManager () override
Definition at line 64 of file TraCIScenarioManager.cc.
 {
     if (connection) {
         TraCIBuffer buf = connection->query(CMD_CLOSE, TraCIBuffer());
     }
     if (connectAndStartTrigger) {
         cancelAndDelete(connectAndStartTrigger);
         connectAndStartTrigger = nullptr;
     }
     if (executeOneTimestepTrigger) {
         cancelAndDelete(executeOneTimestepTrigger);
         executeOneTimestepTrigger = nullptr;
     }
 }
References veins::TraCIConstants::CMD_CLOSE, connectAndStartTrigger, connection, and executeOneTimestepTrigger.
Member Function Documentation
addModule()
void TraCIScenarioManager::addModule (std::string nodeId, std::string type, std::string name, std::string displayString, const Coord & position, std::string road_id = "", double speed = -1, Heading heading = Heading::nan, VehicleSignalSet signals = {VehicleSignal::undefined}, double length = 0, double height = 0, double width = 0) protected
Definition at line 514 of file TraCIScenarioManager.cc.
 {
     if (hosts.find(nodeId) != hosts.end()) throw cRuntimeError("tried adding duplicate module");
     double option1 = hosts.size() / (hosts.size() + unEquippedHosts.size() + 1.0);
     double option2 = (hosts.size() + 1) / (hosts.size() + unEquippedHosts.size() + 1.0);
     if (fabs(option1 - penetrationRate) < fabs(option2 - penetrationRate)) {
         unEquippedHosts.insert(nodeId);
         return;
     }
     int32_t nodeVectorIndex = nextNodeVectorIndex++;
     cModule* parentmod = getParentModule();
     if (!parentmod) throw cRuntimeError("Parent Module not found");
     cModuleType* nodeType = cModuleType::get(type.c_str());
     if (!nodeType) throw cRuntimeError("Module Type \"%s\" not found", type.c_str());
 #if OMNETPP_BUILDNUM >= 1525
     parentmod->setSubmoduleVectorSize(name.c_str(), nodeVectorIndex + 1);
     cModule* mod = nodeType->create(name.c_str(), parentmod, nodeVectorIndex);
 #else
     // TODO: this trashes the vectsize member of the cModule, although nobody seems to use it
     cModule* mod = nodeType->create(name.c_str(), parentmod, nodeVectorIndex, nodeVectorIndex);
 #endif
     mod->finalizeParameters();
     if (displayString.length() > 0) {
         mod->getDisplayString().parse(displayString.c_str());
     }
     mod->buildInside();
     mod->scheduleStart(simTime() + updateInterval);
     preInitializeModule(mod, nodeId, position, road_id, speed, heading, signals);
     emit(traciModulePreInitSignal, mod);
     mod->callInitialize();
     hosts[nodeId] = mod;
     // post-initialize TraCIMobility
     auto mobilityModules = getSubmodulesOfType<TraCIMobility>(mod);
     for (auto mm : mobilityModules) {
         mm->changePosition();
     }
     if (vehicleObstacleControl) {
         std::vector<AntennaPosition> initialAntennaPositions;
         for (auto& caModule : getSubmodulesOfType<ChannelAccess>(mod, true)) {
             initialAntennaPositions.push_back(caModule->getAntennaPosition());
         }
         ASSERT(mobilityModules.size() == 1);
         auto mm = mobilityModules[0];
         double offset = mm->getHostPositionOffset();
         const MobileHostObstacle* vo = vehicleObstacleControl->add(MobileHostObstacle(initialAntennaPositions, mm, length, offset, width, height));
         vehicleObstacles[mm] = vo;
     }
     emit(traciModuleAddedSignal, mod);
 }
References veins::VehicleObstacleControl::add(), hosts, nextNodeVectorIndex, penetrationRate, preInitializeModule(), traciModuleAddedSignal, traciModulePreInitSignal, unEquippedHosts, updateInterval, vehicleObstacleControl, and vehicleObstacles.
Referenced by processVehicleSubscription().
deleteManagedModule()
void TraCIScenarioManager::deleteManagedModule (std::string nodeId) protected
Definition at line 589 of file TraCIScenarioManager.cc.
 {
     cModule* mod = getManagedModule(nodeId);
     if (!mod) throw cRuntimeError("no vehicle with Id \"%s\" found", nodeId.c_str());
     emit(traciModuleRemovedSignal, mod);
     auto cas = getSubmodulesOfType<ChannelAccess>(mod, true);
     for (auto ca : cas) {
         cModule* nic = ca->getParentModule();
         auto connectionManager = ChannelAccess::getConnectionManager(nic);
         connectionManager->unregisterNic(nic);
     }
     if (vehicleObstacleControl) {
         for (cModule::SubmoduleIterator iter(mod); !iter.end(); iter++) {
             cModule* submod = *iter;
             TraCIMobility* mm = dynamic_cast<TraCIMobility*>(submod);
             if (!mm) continue;
             auto vo = vehicleObstacles.find(mm);
             ASSERT(vo != vehicleObstacles.end());
             vehicleObstacleControl->erase(vo->second);
         }
     }
     hosts.erase(nodeId);
     mod->callFinish();
     mod->deleteModule();
 }
References veins::VehicleObstacleControl::erase(), veins::ChannelAccess::getConnectionManager(), getManagedModule(), hosts, traciModuleRemovedSignal, vehicleObstacleControl, and vehicleObstacles.
Referenced by preNetworkFinish(), processSimSubscription(), and processVehicleSubscription().
executeOneTimestep()
void TraCIScenarioManager::executeOneTimestep () protected
read and execute all commands for the next timestep
Definition at line 618 of file TraCIScenarioManager.cc.
 {
     EV_DEBUG << "Triggering TraCI server simulation advance to t=" << simTime() << endl;
     simtime_t targetTime = simTime();
     emit(traciTimestepBeginSignal, targetTime);
     if (isConnected()) {
         TraCIBuffer buf = connection->query(CMD_SIMSTEP2, TraCIBuffer() << targetTime);
         uint32_t count;
         buf >> count;
         EV_DEBUG << "Getting " << count << " subscription results" << endl;
         for (uint32_t i = 0; i < count; ++i) {
             processSubcriptionResult(buf);
         }
     }
     emit(traciTimestepEndSignal, targetTime);
     if (!autoShutdownTriggered) scheduleAt(simTime() + updateInterval, executeOneTimestepTrigger);
 }
References autoShutdownTriggered, veins::TraCIConstants::CMD_SIMSTEP2, connection, executeOneTimestepTrigger, isConnected(), processSubcriptionResult(), traciTimestepBeginSignal, traciTimestepEndSignal, and updateInterval.
Referenced by handleSelfMsg().
finish()
void TraCIScenarioManager::finish () override
Definition at line 466 of file TraCIScenarioManager.cc.
 {
     recordScalar("roiArea", areaSum);
 }
References areaSum.
Referenced by veins::TraCIScenarioManagerForker::finish(), and veins::TraCIScenarioManagerLaunchd::finish().
getAutoShutdownTriggered()
bool veins::TraCIScenarioManager::getAutoShutdownTriggered () inline
Definition at line 103 of file TraCIScenarioManager.h.
     {
         return autoShutdownTriggered;
     }
getCommandInterface()
TraCICommandInterface* veins::TraCIScenarioManager::getCommandInterface () const inline
Definition at line 93 of file TraCIScenarioManager.h.
     {
         return commandIfc.get();
     }
Referenced by veins::TraCIScreenRecorder::handleMessage(), veins::AnnotationManager::hide(), init_traci(), veins::RoadsCanvasVisualizer::initialize(), veins::TraCIVehicleInserter::insertVehicles(), processSimSubscription(), processTrafficLightSubscription(), veins::TraCIVehicleInserter::receiveSignal(), and veins::AnnotationManager::show().
getConnection()
TraCIConnection* veins::TraCIScenarioManager::getConnection () const inline
Definition at line 98 of file TraCIScenarioManager.h.
     {
         return connection.get();
     }
getManagedHosts()
const std::map<std::string, cModule*>& veins::TraCIScenarioManager::getManagedHosts () inline
Definition at line 108 of file TraCIScenarioManager.h.
     {
         return hosts;
     }
Referenced by veins::TraCIVehicleInserter::receiveSignal().
getManagedModule()
cModule * TraCIScenarioManager::getManagedModule (std::string nodeId) protected
returns a pointer to the managed module named moduleName, or 0 if no module can be found
Definition at line 577 of file TraCIScenarioManager.cc.
 {
     if (hosts.find(nodeId) == hosts.end()) return nullptr;
     return hosts[nodeId];
 }
References hosts.
Referenced by deleteManagedModule(), processSimSubscription(), and processVehicleSubscription().
getPortNumber()
int TraCIScenarioManager::getPortNumber () const protected virtual
Reimplemented in veins::TraCIScenarioManagerForker.
Definition at line 1161 of file TraCIScenarioManager.cc.
 {
     int port = par("port");
     if (port != -1) {
         return port;
     }
     // search for externally configured traci port
     const char* env_port = std::getenv("VEINS_TRACI_PORT");
     if (env_port != nullptr) {
         port = std::atoi(env_port);
     }
     return port;
 }
References port.
Referenced by veins::TraCIScenarioManagerForker::getPortNumber(), and initialize().
handleMessage()
void TraCIScenarioManager::handleMessage (cMessage * msg) override
Definition at line 471 of file TraCIScenarioManager.cc.
 {
     if (msg->isSelfMessage()) {
         handleSelfMsg(msg);
         return;
     }
     throw cRuntimeError("TraCIScenarioManager doesn't handle messages from other modules");
 }
References handleSelfMsg().
handleSelfMsg()
void TraCIScenarioManager::handleSelfMsg (cMessage * msg) virtual
Definition at line 480 of file TraCIScenarioManager.cc.
 {
     if (msg == connectAndStartTrigger) {
         connection.reset(TraCIConnection::connect(this, host.c_str(), port));
         commandIfc.reset(new TraCICommandInterface(this, *connection, ignoreGuiCommands));
         init_traci();
         return;
     }
     if (msg == executeOneTimestepTrigger) {
         executeOneTimestep();
         return;
     }
     throw cRuntimeError("TraCIScenarioManager received unknown self-message");
 }
References commandIfc, veins::TraCIConnection::connect(), connectAndStartTrigger, connection, executeOneTimestep(), executeOneTimestepTrigger, host, ignoreGuiCommands, init_traci(), and port.
Referenced by handleMessage().
init_traci()
void TraCIScenarioManager::init_traci () protected virtual
Reimplemented in veins::TraCIScenarioManagerLaunchd.
Definition at line 296 of file TraCIScenarioManager.cc.
 {
     auto* commandInterface = getCommandInterface();
     {
         auto apiVersion = commandInterface->getVersion();
         EV_DEBUG << "TraCI server \"" << apiVersion.second << "\" reports API version " << apiVersion.first << endl;
         commandInterface->setApiVersion(apiVersion.first);
     }
     {
         // query and set road network boundaries
         auto networkBoundaries = commandInterface->initNetworkBoundaries(par("margin"));
         if (world != nullptr && ((connection->traci2omnet(networkBoundaries.second).x > world->getPgs()->x) || (connection->traci2omnet(networkBoundaries.first).y > world->getPgs()->y))) {
             EV_WARN << "WARNING: Playground size (" << world->getPgs()->x << ", " << world->getPgs()->y << ") might be too small for vehicle at network bounds (" << connection->traci2omnet(networkBoundaries.second).x << ", " << connection->traci2omnet(networkBoundaries.first).y << ")" << endl;
         }
     }
     {
         // subscribe to list of departed and arrived vehicles, as well as simulation time
         simtime_t beginTime = 0;
         simtime_t endTime = SimTime::getMaxTime();
         std::string objectId = "";
         std::list<uint8_t> variables;
         variables.push_back(VAR_DEPARTED_VEHICLES_IDS);
         variables.push_back(VAR_ARRIVED_VEHICLES_IDS);
         variables.push_back(commandInterface->getTimeStepCmd());
         if (commandInterface->getApiVersion() >= 18) {
             variables.push_back(VAR_COLLIDING_VEHICLES_IDS);
         }
         variables.push_back(VAR_TELEPORT_STARTING_VEHICLES_IDS);
         variables.push_back(VAR_TELEPORT_ENDING_VEHICLES_IDS);
         variables.push_back(VAR_PARKING_STARTING_VEHICLES_IDS);
         variables.push_back(VAR_PARKING_ENDING_VEHICLES_IDS);
         uint8_t variableNumber = variables.size();
         TraCIBuffer buf1 = TraCIBuffer();
         buf1 << beginTime << endTime << objectId << variableNumber;
         for (auto variable : variables) {
             buf1 << variable;
         }
         TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_SIM_VARIABLE, buf1);
         processSubcriptionResult(buf);
         ASSERT(buf.eof());
     }
     {
         // subscribe to list of vehicle ids
         simtime_t beginTime = 0;
         simtime_t endTime = SimTime::getMaxTime();
         std::string objectId = "";
         uint8_t variableNumber = 1;
         uint8_t variable1 = ID_LIST;
         TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber << variable1);
         processSubcriptionResult(buf);
         ASSERT(buf.eof());
     }
     if (!trafficLightModuleType.empty() && !trafficLightModuleIds.empty()) {
         // initialize traffic lights
         cModule* parentmod = getParentModule();
         if (!parentmod) {
             throw cRuntimeError("Parent Module not found (for traffic light creation)");
         }
         cModuleType* tlModuleType = cModuleType::get(trafficLightModuleType.c_str());
         // query traffic lights via TraCI
         std::list<std::string> trafficLightIds = commandInterface->getTrafficlightIds();
 #if OMNETPP_BUILDNUM >= 1525
 #else
         size_t nrOfTrafficLights = trafficLightIds.size();
 #endif
         int cnt = 0;
         for (std::list<std::string>::iterator i = trafficLightIds.begin(); i != trafficLightIds.end(); ++i) {
             std::string tlId = *i;
             if (std::find(trafficLightModuleIds.begin(), trafficLightModuleIds.end(), tlId) == trafficLightModuleIds.end()) {
                 continue; // filter only selected elements
             }
             Coord position = commandInterface->junction(tlId).getPosition();
 #if OMNETPP_BUILDNUM >= 1525
             parentmod->setSubmoduleVectorSize(trafficLightModuleName.c_str(), cnt + 1);
             cModule* module = tlModuleType->create(trafficLightModuleName.c_str(), parentmod, cnt);
 #else
             cModule* module = tlModuleType->create(trafficLightModuleName.c_str(), parentmod, nrOfTrafficLights, cnt);
 #endif
             module->par("externalId") = tlId;
             module->finalizeParameters();
             module->getDisplayString().parse(trafficLightModuleDisplayString.c_str());
             module->buildInside();
             module->scheduleStart(simTime() + updateInterval);
             cModule* tlIfSubmodule = module->getSubmodule("tlInterface");
             // initialize traffic light interface with current program
             TraCITrafficLightInterface* tlIfModule = dynamic_cast<TraCITrafficLightInterface*>(tlIfSubmodule);
             tlIfModule->preInitialize(tlId, position, updateInterval);
             // initialize mobility for positioning
             BaseMobility* mobiSubmodule = check_and_cast<BaseMobility*>(module->getSubmodule("mobility"));
             mobiSubmodule->setStartPosition(position);
             module->callInitialize();
             trafficLights[tlId] = module;
             subscribeToTrafficLightVariables(tlId); // subscribe after module is in trafficLights
             cnt++;
         }
     }
     ObstacleControl* obstacles = ObstacleControlAccess().getIfExists();
     if (obstacles) {
         {
             // get list of polygons
             std::list<std::string> ids = commandInterface->getPolygonIds();
             for (std::list<std::string>::iterator i = ids.begin(); i != ids.end(); ++i) {
                 std::string id = *i;
                 std::string typeId = commandInterface->polygon(id).getTypeId();
                 if (!obstacles->isTypeSupported(typeId)) continue;
                 std::list<Coord> coords = commandInterface->polygon(id).getShape();
                 std::vector<Coord> shape;
                 std::copy(coords.begin(), coords.end(), std::back_inserter(shape));
                 for (auto p : shape) {
                     if ((p.x < 0) || (p.y < 0) || (p.x > world->getPgs()->x) || (p.y > world->getPgs()->y)) {
                         EV_WARN << "WARNING: Playground (" << world->getPgs()->x << ", " << world->getPgs()->y << ") will not fit radio obstacle at (" << p.x << ", " << p.y << ")" << endl;
                     }
                 }
                 obstacles->addFromTypeAndShape(id, typeId, shape);
             }
         }
     }
     traciInitialized = true;
     emit(traciInitializedSignal, true);
     // draw and calculate area of rois
     for (std::list<std::pair<TraCICoord, TraCICoord>>::const_iterator r = roi.getRectangles().begin(), end = roi.getRectangles().end(); r != end; ++r) {
         TraCICoord first = r->first;
         TraCICoord second = r->second;
         std::list<Coord> pol;
         Coord a = connection->traci2omnet(first);
         Coord b = connection->traci2omnet(TraCICoord(first.x, second.y));
         Coord c = connection->traci2omnet(second);
         Coord d = connection->traci2omnet(TraCICoord(second.x, first.y));
         pol.push_back(a);
         pol.push_back(b);
         pol.push_back(c);
         pol.push_back(d);
         // draw polygon for region of interest
         if (annotations) {
             annotations->drawPolygon(pol, "black");
         }
         // calculate region area
         double ab = a.distance(b);
         double ad = a.distance(d);
         double area = ab * ad;
         areaSum += area;
     }
 }
References veins::ObstacleControl::addFromTypeAndShape(), annotations, areaSum, veins::TraCIConstants::CMD_SUBSCRIBE_SIM_VARIABLE, veins::TraCIConstants::CMD_SUBSCRIBE_VEHICLE_VARIABLE, connection, veins::Coord::distance(), veins::AnnotationManager::drawPolygon(), veins::TraCIBuffer::eof(), getCommandInterface(), veins::ObstacleControlAccess::getIfExists(), veins::BaseWorldUtility::getPgs(), veins::TraCIRegionOfInterest::getRectangles(), veins::TraCIConstants::ID_LIST, veins::ObstacleControl::isTypeSupported(), veins::TraCITrafficLightInterface::preInitialize(), processSubcriptionResult(), roi, veins::BaseMobility::setStartPosition(), subscribeToTrafficLightVariables(), traciInitialized, traciInitializedSignal, trafficLightModuleDisplayString, trafficLightModuleIds, trafficLightModuleName, trafficLightModuleType, trafficLights, updateInterval, veins::TraCIConstants::VAR_ARRIVED_VEHICLES_IDS, veins::TraCIConstants::VAR_COLLIDING_VEHICLES_IDS, veins::TraCIConstants::VAR_DEPARTED_VEHICLES_IDS, veins::TraCIConstants::VAR_PARKING_ENDING_VEHICLES_IDS, veins::TraCIConstants::VAR_PARKING_STARTING_VEHICLES_IDS, veins::TraCIConstants::VAR_TELEPORT_ENDING_VEHICLES_IDS, veins::TraCIConstants::VAR_TELEPORT_STARTING_VEHICLES_IDS, world, veins::Coord::x, veins::TraCICoord::x, veins::Coord::y, and veins::TraCICoord::y.
Referenced by handleSelfMsg(), and veins::TraCIScenarioManagerLaunchd::init_traci().
initialize()
void TraCIScenarioManager::initialize (int stage) override
Definition at line 239 of file TraCIScenarioManager.cc.
 {
     cSimpleModule::initialize(stage);
     if (stage != 1) {
         return;
     }
     trafficLightModuleType = par("trafficLightModuleType").stdstringValue();
     trafficLightModuleName = par("trafficLightModuleName").stdstringValue();
     trafficLightModuleDisplayString = par("trafficLightModuleDisplayString").stdstringValue();
     trafficLightModuleIds.clear();
     std::istringstream filterstream(par("trafficLightFilter").stdstringValue());
     std::copy(std::istream_iterator<std::string>(filterstream), std::istream_iterator<std::string>(), std::back_inserter(trafficLightModuleIds));
     connectAt = par("connectAt");
     firstStepAt = par("firstStepAt");
     updateInterval = par("updateInterval");
     if (firstStepAt == -1) firstStepAt = connectAt + updateInterval;
     parseModuleTypes();
     penetrationRate = par("penetrationRate").doubleValue();
     ignoreGuiCommands = par("ignoreGuiCommands");
     host = par("host").stdstringValue();
     port = getPortNumber();
     if (port == -1) {
         throw cRuntimeError("TraCI Port autoconfiguration failed, set 'port' != -1 in omnetpp.ini or provide VEINS_TRACI_PORT environment variable.");
     }
     autoShutdown = par("autoShutdown");
     annotations = AnnotationManagerAccess().getIfExists();
     roi.clear();
     roi.addRoads(par("roiRoads"));
     roi.addRectangles(par("roiRects"));
     areaSum = 0;
     nextNodeVectorIndex = 0;
     hosts.clear();
     subscribedVehicles.clear();
     trafficLights.clear();
     activeVehicleCount = 0;
     parkingVehicleCount = 0;
     drivingVehicleCount = 0;
     autoShutdownTriggered = false;
     world = FindModule<BaseWorldUtility*>::findGlobalModule();
     vehicleObstacleControl = FindModule<VehicleObstacleControl*>::findGlobalModule();
     ASSERT(firstStepAt > connectAt);
     connectAndStartTrigger = new cMessage("connect");
     scheduleAt(connectAt, connectAndStartTrigger);
     executeOneTimestepTrigger = new cMessage("step");
     scheduleAt(firstStepAt, executeOneTimestepTrigger);
     EV_DEBUG << "initialized TraCIScenarioManager" << endl;
 }
References activeVehicleCount, veins::TraCIRegionOfInterest::addRectangles(), veins::TraCIRegionOfInterest::addRoads(), annotations, areaSum, autoShutdown, autoShutdownTriggered, veins::TraCIRegionOfInterest::clear(), connectAndStartTrigger, connectAt, drivingVehicleCount, executeOneTimestepTrigger, veins::FindModule< T >::findGlobalModule(), firstStepAt, veins::AnnotationManagerAccess::getIfExists(), getPortNumber(), host, hosts, ignoreGuiCommands, nextNodeVectorIndex, parkingVehicleCount, parseModuleTypes(), penetrationRate, port, roi, subscribedVehicles, trafficLightModuleDisplayString, trafficLightModuleIds, trafficLightModuleName, trafficLightModuleType, trafficLights, updateInterval, vehicleObstacleControl, and world.
Referenced by veins::TraCIScenarioManagerForker::initialize(), and veins::TraCIScenarioManagerLaunchd::initialize().
isConnected()
bool veins::TraCIScenarioManager::isConnected () const inline
Definition at line 88 of file TraCIScenarioManager.h.
     {
         return static_cast<bool>(connection);
     }
Referenced by executeOneTimestep(), veins::AnnotationManager::hide(), veins::TraCIVehicleInserter::receiveSignal(), and veins::AnnotationManager::show().
isModuleUnequipped()
bool TraCIScenarioManager::isModuleUnequipped (std::string nodeId) protected
returns true if this vehicle is Unequipped
Definition at line 583 of file TraCIScenarioManager.cc.
 {
     if (unEquippedHosts.find(nodeId) == unEquippedHosts.end()) return false;
     return true;
 }
References unEquippedHosts.
Referenced by processVehicleSubscription().
isUsable()
bool veins::TraCIScenarioManager::isUsable () const inline
Predicate indicating a successful connection to the TraCI server.
Note
Once the connection has been established, this will return true even when the connection has been torn down again.
Definition at line 118 of file TraCIScenarioManager.h.
     {
         return traciInitialized;
     }
lifecycleEvent()
void TraCIScenarioManager::lifecycleEvent (SimulationLifecycleEventType eventType, cObject * details) override protected
Definition at line 1177 of file TraCIScenarioManager.cc.
 {
     if (eventType == LF_PRE_NETWORK_FINISH) {
         preNetworkFinish();
     }
 }
References preNetworkFinish().
listenerRemoved()
void TraCIScenarioManager::listenerRemoved () override protected
Definition at line 1184 of file TraCIScenarioManager.cc.
 {
     delete this;
 }
numInitStages()
int veins::TraCIScenarioManager::numInitStages () const inline override
Definition at line 78 of file TraCIScenarioManager.h.
     {
         return std::max(cSimpleModule::numInitStages(), 2);
     }
parseMappings()
TraCIScenarioManager::TypeMapping TraCIScenarioManager::parseMappings (std::string parameter, std::string parameterName, bool allowEmpty = false) protected
transforms a list of mappings of an omnetpp.ini parameter in a list
possible syntaxes
"a" : assign module type "a" to all nodes (for backward compatibility) "a=b" : assign module type "b" to vehicle type "a". the presence of any other vehicle type in the simulation will cause the simulation to stop "a=b c=d" : assign module type "b" to vehicle type "a" and "d" to "c". the presence of any other vehicle type in the simulation will cause the simulation to stop "a=b c=d *=e": everything which is not of vehicle type "a" or "b", assign module type "e" "a=b c=0" : for vehicle type "c" no module should be instantiated "a=b c=d *=0": everything which is not of vehicle type a or c should not be instantiated
For display strings key-value pairs needs to be protected with single quotes, as they use an = sign as the type mappings. For example *.manager.moduleDisplayString = "'i=block/process'" *.manager.moduleDisplayString = "a='i=block/process' b='i=misc/sun'"
moduleDisplayString can also be left empty: *.manager.moduleDisplayString = ""
Definition at line 129 of file TraCIScenarioManager.cc.
 {
     /**
      * possible syntaxes
      *
      * "a"          : assign module type "a" to all nodes (for backward compatibility)
      * "a=b"        : assign module type "b" to vehicle type "a". the presence of any other vehicle type in the simulation will cause the simulation to stop
      * "a=b c=d"    : assign module type "b" to vehicle type "a" and "d" to "c". the presence of any other vehicle type in the simulation will cause the simulation to stop
      * "a=b c=d *=e": everything which is not of vehicle type "a" or "b", assign module type "e"
      * "a=b c=0"    : for vehicle type "c" no module should be instantiated
      * "a=b c=d *=0": everything which is not of vehicle type a or c should not be instantiated
      *
      * For display strings key-value pairs needs to be protected with single quotes, as they use an = sign as the type mappings. For example
      * *.manager.moduleDisplayString = "'i=block/process'"
      * *.manager.moduleDisplayString = "a='i=block/process' b='i=misc/sun'"
      *
      * moduleDisplayString can also be left empty:
      * *.manager.moduleDisplayString = ""
      */
     unsigned int i;
     TypeMapping map;
     // tokenizer to split into mappings ("a=b c=d", -> ["a=b", "c=d"])
     cStringTokenizer typesTz(parameter.c_str(), " ");
     // get all mappings
     std::vector<std::string> typeMappings = typesTz.asVector();
     // and check that there exists at least one
     if (typeMappings.size() == 0) {
         if (!allowEmpty)
             throw cRuntimeError("parameter \"%s\" is empty", parameterName.c_str());
         else
             return map;
     }
     // loop through all mappings
     for (i = 0; i < typeMappings.size(); i++) {
         // tokenizer to find the mapping from vehicle type to module type
         std::string typeMapping = typeMappings[i];
         std::vector<std::string> mapping = getMapping(typeMapping);
         if (mapping.size() == 1) {
             // we are where there is no actual assignment
             // "a": this is good
             // "a b=c": this is not
             if (typeMappings.size() != 1)
                 // stop simulation with an error
                 throw cRuntimeError("parameter \"%s\" includes multiple mappings, but \"%s\" is not mapped to any vehicle type", parameterName.c_str(), mapping[0].c_str());
             else
                 // all vehicle types should be instantiated with this module type
                 map["*"] = mapping[0];
         }
         else {
             // check that mapping is valid (a=b and not like a=b=c)
             if (mapping.size() != 2) throw cRuntimeError("invalid syntax for mapping \"%s\" for parameter \"%s\"", typeMapping.c_str(), parameterName.c_str());
             // check that the mapping does not already exist
             if (map.find(mapping[0]) != map.end()) throw cRuntimeError("duplicated mapping for vehicle type \"%s\" for parameter \"%s\"", mapping[0].c_str(), parameterName.c_str());
             // finally save the mapping
             map[mapping[0]] = mapping[1];
         }
     }
     return map;
 }
References anonymous_namespace{TraCIScenarioManager.cc}::getMapping().
Referenced by parseModuleTypes().
parseModuleTypes()
void TraCIScenarioManager::parseModuleTypes () protected
parses the vector of module types in ini file
in case of inconsistencies the function kills the simulation
Definition at line 199 of file TraCIScenarioManager.cc.
 {
     TypeMapping::iterator i;
     std::vector<std::string> typeKeys, nameKeys, displayStringKeys;
     std::string moduleTypes = par("moduleType").stdstringValue();
     std::string moduleNames = par("moduleName").stdstringValue();
     std::string moduleDisplayStrings = par("moduleDisplayString").stdstringValue();
     moduleType = parseMappings(moduleTypes, "moduleType", false);
     moduleName = parseMappings(moduleNames, "moduleName", false);
     moduleDisplayString = parseMappings(moduleDisplayStrings, "moduleDisplayString", true);
     // perform consistency check. for each vehicle type in moduleType there must be a vehicle type
     // in moduleName (and in moduleDisplayString if moduleDisplayString is not empty)
     // get all the keys
     for (i = moduleType.begin(); i != moduleType.end(); i++) typeKeys.push_back(i->first);
     for (i = moduleName.begin(); i != moduleName.end(); i++) nameKeys.push_back(i->first);
     for (i = moduleDisplayString.begin(); i != moduleDisplayString.end(); i++) displayStringKeys.push_back(i->first);
     // sort them (needed for intersection)
     std::sort(typeKeys.begin(), typeKeys.end());
     std::sort(nameKeys.begin(), nameKeys.end());
     std::sort(displayStringKeys.begin(), displayStringKeys.end());
     std::vector<std::string> intersection;
     // perform set intersection
     std::set_intersection(typeKeys.begin(), typeKeys.end(), nameKeys.begin(), nameKeys.end(), std::back_inserter(intersection));
     if (intersection.size() != typeKeys.size() || intersection.size() != nameKeys.size()) throw cRuntimeError("keys of mappings of moduleType and moduleName are not the same");
     if (displayStringKeys.size() == 0) return;
     intersection.clear();
     std::set_intersection(typeKeys.begin(), typeKeys.end(), displayStringKeys.begin(), displayStringKeys.end(), std::back_inserter(intersection));
     if (intersection.size() != displayStringKeys.size()) throw cRuntimeError("keys of mappings of moduleType and moduleDisplayString are not the same");
 }
References moduleDisplayString, moduleName, moduleType, and parseMappings().
Referenced by initialize().
preInitializeModule()
void TraCIScenarioManager::preInitializeModule (cModule * mod, const std::string & nodeId, const Coord & position, const std::string & road_id, double speed, Heading heading, VehicleSignalSet signals) protected virtual
Definition at line 495 of file TraCIScenarioManager.cc.
 {
     // pre-initialize TraCIMobility
     auto mobilityModules = getSubmodulesOfType<TraCIMobility>(mod);
     for (auto mm : mobilityModules) {
         mm->preInitialize(nodeId, position, road_id, speed, heading);
     }
 }
Referenced by addModule().
preNetworkFinish()
void TraCIScenarioManager::preNetworkFinish ()
Definition at line 459 of file TraCIScenarioManager.cc.
 {
     while (hosts.begin() != hosts.end()) {
         deleteManagedModule(hosts.begin()->first);
     }
 }
References deleteManagedModule(), and hosts.
Referenced by lifecycleEvent().
processSimSubscription()
void TraCIScenarioManager::processSimSubscription (std::string objectId, TraCIBuffer & buf) protected
Definition at line 760 of file TraCIScenarioManager.cc.
 {
     uint8_t variableNumber_resp;
     buf >> variableNumber_resp;
     for (uint8_t j = 0; j < variableNumber_resp; ++j) {
         uint8_t variable1_resp;
         buf >> variable1_resp;
         uint8_t isokay;
         buf >> isokay;
         if (isokay != RTYPE_OK) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRING);
             std::string description;
             buf >> description;
             if (isokay == RTYPE_NOTIMPLEMENTED) throw cRuntimeError("TraCI server reported subscribing to variable 0x%2x not implemented (\"%s\"). Might need newer version.", variable1_resp, description.c_str());
             throw cRuntimeError("TraCI server reported error subscribing to variable 0x%2x (\"%s\").", variable1_resp, description.c_str());
         }
         if (variable1_resp == VAR_DEPARTED_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " departed vehicles." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 // adding modules is handled on the fly when entering/leaving the ROI
             }
             activeVehicleCount += count;
             drivingVehicleCount += count;
         }
         else if (variable1_resp == VAR_ARRIVED_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " arrived vehicles." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 if (subscribedVehicles.find(idstring) != subscribedVehicles.end()) {
                     subscribedVehicles.erase(idstring);
                     // no unsubscription via TraCI possible/necessary as of SUMO 1.0.0 (the vehicle has arrived)
                 }
                 // check if this object has been deleted already (e.g. because it was outside the ROI)
                 cModule* mod = getManagedModule(idstring);
                 if (mod) deleteManagedModule(idstring);
                 if (unEquippedHosts.find(idstring) != unEquippedHosts.end()) {
                     unEquippedHosts.erase(idstring);
                 }
             }
             if ((count > 0) && (count >= activeVehicleCount) && autoShutdown) autoShutdownTriggered = true;
             activeVehicleCount -= count;
             drivingVehicleCount -= count;
         }
         else if (variable1_resp == VAR_TELEPORT_STARTING_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " vehicles starting to teleport." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 // check if this object has been deleted already (e.g. because it was outside the ROI)
                 cModule* mod = getManagedModule(idstring);
                 if (mod) deleteManagedModule(idstring);
                 if (unEquippedHosts.find(idstring) != unEquippedHosts.end()) {
                     unEquippedHosts.erase(idstring);
                 }
             }
             activeVehicleCount -= count;
             drivingVehicleCount -= count;
         }
         else if (variable1_resp == VAR_TELEPORT_ENDING_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " vehicles ending teleport." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 // adding modules is handled on the fly when entering/leaving the ROI
             }
             activeVehicleCount += count;
             drivingVehicleCount += count;
         }
         else if (variable1_resp == VAR_PARKING_STARTING_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " vehicles starting to park." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 cModule* mod = getManagedModule(idstring);
                 auto mobilityModules = getSubmodulesOfType<TraCIMobility>(mod);
                 for (auto mm : mobilityModules) {
                     mm->changeParkingState(true);
                 }
             }
             parkingVehicleCount += count;
             drivingVehicleCount -= count;
         }
         else if (variable1_resp == VAR_PARKING_ENDING_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " vehicles ending to park." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 cModule* mod = getManagedModule(idstring);
                 auto mobilityModules = getSubmodulesOfType<TraCIMobility>(mod);
                 for (auto mm : mobilityModules) {
                     mm->changeParkingState(false);
                 }
             }
             parkingVehicleCount -= count;
             drivingVehicleCount += count;
         }
         else if (variable1_resp == getCommandInterface()->getTimeStepCmd()) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == getCommandInterface()->getTimeType());
             simtime_t serverTimestep;
             buf >> serverTimestep;
             EV_DEBUG << "TraCI reports current time step as " << serverTimestep << " s." << endl;
             simtime_t omnetTimestep = simTime();
             ASSERT(omnetTimestep == serverTimestep);
         }
         else if (variable1_resp == VAR_COLLIDING_VEHICLES_IDS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " collided vehicles." << endl;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 cModule* mod = getManagedModule(idstring);
                 if (mod) {
                     auto mobilityModules = getSubmodulesOfType<TraCIMobility>(mod);
                     for (auto mm : mobilityModules) {
                         mm->collisionOccurred(true);
                     }
                 }
             }
         }
         else {
             throw cRuntimeError("Received unhandled sim subscription result");
         }
     }
 }
References activeVehicleCount, autoShutdown, autoShutdownTriggered, deleteManagedModule(), drivingVehicleCount, getCommandInterface(), getManagedModule(), parkingVehicleCount, veins::TraCIConstants::RTYPE_NOTIMPLEMENTED, veins::TraCIConstants::RTYPE_OK, subscribedVehicles, veins::TraCIConstants::TYPE_STRING, veins::TraCIConstants::TYPE_STRINGLIST, unEquippedHosts, veins::TraCIConstants::VAR_ARRIVED_VEHICLES_IDS, veins::TraCIConstants::VAR_COLLIDING_VEHICLES_IDS, veins::TraCIConstants::VAR_DEPARTED_VEHICLES_IDS, veins::TraCIConstants::VAR_PARKING_ENDING_VEHICLES_IDS, veins::TraCIConstants::VAR_PARKING_STARTING_VEHICLES_IDS, veins::TraCIConstants::VAR_TELEPORT_ENDING_VEHICLES_IDS, and veins::TraCIConstants::VAR_TELEPORT_STARTING_VEHICLES_IDS.
Referenced by processSubcriptionResult().
processSubcriptionResult()
void TraCIScenarioManager::processSubcriptionResult (TraCIBuffer & buf) protected
Definition at line 1139 of file TraCIScenarioManager.cc.
 {
     uint8_t cmdLength_resp;
     buf >> cmdLength_resp;
     uint32_t cmdLengthExt_resp;
     buf >> cmdLengthExt_resp;
     uint8_t commandId_resp;
     buf >> commandId_resp;
     std::string objectId_resp;
     buf >> objectId_resp;
     if (commandId_resp == RESPONSE_SUBSCRIBE_VEHICLE_VARIABLE)
         processVehicleSubscription(objectId_resp, buf);
     else if (commandId_resp == RESPONSE_SUBSCRIBE_SIM_VARIABLE)
         processSimSubscription(objectId_resp, buf);
     else if (commandId_resp == RESPONSE_SUBSCRIBE_TL_VARIABLE)
         processTrafficLightSubscription(objectId_resp, buf);
     else {
         throw cRuntimeError("Received unhandled subscription result");
     }
 }
References processSimSubscription(), processTrafficLightSubscription(), processVehicleSubscription(), veins::TraCIConstants::RESPONSE_SUBSCRIBE_SIM_VARIABLE, veins::TraCIConstants::RESPONSE_SUBSCRIBE_TL_VARIABLE, and veins::TraCIConstants::RESPONSE_SUBSCRIBE_VEHICLE_VARIABLE.
Referenced by executeOneTimestep(), init_traci(), subscribeToTrafficLightVariables(), and subscribeToVehicleVariables().
processTrafficLightSubscription()
void TraCIScenarioManager::processTrafficLightSubscription (std::string objectId, TraCIBuffer & buf) protected
Definition at line 712 of file TraCIScenarioManager.cc.
 {
     cModule* tlIfSubmodule = trafficLights[objectId]->getSubmodule("tlInterface");
     TraCITrafficLightInterface* tlIfModule = dynamic_cast<TraCITrafficLightInterface*>(tlIfSubmodule);
     if (!tlIfModule) {
         throw cRuntimeError("Could not find traffic light module %s", objectId.c_str());
     }
     uint8_t variableNumber_resp;
     buf >> variableNumber_resp;
     for (uint8_t j = 0; j < variableNumber_resp; ++j) {
         uint8_t response_type;
         buf >> response_type;
         uint8_t isokay;
         buf >> isokay;
         if (isokay != RTYPE_OK) {
             std::string description = buf.readTypeChecked<std::string>(TYPE_STRING);
             if (isokay == RTYPE_NOTIMPLEMENTED) {
                 throw cRuntimeError("TraCI server reported subscribing to 0x%2x not implemented (\"%s\"). Might need newer version.", response_type, description.c_str());
             }
             else {
                 throw cRuntimeError("TraCI server reported error subscribing to variable 0x%2x (\"%s\").", response_type, description.c_str());
             }
         }
         switch (response_type) {
         case TL_CURRENT_PHASE:
             tlIfModule->setCurrentPhaseByNr(buf.readTypeChecked<int32_t>(TYPE_INTEGER), false);
             break;
         case TL_CURRENT_PROGRAM:
             tlIfModule->setCurrentLogicById(buf.readTypeChecked<std::string>(TYPE_STRING), false);
             break;
         case TL_NEXT_SWITCH:
             tlIfModule->setNextSwitch(buf.readTypeChecked<simtime_t>(getCommandInterface()->getTimeType()), false);
             break;
         case TL_RED_YELLOW_GREEN_STATE:
             tlIfModule->setCurrentState(buf.readTypeChecked<std::string>(TYPE_STRING), false);
             break;
         default:
             throw cRuntimeError("Received unhandled traffic light subscription result; type: 0x%02x", response_type);
             break;
         }
     }
 }
References getCommandInterface(), veins::TraCIBuffer::readTypeChecked(), veins::TraCIConstants::RTYPE_NOTIMPLEMENTED, veins::TraCIConstants::RTYPE_OK, veins::TraCITrafficLightInterface::setCurrentLogicById(), veins::TraCITrafficLightInterface::setCurrentPhaseByNr(), veins::TraCITrafficLightInterface::setCurrentState(), veins::TraCITrafficLightInterface::setNextSwitch(), veins::TraCIConstants::TL_CURRENT_PHASE, veins::TraCIConstants::TL_CURRENT_PROGRAM, veins::TraCIConstants::TL_NEXT_SWITCH, veins::TraCIConstants::TL_RED_YELLOW_GREEN_STATE, trafficLights, veins::TraCIConstants::TYPE_INTEGER, and veins::TraCIConstants::TYPE_STRING.
Referenced by processSubcriptionResult().
processVehicleSubscription()
void TraCIScenarioManager::processVehicleSubscription (std::string objectId, TraCIBuffer & buf) protected
Definition at line 939 of file TraCIScenarioManager.cc.
 {
     bool isSubscribed = (subscribedVehicles.find(objectId) != subscribedVehicles.end());
     double px;
     double py;
     std::string edge;
     double speed;
     double angle_traci;
     int signals;
     double length;
     double height;
     double width;
     int numRead = 0;
     uint8_t variableNumber_resp;
     buf >> variableNumber_resp;
     for (uint8_t j = 0; j < variableNumber_resp; ++j) {
         uint8_t variable1_resp;
         buf >> variable1_resp;
         uint8_t isokay;
         buf >> isokay;
         if (isokay != RTYPE_OK) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRING);
             std::string errormsg;
             buf >> errormsg;
             if (isSubscribed) {
                 if (isokay == RTYPE_NOTIMPLEMENTED) throw cRuntimeError("TraCI server reported subscribing to vehicle variable 0x%2x not implemented (\"%s\"). Might need newer version.", variable1_resp, errormsg.c_str());
                 throw cRuntimeError("TraCI server reported error subscribing to vehicle variable 0x%2x (\"%s\").", variable1_resp, errormsg.c_str());
             }
         }
         else if (variable1_resp == ID_LIST) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRINGLIST);
             uint32_t count;
             buf >> count;
             EV_DEBUG << "TraCI reports " << count << " active vehicles." << endl;
             ASSERT(count == activeVehicleCount);
             std::set<std::string> drivingVehicles;
             for (uint32_t i = 0; i < count; ++i) {
                 std::string idstring;
                 buf >> idstring;
                 drivingVehicles.insert(idstring);
             }
             // check for vehicles that need subscribing to
             std::set<std::string> needSubscribe;
             std::set_difference(drivingVehicles.begin(), drivingVehicles.end(), subscribedVehicles.begin(), subscribedVehicles.end(), std::inserter(needSubscribe, needSubscribe.begin()));
             for (std::set<std::string>::const_iterator i = needSubscribe.begin(); i != needSubscribe.end(); ++i) {
                 subscribedVehicles.insert(*i);
                 subscribeToVehicleVariables(*i);
             }
             // check for vehicles that need unsubscribing from
             std::set<std::string> needUnsubscribe;
             std::set_difference(subscribedVehicles.begin(), subscribedVehicles.end(), drivingVehicles.begin(), drivingVehicles.end(), std::inserter(needUnsubscribe, needUnsubscribe.begin()));
             for (std::set<std::string>::const_iterator i = needUnsubscribe.begin(); i != needUnsubscribe.end(); ++i) {
                 subscribedVehicles.erase(*i);
                 unsubscribeFromVehicleVariables(*i);
             }
         }
         else if (variable1_resp == VAR_POSITION) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == POSITION_2D);
             buf >> px;
             buf >> py;
             numRead++;
         }
         else if (variable1_resp == VAR_ROAD_ID) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_STRING);
             buf >> edge;
             numRead++;
         }
         else if (variable1_resp == VAR_SPEED) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_DOUBLE);
             buf >> speed;
             numRead++;
         }
         else if (variable1_resp == VAR_ANGLE) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_DOUBLE);
             buf >> angle_traci;
             numRead++;
         }
         else if (variable1_resp == VAR_SIGNALS) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_INTEGER);
             buf >> signals;
             numRead++;
         }
         else if (variable1_resp == VAR_LENGTH) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_DOUBLE);
             buf >> length;
             numRead++;
         }
         else if (variable1_resp == VAR_HEIGHT) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_DOUBLE);
             buf >> height;
             numRead++;
         }
         else if (variable1_resp == VAR_WIDTH) {
             uint8_t varType;
             buf >> varType;
             ASSERT(varType == TYPE_DOUBLE);
             buf >> width;
             numRead++;
         }
         else {
             throw cRuntimeError("Received unhandled vehicle subscription result");
         }
     }
     // bail out if we didn't want to receive these subscription results
     if (!isSubscribed) return;
     // make sure we got updates for all attributes
     if (numRead != 8) return;
     Coord p = connection->traci2omnet(TraCICoord(px, py));
     if ((p.x < 0) || (p.y < 0)) throw cRuntimeError("received bad node position (%.2f, %.2f), translated to (%.2f, %.2f)", px, py, p.x, p.y);
     Heading heading = connection->traci2omnetHeading(angle_traci);
     cModule* mod = getManagedModule(objectId);
     // is it in the ROI?
     bool inRoi = !roi.hasConstraints() ? true : (roi.onAnyRectangle(TraCICoord(px, py)) || roi.partOfRoads(edge));
     if (!inRoi) {
         if (mod) {
             deleteManagedModule(objectId);
             EV_DEBUG << "Vehicle #" << objectId << " left region of interest" << endl;
         }
         else if (unEquippedHosts.find(objectId) != unEquippedHosts.end()) {
             unEquippedHosts.erase(objectId);
             EV_DEBUG << "Vehicle (unequipped) # " << objectId << " left region of interest" << endl;
         }
         return;
     }
     if (isModuleUnequipped(objectId)) {
         return;
     }
     if (!mod) {
         // no such module - need to create
         std::string vType = commandIfc->vehicle(objectId).getTypeId();
         std::string mType, mName, mDisplayString;
         TypeMapping::iterator iType, iName, iDisplayString;
         TypeMapping::iterator i;
         iType = moduleType.find(vType);
         if (iType == moduleType.end()) {
             iType = moduleType.find("*");
             if (iType == moduleType.end()) throw cRuntimeError("cannot find a module type for vehicle type \"%s\"", vType.c_str());
         }
         mType = iType->second;
         // search for module name
         iName = moduleName.find(vType);
         if (iName == moduleName.end()) {
             iName = moduleName.find(std::string("*"));
             if (iName == moduleName.end()) throw cRuntimeError("cannot find a module name for vehicle type \"%s\"", vType.c_str());
         }
         mName = iName->second;
         if (moduleDisplayString.size() != 0) {
             iDisplayString = moduleDisplayString.find(vType);
             if (iDisplayString == moduleDisplayString.end()) {
                 iDisplayString = moduleDisplayString.find("*");
                 if (iDisplayString == moduleDisplayString.end()) throw cRuntimeError("cannot find a module display string for vehicle type \"%s\"", vType.c_str());
             }
             mDisplayString = iDisplayString->second;
         }
         else {
             mDisplayString = "";
         }
         if (mType != "0") {
             addModule(objectId, mType, mName, mDisplayString, p, edge, speed, heading, VehicleSignalSet(signals), length, height, width);
             EV_DEBUG << "Added vehicle #" << objectId << endl;
         }
     }
     else {
         // module existed - update position
         EV_DEBUG << "module " << objectId << " moving to " << p.x << "," << p.y << endl;
         updateModulePosition(mod, p, edge, speed, heading, VehicleSignalSet(signals));
     }
 }
References activeVehicleCount, addModule(), commandIfc, connection, deleteManagedModule(), getManagedModule(), veins::TraCIRegionOfInterest::hasConstraints(), veins::TraCIConstants::ID_LIST, isModuleUnequipped(), moduleDisplayString, moduleName, moduleType, veins::TraCIRegionOfInterest::onAnyRectangle(), veins::TraCIRegionOfInterest::partOfRoads(), veins::TraCIConstants::POSITION_2D, roi, veins::TraCIConstants::RTYPE_NOTIMPLEMENTED, veins::TraCIConstants::RTYPE_OK, subscribedVehicles, subscribeToVehicleVariables(), veins::TraCIConstants::TYPE_DOUBLE, veins::TraCIConstants::TYPE_INTEGER, veins::TraCIConstants::TYPE_STRING, veins::TraCIConstants::TYPE_STRINGLIST, unEquippedHosts, unsubscribeFromVehicleVariables(), updateModulePosition(), veins::TraCIConstants::VAR_ANGLE, veins::TraCIConstants::VAR_HEIGHT, veins::TraCIConstants::VAR_LENGTH, veins::TraCIConstants::VAR_POSITION, veins::TraCIConstants::VAR_ROAD_ID, veins::TraCIConstants::VAR_SIGNALS, veins::TraCIConstants::VAR_SPEED, veins::TraCIConstants::VAR_WIDTH, veins::Coord::x, and veins::Coord::y.
Referenced by processSubcriptionResult().
subscribeToTrafficLightVariables()
void TraCIScenarioManager::subscribeToTrafficLightVariables (std::string tlId) protected
Definition at line 681 of file TraCIScenarioManager.cc.
 {
     // subscribe to some attributes of the traffic light system
     simtime_t beginTime = 0;
     simtime_t endTime = SimTime::getMaxTime();
     std::string objectId = tlId;
     uint8_t variableNumber = 4;
     uint8_t variable1 = TL_CURRENT_PHASE;
     uint8_t variable2 = TL_CURRENT_PROGRAM;
     uint8_t variable3 = TL_NEXT_SWITCH;
     uint8_t variable4 = TL_RED_YELLOW_GREEN_STATE;
     TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_TL_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber << variable1 << variable2 << variable3 << variable4);
     processSubcriptionResult(buf);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SUBSCRIBE_TL_VARIABLE, connection, veins::TraCIBuffer::eof(), processSubcriptionResult(), veins::TraCIConstants::TL_CURRENT_PHASE, veins::TraCIConstants::TL_CURRENT_PROGRAM, veins::TraCIConstants::TL_NEXT_SWITCH, and veins::TraCIConstants::TL_RED_YELLOW_GREEN_STATE.
Referenced by init_traci().
subscribeToVehicleVariables()
void TraCIScenarioManager::subscribeToVehicleVariables (std::string vehicleId) protected
Definition at line 643 of file TraCIScenarioManager.cc.
 {
     // subscribe to some attributes of the vehicle
     simtime_t beginTime = 0;
     simtime_t endTime = SimTime::getMaxTime();
     std::string objectId = vehicleId;
     std::list<uint8_t> variables;
     variables.push_back(VAR_POSITION);
     variables.push_back(VAR_ROAD_ID);
     variables.push_back(VAR_SPEED);
     variables.push_back(VAR_ANGLE);
     variables.push_back(VAR_SIGNALS);
     variables.push_back(VAR_LENGTH);
     variables.push_back(VAR_HEIGHT);
     variables.push_back(VAR_WIDTH);
     uint8_t variableNumber = variables.size();
     TraCIBuffer buf1;
     buf1 << beginTime << endTime << objectId << variableNumber;
     for (auto variable : variables) {
         buf1 << variable;
     }
     TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_VEHICLE_VARIABLE, buf1);
     processSubcriptionResult(buf);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SUBSCRIBE_VEHICLE_VARIABLE, connection, veins::TraCIBuffer::eof(), processSubcriptionResult(), veins::TraCIConstants::VAR_ANGLE, veins::TraCIConstants::VAR_HEIGHT, veins::TraCIConstants::VAR_LENGTH, veins::TraCIConstants::VAR_POSITION, veins::TraCIConstants::VAR_ROAD_ID, veins::TraCIConstants::VAR_SIGNALS, veins::TraCIConstants::VAR_SPEED, and veins::TraCIConstants::VAR_WIDTH.
Referenced by processVehicleSubscription().
unsubscribeFromTrafficLightVariables()
void TraCIScenarioManager::unsubscribeFromTrafficLightVariables (std::string tlId) protected
Definition at line 698 of file TraCIScenarioManager.cc.
 {
     // unsubscribe from some attributes of the traffic light system
     // this method is mainly for completeness as traffic lights are not supposed to be removed at runtime
     simtime_t beginTime = 0;
     simtime_t endTime = SimTime::getMaxTime();
     std::string objectId = tlId;
     uint8_t variableNumber = 0;
     TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_TL_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SUBSCRIBE_TL_VARIABLE, connection, and veins::TraCIBuffer::eof().
unsubscribeFromVehicleVariables()
void TraCIScenarioManager::unsubscribeFromVehicleVariables (std::string vehicleId) protected
Definition at line 670 of file TraCIScenarioManager.cc.
 {
     // subscribe to some attributes of the vehicle
     simtime_t beginTime = 0;
     simtime_t endTime = SimTime::getMaxTime();
     std::string objectId = vehicleId;
     uint8_t variableNumber = 0;
     TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SUBSCRIBE_VEHICLE_VARIABLE, connection, and veins::TraCIBuffer::eof().
Referenced by processVehicleSubscription().
updateModulePosition()
void TraCIScenarioManager::updateModulePosition (cModule * mod, const Coord & p, const std::string & edge, double speed, Heading heading, VehicleSignalSet signals) protected virtual
Definition at line 504 of file TraCIScenarioManager.cc.
 {
     // update position in TraCIMobility
     auto mobilityModules = getSubmodulesOfType<TraCIMobility>(mod);
     for (auto mm : mobilityModules) {
         mm->nextPosition(p, edge, speed, heading, signals);
     }
 }
Referenced by processVehicleSubscription().
Member Data Documentation
activeVehicleCount
uint32_t veins::TraCIScenarioManager::activeVehicleCount protected
number of vehicles, be it parking or driving
Definition at line 156 of file TraCIScenarioManager.h.
Referenced by initialize(), processSimSubscription(), and processVehicleSubscription().
annotations
AnnotationManager* veins::TraCIScenarioManager::annotations protected
Definition at line 147 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
areaSum
double veins::TraCIScenarioManager::areaSum protected
Definition at line 145 of file TraCIScenarioManager.h.
Referenced by finish(), init_traci(), and initialize().
autoShutdown
bool veins::TraCIScenarioManager::autoShutdown protected
Shutdown module as soon as no more vehicles are in the simulation.
Definition at line 141 of file TraCIScenarioManager.h.
Referenced by initialize(), and processSimSubscription().
autoShutdownTriggered
bool veins::TraCIScenarioManager::autoShutdownTriggered protected
Definition at line 159 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), initialize(), and processSimSubscription().
commandIfc
std::unique_ptr<TraCICommandInterface> veins::TraCIScenarioManager::commandIfc protected
Definition at line 149 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and processVehicleSubscription().
connectAndStartTrigger
cMessage* veins::TraCIScenarioManager::connectAndStartTrigger protected
self-message scheduled for when to connect to TraCI server and start running
Definition at line 160 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), initialize(), and ~TraCIScenarioManager().
connectAt
simtime_t veins::TraCIScenarioManager::connectAt protected
when to connect to TraCI server (must be the initial timestep of the server)
Definition at line 125 of file TraCIScenarioManager.h.
Referenced by initialize().
connection
std::unique_ptr<TraCIConnection> veins::TraCIScenarioManager::connection protected
Definition at line 148 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), handleSelfMsg(), init_traci(), processVehicleSubscription(), subscribeToTrafficLightVariables(), subscribeToVehicleVariables(), unsubscribeFromTrafficLightVariables(), unsubscribeFromVehicleVariables(), and ~TraCIScenarioManager().
drivingVehicleCount
uint32_t veins::TraCIScenarioManager::drivingVehicleCount protected
number of driving, as reported by sumo
Definition at line 158 of file TraCIScenarioManager.h.
Referenced by initialize(), and processSimSubscription().
executeOneTimestepTrigger
cMessage* veins::TraCIScenarioManager::executeOneTimestepTrigger protected
self-message scheduled for when to next call executeOneTimestep
Definition at line 161 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), handleSelfMsg(), initialize(), and ~TraCIScenarioManager().
firstStepAt
simtime_t veins::TraCIScenarioManager::firstStepAt protected
when to start synchronizing with the TraCI server (-1: immediately after connecting)
Definition at line 126 of file TraCIScenarioManager.h.
Referenced by initialize().
host
std::string veins::TraCIScenarioManager::host protected
Definition at line 133 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and initialize().
hosts
std::map<std::string, cModule*> veins::TraCIScenarioManager::hosts protected
vector of all hosts managed by us
Definition at line 152 of file TraCIScenarioManager.h.
Referenced by addModule(), deleteManagedModule(), getManagedModule(), initialize(), and preNetworkFinish().
ignoreGuiCommands
bool veins::TraCIScenarioManager::ignoreGuiCommands protected
whether to ignore all TraCI commands that only make sense when the server has a graphical user interface
Definition at line 143 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and initialize().
moduleDisplayString
TypeMapping veins::TraCIScenarioManager::moduleDisplayString protected
module displayString to be used in the simulation for each managed vehicle
Definition at line 132 of file TraCIScenarioManager.h.
Referenced by parseModuleTypes(), and processVehicleSubscription().
moduleName
TypeMapping veins::TraCIScenarioManager::moduleName protected
module name to be used in the simulation for each managed vehicle
Definition at line 131 of file TraCIScenarioManager.h.
Referenced by parseModuleTypes(), and processVehicleSubscription().
moduleType
TypeMapping veins::TraCIScenarioManager::moduleType protected
module type to be used in the simulation for each managed vehicle
Definition at line 130 of file TraCIScenarioManager.h.
Referenced by parseModuleTypes(), and processVehicleSubscription().
nextNodeVectorIndex
size_t veins::TraCIScenarioManager::nextNodeVectorIndex protected
next OMNeT++ module vector index to use
Definition at line 151 of file TraCIScenarioManager.h.
Referenced by addModule(), and initialize().
parkingVehicleCount
uint32_t veins::TraCIScenarioManager::parkingVehicleCount protected
number of parking vehicles, derived from parking start/end events
Definition at line 157 of file TraCIScenarioManager.h.
Referenced by initialize(), and processSimSubscription().
penetrationRate
double veins::TraCIScenarioManager::penetrationRate protected
Definition at line 142 of file TraCIScenarioManager.h.
Referenced by addModule(), and initialize().
port
int veins::TraCIScenarioManager::port protected
Definition at line 134 of file TraCIScenarioManager.h.
Referenced by getPortNumber(), veins::TraCIScenarioManagerForker::getPortNumber(), handleSelfMsg(), initialize(), and veins::TraCIScenarioManagerForker::startServer().
roi
TraCIRegionOfInterest veins::TraCIScenarioManager::roi protected
Can return whether a given position lies within the simulation's region of interest.
Modules are destroyed and re-created as managed vehicles leave and re-enter the ROI
Definition at line 144 of file TraCIScenarioManager.h.
Referenced by init_traci(), initialize(), and processVehicleSubscription().
subscribedVehicles
std::set<std::string> veins::TraCIScenarioManager::subscribedVehicles protected
all vehicles we have already subscribed to
Definition at line 154 of file TraCIScenarioManager.h.
Referenced by initialize(), processSimSubscription(), and processVehicleSubscription().
traciInitialized
bool veins::TraCIScenarioManager::traciInitialized = false protected
Flag indicating whether the init_traci routine has been run.
Note that it will change to false again once set, even during shutdown.
Definition at line 124 of file TraCIScenarioManager.h.
Referenced by init_traci().
traciInitializedSignal
const simsignal_t TraCIScenarioManager::traciInitializedSignal = registerSignal("org_car2x_veins_modules_mobility_traciInitialized") static
Definition at line 69 of file TraCIScenarioManager.h.
Referenced by init_traci(), and veins::RoadsCanvasVisualizer::initialize().
traciModuleAddedSignal
const simsignal_t TraCIScenarioManager::traciModuleAddedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleAdded") static
Definition at line 71 of file TraCIScenarioManager.h.
Referenced by addModule(), veins::TraCIVehicleInserter::finish(), veins::TraCIVehicleInserter::initialize(), and veins::TraCIVehicleInserter::receiveSignal().
traciModulePreInitSignal
const simsignal_t TraCIScenarioManager::traciModulePreInitSignal = registerSignal("org_car2x_veins_modules_mobility_traciModulePreInit") static
Definition at line 70 of file TraCIScenarioManager.h.
Referenced by addModule().
traciModuleRemovedSignal
const simsignal_t TraCIScenarioManager::traciModuleRemovedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleRemoved") static
Definition at line 72 of file TraCIScenarioManager.h.
Referenced by deleteManagedModule().
traciTimestepBeginSignal
const simsignal_t TraCIScenarioManager::traciTimestepBeginSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepBegin") static
Definition at line 73 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), veins::TraCIVehicleInserter::finish(), veins::TraCIVehicleInserter::initialize(), and veins::TraCIVehicleInserter::receiveSignal().
traciTimestepEndSignal
const simsignal_t TraCIScenarioManager::traciTimestepEndSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepEnd") static
Definition at line 74 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep().
trafficLightModuleDisplayString
std::string veins::TraCIScenarioManager::trafficLightModuleDisplayString protected
module displayString to be used in the simulation for each managed vehicle
Definition at line 138 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
trafficLightModuleIds
std::vector<std::string> veins::TraCIScenarioManager::trafficLightModuleIds protected
list of traffic light module ids that is subscribed to (whitelist)
Definition at line 139 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
trafficLightModuleName
std::string veins::TraCIScenarioManager::trafficLightModuleName protected
module name to be used in the simulation for each managed traffic light
Definition at line 137 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
trafficLightModuleType
std::string veins::TraCIScenarioManager::trafficLightModuleType protected
module type to be used in the simulation for each managed traffic light
Definition at line 136 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
trafficLights
std::map<std::string, cModule*> veins::TraCIScenarioManager::trafficLights protected
vector of all traffic lights managed by us
Definition at line 155 of file TraCIScenarioManager.h.
Referenced by init_traci(), initialize(), and processTrafficLightSubscription().
unEquippedHosts
std::set<std::string> veins::TraCIScenarioManager::unEquippedHosts protected
Definition at line 153 of file TraCIScenarioManager.h.
Referenced by addModule(), isModuleUnequipped(), processSimSubscription(), and processVehicleSubscription().
updateInterval
simtime_t veins::TraCIScenarioManager::updateInterval protected
time interval of hosts' position updates
Definition at line 127 of file TraCIScenarioManager.h.
Referenced by addModule(), executeOneTimestep(), init_traci(), and initialize().
vehicleObstacleControl
VehicleObstacleControl* veins::TraCIScenarioManager::vehicleObstacleControl protected
Definition at line 165 of file TraCIScenarioManager.h.
Referenced by addModule(), deleteManagedModule(), and initialize().
vehicleObstacles
std::map<const BaseMobility*, const MobileHostObstacle*> veins::TraCIScenarioManager::vehicleObstacles protected
Definition at line 164 of file TraCIScenarioManager.h.
Referenced by addModule(), and deleteManagedModule().
world
BaseWorldUtility* veins::TraCIScenarioManager::world protected
Definition at line 163 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
The documentation for this class was generated from the following files:
TraCIScenarioManager.h
TraCIScenarioManager.cc