Veins: veins::NakagamiFading Class Reference
veins::NakagamiFading Class Reference
A simple model to account for fast fading using the Nakagami Distribution.
#include <NakagamiFading.h>
Public Member Functions
NakagamiFading (cComponent *owner, bool constM, double m)
~NakagamiFading () override
void filterSignal (Signal *signal) override
Simple Nakagami-m fading (based on a constant factor across all time and frequencies).
Public Member Functions inherited from veins::AnalogueModel
AnalogueModel (cComponent *owner)
virtual ~AnalogueModel ()
virtual bool neverIncreasesPower ()
If the model never increases the power level of any signal given to filterSignal, it returns true here.
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Attributes
bool constM
Whether to use a constant m or a m based on distance.
double m
The value of the coefficient m.
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
A simple model to account for fast fading using the Nakagami Distribution.
See the Veins website for a tutorial, documentation, and publications .
An in-depth description of the model is available at: Todo: add paper
Author
David Eckhoff, Christoph Sommer
Definition at line 45 of file NakagamiFading.h.
Constructor & Destructor Documentation
NakagamiFading()
veins::NakagamiFading::NakagamiFading (cComponent * owner, bool constM, double m) inline
Definition at line 48 of file NakagamiFading.h.
         : AnalogueModel(owner)
         , constM(constM)
         , m(m)
     {
     }
~NakagamiFading()
veins::NakagamiFading::~NakagamiFading () inline override
Definition at line 55 of file NakagamiFading.h.
     {
     }
Member Function Documentation
filterSignal()
void NakagamiFading::filterSignal (Signal * signal) override virtual
Simple Nakagami-m fading (based on a constant factor across all time and frequencies).
Implements veins::AnalogueModel.
Definition at line 31 of file NakagamiFading.cc.
 {
     auto senderPos = signal->getSenderPoa().pos.getPositionAt();
     auto receiverPos = signal->getReceiverPoa().pos.getPositionAt();
     const double M_CLOSE = 1.5;
     const double M_FAR = 0.75;
     const double DIS_THRESHOLD = 80;
     EV_TRACE << "Add NakagamiFading ..." << endl;
     // get average TX power
     // FIXME: really use average power (instead of max)
     EV_TRACE << "Finding max TX power ..." << endl;
     double sendPower_mW = signal->getMax();
     EV_TRACE << "TX power is " << FWMath::mW2dBm(sendPower_mW) << " dBm" << endl;
     // get m value
     double m = this->m;
     {
         const Coord senderPos2D(senderPos.x, senderPos.y);
         const Coord receiverPos2D(receiverPos.x, receiverPos.y);
         double d = senderPos2D.distance(receiverPos2D);
         if (!constM) {
             m = (d < DIS_THRESHOLD) ? M_CLOSE : M_FAR;
         }
     }
     // calculate average RX power
     double recvPower_mW = (RNGCONTEXT gamma_d(m, sendPower_mW / 1000 / m)) * 1000.0;
     if (recvPower_mW > sendPower_mW) {
         recvPower_mW = sendPower_mW;
     }
     EV_TRACE << "RX power is " << FWMath::mW2dBm(recvPower_mW) << " dBm" << endl;
     // infer average attenuation
     double factor = recvPower_mW / sendPower_mW;
     EV_TRACE << "factor is: " << factor << " (i.e. " << FWMath::mW2dBm(factor) << " dB)" << endl;
     *signal *= factor;
 }
References constM, veins::Coord::distance(), veins::Signal::getMax(), veins::AntennaPosition::getPositionAt(), veins::Signal::getReceiverPoa(), veins::Signal::getSenderPoa(), m, veins::FWMath::mW2dBm(), veins::POA::pos, and RNGCONTEXT.
Member Data Documentation
constM
bool veins::NakagamiFading::constM protected
Whether to use a constant m or a m based on distance.
Definition at line 63 of file NakagamiFading.h.
Referenced by filterSignal().
m
double veins::NakagamiFading::m protected
The value of the coefficient m.
Definition at line 66 of file NakagamiFading.h.
Referenced by filterSignal().
The documentation for this class was generated from the following files:
NakagamiFading.h
NakagamiFading.cc