Veins: veins::TraCICommandInterface::GuiView Class Reference
veins::TraCICommandInterface::GuiView Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
GuiView (TraCICommandInterface *traci, std::string viewId)
std::string getScheme ()
void setScheme (std::string name)
double getZoom ()
void setZoom (double zoom)
void setBoundary (Coord p1, Coord p2)
void takeScreenshot (std::string filename="", int32_t width=-1, int32_t height=-1)
void trackVehicle (std::string vehicleId)
Track the vehicle identified by vehicleId in the Sumo GUI.
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string viewId
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Definition at line 512 of file TraCICommandInterface.h.
Constructor & Destructor Documentation
GuiView()
veins::TraCICommandInterface::GuiView::GuiView (TraCICommandInterface * traci, std::string viewId) inline
Definition at line 514 of file TraCICommandInterface.h.
             : HasLogProxy(traci->owner)
             , traci(traci)
             , viewId(viewId)
         {
             connection = &traci->connection;
         }
References veins::TraCICommandInterface::connection.
Member Function Documentation
getScheme()
std::string veins::TraCICommandInterface::GuiView::getScheme ()
Definition at line 1341 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return std::string();
     }
     return traci->genericGetString(CMD_GET_GUI_VARIABLE, viewId, VAR_VIEW_SCHEMA, RESPONSE_GET_GUI_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_GUI_VARIABLE, veins::TraCIConstants::RESPONSE_GET_GUI_VARIABLE, and veins::TraCIConstants::VAR_VIEW_SCHEMA.
getZoom()
double veins::TraCICommandInterface::GuiView::getZoom ()
Definition at line 1360 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return 0;
     }
     return traci->genericGetDouble(CMD_GET_GUI_VARIABLE, viewId, VAR_VIEW_ZOOM, RESPONSE_GET_GUI_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_GUI_VARIABLE, veins::TraCIConstants::RESPONSE_GET_GUI_VARIABLE, and veins::TraCIConstants::VAR_VIEW_ZOOM.
setBoundary()
void veins::TraCICommandInterface::GuiView::setBoundary (Coord p1, Coord p2)
Definition at line 1378 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return;
     }
     TraCICoord p1 = connection->omnet2traci(p1_);
     TraCICoord p2 = connection->omnet2traci(p2_);
     if (traci->getNetBoundaryType() == TYPE_POLYGON) {
         uint8_t count = 2;
         TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_VIEW_BOUNDARY) << viewId << static_cast<uint8_t>(TYPE_POLYGON) << count << p1.x << p1.y << p2.x << p2.y);
         ASSERT(buf.eof());
     }
     else {
         TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_VIEW_BOUNDARY) << viewId << static_cast<uint8_t>(TYPE_BOUNDINGBOX) << p1.x << p1.y << p2.x << p2.y);
         ASSERT(buf.eof());
     }
 }
References veins::TraCIConstants::CMD_SET_GUI_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::omnet2traci(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_BOUNDINGBOX, veins::TraCIConstants::TYPE_POLYGON, veins::TraCIConstants::VAR_VIEW_BOUNDARY, veins::TraCICoord::x, and veins::TraCICoord::y.
setScheme()
void veins::TraCICommandInterface::GuiView::setScheme (std::string name)
Definition at line 1350 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return;
     }
     TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_VIEW_SCHEMA) << viewId << static_cast<uint8_t>(TYPE_STRING) << name);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_GUI_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_VIEW_SCHEMA.
setZoom()
void veins::TraCICommandInterface::GuiView::setZoom (double zoom)
Definition at line 1368 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return;
     }
     TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_VIEW_ZOOM) << viewId << static_cast<uint8_t>(TYPE_DOUBLE) << zoom);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_GUI_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_DOUBLE, and veins::TraCIConstants::VAR_VIEW_ZOOM.
takeScreenshot()
void veins::TraCICommandInterface::GuiView::takeScreenshot (std::string filename = "", int32_t width = -1, int32_t height = -1)
Definition at line 1398 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return;
     }
     if (filename == "") {
         // get absolute path of results/ directory
         const char* myResultsDir = cSimulation::getActiveSimulation()->getEnvir()->getConfigEx()->getVariable(CFGVAR_RESULTDIR);
         char* s = realpath(myResultsDir, nullptr);
         std::string absolutePath = s;
         free(s);
         // get run id
         const char* myRunID = cSimulation::getActiveSimulation()->getEnvir()->getConfigEx()->getVariable(CFGVAR_RUNID);
         // build filename from this
         char ss[512];
         snprintf(ss, sizeof(ss), "%s/screenshot-%s-@%08.2f.png", absolutePath.c_str(), myRunID, simTime().dbl());
         filename = ss;
     }
     const auto apiVersion = traci->versionConfig.version;
     if (apiVersion == 15 || apiVersion == 16 || apiVersion == 17) {
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 3;
         uint8_t filenameType = TYPE_STRING;
         uint8_t widthType = TYPE_INTEGER;
         uint8_t heightType = TYPE_INTEGER;
         TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_SCREENSHOT) << viewId << variableType << count << filenameType << filename << widthType << width << heightType << height);
         ASSERT(buf.eof());
     }
     else if (apiVersion == 18 || apiVersion == 19 || apiVersion == 20) {
         uint8_t filenameType = TYPE_STRING;
         TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_SCREENSHOT) << viewId << filenameType << filename);
         ASSERT(buf.eof());
     }
     else {
         throw cRuntimeError("Invalid API version used, check your code.");
     }
 }
References veins::TraCIConstants::CMD_SET_GUI_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_INTEGER, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_SCREENSHOT.
Referenced by veins::TraCIScreenRecorder::handleMessage().
trackVehicle()
void veins::TraCICommandInterface::GuiView::trackVehicle (std::string vehicleId)
Track the vehicle identified by vehicleId in the Sumo GUI.
Definition at line 1440 of file TraCICommandInterface.cc.
 {
     if (traci->ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return;
     }
     TraCIBuffer buf = connection->query(CMD_SET_GUI_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_TRACK_VEHICLE) << viewId << static_cast<uint8_t>(TYPE_STRING) << vehicleId);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_GUI_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_TRACK_VEHICLE.
Member Data Documentation
connection
TraCIConnection* veins::TraCICommandInterface::GuiView::connection protected
Definition at line 536 of file TraCICommandInterface.h.
traci
TraCICommandInterface* veins::TraCICommandInterface::GuiView::traci protected
Definition at line 535 of file TraCICommandInterface.h.
viewId
std::string veins::TraCICommandInterface::GuiView::viewId protected
Definition at line 537 of file TraCICommandInterface.h.
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc