Veins: veins::TraCICommandInterface::Polygon Class Reference
veins::TraCICommandInterface::Polygon Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
Polygon (TraCICommandInterface *traci, std::string polyId)
std::string getTypeId ()
std::list< Coord > getShape ()
void setShape (const std::list< Coord > &points)
void remove (int32_t layer)
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string polyId
Detailed Description
Definition at line 408 of file TraCICommandInterface.h.
Constructor & Destructor Documentation
Polygon()
veins::TraCICommandInterface::Polygon::Polygon (TraCICommandInterface * traci, std::string polyId) inline
Definition at line 410 of file TraCICommandInterface.h.
             : traci(traci)
             , polyId(polyId)
         {
             connection = &traci->connection;
         }
References veins::TraCICommandInterface::connection.
Member Function Documentation
getShape()
std::list< Coord > veins::TraCICommandInterface::Polygon::getShape ()
Definition at line 1018 of file TraCICommandInterface.cc.
 {
     return traci->genericGetCoordList(CMD_GET_POLYGON_VARIABLE, polyId, VAR_SHAPE, RESPONSE_GET_POLYGON_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_POLYGON_VARIABLE, veins::TraCIConstants::RESPONSE_GET_POLYGON_VARIABLE, and veins::TraCIConstants::VAR_SHAPE.
getTypeId()
std::string veins::TraCICommandInterface::Polygon::getTypeId ()
Definition at line 1013 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_POLYGON_VARIABLE, polyId, VAR_TYPE, RESPONSE_GET_POLYGON_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_POLYGON_VARIABLE, veins::TraCIConstants::RESPONSE_GET_POLYGON_VARIABLE, and veins::TraCIConstants::VAR_TYPE.
remove()
void veins::TraCICommandInterface::Polygon::remove (int32_t layer)
Definition at line 1057 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     p << static_cast<uint8_t>(REMOVE) << polyId;
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     TraCIBuffer buf = connection->query(CMD_SET_POLYGON_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_POLYGON_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::REMOVE, and veins::TraCIConstants::TYPE_INTEGER.
setShape()
void veins::TraCICommandInterface::Polygon::setShape (const std::list< Coord > & points)
Definition at line 1023 of file TraCICommandInterface.cc.
 {
     TraCIBuffer buf;
     uint8_t count = static_cast<uint8_t>(points.size());
     buf << static_cast<uint8_t>(VAR_SHAPE) << polyId << static_cast<uint8_t>(TYPE_POLYGON) << count;
     for (std::list<Coord>::const_iterator i = points.begin(); i != points.end(); ++i) {
         const TraCICoord& pos = connection->omnet2traci(*i);
         buf << static_cast<double>(pos.x) << static_cast<double>(pos.y);
     }
     TraCIBuffer obuf = connection->query(CMD_SET_POLYGON_VARIABLE, buf);
     ASSERT(obuf.eof());
 }
References veins::TraCIConstants::CMD_SET_POLYGON_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::omnet2traci(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_POLYGON, veins::TraCIConstants::VAR_SHAPE, veins::TraCICoord::x, and veins::TraCICoord::y.
Member Data Documentation
connection
TraCIConnection* veins::TraCICommandInterface::Polygon::connection protected
Definition at line 424 of file TraCICommandInterface.h.
polyId
std::string veins::TraCICommandInterface::Polygon::polyId protected
Definition at line 425 of file TraCICommandInterface.h.
traci
TraCICommandInterface* veins::TraCICommandInterface::Polygon::traci protected
Definition at line 423 of file TraCICommandInterface.h.
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc