Veins: veins::TraCIScenarioManagerAccess Class Reference
veins::TraCIScenarioManagerAccess Class Reference
#include <TraCIScenarioManager.h>
Public Member Functions
TraCIScenarioManager * get ()
Detailed Description
Definition at line 206 of file TraCIScenarioManager.h.
Member Function Documentation
get()
TraCIScenarioManager* veins::TraCIScenarioManagerAccess::get () inline
Definition at line 208 of file TraCIScenarioManager.h.
     {
         return FindModule<TraCIScenarioManager*>::findGlobalModule();
     };
References veins::FindModule< T >::findGlobalModule().
Referenced by veins::TraCIMobility::getManager(), veins::TraCITrafficLightInterface::getManager(), veins::TraCIScreenRecorder::handleMessage(), veins::AnnotationManager::hide(), veins::TraCIVehicleInserter::initialize(), veins::RoadsCanvasVisualizer::initialize(), and veins::AnnotationManager::show().
The documentation for this class was generated from the following file:
TraCIScenarioManager.h