Veins: veins::TraCITrafficLightProgram Class Reference
veins::TraCITrafficLightProgram Class Reference
#include <TraCITrafficLightProgram.h>
Classes
struct Logic
struct Phase
Public Member Functions
TraCITrafficLightProgram (std::string id="")
void addLogic (const Logic &logic)
TraCITrafficLightProgram::Logic getLogic (const std::string &lid) const
bool hasLogic (const std::string &lid) const
Private Attributes
std::string id
std::map< std::string, TraCITrafficLightProgram::Logic > logics
Detailed Description
Definition at line 34 of file TraCITrafficLightProgram.h.
Constructor & Destructor Documentation
TraCITrafficLightProgram()
TraCITrafficLightProgram::TraCITrafficLightProgram (std::string id = "")
Definition at line 39 of file TraCITrafficLightProgram.cc.
     : id(id)
     , logics()
 {
 }
Member Function Documentation
addLogic()
void TraCITrafficLightProgram::addLogic (const Logic & logic)
Definition at line 45 of file TraCITrafficLightProgram.cc.
 {
     logics[logic.id] = logic;
 }
References veins::TraCITrafficLightProgram::Logic::id, and logics.
Referenced by veins::TraCICommandInterface::Trafficlight::getProgramDefinition().
getLogic()
TraCITrafficLightProgram::Logic TraCITrafficLightProgram::getLogic (const std::string & lid) const
Definition at line 50 of file TraCITrafficLightProgram.cc.
 {
     return logics.at(lid);
 }
References logics.
Referenced by veins::TraCITrafficLightInterface::getCurrentLogic().
hasLogic()
bool TraCITrafficLightProgram::hasLogic (const std::string & lid) const
Definition at line 55 of file TraCITrafficLightProgram.cc.
 {
     return logics.find(lid) != logics.end();
 }
References logics.
Referenced by veins::TraCITrafficLightInterface::setCurrentLogicById().
Member Data Documentation
id
std::string veins::TraCITrafficLightProgram::id private
Definition at line 61 of file TraCITrafficLightProgram.h.
logics
std::map<std::string, TraCITrafficLightProgram::Logic> veins::TraCITrafficLightProgram::logics private
Definition at line 62 of file TraCITrafficLightProgram.h.
Referenced by addLogic(), getLogic(), and hasLogic().
The documentation for this class was generated from the following files:
TraCITrafficLightProgram.h
TraCITrafficLightProgram.cc