Veins: veins::TraCIConnection Class Reference
veins::TraCIConnection Class Reference
#include <TraCIConnection.h>
Classes
class Result
Public Member Functions
void setNetbounds (TraCICoord netbounds1, TraCICoord netbounds2, int margin)
~TraCIConnection ()
TraCIBuffer query (uint8_t commandId, const TraCIBuffer &buf=TraCIBuffer(), Result *result=nullptr)
sends a single command via TraCI, checks status response, returns additional responses.
void sendMessage (std::string buf)
sends a message via TraCI (after adding the header)
std::string receiveMessage ()
receives a message via TraCI (and strips the header)
Heading traci2omnetHeading (double heading) const
convert TraCI heading to OMNeT++ heading (in rad)
double omnet2traciHeading (Heading heading) const
convert OMNeT++ heading (in rad) to TraCI heading
Coord traci2omnet (TraCICoord coord) const
convert TraCI coordinates to OMNeT++ coordinates
std::list< Coord > traci2omnet (const std::list< TraCICoord > &) const
TraCICoord omnet2traci (Coord coord) const
convert OMNeT++ coordinates to TraCI coordinates
std::list< TraCICoord > omnet2traci (const std::list< Coord > &) const
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Static Public Member Functions
static TraCIConnection * connect (cComponent *owner, const char *host, int port)
Private Member Functions
TraCIConnection (cComponent *owner, void *ptr)
Private Attributes
void * socketPtr
std::unique_ptr< TraCICoordinateTransformation > coordinateTransformation
Additional Inherited Members
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Definition at line 37 of file TraCIConnection.h.
Constructor & Destructor Documentation
~TraCIConnection()
veins::TraCIConnection::~TraCIConnection ()
Definition at line 84 of file TraCIConnection.cc.
 {
     if (socketPtr) {
         closesocket(socket(socketPtr));
         delete static_cast<SOCKET*>(socketPtr);
     }
 }
References veins::socket(), and socketPtr.
TraCIConnection()
veins::TraCIConnection::TraCIConnection (cComponent * owner, void * ptr) private
Definition at line 77 of file TraCIConnection.cc.
     : HasLogProxy(owner)
     , socketPtr(ptr)
 {
     ASSERT(socketPtr);
 }
References socketPtr.
Referenced by connect().
Member Function Documentation
connect()
TraCIConnection * veins::TraCIConnection::connect (cComponent * owner, const char * host, int port) static
Definition at line 92 of file TraCIConnection.cc.
 {
     EV_STATICCONTEXT;
     EV_INFO << "TraCIScenarioManager connecting to TraCI server" << endl;
     if (initsocketlibonce() != 0) throw cRuntimeError("Could not init socketlib");
     in_addr addr;
     struct hostent* host_ent;
     struct in_addr saddr;
     saddr.s_addr = inet_addr(host);
     if (saddr.s_addr != static_cast<unsigned int>(-1)) {
         addr = saddr;
     }
     else if ((host_ent = gethostbyname(host))) {
         addr = *((struct in_addr*) host_ent->h_addr_list[0]);
     }
     else {
         throw cRuntimeError("Invalid TraCI server address: %s", host);
         return nullptr;
     }
     sockaddr_in address;
     sockaddr* address_p = (sockaddr*) &address;
     memset(address_p, 0, sizeof(address));
     address.sin_family = AF_INET;
     address.sin_port = htons(port);
     address.sin_addr.s_addr = addr.s_addr;
     SOCKET* socketPtr = new SOCKET();
     for (int tries = 1; tries <= 10; ++tries) {
         *socketPtr = ::socket(AF_INET, SOCK_STREAM, 0);
         if (*socketPtr == INVALID_SOCKET) throw cRuntimeError("Could not create socket to connect to TraCI server");
         if (::connect(*socketPtr, address_p, sizeof(address)) >= 0) break;
         closesocket(socket(socketPtr));
         std::stringstream ss;
         ss << "Could not connect to TraCI server; error message: " << sock_errno() << ": " << strerror(sock_errno());
         std::string msg = ss.str();
         int sleepDuration = tries * .25 + 1;
         if (tries >= 10) {
             throw cRuntimeError("%s", msg.c_str());
         }
         else if (tries == 3) {
             EV_WARN << msg << " -- Will retry in " << sleepDuration << " second(s)." << std::endl;
         }
         sleep(sleepDuration);
     }
     {
         int x = 1;
         ::setsockopt(*socketPtr, IPPROTO_TCP, TCP_NODELAY, (const char*) &x, sizeof(x));
     }
     return new TraCIConnection(owner, socketPtr);
 }
References veins::HasLogProxy::owner, veins::socket(), socketPtr, and TraCIConnection().
Referenced by veins::TraCIScenarioManager::handleSelfMsg().
omnet2traci() [1/2]
std::list< TraCICoord > veins::TraCIConnection::omnet2traci (const std::list< Coord > & list) const
Definition at line 299 of file TraCIConnection.cc.
 {
     ASSERT(coordinateTransformation.get());
     return coordinateTransformation->omnet2traci(list);
 }
References coordinateTransformation.
omnet2traci() [2/2]
TraCICoord veins::TraCIConnection::omnet2traci (Coord coord) const
convert OMNeT++ coordinates to TraCI coordinates
Definition at line 293 of file TraCIConnection.cc.
 {
     ASSERT(coordinateTransformation.get());
     return coordinateTransformation->omnet2traci(coord);
 }
References coordinateTransformation.
Referenced by veins::TraCICommandInterface::addPoi(), veins::TraCICommandInterface::addPolygon(), veins::TraCICommandInterface::getDistance(), veins::TraCICommandInterface::getLonLat(), veins::TraCICommandInterface::getRoadMapPos(), veins::TraCICommandInterface::GuiView::setBoundary(), and veins::TraCICommandInterface::Polygon::setShape().
omnet2traciHeading()
double veins::TraCIConnection::omnet2traciHeading (Heading heading) const
convert OMNeT++ heading (in rad) to TraCI heading
Definition at line 311 of file TraCIConnection.cc.
 {
     ASSERT(coordinateTransformation.get());
     return coordinateTransformation->omnet2traciHeading(heading);
 }
References coordinateTransformation.
query()
TraCIBuffer veins::TraCIConnection::query (uint8_t commandId, const TraCIBuffer & buf = TraCIBuffer(), Result * result = nullptr)
sends a single command via TraCI, checks status response, returns additional responses.
Parameters
commandId command to send
buf additional parameters to send
result where to store return value (if set to nullptr, any return value other than RTYPE_OK will trigger an exception).
Definition at line 153 of file TraCIConnection.cc.
 {
     sendMessage(makeTraCICommand(commandId, buf));
     TraCIBuffer obuf(receiveMessage());
     uint8_t cmdLength;
     obuf >> cmdLength;
     uint8_t commandResp;
     obuf >> commandResp;
     ASSERT(commandResp == commandId);
     uint8_t resultCode;
     obuf >> resultCode;
     std::string description;
     obuf >> description;
     if (result != nullptr) {
         result->success = (resultCode == RTYPE_OK);
         result->not_impl = (resultCode == RTYPE_NOTIMPLEMENTED);
         result->message = description;
     }
     else {
         if (resultCode == RTYPE_NOTIMPLEMENTED) throw cRuntimeError("TraCI server reported command 0x%2x not implemented (\"%s\"). Might need newer version.", commandId, description.c_str());
         if (resultCode != RTYPE_OK) throw cRuntimeError("TraCI server reported status %d executing command 0x%2x (\"%s\").", (int) resultCode, commandId, description.c_str());
     }
     return obuf;
 }
References veins::makeTraCICommand(), veins::TraCIConnection::Result::message, veins::TraCIConnection::Result::not_impl, receiveMessage(), veins::TraCIConstants::RTYPE_NOTIMPLEMENTED, veins::TraCIConstants::RTYPE_OK, sendMessage(), and veins::TraCIConnection::Result::success.
Referenced by veins::TraCICommandInterface::addPoi(), veins::TraCICommandInterface::addPolygon(), veins::TraCICommandInterface::addRoute(), veins::TraCICommandInterface::addVehicle(), veins::TraCICommandInterface::Vehicle::changeRoute(), veins::TraCICommandInterface::Vehicle::changeVehicleRoute(), veins::TraCICommandInterface::genericGetCoord(), veins::TraCICommandInterface::genericGetCoordList(), veins::TraCICommandInterface::genericGetDouble(), veins::TraCICommandInterface::genericGetInt(), veins::TraCICommandInterface::genericGetString(), veins::TraCICommandInterface::genericGetStringList(), veins::TraCICommandInterface::genericGetTime(), veins::TraCICommandInterface::genericGetUnsignedByte(), veins::TraCICommandInterface::genericSetDouble(), veins::TraCICommandInterface::Vehicle::getColor(), veins::TraCICommandInterface::Trafficlight::getControlledLinks(), veins::TraCICommandInterface::getDistance(), veins::TraCICommandInterface::Vehicle::getLeader(), veins::TraCICommandInterface::getLonLat(), veins::TraCICommandInterface::Vehicle::getNextTls(), veins::TraCICommandInterface::Trafficlight::getProgramDefinition(), veins::TraCICommandInterface::getRoadMapPos(), veins::TraCICommandInterface::getVersion(), veins::TraCICommandInterface::initNetworkBoundaries(), veins::TraCICommandInterface::Vehicle::newRoute(), veins::TraCICommandInterface::Polygon::remove(), veins::TraCICommandInterface::Poi::remove(), veins::TraCICommandInterface::GuiView::setBoundary(), veins::TraCICommandInterface::Vehicle::setColor(), veins::TraCICommandInterface::Lane::setDisallowed(), veins::TraCICommandInterface::Trafficlight::setPhaseDuration(), veins::TraCICommandInterface::Trafficlight::setPhaseIndex(), veins::TraCICommandInterface::Trafficlight::setProgram(), veins::TraCICommandInterface::Trafficlight::setProgramDefinition(), veins::TraCICommandInterface::GuiView::setScheme(), veins::TraCICommandInterface::Polygon::setShape(), veins::TraCICommandInterface::Vehicle::setSpeedMode(), veins::TraCICommandInterface::Trafficlight::setState(), veins::TraCICommandInterface::GuiView::setZoom(), veins::TraCICommandInterface::Vehicle::slowDown(), veins::TraCICommandInterface::Vehicle::stopAt(), veins::TraCICommandInterface::GuiView::takeScreenshot(), and veins::TraCICommandInterface::GuiView::trackVehicle().
receiveMessage()
std::string veins::TraCIConnection::receiveMessage ()
receives a message via TraCI (and strips the header)
Definition at line 179 of file TraCIConnection.cc.
 {
     if (!socketPtr) throw cRuntimeError("Not connected to TraCI server");
     uint32_t msgLength;
     {
         char buf2[sizeof(uint32_t)];
         uint32_t bytesRead = 0;
         while (bytesRead < sizeof(uint32_t)) {
             int receivedBytes = ::recv(socket(socketPtr), reinterpret_cast<char*>(&buf2) + bytesRead, sizeof(uint32_t) - bytesRead, 0);
             if (receivedBytes > 0) {
                 bytesRead += receivedBytes;
             }
             else if (receivedBytes == 0) {
                 throw cRuntimeError("Connection to TraCI server closed unexpectedly. Check your server's log");
             }
             else {
                 if (sock_errno() == EINTR) continue;
                 if (sock_errno() == EAGAIN) continue;
                 throw cRuntimeError("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
             }
         }
         TraCIBuffer(std::string(buf2, sizeof(uint32_t))) >> msgLength;
     }
     uint32_t bufLength = msgLength - sizeof(msgLength);
     char buf[bufLength];
     {
         EV_TRACE << "Reading TraCI message of " << bufLength << " bytes" << endl;
         uint32_t bytesRead = 0;
         while (bytesRead < bufLength) {
             int receivedBytes = ::recv(socket(socketPtr), reinterpret_cast<char*>(&buf) + bytesRead, bufLength - bytesRead, 0);
             if (receivedBytes > 0) {
                 bytesRead += receivedBytes;
             }
             else if (receivedBytes == 0) {
                 throw cRuntimeError("Connection to TraCI server closed unexpectedly. Check your server's log");
             }
             else {
                 if (sock_errno() == EINTR) continue;
                 if (sock_errno() == EAGAIN) continue;
                 throw cRuntimeError("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
             }
         }
     }
     return std::string(buf, bufLength);
 }
References veins::socket(), and socketPtr.
Referenced by query().
sendMessage()
void veins::TraCIConnection::sendMessage (std::string buf)
sends a message via TraCI (after adding the header)
Definition at line 227 of file TraCIConnection.cc.
 {
     if (!socketPtr) throw cRuntimeError("Not connected to TraCI server");
     {
         uint32_t msgLength = sizeof(uint32_t) + buf.length();
         TraCIBuffer buf2 = TraCIBuffer();
         buf2 << msgLength;
         uint32_t bytesWritten = 0;
         while (bytesWritten < sizeof(uint32_t)) {
             ssize_t sentBytes = ::send(socket(socketPtr), buf2.str().c_str() + bytesWritten, sizeof(uint32_t) - bytesWritten, 0);
             if (sentBytes > 0) {
                 bytesWritten += sentBytes;
             }
             else {
                 if (sock_errno() == EINTR) continue;
                 if (sock_errno() == EAGAIN) continue;
                 throw cRuntimeError("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
             }
         }
     }
     {
         EV_TRACE << "Writing TraCI message of " << buf.length() << " bytes" << endl;
         uint32_t bytesWritten = 0;
         while (bytesWritten < buf.length()) {
             ssize_t sentBytes = ::send(socket(socketPtr), buf.c_str() + bytesWritten, buf.length() - bytesWritten, 0);
             if (sentBytes > 0) {
                 bytesWritten += sentBytes;
             }
             else {
                 if (sock_errno() == EINTR) continue;
                 if (sock_errno() == EAGAIN) continue;
                 throw cRuntimeError("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
             }
         }
     }
 }
References veins::socket(), socketPtr, and veins::TraCIBuffer::str().
Referenced by query().
setNetbounds()
void veins::TraCIConnection::setNetbounds (TraCICoord netbounds1, TraCICoord netbounds2, int margin)
Definition at line 276 of file TraCIConnection.cc.
 {
     coordinateTransformation.reset(new TraCICoordinateTransformation(netbounds1, netbounds2, margin));
 }
References coordinateTransformation.
Referenced by veins::TraCICommandInterface::initNetworkBoundaries().
traci2omnet() [1/2]
std::list< Coord > veins::TraCIConnection::traci2omnet (const std::list< TraCICoord > & list) const
Definition at line 287 of file TraCIConnection.cc.
 {
     ASSERT(coordinateTransformation.get());
     return coordinateTransformation->traci2omnet(list);
 }
References coordinateTransformation.
traci2omnet() [2/2]
Coord veins::TraCIConnection::traci2omnet (TraCICoord coord) const
convert TraCI coordinates to OMNeT++ coordinates
Definition at line 281 of file TraCIConnection.cc.
 {
     ASSERT(coordinateTransformation.get());
     return coordinateTransformation->traci2omnet(coord);
 }
References coordinateTransformation.
Referenced by veins::TraCICommandInterface::genericGetCoord(), and veins::TraCICommandInterface::genericGetCoordList().
traci2omnetHeading()
Heading veins::TraCIConnection::traci2omnetHeading (double heading) const
convert TraCI heading to OMNeT++ heading (in rad)
Definition at line 305 of file TraCIConnection.cc.
 {
     ASSERT(coordinateTransformation.get());
     return coordinateTransformation->traci2omnetHeading(heading);
 }
References coordinateTransformation.
Member Data Documentation
coordinateTransformation
std::unique_ptr<TraCICoordinateTransformation> veins::TraCIConnection::coordinateTransformation private
Definition at line 97 of file TraCIConnection.h.
Referenced by omnet2traci(), omnet2traciHeading(), setNetbounds(), traci2omnet(), and traci2omnetHeading().
socketPtr
void* veins::TraCIConnection::socketPtr private
Definition at line 96 of file TraCIConnection.h.
Referenced by connect(), receiveMessage(), sendMessage(), TraCIConnection(), and ~TraCIConnection().
The documentation for this class was generated from the following files:
TraCIConnection.h
TraCIConnection.cc