Veins: veins::BaseMacLayer Class Reference
veins::BaseMacLayer Class Reference
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses.
#include <BaseMacLayer.h>
Public Types
enum BaseMacMessageKinds { LAST_BASE_MAC_MESSAGE_KIND = 23000 }
Message kinds used by this layer.
enum BaseMacControlKinds { TX_OVER = 23500 , PACKET_DROPPED , LAST_BASE_MAC_CONTROL_KIND }
Control message kinds used by this layer.
Public Member Functions
BaseMacLayer ()
BaseMacLayer (unsigned stacksize)
void initialize (int) override
Initialization of the module and some variables.
const LAddress::L2Type & getMACAddress ()
Returns the MAC address of this MAC module.
void setMACAddress (LAddress::L2Type macAddr)
Sets the MAC address of this MAC module.
Public Member Functions inherited from veins::BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
virtual void registerInterface ()
Registers this bridge's NIC with INET's InterfaceTable.
void handleUpperMsg (cMessage *msg) override
Handle messages comming from the network layer.
void handleLowerMsg (cMessage *msg) override
If message arrives from lower layer, check whether it is for us.
void handleSelfMsg (cMessage *msg) override
Handle self messages such as timer...
void handleLowerControl (cMessage *msg) override
Handle control messages from lower layer.
void handleUpperControl (cMessage *msg) override
Handle control messages from upper layer.
virtual cPacket * decapsMsg (MacPkt *)
decapsulate the network message from the MacPkt
virtual MacPkt * encapsMsg (cPacket *)
Encapsulate the NetwPkt into an MacPkt.
BaseConnectionManager * getConnectionManager ()
Returns a pointer to this MACs NICs ConnectionManager module.
virtual const LAddress::L2Type & getUpperDestinationFromControlInfo (const cObject *const pCtrlInfo)
Extracts the MAC address from the "control info" structure (object).
virtual cObject *const setUpControlInfo (cMessage *const pMsg, const LAddress::L2Type &pSrcAddr)
Attaches a "control info" (MacToNetw) structure (object) to the message pMsg.
Protected Member Functions inherited from veins::BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
MacToPhyInterface * phy
Handler to the physical layer.
int headerLength
Pointer to the arp module.
LAddress::L2Type myMacAddr
MAC address.
Protected Attributes inherited from veins::BaseLayer
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
PassedMessage * passedMsg
The last message passed through this layer.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Public Attributes inherited from veins::BaseLayer
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses.
It also provides basic handling of lower layer messages.
Author
Daniel Willkomm, Karl Wessel
Definition at line 50 of file BaseMacLayer.h.
Member Enumeration Documentation
BaseMacControlKinds
enum veins::BaseMacLayer::BaseMacControlKinds
Control message kinds used by this layer.
Enumerator
TX_OVER
Indicates the end of a transmission.
PACKET_DROPPED
Tells the netw layer that a packet to be sent has been dropped.
LAST_BASE_MAC_CONTROL_KIND
Stores the id on which classes extending BaseMac should continue their own control kinds.
Definition at line 59 of file BaseMacLayer.h.
{
         /** Indicates the end of a transmission*/
         TX_OVER = 23500,
         /** Tells the netw layer that a packet to be sent has been dropped.*/
         PACKET_DROPPED,
         /** Stores the id on which classes extending BaseMac should
          * continue their own control kinds.*/
         LAST_BASE_MAC_CONTROL_KIND,
     };
BaseMacMessageKinds
enum veins::BaseMacLayer::BaseMacMessageKinds
Message kinds used by this layer.
Enumerator
LAST_BASE_MAC_MESSAGE_KIND
Stores the id on which classes extending BaseMac should continue their own message kinds.
Definition at line 53 of file BaseMacLayer.h.
{
         /** Stores the id on which classes extending BaseMac should
          * continue their own message kinds.*/
         LAST_BASE_MAC_MESSAGE_KIND = 23000,
     };
Constructor & Destructor Documentation
BaseMacLayer() [1/2]
veins::BaseMacLayer::BaseMacLayer () inline
Definition at line 88 of file BaseMacLayer.h.
         : BaseLayer()
         , phy(nullptr)
         , myMacAddr(LAddress::L2NULL())
     {
     }
BaseMacLayer() [2/2]
veins::BaseMacLayer::BaseMacLayer (unsigned stacksize) inline
Definition at line 94 of file BaseMacLayer.h.
         : BaseLayer(stacksize)
         , phy(nullptr)
         , myMacAddr(LAddress::L2NULL())
     {
     }
Member Function Documentation
decapsMsg()
cPacket * BaseMacLayer::decapsMsg (MacPkt * msg) protected virtual
decapsulate the network message from the MacPkt
Decapsulates the network packet from the received MacPkt.
Definition at line 86 of file BaseMacLayer.cc.
 {
     cPacket* m = msg->decapsulate();
     setUpControlInfo(m, msg->getSrcAddr());
     // delete the macPkt
     delete msg;
     EV_TRACE << " message decapsulated " << endl;
     return m;
 }
References setUpControlInfo().
Referenced by handleLowerMsg().
encapsMsg()
MacPkt * BaseMacLayer::encapsMsg (cPacket * netwPkt) protected virtual
Encapsulate the NetwPkt into an MacPkt.
Encapsulates the received NetwPkt into a MacPkt and set all needed header fields.
Definition at line 100 of file BaseMacLayer.cc.
 {
     MacPkt* pkt = new MacPkt(netwPkt->getName(), netwPkt->getKind());
     pkt->setBitLength(headerLength);
     // copy dest address from the Control Info attached to the network
     // message by the network layer
     cObject* cInfo = netwPkt->removeControlInfo();
     EV_TRACE << "CInfo removed, mac addr=" << getUpperDestinationFromControlInfo(cInfo) << endl;
     pkt->setDestAddr(getUpperDestinationFromControlInfo(cInfo));
     // delete the control info
     delete cInfo;
     // set the src address to own mac address (nic module getId())
     pkt->setSrcAddr(myMacAddr);
     // encapsulate the network packet
     pkt->encapsulate(netwPkt);
     EV_TRACE << "pkt encapsulated\n";
     return pkt;
 }
References getUpperDestinationFromControlInfo(), headerLength, and myMacAddr.
Referenced by handleUpperMsg().
getConnectionManager()
BaseConnectionManager * BaseMacLayer::getConnectionManager () protected
Returns a pointer to this MACs NICs ConnectionManager module.
Returns
pointer to the connection manager module
Definition at line 177 of file BaseMacLayer.cc.
 {
     cModule* nic = getParentModule();
     return ChannelAccess::getConnectionManager(nic);
 }
References veins::ChannelAccess::getConnectionManager().
getMACAddress()
const LAddress::L2Type& veins::BaseMacLayer::getMACAddress () inline
Returns the MAC address of this MAC module.
Definition at line 107 of file BaseMacLayer.h.
     {
         Enter_Method_Silent();
         ASSERT(myMacAddr != LAddress::L2NULL());
         return myMacAddr;
     }
References veins::LAddress::L2NULL().
Referenced by veins::Mac1609_4::getMACAddress().
getUpperDestinationFromControlInfo()
const LAddress::L2Type & BaseMacLayer::getUpperDestinationFromControlInfo (const cObject *const pCtrlInfo) protected virtual
Extracts the MAC address from the "control info" structure (object).
Extract the destination MAC address from the "control info" which was prev. set by NetwToMacControlInfo::setControlInfo().
Parameters
pCtrlInfo The "control info" structure (object) prev. set by NetwToMacControlInfo::setControlInfo().
Returns
The MAC address of message receiver.
Definition at line 183 of file BaseMacLayer.cc.
 {
     return NetwToMacControlInfo::getDestFromControlInfo(pCtrlInfo);
 }
References veins::NetwToMacControlInfo::getDestFromControlInfo().
Referenced by encapsMsg().
handleLowerControl()
void BaseMacLayer::handleLowerControl (cMessage * msg) override protected virtual
Handle control messages from lower layer.
Implements veins::BaseLayer.
Reimplemented in veins::Mac1609_4.
Definition at line 163 of file BaseMacLayer.cc.
 {
     switch (msg->getKind()) {
     case MacToPhyInterface::TX_OVER:
         msg->setKind(TX_OVER);
         sendControlUp(msg);
         break;
     default:
         EV << "BaseMacLayer does not handle control messages of this type (name was " << msg->getName() << ")\n";
         delete msg;
         break;
     }
 }
References veins::BaseLayer::sendControlUp(), TX_OVER, and veins::MacToPhyInterface::TX_OVER.
handleLowerMsg()
void BaseMacLayer::handleLowerMsg (cMessage * msg) override protected virtual
If message arrives from lower layer, check whether it is for us.
This basic implementation just forwards all message that are broadcast (destAddr = L2BROADCAST) or destined for this node (destAddr = nic module getId()) to the network layer.
Send it up if yes.
See also
sendUp
Implements veins::BaseLayer.
Reimplemented in veins::Mac1609_4.
Definition at line 146 of file BaseMacLayer.cc.
 {
     MacPkt* mac = static_cast<MacPkt*>(msg);
     LAddress::L2Type dest = mac->getDestAddr();
     LAddress::L2Type src = mac->getSrcAddr();
     // only foward to upper layer if message is for me or broadcast
     if ((dest == myMacAddr) || LAddress::isL2Broadcast(dest)) {
         EV_TRACE << "message with mac addr " << src << " for me (dest=" << dest << ") -> forward packet to upper layer\n";
         sendUp(decapsMsg(mac));
     }
     else {
         EV_TRACE << "message with mac addr " << src << " not for me (dest=" << dest << ") -> delete (my MAC=" << myMacAddr << ")\n";
         delete mac;
     }
 }
References decapsMsg(), veins::LAddress::isL2Broadcast(), myMacAddr, and veins::BaseLayer::sendUp().
handleSelfMsg()
void veins::BaseMacLayer::handleSelfMsg (cMessage * msg) inline override protected virtual
Handle self messages such as timer...
Implements veins::BaseLayer.
Reimplemented in veins::Mac1609_4.
Definition at line 148 of file BaseMacLayer.h.
     {
         throw cRuntimeError("BaseMacLayer does not handle self messages");
     };
handleUpperControl()
void veins::BaseMacLayer::handleUpperControl (cMessage * msg) inline override protected virtual
Handle control messages from upper layer.
Implements veins::BaseLayer.
Reimplemented in veins::Mac1609_4.
Definition at line 154 of file BaseMacLayer.h.
     {
         throw cRuntimeError("BaseMacLayer does not handle control messages from upper layers");
     };
handleUpperMsg()
void BaseMacLayer::handleUpperMsg (cMessage * mac) override protected virtual
Handle messages comming from the network layer.
Redefine this function if you want to process messages from upper layers before they are send to lower layers.
Here is the place to implement a real medium access functionality.
If message arrives from upper layer, make a MAC packet from it (encapsMsg) and send it down (sendDown).
See also
encapsMsg, sendDown
To forward the message to lower layers after processing it please use sendDown. It will take care of anything needed
Implements veins::BaseLayer.
Reimplemented in veins::Mac1609_4.
Definition at line 132 of file BaseMacLayer.cc.
 {
     ASSERT(dynamic_cast<cPacket*>(mac));
     sendDown(encapsMsg(static_cast<cPacket*>(mac)));
 }
References encapsMsg(), and veins::BaseLayer::sendDown().
initialize()
void BaseMacLayer::initialize (int stage) override
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Definition at line 49 of file BaseMacLayer.cc.
 {
     BaseLayer::initialize(stage);
     if (stage == 0) {
         // get handle to phy layer
         if ((phy = FindModule<MacToPhyInterface*>::findSubModule(getParentModule())) == nullptr) {
             throw cRuntimeError("Could not find a PHY module.");
         }
         headerLength = par("headerLength");
     }
     if (myMacAddr == LAddress::L2NULL()) {
         // see if there is an addressing module available
         // otherwise use NIC modules id as MAC address
         AddressingInterface* addrScheme = FindModule<AddressingInterface*>::findSubModule(findHost());
         if (addrScheme) {
             myMacAddr = addrScheme->myMacAddr(this);
         }
         else {
             const std::string addressString = par("address").stringValue();
             if (addressString.empty() || addressString == "auto")
                 myMacAddr = LAddress::L2Type(getParentModule()->getId());
             else
                 myMacAddr = 0;
         }
         registerInterface();
     }
 }
References veins::BaseModule::findHost(), veins::FindModule< T >::findSubModule(), headerLength, veins::BaseLayer::initialize(), veins::LAddress::L2NULL(), veins::AddressingInterface::myMacAddr(), myMacAddr, phy, and registerInterface().
Referenced by veins::Mac1609_4::initialize().
registerInterface()
void BaseMacLayer::registerInterface () protected virtual
Registers this bridge's NIC with INET's InterfaceTable.
Definition at line 79 of file BaseMacLayer.cc.
 {
 }
Referenced by initialize().
setMACAddress()
void veins::BaseMacLayer::setMACAddress (LAddress::L2Type macAddr) inline
Sets the MAC address of this MAC module.
Definition at line 117 of file BaseMacLayer.h.
     {
         Enter_Method_Silent();
         ASSERT(macAddr != LAddress::L2BROADCAST() && macAddr != LAddress::L2NULL());
         myMacAddr = macAddr;
     }
References veins::LAddress::L2BROADCAST(), and veins::LAddress::L2NULL().
setUpControlInfo()
cObject *const BaseMacLayer::setUpControlInfo (cMessage *const pMsg, const LAddress::L2Type & pSrcAddr) protected virtual
Attaches a "control info" (MacToNetw) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message receiver.
Definition at line 191 of file BaseMacLayer.cc.
 {
     return MacToNetwControlInfo::setControlInfo(pMsg, pSrcAddr);
 }
References veins::MacToNetwControlInfo::setControlInfo().
Referenced by decapsMsg().
Member Data Documentation
headerLength
int veins::BaseMacLayer::headerLength protected
Pointer to the arp module.
Length of the MacPkt header
Definition at line 79 of file BaseMacLayer.h.
Referenced by encapsMsg(), and initialize().
myMacAddr
LAddress::L2Type veins::BaseMacLayer::myMacAddr protected
MAC address.
Definition at line 84 of file BaseMacLayer.h.
Referenced by encapsMsg(), veins::Mac1609_4::handleLowerMsg(), handleLowerMsg(), veins::Mac1609_4::handleSelfMsg(), initialize(), and veins::Mac1609_4::sendAck().
phy
MacToPhyInterface* veins::BaseMacLayer::phy protected
Handler to the physical layer.
Definition at line 71 of file BaseMacLayer.h.
Referenced by veins::Mac1609_4::handleLowerControl(), initialize(), and veins::Mac1609_4::sendFrame().
The documentation for this class was generated from the following files:
BaseMacLayer.h
BaseMacLayer.cc