Veins: veins::TraCIScreenRecorder Class Reference
veins::TraCIScreenRecorder Class Reference
Simple support module to take (a series of) screenshots of a simulation running in the TraCI server.
#include <TraCIScreenRecorder.h>
Public Member Functions
void initialize (int stage) override
void handleMessage (cMessage *msg) override
void finish () override
Protected Attributes
cMessage * takeScreenshot
Detailed Description
Simple support module to take (a series of) screenshots of a simulation running in the TraCI server.
Note that the TraCI server needs to be run in GUI mode and support taking screenshots for this to work.
The screenshots can then be converted to a video using something along the lines of mencoder 'mf://results/screenshot-*.png' -mf w=800:h=600:fps=25:type=png -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy -o output.avi
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer
See also
TraCIScenarioManager
Definition at line 45 of file TraCIScreenRecorder.h.
Member Function Documentation
finish()
void TraCIScreenRecorder::finish () override
Definition at line 106 of file TraCIScreenRecorder.cc.
 {
     cancelAndDelete(takeScreenshot);
 }
References takeScreenshot.
handleMessage()
void TraCIScreenRecorder::handleMessage (cMessage * msg) override
Definition at line 45 of file TraCIScreenRecorder.cc.
 {
     ASSERT(msg == takeScreenshot);
     // get dirname
     const char* dirname = par("dirname").stringValue();
     if (std::string(dirname) == "") {
         dirname = cSimulation::getActiveSimulation()->getEnvir()->getConfigEx()->getVariable(CFGVAR_RESULTDIR);
     }
     // get absolute path of dirname (the TraCI server might be running in a different directory than OMNeT++)
     std::string dirname_abs;
     {
         char* s = realpath(dirname, nullptr);
         if (!s) {
             perror("cannot open output directory");
             throw cRuntimeError("cannot open output directory '%s'", dirname);
         }
         dirname_abs = s;
         free(s);
     }
     // get filename template
     std::string filenameTemplate = par("filenameTemplate").stdstringValue();
     if (filenameTemplate == "") {
         const char* myRunID = cSimulation::getActiveSimulation()->getEnvir()->getConfigEx()->getVariable(CFGVAR_RUNID);
         filenameTemplate = "screenshot-" + std::string(myRunID) + "-@%08.2f.png";
 #ifdef _WIN32
         // replace ':' with '-'
         for (std::string::iterator i = filenameTemplate.begin(); i != filenameTemplate.end(); ++i)
             if (*i == ':') *i = '-';
 #endif /* _WIN32 */
     }
     // assemble filename
     std::string filename;
     {
         std::string tmpl = dirname_abs + "/" + filenameTemplate;
         char buf[1024];
         snprintf(buf, 1024, tmpl.c_str(), simTime().dbl());
         buf[1023] = 0;
         filename = buf;
     }
     // take screenshot
     TraCIScenarioManager* manager = TraCIScenarioManagerAccess().get();
     ASSERT(manager);
     TraCICommandInterface* traci = manager->getCommandInterface();
     if (!traci) {
         throw cRuntimeError("Cannot create screenshot: TraCI is not connected yet");
     }
     TraCICommandInterface::GuiView view = traci->guiView(par("viewName"));
     view.takeScreenshot(filename);
     // schedule next screenshot
     simtime_t stop = par("stop");
     if ((stop == -1) || (simTime() < stop)) {
         scheduleAt(simTime() + par("interval"), takeScreenshot);
     }
 }
References veins::TraCIScenarioManagerAccess::get(), veins::TraCIScenarioManager::getCommandInterface(), veins::TraCICommandInterface::guiView(), veins::TraCICommandInterface::GuiView::takeScreenshot(), and takeScreenshot.
initialize()
void TraCIScreenRecorder::initialize (int stage) override
Definition at line 35 of file TraCIScreenRecorder.cc.
 {
     if (stage == 0) {
         takeScreenshot = new cMessage("take screenshot");
         takeScreenshot->setSchedulingPriority(1); // this schedules screenshots after TraCI timesteps
         scheduleAt(par("start"), takeScreenshot);
         return;
     }
 }
References takeScreenshot.
Member Data Documentation
takeScreenshot
cMessage* veins::TraCIScreenRecorder::takeScreenshot protected
Definition at line 52 of file TraCIScreenRecorder.h.
Referenced by finish(), handleMessage(), and initialize().
The documentation for this class was generated from the following files:
TraCIScreenRecorder.h
TraCIScreenRecorder.cc