Veins: veins::FindModule< T > Class Template Reference
veins::FindModule< T > Class Template Reference
Provides method templates to find omnet modules.
#include <FindModule.h>
Static Public Member Functions
static T findSubModule (const cModule *const top)
Returns a pointer to a sub module of the passed module with the type of this template.
static std::vector< T > findSubModules (const cModule *const top)
Returns a list of pointers to sub modules of the passed module with the type of this template.
static T findGlobalModule ()
Returns a pointer to the module with the type of this template.
static cModule *const findHost (cModule *const m)
Returns a pointer to the host module of the passed module.
static const cModule *const findHost (const cModule *const m)
Detailed Description
template<typename T = cModule* const>
class veins::FindModule< T >
Provides method templates to find omnet modules.
Definition at line 38 of file FindModule.h.
Member Function Documentation
findGlobalModule()
template<typename T = cModule* const> static T veins::FindModule< T >::findGlobalModule () inline static
Returns a pointer to the module with the type of this template.
Returns NULL if no module of this type could be found.
Definition at line 86 of file FindModule.h.
     {
         return findSubModule(getSimulation()->getSystemModule());
     }
Referenced by veins::TraCIScenarioManagerAccess::get(), veins::TraCIScenarioManagerForkerAccess::get(), veins::TraCIScenarioManagerLaunchdAccess::get(), veins::AnnotationManagerAccess::getIfExists(), veins::BaseConnectionManager::initialize(), veins::BasePhyLayer::initialize(), veins::TraCIScenarioManager::initialize(), veins::BaseMobility::initialize(), and anonymous_namespace{ObstacleControl.cc}::rebuildBBoxLookup().
findHost() [1/2]
template<typename T = cModule* const> static cModule* const veins::FindModule< T >::findHost (cModule *const m) inline static
Returns a pointer to the host module of the passed module.
Assumes that every host module is a direct sub module of the simulation.
Definition at line 97 of file FindModule.h.
     {
         cModule* parent = m != nullptr ? m->getParentModule() : nullptr;
         cModule* node = m;
         // all nodes should be a sub module of the simulation which has no parent module!!!
         while (parent != nullptr && parent->getParentModule() != nullptr) {
             node = parent;
             parent = node->getParentModule();
         }
         return node;
     }
Referenced by veins::BaseModule::findHost().
findHost() [2/2]
template<typename T = cModule* const> static const cModule* const veins::FindModule< T >::findHost (const cModule *const m) inline static
Definition at line 110 of file FindModule.h.
     {
         const cModule* parent = m != nullptr ? m->getParentModule() : nullptr;
         const cModule* node = m;
         // all nodes should be a sub module of the simulation which has no parent module!!!
         while (parent != nullptr && parent->getParentModule() != nullptr) {
             node = parent;
             parent = node->getParentModule();
         }
         return node;
     }
findSubModule()
template<typename T = cModule* const> static T veins::FindModule< T >::findSubModule (const cModule *const top) inline static
Returns a pointer to a sub module of the passed module with the type of this template.
Returns NULL if no matching submodule could be found.
Definition at line 46 of file FindModule.h.
     {
         for (cModule::SubmoduleIterator i(top); !i.end(); i++) {
             cModule* const sub = *i;
             // this allows also a return type of read only pointer: const cModule *const
             T dCastRet = dynamic_cast<T>(sub);
             if (dCastRet != NULL) return dCastRet;
             // this allows also a return type of read only pointer: const cModule *const
             T recFnd = findSubModule(sub);
             if (recFnd != NULL) return recFnd;
         }
         return NULL;
     }
Referenced by veins::AccessModuleWrap< T >::get(), veins::TraCIMobilityAccess::get(), veins::TraCITrafficLightSimpleLogicAccess::get(), veins::TraCITrafficLightInterfaceAccess::get(), veins::DemoBaseApplLayer::initialize(), veins::BaseMacLayer::initialize(), veins::Mac1609_4::initialize(), veins::TraCIVehicleInserter::receiveSignal(), veins::BatteryAccess::registerWithBattery(), veins::NicEntryDebug::requestInGate(), and veins::NicEntryDebug::requestOutGate().
findSubModules()
template<typename T = cModule* const> static std::vector<T> veins::FindModule< T >::findSubModules (const cModule *const top) inline static
Returns a list of pointers to sub modules of the passed module with the type of this template.
Returns an empty list if no matching submodule could be found.
Definition at line 65 of file FindModule.h.
     {
         std::vector<T> modules;
         for (cModule::SubmoduleIterator i(top); !i.end(); i++) {
             cModule* const sub = *i;
             // this allows also a return type of read only pointer: const cModule *const
             T dCastRet = dynamic_cast<T>(sub);
             if (dCastRet != NULL) modules.push_back(dCastRet);
             // this allows also a return type of read only pointer: const cModule *const
             std::vector<T> recFnd = findSubModules(sub);
             if (recFnd.size()) std::copy(recFnd.begin(), recFnd.end(), std::back_inserter(modules));
         }
         return modules;
     }
The documentation for this class was generated from the following file:
FindModule.h