Veins: veins::LAddress Class Reference
veins::LAddress Class Reference
Layer address handling helper function.
#include <SimpleAddress.h>
Public Types
using L2Type = long
Type definition for a L2 (MAC) address.
using L3Type = long
Type definition for a L3 (Network) address.
Static Public Member Functions
static const L2Type & L2BROADCAST ()
Broadcast address for L2 addresses.
static const L2Type & L2NULL ()
NULL address for L2 addresses.
static const L3Type & L3BROADCAST ()
Broadcast address for L3 addresses.
static const L3Type & L3NULL ()
NULL address for L3 addresses.
static bool isL2Broadcast (const L2Type &pSrcAddr)
Test if a L2 address (pSrcAddr) is a broadcast address.
static bool isL3Broadcast (const L3Type &pSrcAddr)
Test if a L3 address (pSrcAddr) is a broadcast address.
Detailed Description
Layer address handling helper function.
This class helps to make the layer addressing more generic. The type definition for L2, and L3 addresses should be used for address definitions to simplify the switching to other types.
Attention
Both types (LAddress::L2Type, LAddress::L3Type) will be used as keys in in STL containers.
Definition at line 41 of file SimpleAddress.h.
Member Typedef Documentation
L2Type
using veins::LAddress::L2Type = long
Type definition for a L2 (MAC) address.
The type should support initialization with long/string values and casting to long/double. The type should be also support the ==,<, and > operators.
Definition at line 48 of file SimpleAddress.h.
L3Type
using veins::LAddress::L3Type = long
Type definition for a L3 (Network) address.
The type should support initialization with long values and casting to long/double. The type should be also support the ==,<, and > operators.
Definition at line 54 of file SimpleAddress.h.
Member Function Documentation
isL2Broadcast()
static bool veins::LAddress::isL2Broadcast (const L2Type & pSrcAddr) inline static
Test if a L2 address (pSrcAddr) is a broadcast address.
Parameters
pSrcAddr The L2 address which should be tested.
Returns
True if pSrcAddr is a braodcast address.
Definition at line 88 of file SimpleAddress.h.
     {
         return pSrcAddr == L2BROADCAST();
     }
Referenced by veins::BaseMacLayer::handleLowerMsg().
isL3Broadcast()
static bool veins::LAddress::isL3Broadcast (const L3Type & pSrcAddr) inline static
Test if a L3 address (pSrcAddr) is a broadcast address.
Parameters
pSrcAddr The L3 address which should be tested.
Returns
True if pSrcAddr is a braodcast address.
Definition at line 98 of file SimpleAddress.h.
     {
         return pSrcAddr == L3BROADCAST();
     }
L2BROADCAST()
static const L2Type& veins::LAddress::L2BROADCAST () inline static
Broadcast address for L2 addresses.
Definition at line 57 of file SimpleAddress.h.
     {
         static L2Type o(-1);
         return o;
     }
Referenced by veins::Mac1609_4::handleLowerMsg(), veins::Mac1609_4::handleSelfMsg(), veins::Mac1609_4::EDCA::postTransmit(), and veins::BaseMacLayer::setMACAddress().
L2NULL()
static const L2Type& veins::LAddress::L2NULL () inline static
NULL address for L2 addresses.
Definition at line 63 of file SimpleAddress.h.
     {
         static L2Type o(0);
         return o;
     }
Referenced by veins::MacToNetwControlInfo::getAddressFromControlInfo(), veins::BaseMacLayer::getMACAddress(), veins::Mac1609_4::getMACAddress(), veins::BaseMacLayer::initialize(), and veins::BaseMacLayer::setMACAddress().
L3BROADCAST()
static const L3Type& veins::LAddress::L3BROADCAST () inline static
Broadcast address for L3 addresses.
Definition at line 69 of file SimpleAddress.h.
     {
         static L3Type o(-1);
         return o;
     }
L3NULL()
static const L3Type& veins::LAddress::L3NULL () inline static
NULL address for L3 addresses.
Definition at line 75 of file SimpleAddress.h.
     {
         static L3Type o(0);
         return o;
     }
The documentation for this class was generated from the following file:
SimpleAddress.h