Veins: veins::TraCITrafficLightInterface Class Reference
veins::TraCITrafficLightInterface Class Reference
#include <TraCITrafficLightInterface.h>
Public Member Functions
TraCITrafficLightInterface ()
~TraCITrafficLightInterface () override
virtual void preInitialize (const std::string &external_id, const Coord &position, const simtime_t &updateInterval)
Set parameters for connection to TraCI.
virtual void setExternalId (const std::string &external_id)
virtual std::string getExternalId () const
virtual TraCIScenarioManager * getManager () const
virtual TraCICommandInterface * getCommandInterface () const
virtual TraCICommandInterface::Trafficlight * getTlCommandInterface () const
virtual std::list< std::list< TraCITrafficLightLink > > getControlledLinks ()
virtual Coord getPosition () const
virtual TraCITrafficLightProgram::Logic getCurrentLogic () const
virtual std::string getCurrentLogicId () const
virtual int getCurrentPhaseId () const
virtual TraCITrafficLightProgram::Phase getCurrentPhase () const
virtual simtime_t getAssumedNextSwitch () const
virtual simtime_t getRemainingDuration () const
virtual std::string getCurrentState () const
virtual bool isInOnlineSignalState () const
virtual void setProgramDefinition (const TraCITrafficLightProgram &programDefinition)
virtual void setControlledLinks (const std::list< std::list< TraCITrafficLightLink >> &controlledLinks)
virtual void setCurrentLogicById (const std::string &logicId, bool setSumo=true)
virtual void setCurrentPhaseByNr (const unsigned int phaseNr, bool setSumo=true)
virtual void setCurrentState (const std::string &state, bool setSumo=true)
virtual void setNextSwitch (const simtime_t &newNextSwitch, bool setSumo=true)
virtual void setRemainingDuration (const simtime_t &timeTillSwitch, bool setSumo=true)
Protected Member Functions
void initialize () override
void handleMessage (cMessage *msg) override
virtual void handleChangeCommandMessage (cMessage *msg)
virtual void sendChangeMsg (int changedAttribute, const std::string newValue, const std::string oldValue)
Protected Attributes
bool isPreInitialized
true if preInitialize() has been called immediately before initialize()
simtime_t updateInterval
ScenarioManager's update interval.
TraCIScenarioManager * manager
reference to the simulations ScenarioManager
TraCICommandInterface * commandInterface
reference to the simulations traffic light-specific TraCI command interface
TraCICommandInterface::Trafficlight * tlCommandInterface
reference to the simulations traffic light-specific TraCI command interface
std::string external_id
id used on the other end of TraCI
Coord position
position of the traffic light
TraCITrafficLightProgram programDefinition
full definition of program (all logics)
std::list< std::list< TraCITrafficLightLink > > controlledLinks
controlledLinks[signal][link]
std::string currentLogicId
id of the currently active logic
int currentPhaseNr
current phase of the current program
simtime_t nextSwitchTime
predicted next phase switch time (absolute timestamp)
std::string currentSignalState
current state of the signals (rRgGyY-String)
bool inOnlineSignalState
whether the TLS is currently set to a manual (i.e.
Detailed Description
Definition at line 33 of file TraCITrafficLightInterface.h.
Constructor & Destructor Documentation
TraCITrafficLightInterface()
TraCITrafficLightInterface::TraCITrafficLightInterface ()
Definition at line 34 of file TraCITrafficLightInterface.cc.
     : cSimpleModule()
     , isPreInitialized(false)
     , updateInterval()
     , manager(nullptr)
     , commandInterface(nullptr)
     , tlCommandInterface(nullptr)
     , external_id("")
     , position()
     , programDefinition()
     , currentLogicId("")
     , currentPhaseNr(-1)
     , nextSwitchTime()
     , inOnlineSignalState(false)
 {
 }
~TraCITrafficLightInterface()
TraCITrafficLightInterface::~TraCITrafficLightInterface () override
Definition at line 51 of file TraCITrafficLightInterface.cc.
 {
     delete tlCommandInterface;
 }
References tlCommandInterface.
Member Function Documentation
getAssumedNextSwitch()
simtime_t TraCITrafficLightInterface::getAssumedNextSwitch () const virtual
Definition at line 93 of file TraCITrafficLightInterface.cc.
 {
     return nextSwitchTime;
 }
References nextSwitchTime.
getCommandInterface()
virtual TraCICommandInterface* veins::TraCITrafficLightInterface::getCommandInterface () const inline virtual
Definition at line 57 of file TraCITrafficLightInterface.h.
     {
         if (!commandInterface) {
             commandInterface = getManager()->getCommandInterface();
         }
         return commandInterface;
     }
getControlledLinks()
std::list< std::list< TraCITrafficLightLink > > TraCITrafficLightInterface::getControlledLinks () virtual
Definition at line 68 of file TraCITrafficLightInterface.cc.
 {
     return controlledLinks;
 }
References controlledLinks.
Referenced by initialize().
getCurrentLogic()
TraCITrafficLightProgram::Logic TraCITrafficLightInterface::getCurrentLogic () const virtual
Definition at line 73 of file TraCITrafficLightInterface.cc.
 {
     return programDefinition.getLogic(currentLogicId);
 }
References currentLogicId, veins::TraCITrafficLightProgram::getLogic(), and programDefinition.
Referenced by getCurrentPhase(), and setCurrentPhaseByNr().
getCurrentLogicId()
std::string TraCITrafficLightInterface::getCurrentLogicId () const virtual
Definition at line 78 of file TraCITrafficLightInterface.cc.
 {
     return currentLogicId;
 }
References currentLogicId.
getCurrentPhase()
TraCITrafficLightProgram::Phase TraCITrafficLightInterface::getCurrentPhase () const virtual
Definition at line 88 of file TraCITrafficLightInterface.cc.
 {
     return getCurrentLogic().phases[currentPhaseNr];
 }
References currentPhaseNr, getCurrentLogic(), and veins::TraCITrafficLightProgram::Logic::phases.
Referenced by getCurrentState().
getCurrentPhaseId()
int TraCITrafficLightInterface::getCurrentPhaseId () const virtual
Definition at line 83 of file TraCITrafficLightInterface.cc.
 {
     return currentPhaseNr;
 }
References currentPhaseNr.
getCurrentState()
std::string TraCITrafficLightInterface::getCurrentState () const virtual
Definition at line 103 of file TraCITrafficLightInterface.cc.
 {
     if (isInOnlineSignalState()) {
         return currentSignalState;
     }
     else {
         return getCurrentPhase().state;
     }
 }
References currentSignalState, getCurrentPhase(), isInOnlineSignalState(), and veins::TraCITrafficLightProgram::Phase::state.
getExternalId()
virtual std::string veins::TraCITrafficLightInterface::getExternalId () const inline virtual
Definition at line 45 of file TraCITrafficLightInterface.h.
     {
         if (external_id == "") throw cRuntimeError("TraCITrafficLightInterface::getExternalId called with no external_id set yet");
         return external_id;
     }
getManager()
virtual TraCIScenarioManager* veins::TraCITrafficLightInterface::getManager () const inline virtual
Definition at line 50 of file TraCITrafficLightInterface.h.
     {
         if (!manager) {
             manager = TraCIScenarioManagerAccess().get();
         }
         return manager;
     }
References veins::TraCIScenarioManagerAccess::get().
getPosition()
Coord TraCITrafficLightInterface::getPosition () const virtual
Definition at line 64 of file TraCITrafficLightInterface.cc.
 {
     return this->position;
 }
References position.
getRemainingDuration()
simtime_t TraCITrafficLightInterface::getRemainingDuration () const virtual
Definition at line 98 of file TraCITrafficLightInterface.cc.
 {
     return nextSwitchTime - simTime();
 }
References nextSwitchTime.
getTlCommandInterface()
virtual TraCICommandInterface::Trafficlight* veins::TraCITrafficLightInterface::getTlCommandInterface () const inline virtual
Definition at line 64 of file TraCITrafficLightInterface.h.
     {
         if (!tlCommandInterface) {
             tlCommandInterface = new TraCICommandInterface::Trafficlight(getCommandInterface(), external_id);
         }
         return tlCommandInterface;
     }
Referenced by initialize(), setNextSwitch(), and setRemainingDuration().
handleChangeCommandMessage()
void TraCITrafficLightInterface::handleChangeCommandMessage (cMessage * msg) protected virtual
Definition at line 246 of file TraCITrafficLightInterface.cc.
 {
     TraCITrafficLightMessage* tmMsg = check_and_cast<TraCITrafficLightMessage*>(msg);
     switch (tmMsg->getChangedAttribute()) {
     case TrafficLightAtrributeType::LOGICID:
         setCurrentLogicById(tmMsg->getNewValue(), true);
         break;
     case TrafficLightAtrributeType::PHASEID:
         setCurrentPhaseByNr(std::stoi(tmMsg->getNewValue()), true);
         break;
     case TrafficLightAtrributeType::SWITCHTIME:
         setNextSwitch(SimTime(std::stoi(tmMsg->getNewValue()), SIMTIME_MS), true);
         break;
     case TrafficLightAtrributeType::STATE:
         setCurrentState(tmMsg->getNewValue(), true);
         break;
     }
 }
References setCurrentLogicById(), setCurrentPhaseByNr(), setCurrentState(), and setNextSwitch().
Referenced by handleMessage().
handleMessage()
void TraCITrafficLightInterface::handleMessage (cMessage * msg) override protected
Definition at line 235 of file TraCITrafficLightInterface.cc.
 {
     if (msg->isSelfMessage()) {
         // not in use (yet)
     }
     else if (msg->arrivedOn("logic$i")) {
         handleChangeCommandMessage(msg);
     }
     delete msg;
 }
References handleChangeCommandMessage().
initialize()
void TraCITrafficLightInterface::initialize () override protected
Definition at line 223 of file TraCITrafficLightInterface.cc.
 {
     ASSERT(isPreInitialized);
     isPreInitialized = false;
     setProgramDefinition(getTlCommandInterface()->getProgramDefinition());
     setControlledLinks(getTlCommandInterface()->getControlledLinks());
     currentLogicId = getTlCommandInterface()->getCurrentProgramID();
     currentPhaseNr = getTlCommandInterface()->getCurrentPhaseIndex();
     nextSwitchTime = getTlCommandInterface()->getAssumedNextSwitchTime();
     currentSignalState = getTlCommandInterface()->getCurrentState();
 }
References currentLogicId, currentPhaseNr, currentSignalState, veins::TraCICommandInterface::Trafficlight::getAssumedNextSwitchTime(), getControlledLinks(), veins::TraCICommandInterface::Trafficlight::getCurrentPhaseIndex(), veins::TraCICommandInterface::Trafficlight::getCurrentProgramID(), veins::TraCICommandInterface::Trafficlight::getCurrentState(), getTlCommandInterface(), isPreInitialized, nextSwitchTime, setControlledLinks(), and setProgramDefinition().
isInOnlineSignalState()
bool TraCITrafficLightInterface::isInOnlineSignalState () const virtual
Definition at line 113 of file TraCITrafficLightInterface.cc.
 {
     return inOnlineSignalState;
 }
References inOnlineSignalState.
Referenced by getCurrentState(), setCurrentLogicById(), and setCurrentPhaseByNr().
preInitialize()
void TraCITrafficLightInterface::preInitialize (const std::string & external_id, const Coord & position, const simtime_t & updateInterval) virtual
Set parameters for connection to TraCI.
Definition at line 56 of file TraCITrafficLightInterface.cc.
 {
     isPreInitialized = true;
     this->updateInterval = updateInterval;
     setExternalId(external_id);
     this->position = position;
 }
References external_id, isPreInitialized, position, setExternalId(), and updateInterval.
Referenced by veins::TraCIScenarioManager::init_traci().
sendChangeMsg()
void TraCITrafficLightInterface::sendChangeMsg (int changedAttribute, const std::string newValue, const std::string oldValue) protected virtual
Definition at line 268 of file TraCITrafficLightInterface.cc.
 {
     Enter_Method_Silent();
     TraCITrafficLightMessage* pMsg = new TraCITrafficLightMessage("TrafficLightChangeMessage");
     pMsg->setTlId(external_id.c_str());
     pMsg->setChangedAttribute(changedAttribute);
     pMsg->setChangeSource(TrafficLightChangeSource::SUMO);
     pMsg->setOldValue(oldValue.c_str());
     pMsg->setNewValue(newValue.c_str());
     send(pMsg, "logic$o");
 }
References external_id.
Referenced by setCurrentLogicById(), setCurrentPhaseByNr(), setCurrentState(), setNextSwitch(), and setRemainingDuration().
setControlledLinks()
void TraCITrafficLightInterface::setControlledLinks (const std::list< std::list< TraCITrafficLightLink >> & controlledLinks) virtual
Definition at line 123 of file TraCITrafficLightInterface.cc.
 {
     this->controlledLinks = controlledLinks;
 }
References controlledLinks.
Referenced by initialize().
setCurrentLogicById()
void TraCITrafficLightInterface::setCurrentLogicById (const std::string & logicId, bool setSumo = true) virtual
Definition at line 128 of file TraCITrafficLightInterface.cc.
 {
     if (setSumo) {
         ASSERT(logicId != "online");
         if (!programDefinition.hasLogic(logicId)) {
             throw cRuntimeError("Logic '%s' not found in program of TraCITrafficLightInterface %s", logicId.c_str(), external_id.c_str());
         }
         tlCommandInterface->setProgram(logicId);
         const std::string newValueInSumo = tlCommandInterface->getCurrentProgramID();
         ASSERT(newValueInSumo == logicId);
     }
     if (currentLogicId != logicId || (isInOnlineSignalState() && logicId != "online")) {
         sendChangeMsg(TrafficLightAtrributeType::LOGICID, logicId, currentLogicId);
     }
     if (logicId != "online") {
         inOnlineSignalState = false;
         this->currentLogicId = logicId;
     }
 }
References currentLogicId, external_id, veins::TraCICommandInterface::Trafficlight::getCurrentProgramID(), veins::TraCITrafficLightProgram::hasLogic(), inOnlineSignalState, isInOnlineSignalState(), programDefinition, sendChangeMsg(), veins::TraCICommandInterface::Trafficlight::setProgram(), and tlCommandInterface.
Referenced by handleChangeCommandMessage(), and veins::TraCIScenarioManager::processTrafficLightSubscription().
setCurrentPhaseByNr()
void TraCITrafficLightInterface::setCurrentPhaseByNr (const unsigned int phaseNr, bool setSumo = true) virtual
Definition at line 148 of file TraCITrafficLightInterface.cc.
 {
     if (setSumo) {
         if (phaseNr >= getCurrentLogic().phases.size()) {
             throw cRuntimeError("Cannot set current phase to %d: current logic has only %d Phases (TraCITrafficLightInterface %s)", phaseNr, static_cast<int>(getCurrentLogic().phases.size()), external_id.c_str());
         }
         tlCommandInterface->setPhaseIndex(phaseNr);
         const unsigned int newValueInSumo = tlCommandInterface->getCurrentPhaseIndex();
         ASSERT(newValueInSumo == phaseNr);
     }
     if (currentPhaseNr != static_cast<int>(phaseNr) || isInOnlineSignalState()) {
         sendChangeMsg(TrafficLightAtrributeType::PHASEID, std::to_string(phaseNr), std::to_string(currentPhaseNr));
     }
     inOnlineSignalState = false;
     currentPhaseNr = phaseNr;
 }
References currentPhaseNr, external_id, getCurrentLogic(), veins::TraCICommandInterface::Trafficlight::getCurrentPhaseIndex(), inOnlineSignalState, isInOnlineSignalState(), sendChangeMsg(), veins::TraCICommandInterface::Trafficlight::setPhaseIndex(), and tlCommandInterface.
Referenced by handleChangeCommandMessage(), and veins::TraCIScenarioManager::processTrafficLightSubscription().
setCurrentState()
void TraCITrafficLightInterface::setCurrentState (const std::string & state, bool setSumo = true) virtual
Definition at line 165 of file TraCITrafficLightInterface.cc.
 {
     if (setSumo) {
         tlCommandInterface->setState(state);
         const std::string newValueInSumo = tlCommandInterface->getCurrentState();
         ASSERT(newValueInSumo == state);
     }
     if (currentSignalState != state) {
         sendChangeMsg(TrafficLightAtrributeType::STATE, state, currentSignalState);
     }
     inOnlineSignalState = true;
     currentSignalState = state;
 }
References currentSignalState, veins::TraCICommandInterface::Trafficlight::getCurrentState(), inOnlineSignalState, sendChangeMsg(), veins::TraCICommandInterface::Trafficlight::setState(), and tlCommandInterface.
Referenced by handleChangeCommandMessage(), and veins::TraCIScenarioManager::processTrafficLightSubscription().
setExternalId()
virtual void veins::TraCITrafficLightInterface::setExternalId (const std::string & external_id) inline virtual
Definition at line 41 of file TraCITrafficLightInterface.h.
     {
         this->external_id = external_id;
     }
Referenced by preInitialize().
setNextSwitch()
void TraCITrafficLightInterface::setNextSwitch (const simtime_t & newNextSwitch, bool setSumo = true) virtual
Definition at line 179 of file TraCITrafficLightInterface.cc.
 {
     // FIXME: not working reliably - use setRemainingDuration instead!
     // round to be feasible for SUMO
     simtime_t nextSwitch = ceil(newNextSwitch, updateInterval, 0);
     if (setSumo) {
         simtime_t remainingDuration = ceil(nextSwitch - simTime(), updateInterval, 0);
         if (remainingDuration < 0) {
             EV << "Warning: remaining duration for switch below 0: " << remainingDuration << std::endl;
             // maybe issue even an error if this occurs
             remainingDuration = 0;
         }
         getTlCommandInterface()->setPhaseDuration(remainingDuration);
         simtime_t newValueInSumo = tlCommandInterface->getAssumedNextSwitchTime();
         ASSERT(newValueInSumo == nextSwitch);
     }
     if (nextSwitchTime != nextSwitch) {
         sendChangeMsg(TrafficLightAtrributeType::SWITCHTIME, std::to_string(nextSwitch.inUnit(SIMTIME_MS)), std::to_string(nextSwitchTime.inUnit(SIMTIME_MS)));
     }
     nextSwitchTime = nextSwitch;
 }
References veins::TraCICommandInterface::Trafficlight::getAssumedNextSwitchTime(), getTlCommandInterface(), nextSwitchTime, sendChangeMsg(), veins::TraCICommandInterface::Trafficlight::setPhaseDuration(), tlCommandInterface, and updateInterval.
Referenced by handleChangeCommandMessage(), and veins::TraCIScenarioManager::processTrafficLightSubscription().
setProgramDefinition()
void TraCITrafficLightInterface::setProgramDefinition (const TraCITrafficLightProgram & programDefinition) virtual
Definition at line 118 of file TraCITrafficLightInterface.cc.
 {
     this->programDefinition = programDefinition;
 }
References programDefinition.
Referenced by initialize().
setRemainingDuration()
void TraCITrafficLightInterface::setRemainingDuration (const simtime_t & timeTillSwitch, bool setSumo = true) virtual
Definition at line 201 of file TraCITrafficLightInterface.cc.
 {
     ASSERT(rawRemainingDuration >= 0);
     // round (up) to match sumo time steps
     simtime_t veinsTimeNow(simTime());
     simtime_t sumoTimeNow(ceil(veinsTimeNow, updateInterval) - updateInterval);
     simtime_t roundedRemainingDuration = ceil(rawRemainingDuration, updateInterval, 0);
     // simtime_t nextSwitchInVeins = floor(simTime() + roundedRemainingDuration, updateInterval, 0) - updateInterval;
     simtime_t nextSwitchInVeins = sumoTimeNow + roundedRemainingDuration;
     if (setSumo) {
         // set value to sumo
         getTlCommandInterface()->setPhaseDuration(roundedRemainingDuration);
         // check that everything is consistent
         simtime_t nextSwitchInSumo = tlCommandInterface->getAssumedNextSwitchTime();
         ASSERT(nextSwitchInSumo == nextSwitchInVeins);
     }
     if (nextSwitchTime != nextSwitchInVeins) {
         sendChangeMsg(TrafficLightAtrributeType::SWITCHTIME, std::to_string(nextSwitchInVeins.inUnit(SIMTIME_MS)), std::to_string(nextSwitchTime.inUnit(SIMTIME_MS)));
     }
     nextSwitchTime = nextSwitchInVeins;
 }
References veins::TraCICommandInterface::Trafficlight::getAssumedNextSwitchTime(), getTlCommandInterface(), nextSwitchTime, sendChangeMsg(), veins::TraCICommandInterface::Trafficlight::setPhaseDuration(), tlCommandInterface, and updateInterval.
Member Data Documentation
commandInterface
TraCICommandInterface* veins::TraCITrafficLightInterface::commandInterface mutable protected
reference to the simulations traffic light-specific TraCI command interface
Definition at line 102 of file TraCITrafficLightInterface.h.
controlledLinks
std::list<std::list<TraCITrafficLightLink> > veins::TraCITrafficLightInterface::controlledLinks protected
controlledLinks[signal][link]
Definition at line 110 of file TraCITrafficLightInterface.h.
Referenced by getControlledLinks(), and setControlledLinks().
currentLogicId
std::string veins::TraCITrafficLightInterface::currentLogicId protected
id of the currently active logic
Definition at line 112 of file TraCITrafficLightInterface.h.
Referenced by getCurrentLogic(), getCurrentLogicId(), initialize(), and setCurrentLogicById().
currentPhaseNr
int veins::TraCITrafficLightInterface::currentPhaseNr protected
current phase of the current program
Definition at line 113 of file TraCITrafficLightInterface.h.
Referenced by getCurrentPhase(), getCurrentPhaseId(), initialize(), and setCurrentPhaseByNr().
currentSignalState
std::string veins::TraCITrafficLightInterface::currentSignalState protected
current state of the signals (rRgGyY-String)
Definition at line 115 of file TraCITrafficLightInterface.h.
Referenced by getCurrentState(), initialize(), and setCurrentState().
external_id
std::string veins::TraCITrafficLightInterface::external_id protected
id used on the other end of TraCI
Definition at line 106 of file TraCITrafficLightInterface.h.
Referenced by preInitialize(), sendChangeMsg(), setCurrentLogicById(), and setCurrentPhaseByNr().
inOnlineSignalState
bool veins::TraCITrafficLightInterface::inOnlineSignalState protected
whether the TLS is currently set to a manual (i.e.
online) phase state
Definition at line 116 of file TraCITrafficLightInterface.h.
Referenced by isInOnlineSignalState(), setCurrentLogicById(), setCurrentPhaseByNr(), and setCurrentState().
isPreInitialized
bool veins::TraCITrafficLightInterface::isPreInitialized protected
true if preInitialize() has been called immediately before initialize()
Definition at line 97 of file TraCITrafficLightInterface.h.
Referenced by initialize(), and preInitialize().
manager
TraCIScenarioManager* veins::TraCITrafficLightInterface::manager mutable protected
reference to the simulations ScenarioManager
Definition at line 100 of file TraCITrafficLightInterface.h.
nextSwitchTime
simtime_t veins::TraCITrafficLightInterface::nextSwitchTime protected
predicted next phase switch time (absolute timestamp)
Definition at line 114 of file TraCITrafficLightInterface.h.
Referenced by getAssumedNextSwitch(), getRemainingDuration(), initialize(), setNextSwitch(), and setRemainingDuration().
position
Coord veins::TraCITrafficLightInterface::position protected
position of the traffic light
Definition at line 107 of file TraCITrafficLightInterface.h.
Referenced by getPosition(), and preInitialize().
programDefinition
TraCITrafficLightProgram veins::TraCITrafficLightInterface::programDefinition protected
full definition of program (all logics)
Definition at line 109 of file TraCITrafficLightInterface.h.
Referenced by getCurrentLogic(), setCurrentLogicById(), and setProgramDefinition().
tlCommandInterface
TraCICommandInterface::Trafficlight* veins::TraCITrafficLightInterface::tlCommandInterface mutable protected
reference to the simulations traffic light-specific TraCI command interface
Definition at line 104 of file TraCITrafficLightInterface.h.
Referenced by setCurrentLogicById(), setCurrentPhaseByNr(), setCurrentState(), setNextSwitch(), setRemainingDuration(), and ~TraCITrafficLightInterface().
updateInterval
simtime_t veins::TraCITrafficLightInterface::updateInterval protected
ScenarioManager's update interval.
Definition at line 98 of file TraCITrafficLightInterface.h.
Referenced by preInitialize(), setNextSwitch(), and setRemainingDuration().
The documentation for this class was generated from the following files:
TraCITrafficLightInterface.h
TraCITrafficLightInterface.cc