Veins: veins::ObstacleControl Class Reference
veins::ObstacleControl Class Reference
ObstacleControl models obstacles that block radio transmissions.
#include <ObstacleControl.h>
Classes
struct CacheKey
Public Member Functions
~ObstacleControl () override
void initialize (int stage) override
int numInitStages () const override
void finish () override
void handleMessage (cMessage *msg) override
void handleSelfMsg (cMessage *msg)
void addFromXml (cXMLElement *xml)
void addFromTypeAndShape (std::string id, std::string typeId, std::vector< Coord > shape)
void add (Obstacle obstacle)
void erase (const Obstacle *obstacle)
bool isTypeSupported (std::string type)
double getAttenuationPerCut (std::string type)
double getAttenuationPerMeter (std::string type)
std::vector< std::pair< Obstacle *, std::vector< double > > > getIntersections (const Coord &senderPos, const Coord &receiverPos) const
get hit obstacles (along with a list of points (in [0, 1]) along the line between sender and receiver where the beam intersects with the respective obstacle) as well as any obstacle that contains the sender or receiver (with a list of potentially 0 points)
double calculateAttenuation (const Coord &senderPos, const Coord &receiverPos) const
calculate additional attenuation by obstacles, return multiplicative factor
Protected Types
typedef std::map< CacheKey, double > CacheEntries
Protected Attributes
cXMLElement * obstaclesXml
obstacles to add at startup
int gridCellSize = 250
size of square grid tiles for obstacle store
std::vector< std::unique_ptr< Obstacle > > obstacleOwner
AnnotationManager * annotations
AnnotationManager::Group * annotationGroup
std::map< std::string, double > perCut
std::map< std::string, double > perMeter
CacheEntries cacheEntries
BBoxLookup bboxLookup
bool isBboxLookupDirty = true
Detailed Description
ObstacleControl models obstacles that block radio transmissions.
Each Obstacle is a polygon. Transmissions that cross one of the polygon's lines will have their receive power set to zero.
Definition at line 43 of file ObstacleControl.h.
Member Typedef Documentation
CacheEntries
typedef std::map<CacheKey, double> veins::ObstacleControl::CacheEntries protected
Definition at line 98 of file ObstacleControl.h.
Constructor & Destructor Documentation
~ObstacleControl()
ObstacleControl::~ObstacleControl () override
Definition at line 48 of file ObstacleControl.cc.
 {
 }
Member Function Documentation
add()
void ObstacleControl::add (Obstacle obstacle)
Definition at line 159 of file ObstacleControl.cc.
 {
     Obstacle* o = new Obstacle(obstacle);
     obstacleOwner.emplace_back(o);
     // visualize using AnnotationManager
     if (annotations) o->visualRepresentation = annotations->drawPolygon(o->getShape(), "red", annotationGroup);
     cacheEntries.clear();
     isBboxLookupDirty = true;
 }
References annotationGroup, annotations, cacheEntries, veins::AnnotationManager::drawPolygon(), veins::Obstacle::getShape(), isBboxLookupDirty, obstacleOwner, and veins::Obstacle::visualRepresentation.
Referenced by addFromTypeAndShape(), and addFromXml().
addFromTypeAndShape()
void ObstacleControl::addFromTypeAndShape (std::string id, std::string typeId, std::vector< Coord > shape)
Definition at line 149 of file ObstacleControl.cc.
 {
     if (!isTypeSupported(typeId)) {
         throw cRuntimeError("Unsupported obstacle type: \"%s\"", typeId.c_str());
     }
     Obstacle obs(id, typeId, getAttenuationPerCut(typeId), getAttenuationPerMeter(typeId));
     obs.setShape(shape);
     add(obs);
 }
References add(), getAttenuationPerCut(), getAttenuationPerMeter(), isTypeSupported(), and veins::Obstacle::setShape().
Referenced by veins::TraCIScenarioManager::init_traci().
addFromXml()
void ObstacleControl::addFromXml (cXMLElement * xml)
Definition at line 91 of file ObstacleControl.cc.
 {
     std::string rootTag = xml->getTagName();
     if (rootTag != "obstacles") {
         throw cRuntimeError("Obstacle definition root tag was \"%s\", but expected \"obstacles\"", rootTag.c_str());
     }
     cXMLElementList list = xml->getChildren();
     for (cXMLElementList::const_iterator i = list.begin(); i != list.end(); ++i) {
         cXMLElement* e = *i;
         std::string tag = e->getTagName();
         if (tag == "type") {
             // <type id="building" db-per-cut="9" db-per-meter="0.4" />
             ASSERT(e->getAttribute("id"));
             std::string id = e->getAttribute("id");
             ASSERT(e->getAttribute("db-per-cut"));
             std::string perCutParS = e->getAttribute("db-per-cut");
             double perCutPar = strtod(perCutParS.c_str(), nullptr);
             ASSERT(e->getAttribute("db-per-meter"));
             std::string perMeterParS = e->getAttribute("db-per-meter");
             double perMeterPar = strtod(perMeterParS.c_str(), nullptr);
             perCut[id] = perCutPar;
             perMeter[id] = perMeterPar;
         }
         else if (tag == "poly") {
             // <poly id="building#0" type="building" color="#F00" shape="16,0 8,13.8564 -8,13.8564 -16,0 -8,-13.8564 8,-13.8564" />
             ASSERT(e->getAttribute("id"));
             std::string id = e->getAttribute("id");
             ASSERT(e->getAttribute("type"));
             std::string type = e->getAttribute("type");
             ASSERT(e->getAttribute("color"));
             std::string color = e->getAttribute("color");
             ASSERT(e->getAttribute("shape"));
             std::string shape = e->getAttribute("shape");
             Obstacle obs(id, type, getAttenuationPerCut(type), getAttenuationPerMeter(type));
             std::vector<Coord> sh;
             cStringTokenizer st(shape.c_str());
             while (st.hasMoreTokens()) {
                 std::string xy = st.nextToken();
                 std::vector<double> xya = cStringTokenizer(xy.c_str(), ",").asDoubleVector();
                 ASSERT(xya.size() == 2);
                 sh.push_back(Coord(xya[0], xya[1]));
             }
             obs.setShape(sh);
             add(obs);
         }
         else {
             throw cRuntimeError("Found unknown tag in obstacle definition: \"%s\"", tag.c_str());
         }
     }
 }
References add(), getAttenuationPerCut(), getAttenuationPerMeter(), perCut, perMeter, and veins::Obstacle::setShape().
Referenced by initialize().
calculateAttenuation()
double ObstacleControl::calculateAttenuation (const Coord & senderPos, const Coord & receiverPos) const
calculate additional attenuation by obstacles, return multiplicative factor
Definition at line 213 of file ObstacleControl.cc.
 {
     Enter_Method_Silent();
     if ((perCut.size() == 0) || (perMeter.size() == 0)) {
         throw cRuntimeError("Unable to use SimpleObstacleShadowing: No obstacle types have been configured");
     }
     if (obstacleOwner.size() == 0) {
         throw cRuntimeError("Unable to use SimpleObstacleShadowing: No obstacles have been added");
     }
     // return cached result, if available
     CacheKey cacheKey(senderPos, receiverPos);
     CacheEntries::const_iterator cacheEntryIter = cacheEntries.find(cacheKey);
     if (cacheEntryIter != cacheEntries.end()) {
         return cacheEntryIter->second;
     }
     // get intersections
     auto intersections = getIntersections(senderPos, receiverPos);
     double factor = 1;
     for (auto i = intersections.begin(); i != intersections.end(); ++i) {
         auto o = i->first;
         auto intersectAt = i->second;
         // if beam interacts with neither borders nor matter: bail.
         bool senderInside = o->containsPoint(senderPos);
         bool receiverInside = o->containsPoint(receiverPos);
         if ((intersectAt.size() == 0) && !senderInside && !receiverInside) continue;
         // remember number of cuts before messing with intersection points
         double numCuts = intersectAt.size();
         // for distance calculation, make sure every other pair of points marks transition through matter and void, respectively.
         if (senderInside) intersectAt.insert(intersectAt.begin(), 0);
         if (receiverInside) intersectAt.push_back(1);
         ASSERT((intersectAt.size() % 2) == 0);
         // sum up distances in matter.
         double fractionInObstacle = 0;
         for (auto i = intersectAt.begin(); i != intersectAt.end();) {
             double p1 = *(i++);
             double p2 = *(i++);
             fractionInObstacle += (p2 - p1);
         }
         // calculate attenuation
         double totalDistance = senderPos.distance(receiverPos);
         double attenuation = (o->getAttenuationPerCut() * numCuts) + (o->getAttenuationPerMeter() * fractionInObstacle * totalDistance);
         factor *= pow(10.0, -attenuation / 10.0);
         // bail if attenuation is already extremely high
         if (factor < 1e-30) break;
     }
     // cache result
     if (cacheEntries.size() >= 1000) cacheEntries.clear();
     cacheEntries[cacheKey] = factor;
     return factor;
 }
References cacheEntries, veins::Coord::distance(), getIntersections(), obstacleOwner, perCut, and perMeter.
Referenced by veins::SimpleObstacleShadowing::filterSignal().
erase()
void ObstacleControl::erase (const Obstacle * obstacle)
Definition at line 171 of file ObstacleControl.cc.
 {
     if (annotations && obstacle->visualRepresentation) annotations->erase(obstacle->visualRepresentation);
     for (auto itOwner = obstacleOwner.begin(); itOwner != obstacleOwner.end(); ++itOwner) {
         // find owning pointer and remove it to deallocate obstacle
         if (itOwner->get() == obstacle) {
             obstacleOwner.erase(itOwner);
             break;
         }
     }
     cacheEntries.clear();
     isBboxLookupDirty = true;
 }
References annotations, cacheEntries, veins::AnnotationManager::erase(), isBboxLookupDirty, obstacleOwner, and veins::Obstacle::visualRepresentation.
finish()
void ObstacleControl::finish () override
Definition at line 72 of file ObstacleControl.cc.
 {
     obstacleOwner.clear();
 }
References obstacleOwner.
getAttenuationPerCut()
double ObstacleControl::getAttenuationPerCut (std::string type)
Definition at line 276 of file ObstacleControl.cc.
 {
     if (perCut.find(type) != perCut.end())
         return perCut[type];
     else {
         throw cRuntimeError("Obstacle type %s unknown", type.c_str());
         return -1;
     }
 }
References perCut.
Referenced by addFromTypeAndShape(), and addFromXml().
getAttenuationPerMeter()
double ObstacleControl::getAttenuationPerMeter (std::string type)
Definition at line 286 of file ObstacleControl.cc.
 {
     if (perMeter.find(type) != perMeter.end())
         return perMeter[type];
     else {
         throw cRuntimeError("Obstacle type %s unknown", type.c_str());
         return -1;
     }
 }
References perMeter.
Referenced by addFromTypeAndShape(), and addFromXml().
getIntersections()
std::vector< std::pair< veins::Obstacle *, std::vector< double > > > ObstacleControl::getIntersections (const Coord & senderPos, const Coord & receiverPos) const
get hit obstacles (along with a list of points (in [0, 1]) along the line between sender and receiver where the beam intersects with the respective obstacle) as well as any obstacle that contains the sender or receiver (with a list of potentially 0 points)
Definition at line 186 of file ObstacleControl.cc.
 {
     std::vector<std::pair<Obstacle*, std::vector<double>>> allIntersections;
     // rebuild bounding box lookup structure if dirty (new obstacles added recently)
     if (isBboxLookupDirty) {
         bboxLookup = rebuildBBoxLookup(obstacleOwner);
         isBboxLookupDirty = false;
     }
     auto candidateObstacles = bboxLookup.findOverlapping({senderPos.x, senderPos.y}, {receiverPos.x, receiverPos.y});
     // remove duplicates
     sort(candidateObstacles.begin(), candidateObstacles.end());
     candidateObstacles.erase(unique(candidateObstacles.begin(), candidateObstacles.end()), candidateObstacles.end());
     for (Obstacle* o : candidateObstacles) {
         // if obstacles has neither borders nor matter: bail.
         if (o->getShape().size() < 2) continue;
         auto foundIntersections = o->getIntersections(senderPos, receiverPos);
         if (!foundIntersections.empty() || o->containsPoint(senderPos) || o->containsPoint(receiverPos)) {
             allIntersections.emplace_back(o, foundIntersections);
         }
     }
     return allIntersections;
 }
References bboxLookup, veins::BBoxLookup::findOverlapping(), isBboxLookupDirty, obstacleOwner, anonymous_namespace{ObstacleControl.cc}::rebuildBBoxLookup(), veins::Coord::x, and veins::Coord::y.
Referenced by calculateAttenuation().
handleMessage()
void ObstacleControl::handleMessage (cMessage * msg) override
Definition at line 77 of file ObstacleControl.cc.
 {
     if (msg->isSelfMessage()) {
         handleSelfMsg(msg);
         return;
     }
     throw cRuntimeError("ObstacleControl doesn't handle messages from other modules");
 }
References handleSelfMsg().
handleSelfMsg()
void ObstacleControl::handleSelfMsg (cMessage * msg)
Definition at line 86 of file ObstacleControl.cc.
 {
     throw cRuntimeError("ObstacleControl doesn't handle self-messages");
 }
Referenced by handleMessage().
initialize()
void ObstacleControl::initialize (int stage) override
Definition at line 52 of file ObstacleControl.cc.
 {
     if (stage == 1) {
         obstacleOwner.clear();
         cacheEntries.clear();
         isBboxLookupDirty = true;
         annotations = AnnotationManagerAccess().getIfExists();
         if (annotations) annotationGroup = annotations->createGroup("obstacles");
         obstaclesXml = par("obstacles");
         gridCellSize = par("gridCellSize");
         if (gridCellSize < 1) {
             throw cRuntimeError("gridCellSize was %d, but must be a positive integer number", gridCellSize);
         }
         addFromXml(obstaclesXml);
     }
 }
References addFromXml(), annotationGroup, annotations, cacheEntries, veins::AnnotationManager::createGroup(), veins::AnnotationManagerAccess::getIfExists(), gridCellSize, isBboxLookupDirty, obstacleOwner, and obstaclesXml.
isTypeSupported()
bool ObstacleControl::isTypeSupported (std::string type)
Definition at line 296 of file ObstacleControl.cc.
 {
     // the type of obstacle is supported if there are attenuation values for borders and interior
     return (perCut.find(type) != perCut.end()) && (perMeter.find(type) != perMeter.end());
 }
References perCut, and perMeter.
Referenced by addFromTypeAndShape(), and veins::TraCIScenarioManager::init_traci().
numInitStages()
int veins::ObstacleControl::numInitStages () const inline override
Definition at line 47 of file ObstacleControl.h.
     {
         return 2;
     }
Member Data Documentation
annotationGroup
AnnotationManager::Group* veins::ObstacleControl::annotationGroup protected
Definition at line 105 of file ObstacleControl.h.
Referenced by add(), and initialize().
annotations
AnnotationManager* veins::ObstacleControl::annotations protected
Definition at line 104 of file ObstacleControl.h.
Referenced by add(), erase(), and initialize().
bboxLookup
BBoxLookup veins::ObstacleControl::bboxLookup mutable protected
Definition at line 109 of file ObstacleControl.h.
Referenced by getIntersections().
cacheEntries
CacheEntries veins::ObstacleControl::cacheEntries mutable protected
Definition at line 108 of file ObstacleControl.h.
Referenced by add(), calculateAttenuation(), erase(), and initialize().
gridCellSize
int veins::ObstacleControl::gridCellSize = 250 protected
size of square grid tiles for obstacle store
Definition at line 101 of file ObstacleControl.h.
Referenced by initialize().
isBboxLookupDirty
bool veins::ObstacleControl::isBboxLookupDirty = true mutable protected
Definition at line 110 of file ObstacleControl.h.
Referenced by add(), erase(), getIntersections(), and initialize().
obstacleOwner
std::vector<std::unique_ptr<Obstacle> > veins::ObstacleControl::obstacleOwner protected
Definition at line 103 of file ObstacleControl.h.
Referenced by add(), calculateAttenuation(), erase(), finish(), getIntersections(), and initialize().
obstaclesXml
cXMLElement* veins::ObstacleControl::obstaclesXml protected
obstacles to add at startup
Definition at line 100 of file ObstacleControl.h.
Referenced by initialize().
perCut
std::map<std::string, double> veins::ObstacleControl::perCut protected
Definition at line 106 of file ObstacleControl.h.
Referenced by addFromXml(), calculateAttenuation(), getAttenuationPerCut(), and isTypeSupported().
perMeter
std::map<std::string, double> veins::ObstacleControl::perMeter protected
Definition at line 107 of file ObstacleControl.h.
Referenced by addFromXml(), calculateAttenuation(), getAttenuationPerMeter(), and isTypeSupported().
The documentation for this class was generated from the following files:
ObstacleControl.h
ObstacleControl.cc