Veins: veins::TraCICommandInterface::Vehicle Class Reference
veins::TraCICommandInterface::Vehicle Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
Vehicle (TraCICommandInterface *traci, std::string nodeId)
void setSpeedMode (int32_t bitset)
void setSpeed (double speed)
void setMaxSpeed (double speed)
TraCIColor getColor ()
void setColor (const TraCIColor &color)
void slowDown (double speed, simtime_t time)
void newRoute (std::string roadId)
void setParking ()
std::string getRoadId ()
std::string getLaneId ()
double getMaxSpeed ()
double getLanePosition ()
std::list< std::string > getPlannedRoadIds ()
std::string getRouteId ()
void changeRoute (std::string roadId, simtime_t travelTime)
void stopAt (std::string roadId, double pos, uint8_t laneid, double radius, simtime_t waittime)
int32_t getLaneIndex ()
std::string getTypeId ()
bool changeVehicleRoute (const std::list< std::string > &roads)
double getLength ()
double getWidth ()
double getHeight ()
double getAccel ()
double getDeccel ()
double getSpeed ()
double getAngle ()
double getAcceleration ()
double getDistanceTravelled ()
void setParameter (const std::string &parameter, int value)
void setParameter (const std::string &parameter, double value)
void setParameter (const std::string &parameter, const std::string &value)
void getParameter (const std::string &parameter, int &value)
void getParameter (const std::string &parameter, double &value)
void getParameter (const std::string &parameter, std::string &value)
std::string getVType ()
Returns the vehicle type of a vehicle.
double getCO2Emissions () const
Get the vehicle's CO2 emissions in mg during this time step.
double getCOEmissions () const
Get the vehicle's CO emissions in mg during this time step.
double getHCEmissions () const
Get the vehicle's HC emissions in mg during this time step.
double getPMxEmissions () const
Get the vehicle's PMx emissions in mg during this time step.
double getNOxEmissions () const
Get the vehicle's NOx emissions in mg during this time step.
double getFuelConsumption () const
Get the vehicle's fuel consumption in ml during this time step.
double getNoiseEmission () const
Get the noise generated by the vehicle's in dbA during this time step.
double getElectricityConsumption () const
Get the vehicle's electricity consumption in kWh during this time step.
double getWaitingTime () const
Get the vehicle's waiting time in s.
double getAccumulatedWaitingTime () const
Get the vehicle's accumulated waiting time in s within the previous time interval.
uint8_t getStopState () const
Get the vehicle's stop state which carries information about whether it is currently stopping and in which context.
bool isStopReached () const
Get whether the vehicle is currently stopping at a scheduled stop (e.g.
void changeTarget (const std::string &newTarget) const
Sets the vehicle's current destination edge, causing its route to be rebuilt.
std::pair< std::string, double > getLeader (const double distance)
std::vector< std::tuple< std::string, int, double, char > > getNextTls ()
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string nodeId
Detailed Description
Definition at line 129 of file TraCICommandInterface.h.
Constructor & Destructor Documentation
Vehicle()
veins::TraCICommandInterface::Vehicle::Vehicle (TraCICommandInterface * traci, std::string nodeId) inline
Definition at line 131 of file TraCICommandInterface.h.
             : traci(traci)
             , nodeId(nodeId)
         {
             connection = &traci->connection;
         }
References veins::TraCICommandInterface::connection.
Member Function Documentation
changeRoute()
void veins::TraCICommandInterface::Vehicle::changeRoute (std::string roadId, simtime_t travelTime)
Definition at line 337 of file TraCICommandInterface.cc.
 {
     if (travelTime >= 0) {
         uint8_t variableId = VAR_EDGE_TRAVELTIME;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 2;
         uint8_t edgeIdT = TYPE_STRING;
         std::string edgeId = roadId;
         uint8_t newTimeT = TYPE_DOUBLE; // has always been seconds as double
         double newTime = travelTime.dbl();
         TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << edgeIdT << edgeId << newTimeT << newTime);
         ASSERT(buf.eof());
     }
     else {
         uint8_t variableId = VAR_EDGE_TRAVELTIME;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 1;
         uint8_t edgeIdT = TYPE_STRING;
         std::string edgeId = roadId;
         TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << edgeIdT << edgeId);
         ASSERT(buf.eof());
     }
     {
         uint8_t variableId = CMD_REROUTE_TRAVELTIME;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 0;
         TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count);
         ASSERT(buf.eof());
     }
 }
References veins::TraCIConstants::CMD_REROUTE_TRAVELTIME, veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_DOUBLE, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_EDGE_TRAVELTIME.
Referenced by veins::TraCIDemo11p::onWSM().
changeTarget()
void veins::TraCICommandInterface::Vehicle::changeTarget (const std::string & newTarget) const
Sets the vehicle's current destination edge, causing its route to be rebuilt.
Definition at line 483 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     p << static_cast<uint8_t>(CMD_CHANGETARGET);
     p << nodeId;
     p << static_cast<uint8_t>(TYPE_STRING);
     p << newTarget;
     TraCIBuffer buf = traci->connection.query(CMD_SET_VEHICLE_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_CHANGETARGET, veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCIBuffer::eof(), and veins::TraCIConstants::TYPE_STRING.
changeVehicleRoute()
bool veins::TraCICommandInterface::Vehicle::changeVehicleRoute (const std::list< std::string > & roads)
Definition at line 1193 of file TraCICommandInterface.cc.
 {
     if (getRoadId().find(':') != std::string::npos) return false;
     if (edges.front().compare(getRoadId()) != 0) return false;
     uint8_t variableId = VAR_ROUTE;
     uint8_t variableType = TYPE_STRINGLIST;
     TraCIBuffer obuf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << static_cast<std::list<std::string>>(edges));
     ASSERT(obuf.eof());
     return true;
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_STRINGLIST, and veins::TraCIConstants::VAR_ROUTE.
getAccel()
double veins::TraCICommandInterface::Vehicle::getAccel ()
Definition at line 383 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ACCEL, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_ACCEL.
getAcceleration()
double veins::TraCICommandInterface::Vehicle::getAcceleration ()
Definition at line 403 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ACCELERATION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_ACCELERATION.
getAccumulatedWaitingTime()
double veins::TraCICommandInterface::Vehicle::getAccumulatedWaitingTime () const
Get the vehicle's accumulated waiting time in s within the previous time interval.
The length of the interval is configurable and 100s per default.
Returns
the accumulated waiting time
Definition at line 458 of file TraCICommandInterface.cc.
 {
     const auto apiVersion = traci->versionConfig.version;
     if (apiVersion <= 15) {
         throw cRuntimeError("TraCICommandInterface::Vehicle::getAccumulatedWaitingTime requires SUMO 0.31.0 or newer");
     }
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_WAITING_TIME_ACCUMULATED, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_WAITING_TIME_ACCUMULATED.
getAngle()
double veins::TraCICommandInterface::Vehicle::getAngle ()
Definition at line 398 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ANGLE, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_ANGLE.
getCO2Emissions()
double veins::TraCICommandInterface::Vehicle::getCO2Emissions () const
Get the vehicle's CO2 emissions in mg during this time step.
Returns
the vehicle's CO2 emissions, -1001 in case of error
Definition at line 413 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_CO2EMISSION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_CO2EMISSION.
getCOEmissions()
double veins::TraCICommandInterface::Vehicle::getCOEmissions () const
Get the vehicle's CO emissions in mg during this time step.
Returns
the vehicle's CO emissions, -1001 in case of error
Definition at line 418 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_COEMISSION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_COEMISSION.
getColor()
TraCIColor veins::TraCICommandInterface::Vehicle::getColor ()
Definition at line 158 of file TraCICommandInterface.cc.
 {
     TraCIColor res(0, 0, 0, 0);
     TraCIBuffer p;
     p << static_cast<uint8_t>(VAR_COLOR);
     p << nodeId;
     TraCIBuffer buf = connection->query(CMD_GET_VEHICLE_VARIABLE, p);
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     uint8_t responseId = RESPONSE_GET_VEHICLE_VARIABLE;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     uint8_t variableId = VAR_COLOR;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     std::string objectId = nodeId;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     uint8_t resultTypeId = TYPE_COLOR;
     ASSERT(resType_r == resultTypeId);
     buf >> res.red;
     buf >> res.green;
     buf >> res.blue;
     buf >> res.alpha;
     ASSERT(buf.eof());
     return res;
 }
References veins::TraCIColor::alpha, veins::TraCIColor::blue, veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIColor::green, veins::TraCIConnection::query(), veins::TraCIColor::red, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, veins::TraCIConstants::TYPE_COLOR, and veins::TraCIConstants::VAR_COLOR.
getDeccel()
double veins::TraCICommandInterface::Vehicle::getDeccel ()
Definition at line 388 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_DECEL, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_DECEL.
getDistanceTravelled()
double veins::TraCICommandInterface::Vehicle::getDistanceTravelled ()
Definition at line 408 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_DISTANCE, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_DISTANCE.
getElectricityConsumption()
double veins::TraCICommandInterface::Vehicle::getElectricityConsumption () const
Get the vehicle's electricity consumption in kWh during this time step.
Returns
the vehicle's electricity consumption, -1001 in case of error
Definition at line 448 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ELECTRICITYCONSUMPTION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_ELECTRICITYCONSUMPTION.
getFuelConsumption()
double veins::TraCICommandInterface::Vehicle::getFuelConsumption () const
Get the vehicle's fuel consumption in ml during this time step.
Returns
the vehicle's fuel consumption, -1001 in case of error
Definition at line 438 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_FUELCONSUMPTION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_FUELCONSUMPTION.
getHCEmissions()
double veins::TraCICommandInterface::Vehicle::getHCEmissions () const
Get the vehicle's HC emissions in mg during this time step.
Returns
the vehicle's HC emissions, -1001 in case of error
Definition at line 423 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_HCEMISSION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_HCEMISSION.
getHeight()
double veins::TraCICommandInterface::Vehicle::getHeight ()
Definition at line 378 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_HEIGHT, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_HEIGHT.
getLaneId()
std::string veins::TraCICommandInterface::Vehicle::getLaneId ()
Definition at line 297 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LANE_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_LANE_ID.
getLaneIndex()
int32_t veins::TraCICommandInterface::Vehicle::getLaneIndex ()
Definition at line 302 of file TraCICommandInterface.cc.
 {
     return traci->genericGetInt(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LANE_INDEX, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_LANE_INDEX.
getLanePosition()
double veins::TraCICommandInterface::Vehicle::getLanePosition ()
Definition at line 317 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LANEPOSITION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_LANEPOSITION.
getLeader()
std::pair< std::string, double > veins::TraCICommandInterface::Vehicle::getLeader (const double distance)
Definition at line 549 of file TraCICommandInterface.cc.
 {
     TraCIBuffer request = TraCIBuffer() << VAR_LEADER << nodeId << TYPE_DOUBLE << distance;
     TraCIBuffer response = connection->query(CMD_GET_VEHICLE_VARIABLE, request);
     uint8_t cmdLength;
     response >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         response >> cmdLengthX;
     }
     uint8_t responseId;
     response >> responseId;
     ASSERT(responseId == RESPONSE_GET_VEHICLE_VARIABLE);
     uint8_t variableType;
     response >> variableType;
     ASSERT(variableType == VAR_LEADER);
     std::string rspNodeId;
     response >> rspNodeId;
     ASSERT(strcmp(rspNodeId.c_str(), nodeId.c_str()) == 0);
     uint8_t responseType;
     response >> responseType;
     ASSERT(responseType == TYPE_COMPOUND);
     uint32_t numElements;
     response >> numElements;
     ASSERT(numElements == 2);
     uint8_t leaderType;
     response >> leaderType;
     ASSERT(leaderType == TYPE_STRING);
     std::string leaderId;
     response >> leaderId;
     uint8_t distanceType;
     response >> distanceType;
     ASSERT(distanceType == TYPE_DOUBLE);
     double distanceToLeader;
     response >> distanceToLeader;
     ASSERT(response.eof());
     return std::make_pair(leaderId, distanceToLeader);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_DOUBLE, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_LEADER.
getLength()
double veins::TraCICommandInterface::Vehicle::getLength ()
Definition at line 368 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LENGTH, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_LENGTH.
getMaxSpeed()
double veins::TraCICommandInterface::Vehicle::getMaxSpeed ()
Definition at line 312 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_MAXSPEED, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_MAXSPEED.
getNextTls()
std::vector< std::tuple< std::string, int, double, char > > veins::TraCICommandInterface::Vehicle::getNextTls ()
Definition at line 591 of file TraCICommandInterface.cc.
 {
     std::vector<std::tuple<std::string, int, double, char>> result;
     TraCIBuffer request = TraCIBuffer() << VAR_NEXT_TLS << nodeId;
     TraCIBuffer response = connection->query(CMD_GET_VEHICLE_VARIABLE, request);
     uint8_t cmdLength;
     response >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         response >> cmdLengthX;
     }
     uint8_t responseId;
     response >> responseId;
     ASSERT(responseId == RESPONSE_GET_VEHICLE_VARIABLE);
     uint8_t variableType;
     response >> variableType;
     ASSERT(variableType == VAR_NEXT_TLS);
     std::string rspNodeId;
     response >> rspNodeId;
     ASSERT(strcmp(rspNodeId.c_str(), nodeId.c_str()) == 0);
     uint8_t responseType;
     response >> responseType;
     ASSERT(responseType == TYPE_COMPOUND);
     uint32_t numElements;
     response >> numElements;
     ASSERT((numElements - 1) % 4 == 0);
     uint8_t numLinksType;
     response >> numLinksType;
     ASSERT(numLinksType == TYPE_INTEGER);
     uint32_t numLinks;
     response >> numLinks;
     ASSERT(numLinks * 4 + 1 == numElements);
     for (int i = 0; i < numLinks; ++i) {
         uint8_t tlsIdType;
         response >> tlsIdType;
         ASSERT(tlsIdType == TYPE_STRING);
         std::string tlsId;
         response >> tlsId;
         uint8_t tlsLinkIndexType;
         response >> tlsLinkIndexType;
         ASSERT(tlsLinkIndexType == TYPE_INTEGER);
         int tlsLinkIndex;
         response >> tlsLinkIndex;
         uint8_t distanceToTlsType;
         response >> distanceToTlsType;
         ASSERT(distanceToTlsType == TYPE_DOUBLE);
         double distanceToTls;
         response >> distanceToTls;
         uint8_t linkStateType;
         response >> linkStateType;
         ASSERT(linkStateType == TYPE_BYTE);
         uint8_t linkState;
         response >> linkState;
         result.push_back(std::make_tuple(tlsId, tlsLinkIndex, distanceToTls, linkState));
     }
     ASSERT(response.eof());
     return result;
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, veins::TraCIConstants::TYPE_BYTE, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_DOUBLE, veins::TraCIConstants::TYPE_INTEGER, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_NEXT_TLS.
getNoiseEmission()
double veins::TraCICommandInterface::Vehicle::getNoiseEmission () const
Get the noise generated by the vehicle's in dbA during this time step.
Returns
the noise, -1001 in case of error
Definition at line 443 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_NOISEEMISSION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_NOISEEMISSION.
getNOxEmissions()
double veins::TraCICommandInterface::Vehicle::getNOxEmissions () const
Get the vehicle's NOx emissions in mg during this time step.
Returns
the vehicle's NOx emissions, -1001 in case of error
Definition at line 433 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_NOXEMISSION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_NOXEMISSION.
getParameter() [1/3]
void veins::TraCICommandInterface::Vehicle::getParameter (const std::string & parameter, double & value)
Definition at line 1232 of file TraCICommandInterface.cc.
 {
     std::string v;
     getParameter(parameter, v);
     ParBuffer buf(v);
     buf >> value;
 }
getParameter() [2/3]
void veins::TraCICommandInterface::Vehicle::getParameter (const std::string & parameter, int & value)
Definition at line 1225 of file TraCICommandInterface.cc.
 {
     std::string v;
     getParameter(parameter, v);
     ParBuffer buf(v);
     buf >> value;
 }
getParameter() [3/3]
void veins::TraCICommandInterface::Vehicle::getParameter (const std::string & parameter, std::string & value)
Definition at line 1240 of file TraCICommandInterface.cc.
 {
     TraCIBuffer response = traci->connection.query(CMD_GET_VEHICLE_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_PARAMETER) << nodeId << static_cast<uint8_t>(TYPE_STRING) << parameter);
     uint8_t cmdLength;
     response >> cmdLength;
     uint8_t responseId;
     response >> responseId;
     ASSERT(responseId == RESPONSE_GET_VEHICLE_VARIABLE);
     uint8_t variable;
     response >> variable;
     ASSERT(variable == VAR_PARAMETER);
     std::string id;
     response >> id;
     ASSERT(id == nodeId);
     uint8_t type;
     response >> type;
     ASSERT(type == TYPE_STRING);
     response >> value;
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_PARAMETER.
getPlannedRoadIds()
std::list< std::string > veins::TraCICommandInterface::Vehicle::getPlannedRoadIds ()
Definition at line 322 of file TraCICommandInterface.cc.
 {
     return traci->genericGetStringList(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_EDGES, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_EDGES.
getPMxEmissions()
double veins::TraCICommandInterface::Vehicle::getPMxEmissions () const
Get the vehicle's PMx emissions in mg during this time step.
Returns
the vehicle's PMx emissions, -1001 in case of error
Definition at line 428 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_PMXEMISSION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_PMXEMISSION.
getRoadId()
std::string veins::TraCICommandInterface::Vehicle::getRoadId ()
Definition at line 292 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ROAD_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_ROAD_ID.
getRouteId()
std::string veins::TraCICommandInterface::Vehicle::getRouteId ()
Definition at line 327 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ROUTE_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_ROUTE_ID.
getSpeed()
double veins::TraCICommandInterface::Vehicle::getSpeed ()
Definition at line 393 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_SPEED, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_SPEED.
getStopState()
uint8_t veins::TraCICommandInterface::Vehicle::getStopState () const
Get the vehicle's stop state which carries information about whether it is currently stopping and in which context.
Returns
the stop state which is a bit field defined as follows: 1 * stopped
2 * parking
4 * triggered
8 * containerTriggered
16 * atBusStop
32 * atContainerStop
64 * atChargingStation
128 * atParkingArea
Definition at line 467 of file TraCICommandInterface.cc.
 {
     const auto apiVersion = traci->versionConfig.version;
     if (apiVersion < 18) {
         return traci->genericGetUnsignedByte(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_STOPSTATE, RESPONSE_GET_VEHICLE_VARIABLE);
     }
     else {
         return traci->genericGetInt(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_STOPSTATE, RESPONSE_GET_VEHICLE_VARIABLE);
     }
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_STOPSTATE.
getTypeId()
std::string veins::TraCICommandInterface::Vehicle::getTypeId ()
Definition at line 307 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_TYPE, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_TYPE.
getVType()
std::string veins::TraCICommandInterface::Vehicle::getVType ()
Returns the vehicle type of a vehicle.
Definition at line 1766 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_TYPE, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_TYPE.
getWaitingTime()
double veins::TraCICommandInterface::Vehicle::getWaitingTime () const
Get the vehicle's waiting time in s.
The waiting time of a vehicle is defined as the time (in seconds) spent with a speed below 0.1m/s since the last time it was faster than 0.1m/s. (basically, the waiting time of a vehicle is reset to 0 every time it moves). A vehicle that is stopping intentionally with a "stop" command does not accumulate waiting time.
Returns
the vehicle's waiting time
Definition at line 453 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_WAITING_TIME, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_WAITING_TIME.
getWidth()
double veins::TraCICommandInterface::Vehicle::getWidth ()
Definition at line 373 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_WIDTH, RESPONSE_GET_VEHICLE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_VEHICLE_VARIABLE, and veins::TraCIConstants::VAR_WIDTH.
isStopReached()
bool veins::TraCICommandInterface::Vehicle::isStopReached () const
Get whether the vehicle is currently stopping at a scheduled stop (e.g.
a bus stop or after using stopAt).
Definition at line 478 of file TraCICommandInterface.cc.
 {
     return getStopState() & 0x1;
 }
newRoute()
void veins::TraCICommandInterface::Vehicle::newRoute (std::string roadId)
Definition at line 220 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = LANE_EDGE_ID;
     uint8_t variableType = TYPE_STRING;
     TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << roadId);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConstants::LANE_EDGE_ID, veins::TraCIConnection::query(), and veins::TraCIConstants::TYPE_STRING.
setColor()
void veins::TraCICommandInterface::Vehicle::setColor (const TraCIColor & color)
Definition at line 199 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     p << static_cast<uint8_t>(VAR_COLOR);
     p << nodeId;
     p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
     TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIColor::alpha, veins::TraCIColor::blue, veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIColor::green, veins::TraCIConnection::query(), veins::TraCIColor::red, veins::TraCIConstants::TYPE_COLOR, and veins::TraCIConstants::VAR_COLOR.
setMaxSpeed()
void veins::TraCICommandInterface::Vehicle::setMaxSpeed (double speed)
Definition at line 150 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = VAR_MAXSPEED;
     uint8_t variableType = TYPE_DOUBLE;
     TraCIBuffer buf = traci->connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << speed);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCIBuffer::eof(), veins::TraCIConstants::TYPE_DOUBLE, and veins::TraCIConstants::VAR_MAXSPEED.
setParameter() [1/3]
void veins::TraCICommandInterface::Vehicle::setParameter (const std::string & parameter, const std::string & value)
Definition at line 1218 of file TraCICommandInterface.cc.
 {
     static int32_t nParameters = 2;
     TraCIBuffer buf = traci->connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_PARAMETER) << nodeId << static_cast<uint8_t>(TYPE_COMPOUND) << nParameters << static_cast<uint8_t>(TYPE_STRING) << parameter << static_cast<uint8_t>(TYPE_STRING) << value);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCIBuffer::eof(), veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::VAR_PARAMETER.
setParameter() [2/3]
void veins::TraCICommandInterface::Vehicle::setParameter (const std::string & parameter, double value)
Definition at line 1211 of file TraCICommandInterface.cc.
 {
     std::stringstream strValue;
     strValue << value;
     setParameter(parameter, strValue.str());
 }
setParameter() [3/3]
void veins::TraCICommandInterface::Vehicle::setParameter (const std::string & parameter, int value)
Definition at line 1204 of file TraCICommandInterface.cc.
 {
     std::stringstream strValue;
     strValue << value;
     setParameter(parameter, strValue.str());
 }
setParking()
void veins::TraCICommandInterface::Vehicle::setParking ()
Definition at line 228 of file TraCICommandInterface.cc.
 {
     throw cRuntimeError("TraCICommandInterface::Vehicle::setParking is non-functional as of SUMO 1.0.0");
 }
setSpeed()
void veins::TraCICommandInterface::Vehicle::setSpeed (double speed)
Definition at line 142 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = VAR_SPEED;
     uint8_t variableType = TYPE_DOUBLE;
     TraCIBuffer buf = traci->connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << speed);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCIBuffer::eof(), veins::TraCIConstants::TYPE_DOUBLE, and veins::TraCIConstants::VAR_SPEED.
Referenced by veins::TraCIMobility::handleSelfMsg().
setSpeedMode()
void veins::TraCICommandInterface::Vehicle::setSpeedMode (int32_t bitset)
Definition at line 134 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = VAR_SPEEDSETMODE;
     uint8_t variableType = TYPE_INTEGER;
     TraCIBuffer buf = traci->connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << bitset);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), nodeId, veins::TraCIConnection::query(), traci, veins::TraCIConstants::TYPE_INTEGER, and veins::TraCIConstants::VAR_SPEEDSETMODE.
slowDown()
void veins::TraCICommandInterface::Vehicle::slowDown (double speed, simtime_t time)
Definition at line 209 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = CMD_SLOWDOWN;
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 2;
     uint8_t speedType = TYPE_DOUBLE;
     uint8_t durationType = traci->getTimeType();
     TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << speedType << speed << durationType << time);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCIConstants::CMD_SLOWDOWN, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_COMPOUND, and veins::TraCIConstants::TYPE_DOUBLE.
stopAt()
void veins::TraCICommandInterface::Vehicle::stopAt (std::string roadId, double pos, uint8_t laneid, double radius, simtime_t waittime)
Definition at line 531 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = CMD_STOP;
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 4;
     uint8_t edgeIdT = TYPE_STRING;
     std::string edgeId = roadId;
     uint8_t stopPosT = TYPE_DOUBLE;
     double stopPos = pos;
     uint8_t stopLaneT = TYPE_BYTE;
     uint8_t stopLane = laneid;
     uint8_t durationT = traci->getTimeType();
     simtime_t duration = waittime;
     TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << edgeIdT << edgeId << stopPosT << stopPos << stopLaneT << stopLane << durationT << duration);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, veins::TraCIConstants::CMD_STOP, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TYPE_BYTE, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_DOUBLE, and veins::TraCIConstants::TYPE_STRING.
Member Data Documentation
connection
TraCIConnection* veins::TraCICommandInterface::Vehicle::connection protected
Definition at line 284 of file TraCICommandInterface.h.
nodeId
std::string veins::TraCICommandInterface::Vehicle::nodeId protected
Definition at line 285 of file TraCICommandInterface.h.
Referenced by setSpeedMode().
traci
TraCICommandInterface* veins::TraCICommandInterface::Vehicle::traci protected
Definition at line 283 of file TraCICommandInterface.h.
Referenced by setSpeedMode().
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc