Veins: veins::AnnotationManager Class Reference
veins::AnnotationManager Class Reference
manages annotations on the OMNeT++ canvas.
#include <AnnotationManager.h>
Classes
class Annotation
class Group
class Line
class Point
class Polygon
Public Member Functions
~AnnotationManager () override
void initialize () override
void finish () override
void handleMessage (cMessage *msg) override
void handleSelfMsg (cMessage *msg)
void handleParameterChange (const char *parname) override
void addFromXml (cXMLElement *xml)
adds Annotations from an XML document; example below.
Group * createGroup (std::string title="untitled")
Point * drawPoint (Coord p, std::string color, std::string text, Group *group=nullptr)
Line * drawLine (Coord p1, Coord p2, std::string color, Group *group=nullptr)
Polygon * drawPolygon (std::list< Coord > coords, std::string color, Group *group=nullptr)
Polygon * drawPolygon (std::vector< Coord > coords, std::string color, Group *group=nullptr)
void drawBubble (Coord p1, std::string text)
void erase (const Annotation *annotation)
void eraseAll (Group *group=nullptr)
void scheduleErase (simtime_t deltaT, Annotation *annotation)
void show (const Annotation *annotation)
void hide (const Annotation *annotation)
void showAll (Group *group=nullptr)
void hideAll (Group *group=nullptr)
Public Attributes
class VEINS_API Group
Protected Types
using Annotations = std::list< Annotation * >
using Groups = std::list< Group * >
Protected Attributes
cXMLElement * annotationsXml
annotations to add at startup
std::list< cMessage * > scheduledEraseEvts
Annotations annotations
Groups groups
cGroupFigure * annotationLayer
Detailed Description
manages annotations on the OMNeT++ canvas.
Definition at line 39 of file AnnotationManager.h.
Member Typedef Documentation
Annotations
using veins::AnnotationManager::Annotations = std::list<Annotation*> protected
Definition at line 164 of file AnnotationManager.h.
Groups
using veins::AnnotationManager::Groups = std::list<Group*> protected
Definition at line 165 of file AnnotationManager.h.
Constructor & Destructor Documentation
~AnnotationManager()
AnnotationManager::~AnnotationManager () override
Definition at line 62 of file AnnotationManager.cc.
 {
     while (scheduledEraseEvts.begin() != scheduledEraseEvts.end()) {
         cancelAndDelete(*scheduledEraseEvts.begin());
         scheduledEraseEvts.erase(scheduledEraseEvts.begin());
     }
     scheduledEraseEvts.clear();
     while (annotations.begin() != annotations.end()) {
         delete *annotations.begin();
         annotations.erase(annotations.begin());
     }
     annotations.clear();
     while (groups.begin() != groups.end()) {
         delete *groups.begin();
         groups.erase(groups.begin());
     }
     groups.clear();
 }
References annotations, groups, and scheduledEraseEvts.
Member Function Documentation
addFromXml()
void AnnotationManager::addFromXml (cXMLElement * xml)
adds Annotations from an XML document; example below.
<annotations>
  <line color="#F00" shape="16,0 8,13.8564" />
  <poly color="#0F0" shape="16,64 8,77.8564 -8,77.8564 -16,64 -8,50.1436 8,50.1436" />
</annotations>
Definition at line 131 of file AnnotationManager.cc.
 {
     std::string rootTag = xml->getTagName();
     ASSERT(rootTag == "annotations");
     cXMLElementList list = xml->getChildren();
     for (cXMLElementList::const_iterator i = list.begin(); i != list.end(); ++i) {
         cXMLElement* e = *i;
         std::string tag = e->getTagName();
         if (tag == "point") {
             ASSERT(e->getAttribute("text"));
             std::string text = e->getAttribute("text");
             ASSERT(e->getAttribute("color"));
             std::string color = e->getAttribute("color");
             ASSERT(e->getAttribute("shape"));
             std::string shape = e->getAttribute("shape");
             std::vector<std::string> points = cStringTokenizer(shape.c_str(), " ").asVector();
             ASSERT(points.size() == 2);
             std::vector<double> p1a = cStringTokenizer(points[0].c_str(), ",").asDoubleVector();
             ASSERT(p1a.size() == 2);
             drawPoint(Coord(p1a[0], p1a[1]), color, text);
         }
         else if (tag == "line") {
             ASSERT(e->getAttribute("color"));
             std::string color = e->getAttribute("color");
             ASSERT(e->getAttribute("shape"));
             std::string shape = e->getAttribute("shape");
             std::vector<std::string> points = cStringTokenizer(shape.c_str(), " ").asVector();
             ASSERT(points.size() == 2);
             std::vector<double> p1a = cStringTokenizer(points[0].c_str(), ",").asDoubleVector();
             ASSERT(p1a.size() == 2);
             std::vector<double> p2a = cStringTokenizer(points[1].c_str(), ",").asDoubleVector();
             ASSERT(p2a.size() == 2);
             drawLine(Coord(p1a[0], p1a[1]), Coord(p2a[0], p2a[1]), color);
         }
         else if (tag == "poly") {
             ASSERT(e->getAttribute("color"));
             std::string color = e->getAttribute("color");
             ASSERT(e->getAttribute("shape"));
             std::string shape = e->getAttribute("shape");
             std::vector<std::string> points = cStringTokenizer(shape.c_str(), " ").asVector();
             ASSERT(points.size() >= 2);
             std::vector<Coord> coords;
             for (std::vector<std::string>::const_iterator i = points.begin(); i != points.end(); ++i) {
                 std::vector<double> pa = cStringTokenizer(i->c_str(), ",").asDoubleVector();
                 ASSERT(pa.size() == 2);
                 coords.push_back(Coord(pa[0], pa[1]));
             }
             drawPolygon(coords, color);
         }
         else {
             throw cRuntimeError("while reading annotations xml: expected 'line' or 'poly', but got '%s'", tag.c_str());
         }
     }
 }
References drawLine(), drawPoint(), and drawPolygon().
Referenced by initialize().
createGroup()
AnnotationManager::Group * AnnotationManager::createGroup (std::string title = "untitled")
Definition at line 195 of file AnnotationManager.cc.
 {
     Group* group = new Group(title);
     groups.push_back(group);
     return group;
 }
References Group, and groups.
Referenced by veins::ObstacleControl::initialize(), and veins::VehicleObstacleControl::initialize().
drawBubble()
void AnnotationManager::drawBubble (Coord p1, std::string text)
Definition at line 244 of file AnnotationManager.cc.
 {
     std::string pxOld = getDisplayString().getTagArg("p", 0);
     std::string pyOld = getDisplayString().getTagArg("p", 1);
     std::string px;
     {
         std::stringstream ss;
         ss << p1.x;
         px = ss.str();
     }
     std::string py;
     {
         std::stringstream ss;
         ss << p1.x;
         py = ss.str();
     }
     getDisplayString().setTagArg("p", 0, px.c_str());
     getDisplayString().setTagArg("p", 1, py.c_str());
     bubble(text.c_str());
     getDisplayString().setTagArg("p", 0, pxOld.c_str());
     getDisplayString().setTagArg("p", 1, pyOld.c_str());
 }
References veins::Coord::x.
drawLine()
AnnotationManager::Line * AnnotationManager::drawLine (Coord p1, Coord p2, std::string color, Group * group = nullptr)
Definition at line 215 of file AnnotationManager.cc.
 {
     Line* l = new Line(p1, p2, color);
     l->group = group;
     annotations.push_back(l);
     if (par("draw")) show(l);
     return l;
 }
References annotations, veins::AnnotationManager::Annotation::group, and show().
Referenced by addFromXml(), and veins::VehicleObstacleControl::getPotentialObstacles().
drawPoint()
AnnotationManager::Point * AnnotationManager::drawPoint (Coord p, std::string color, std::string text, Group * group = nullptr)
Definition at line 203 of file AnnotationManager.cc.
 {
     Point* o = new Point(p, color, text);
     o->group = group;
     annotations.push_back(o);
     if (par("draw")) show(o);
     return o;
 }
References annotations, veins::AnnotationManager::Annotation::group, and show().
Referenced by addFromXml().
drawPolygon() [1/2]
AnnotationManager::Polygon * AnnotationManager::drawPolygon (std::list< Coord > coords, std::string color, Group * group = nullptr)
Definition at line 227 of file AnnotationManager.cc.
 {
     Polygon* p = new Polygon(coords, color);
     p->group = group;
     annotations.push_back(p);
     if (par("draw")) show(p);
     return p;
 }
References annotations, veins::AnnotationManager::Annotation::group, and show().
Referenced by veins::ObstacleControl::add(), addFromXml(), drawPolygon(), veins::VehicleObstacleControl::drawVehicleObstacles(), and veins::TraCIScenarioManager::init_traci().
drawPolygon() [2/2]
AnnotationManager::Polygon * AnnotationManager::drawPolygon (std::vector< Coord > coords, std::string color, Group * group = nullptr)
Definition at line 239 of file AnnotationManager.cc.
 {
     return drawPolygon(std::list<Coord>(coords.begin(), coords.end()), color, group);
 }
References drawPolygon().
erase()
void AnnotationManager::erase (const Annotation * annotation)
Definition at line 271 of file AnnotationManager.cc.
 {
     hide(annotation);
     annotations.remove(const_cast<Annotation*>(annotation));
     delete annotation;
 }
References annotations, and hide().
Referenced by veins::ObstacleControl::erase(), eraseAll(), and handleSelfMsg().
eraseAll()
void AnnotationManager::eraseAll (Group * group = nullptr)
Definition at line 278 of file AnnotationManager.cc.
 {
     for (Annotations::iterator i = annotations.begin(); i != annotations.end();) {
         if ((!group) || ((*i)->group == group)) {
             erase(*i++);
         }
         else {
             i++;
         }
     }
 }
References annotations, and erase().
Referenced by veins::VehicleObstacleControl::getPotentialObstacles().
finish()
void AnnotationManager::finish () override
Definition at line 57 of file AnnotationManager.cc.
 {
     hideAll();
 }
References hideAll().
handleMessage()
void AnnotationManager::handleMessage (cMessage * msg) override
Definition at line 83 of file AnnotationManager.cc.
 {
     if (msg->isSelfMessage()) {
         handleSelfMsg(msg);
         return;
     }
     throw cRuntimeError("AnnotationManager doesn't handle messages from other modules");
 }
References handleSelfMsg().
handleParameterChange()
void AnnotationManager::handleParameterChange (const char * parname) override
Definition at line 109 of file AnnotationManager.cc.
 {
     if (parname && (std::string(parname) == "draw")) {
         if (par("draw")) {
             showAll();
         }
         else {
             hideAll();
         }
     }
 }
References hideAll(), and showAll().
handleSelfMsg()
void AnnotationManager::handleSelfMsg (cMessage * msg)
Definition at line 92 of file AnnotationManager.cc.
 {
     if (msg->getKind() == EVT_SCHEDULED_ERASE) {
         Annotation* a = static_cast<Annotation*>(msg->getContextPointer());
         ASSERT(a);
         erase(a);
         scheduledEraseEvts.remove(msg);
         delete msg;
         return;
     }
     throw cRuntimeError("unknown self message type");
 }
References erase(), anonymous_namespace{AnnotationManager.cc}::EVT_SCHEDULED_ERASE, and scheduledEraseEvts.
Referenced by handleMessage().
hide()
void AnnotationManager::hide (const Annotation * annotation)
Definition at line 372 of file AnnotationManager.cc.
 {
     if (annotation->figure) {
         delete annotationLayer->removeFigure(annotation->figure);
         annotation->figure = nullptr;
     }
     TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
     if (traci && traci->isConnected()) {
         for (std::list<std::string>::const_iterator i = annotation->traciPolygonsIds.begin(); i != annotation->traciPolygonsIds.end(); ++i) {
             std::string id = *i;
             traci->getCommandInterface()->polygon(id).remove(3);
         }
         annotation->traciPolygonsIds.clear();
         for (std::list<std::string>::const_iterator i = annotation->traciLineIds.begin(); i != annotation->traciLineIds.end(); ++i) {
             std::string id = *i;
             traci->getCommandInterface()->polygon(id).remove(4);
         }
         annotation->traciLineIds.clear();
         for (std::list<std::string>::const_iterator i = annotation->traciPoiIds.begin(); i != annotation->traciPoiIds.end(); ++i) {
             std::string id = *i;
             traci->getCommandInterface()->poi(id).remove(5);
         }
         annotation->traciPoiIds.clear();
     }
 }
References annotationLayer, veins::AnnotationManager::Annotation::figure, veins::TraCIScenarioManagerAccess::get(), veins::TraCIScenarioManager::getCommandInterface(), veins::TraCIScenarioManager::isConnected(), veins::TraCICommandInterface::poi(), veins::TraCICommandInterface::polygon(), veins::TraCICommandInterface::Poi::remove(), veins::AnnotationManager::Annotation::traciLineIds, veins::AnnotationManager::Annotation::traciPoiIds, and veins::AnnotationManager::Annotation::traciPolygonsIds.
Referenced by erase(), and hideAll().
hideAll()
void AnnotationManager::hideAll (Group * group = nullptr)
Definition at line 406 of file AnnotationManager.cc.
 {
     for (Annotations::const_iterator i = annotations.begin(); i != annotations.end(); ++i) {
         if ((!group) || ((*i)->group == group)) hide(*i);
     }
 }
References annotations, and hide().
Referenced by finish(), and handleParameterChange().
initialize()
void AnnotationManager::initialize () override
Definition at line 42 of file AnnotationManager.cc.
 {
     scheduledEraseEvts.clear();
     annotations.clear();
     groups.clear();
     annotationLayer = new cGroupFigure();
     cCanvas* canvas = getParentModule()->getCanvas();
     canvas->addFigure(annotationLayer, canvas->findFigure("submodules"));
     annotationsXml = par("annotations");
     addFromXml(annotationsXml);
 }
References addFromXml(), annotationLayer, annotations, annotationsXml, groups, and scheduledEraseEvts.
scheduleErase()
void AnnotationManager::scheduleErase (simtime_t deltaT, Annotation * annotation)
Definition at line 290 of file AnnotationManager.cc.
 {
     Enter_Method_Silent();
     cMessage* evt = new cMessage("erase", EVT_SCHEDULED_ERASE);
     evt->setContextPointer(annotation);
     scheduleAt(simTime() + deltaT, evt);
     scheduledEraseEvts.push_back(evt);
 }
References anonymous_namespace{AnnotationManager.cc}::EVT_SCHEDULED_ERASE, and scheduledEraseEvts.
show()
void AnnotationManager::show (const Annotation * annotation)
Definition at line 302 of file AnnotationManager.cc.
 {
     if (annotation->figure) return;
     if (const Point* o = dynamic_cast<const Point*>(annotation)) {
         if (hasGUI()) {
             // no corresponding TkEnv representation
         }
         TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
         if (traci && traci->isConnected()) {
             std::stringstream nameBuilder;
             nameBuilder << o->text << " " << getEnvir()->getUniqueNumber();
             traci->getCommandInterface()->addPoi(nameBuilder.str(), "Annotation", TraCIColor::fromTkColor(o->color), 6, o->pos);
             annotation->traciPoiIds.push_back(nameBuilder.str());
         }
     }
     else if (const Line* l = dynamic_cast<const Line*>(annotation)) {
         if (hasGUI()) {
             cLineFigure* figure = new cLineFigure();
             figure->setStart(cFigure::Point(l->p1.x, l->p1.y));
             figure->setEnd(cFigure::Point(l->p2.x, l->p2.y));
             figure->setLineColor(cFigure::Color(l->color.c_str()));
             annotation->figure = figure;
             annotationLayer->addFigure(annotation->figure);
         }
         TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
         if (traci && traci->isConnected()) {
             std::list<Coord> coords;
             coords.push_back(l->p1);
             coords.push_back(l->p2);
             std::stringstream nameBuilder;
             nameBuilder << "Annotation" << getEnvir()->getUniqueNumber();
             traci->getCommandInterface()->addPolygon(nameBuilder.str(), "Annotation", TraCIColor::fromTkColor(l->color), false, 5, coords);
             annotation->traciLineIds.push_back(nameBuilder.str());
         }
     }
     else if (const Polygon* p = dynamic_cast<const Polygon*>(annotation)) {
         ASSERT(p->coords.size() >= 2);
         if (hasGUI()) {
             cPolygonFigure* figure = new cPolygonFigure();
             std::vector<cFigure::Point> points;
             for (std::list<Coord>::const_iterator i = p->coords.begin(); i != p->coords.end(); ++i) {
                 points.push_back(cFigure::Point(i->x, i->y));
             }
             figure->setPoints(points);
             figure->setLineColor(cFigure::Color(p->color.c_str()));
             figure->setFilled(false);
             annotation->figure = figure;
             annotationLayer->addFigure(annotation->figure);
         }
         TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
         if (traci && traci->isConnected()) {
             std::stringstream nameBuilder;
             nameBuilder << "Annotation" << getEnvir()->getUniqueNumber();
             traci->getCommandInterface()->addPolygon(nameBuilder.str(), "Annotation", TraCIColor::fromTkColor(p->color), false, 4, p->coords);
             annotation->traciPolygonsIds.push_back(nameBuilder.str());
         }
     }
     else {
         throw cRuntimeError("unknown Annotation type");
     }
 }
References veins::TraCICommandInterface::addPoi(), veins::TraCICommandInterface::addPolygon(), annotationLayer, veins::AnnotationManager::Annotation::figure, veins::TraCIColor::fromTkColor(), veins::TraCIScenarioManagerAccess::get(), veins::TraCIScenarioManager::getCommandInterface(), veins::TraCIScenarioManager::isConnected(), veins::AnnotationManager::Annotation::traciLineIds, veins::AnnotationManager::Annotation::traciPoiIds, and veins::AnnotationManager::Annotation::traciPolygonsIds.
Referenced by drawLine(), drawPoint(), drawPolygon(), and showAll().
showAll()
void AnnotationManager::showAll (Group * group = nullptr)
Definition at line 399 of file AnnotationManager.cc.
 {
     for (Annotations::const_iterator i = annotations.begin(); i != annotations.end(); ++i) {
         if ((!group) || ((*i)->group == group)) show(*i);
     }
 }
References annotations, and show().
Referenced by handleParameterChange().
Member Data Documentation
annotationLayer
cGroupFigure* veins::AnnotationManager::annotationLayer protected
Definition at line 174 of file AnnotationManager.h.
Referenced by hide(), initialize(), and show().
annotations
Annotations veins::AnnotationManager::annotations protected
Definition at line 171 of file AnnotationManager.h.
Referenced by drawLine(), drawPoint(), drawPolygon(), erase(), eraseAll(), hideAll(), initialize(), showAll(), and ~AnnotationManager().
annotationsXml
cXMLElement* veins::AnnotationManager::annotationsXml protected
annotations to add at startup
Definition at line 167 of file AnnotationManager.h.
Referenced by initialize().
Group
class VEINS_API veins::AnnotationManager::Group
Definition at line 1 of file AnnotationManager.h.
Referenced by createGroup().
groups
Groups veins::AnnotationManager::groups protected
Definition at line 172 of file AnnotationManager.h.
Referenced by createGroup(), initialize(), and ~AnnotationManager().
scheduledEraseEvts
std::list<cMessage*> veins::AnnotationManager::scheduledEraseEvts protected
Definition at line 169 of file AnnotationManager.h.
Referenced by handleSelfMsg(), initialize(), scheduleErase(), and ~AnnotationManager().
The documentation for this class was generated from the following files:
AnnotationManager.h
AnnotationManager.cc