Veins: veins::DemoBaseApplLayerToMac1609_4Interface Class Reference
veins::DemoBaseApplLayerToMac1609_4Interface Class Reference abstract
Interface between DemoBaseApplLayer Layer and Mac1609_4.
#include <DemoBaseApplLayerToMac1609_4Interface.h>
Public Member Functions
virtual bool isChannelSwitchingActive ()=0
virtual simtime_t getSwitchingInterval ()=0
virtual bool isCurrentChannelCCH ()=0
virtual void changeServiceChannel (Channel channelNumber)=0
virtual ~DemoBaseApplLayerToMac1609_4Interface ()
virtual const LAddress::L2Type & getMACAddress ()=0
Returns the MAC address of this MAC module.
Detailed Description
Interface between DemoBaseApplLayer Layer and Mac1609_4.
Author
David Eckhoff
Definition at line 38 of file DemoBaseApplLayerToMac1609_4Interface.h.
Constructor & Destructor Documentation
~DemoBaseApplLayerToMac1609_4Interface()
virtual veins::DemoBaseApplLayerToMac1609_4Interface::~DemoBaseApplLayerToMac1609_4Interface () inline virtual
Definition at line 48 of file DemoBaseApplLayerToMac1609_4Interface.h.
 {};
Member Function Documentation
changeServiceChannel()
virtual void veins::DemoBaseApplLayerToMac1609_4Interface::changeServiceChannel (Channel channelNumber) pure virtual
Implemented in veins::Mac1609_4.
Referenced by veins::TraCIDemo11p::onWSA(), veins::TraCIDemoRSU11p::onWSA(), and veins::DemoBaseApplLayer::startService().
getMACAddress()
virtual const LAddress::L2Type& veins::DemoBaseApplLayerToMac1609_4Interface::getMACAddress () pure virtual
Returns the MAC address of this MAC module.
Implemented in veins::Mac1609_4.
Referenced by veins::DemoBaseApplLayer::initialize().
getSwitchingInterval()
virtual simtime_t veins::DemoBaseApplLayerToMac1609_4Interface::getSwitchingInterval () pure virtual
Implemented in veins::Mac1609_4.
Referenced by veins::DemoBaseApplLayer::computeAsynchronousSendingTime(), and veins::DemoBaseApplLayer::initialize().
isChannelSwitchingActive()
virtual bool veins::DemoBaseApplLayerToMac1609_4Interface::isChannelSwitchingActive () pure virtual
Implemented in veins::Mac1609_4.
Referenced by veins::DemoBaseApplLayer::initialize().
isCurrentChannelCCH()
virtual bool veins::DemoBaseApplLayerToMac1609_4Interface::isCurrentChannelCCH () pure virtual
Implemented in veins::Mac1609_4.
Referenced by veins::DemoBaseApplLayer::computeAsynchronousSendingTime().
The documentation for this class was generated from the following file:
DemoBaseApplLayerToMac1609_4Interface.h