Veins: veins::BaseModule Class Reference
veins::BaseModule Class Reference
Base class for all simple modules of a host.
#include <BaseModule.h>
Public Member Functions
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Base class for all simple modules of a host.
This method raises an error if the host state changes to something else than ACTIVE. Therefore that a sub-classing module can be used in a simulation where the host state can change it has to override that method which forces the author to make sure the module reacts well to host state changes. Alternatively one can also set a "notAffectedByHostState" parameter of the module to true.
The base module additionally provides a function findHost which returns a pointer to the host module and a function hostIndex to return the index of the host module. The latter one correspondes to the index shown in tkenv and comes in very handy for testing and debugging using tkenv. It is used e.g. in all the 'print' macros used for debugging.
There will never be a stand-alone BaseModule module.
Note: most modules wont derive from BaseModule directly but from its sub class "BatteryAccess" which extends BaseModule by several methods for accessing the battery module.
See also
BatteryAccess
Author
Steffen Sroka
Andreas Koepke
Definition at line 69 of file BaseModule.h.
Constructor & Destructor Documentation
BaseModule() [1/2]
BaseModule::BaseModule ()
Definition at line 36 of file BaseModule.cc.
     : cSimpleModule()
 {
 }
BaseModule() [2/2]
BaseModule::BaseModule (unsigned stacksize)
Definition at line 41 of file BaseModule.cc.
     : cSimpleModule(stacksize)
 {
 }
Member Function Documentation
findHost() [1/2]
cModule *const BaseModule::findHost (void) protected
Function to get a pointer to the host module.
Definition at line 90 of file BaseModule.cc.
 {
     return FindModule<>::findHost(this);
 }
References veins::FindModule< T >::findHost().
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), veins::ChannelAccess::initialize(), veins::DemoBaseApplLayer::initialize(), veins::BaseMacLayer::initialize(), veins::BaseMobility::initialize(), initialize(), veins::PhyLayer80211p::initializeDecider80211p(), logName(), veins::TraCIDemo11p::onWSM(), veins::BatteryAccess::registerWithBattery(), veins::BaseMobility::updatePosition(), and veins::DemoBaseApplLayer::~DemoBaseApplLayer().
findHost() [2/2]
const cModule *const BaseModule::findHost (void) const protected
Definition at line 95 of file BaseModule.cc.
 {
     return FindModule<>::findHost(this);
 }
References veins::FindModule< T >::findHost().
finish() [1/2]
void veins::BaseModule::finish () inline override protected
Function to get the logging name of id.
Definition at line 106 of file BaseModule.h.
     {
         cSimpleModule::finish();
     }
finish() [2/2]
void veins::BaseModule::finish (cComponent * component, simsignal_t signalID) inline override protected
Definition at line 111 of file BaseModule.h.
     {
         cListener::finish(component, signalID);
     }
getNode()
const cModule* const veins::BaseModule::getNode () const inline
Get a reference to the local node module.
Definition at line 152 of file BaseModule.h.
     {
         return findHost();
     };
handleHostState()
void BaseModule::handleHostState (const HostState & state) protected virtual
Called whenever the hosts state changes.
Default implementation of this method throws an error whenever the host state changes and the "notAffectedbyHostState" variable is not explicitly set. This is because every module of a host has to make sure to react well to changes in the host state. Or it has to explicitly set its parameter "notAffectedbyHostState" to true.
Definition at line 75 of file BaseModule.cc.
 {
     if (notAffectedByHostState) return;
     if (state.get() != HostState::ACTIVE) {
         throw cRuntimeError("Hosts state changed to something else than active which is not handled by this module. Either handle this state correctly or if this module really isn't affected by the hosts state set the parameter \"notAffectedByHostState\" of this module to true.");
     }
 }
References veins::HostState::ACTIVE, veins::HostState::get(), and notAffectedByHostState.
Referenced by receiveSignal().
initialize()
void BaseModule::initialize (int stage) override
Basic initialization for all modules.
Subscription should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Definition at line 53 of file BaseModule.cc.
 {
     if (stage == 0) {
         notAffectedByHostState = hasPar("notAffectedByHostState") && par("notAffectedByHostState").boolValue();
         findHost()->subscribe(catHostStateSignal, this);
     }
 }
References catHostStateSignal, findHost(), and notAffectedByHostState.
Referenced by veins::ChannelAccess::initialize(), veins::BaseLayer::initialize(), and veins::BaseMobility::initialize().
logName()
std::string BaseModule::logName (void) const
Function to get the logging name of the host.
This function returns the logging name of the module with the specified id.
The logging name is the ned module name of the host (unless the host ned variable loggingName is specified). It can be used for logging messages to simplify debugging in TKEnv.
It can be used for logging messages to simplify debugging in TKEnv.
Only supports ids from simple module derived from the BaseModule or the nic compound module id.
Returns
logging name of module id or NULL if not found
See also
logName
Definition at line 111 of file BaseModule.cc.
 {
     std::ostringstream ost;
     if (hasPar("logName")) { // let modules override
         ost << par("logName").stringValue();
     }
     else {
         const cModule* const parent = findHost();
         parent->hasPar("logName") ? ost << parent->par("logName").stringValue() : ost << parent->getName();
         ost << "[" << parent->getIndex() << "]";
     }
     return ost.str();
 }
References findHost().
numInitStages()
int veins::BaseModule::numInitStages () const inline override
Divide initialization into two stages.
In the first stage (stage==0), modules subscribe to notification. The first notifications (e.g. about the initial values of some variables such as RadioState) should take place earliest in the second stage (stage==1), when everyone interested in them has already subscribed. Further one should try to keep calls to other modules out of stage 0 to assure that the other module had at least once the chance to initialize itself in stage 0.
Definition at line 135 of file BaseModule.h.
     {
         return 2;
     }
receiveSignal() [1/2]
virtual void veins::BaseModule::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj) inline virtual
Definition at line 165 of file BaseModule.h.
     {
         receiveSignal(source, signalID, obj, nullptr);
     }
receiveSignal() [2/2]
void BaseModule::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override
Definition at line 61 of file BaseModule.cc.
 {
     Enter_Method_Silent();
     if (signalID == catHostStateSignal) {
         const HostState* const pHostState = dynamic_cast<const HostState* const>(obj);
         if (pHostState) {
             handleHostState(*pHostState);
         }
         else {
             throw cRuntimeError("Got catHostStateSignal but obj was not a HostState pointer?");
         }
     }
 }
References catHostStateSignal, and handleHostState().
switchHostState()
void BaseModule::switchHostState (HostState::States state) protected
Switches the host to the passed state.
If the hosts state is switched to anything else than "ACTIVE" every module of the host has to handle this explicitly (see method "handleHostState()")!
Definition at line 84 of file BaseModule.cc.
 {
     HostState hostState(state);
     emit(catHostStateSignal, &hostState);
 }
References catHostStateSignal.
Member Data Documentation
catHostStateSignal
const simsignal_t BaseModule::catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate") static protected
Stores the category of the HostState.
Definition at line 77 of file BaseModule.h.
Referenced by initialize(), receiveSignal(), and switchHostState().
notAffectedByHostState
bool veins::BaseModule::notAffectedByHostState protected
Stores if this module is affected by changes in the hosts state.
If not explicitly set this module has to capture changes in the host state.
Definition at line 74 of file BaseModule.h.
Referenced by handleHostState(), and initialize().
The documentation for this class was generated from the following files:
BaseModule.h
BaseModule.cc