Veins: veins::MobileHostObstacle Class Reference
veins::MobileHostObstacle Class Reference
Obstacle for radio waves derived from a mobile host's body.
#include <MobileHostObstacle.h>
Public Types
using Coords = std::vector< Coord >
Public Member Functions
MobileHostObstacle (std::vector< AntennaPosition > initialAntennaPositions, BaseMobility *mobility, double length, double hostPositionOffset, double width, double height)
void setMobility (BaseMobility *mobility)
void setLength (double d)
void setHostPositionOffset (double d)
void setWidth (double d)
void setHeight (double d)
const std::vector< AntennaPosition > & getInitialAntennaPositions () const
const BaseMobility * getMobility () const
double getLength () const
double getHostPositionOffset () const
double getWidth () const
double getHeight () const
Coords getShape (simtime_t t) const
bool maybeInBounds (double x1, double y1, double x2, double y2, simtime_t t) const
double getIntersectionPoint (const Coord &senderPos, const Coord &receiverPos, simtime_t t) const
return closest point (in meters) along (senderPos–receiverPos) where this obstacle overlaps, or NAN if it doesn't
Protected Attributes
std::vector< AntennaPosition > initialAntennaPositions
Positions with identiers for all antennas connected to the host of this obstacle.
BaseMobility * mobility
double length
double hostPositionOffset
double width
double height
Detailed Description
Obstacle for radio waves derived from a mobile host's body.
Primarily used for VehicleObstacleShadowing.
Definition at line 39 of file MobileHostObstacle.h.
Member Typedef Documentation
Coords
using veins::MobileHostObstacle::Coords = std::vector<Coord>
Definition at line 41 of file MobileHostObstacle.h.
Constructor & Destructor Documentation
MobileHostObstacle()
veins::MobileHostObstacle::MobileHostObstacle (std::vector< AntennaPosition > initialAntennaPositions, BaseMobility * mobility, double length, double hostPositionOffset, double width, double height) inline
Definition at line 43 of file MobileHostObstacle.h.
         : initialAntennaPositions(std::move(initialAntennaPositions))
         , mobility(mobility)
         , length(length)
         , hostPositionOffset(hostPositionOffset)
         , width(width)
         , height(height)
     {
     }
Member Function Documentation
getHeight()
double veins::MobileHostObstacle::getHeight () const inline
Definition at line 94 of file MobileHostObstacle.h.
     {
         return height;
     }
getHostPositionOffset()
double veins::MobileHostObstacle::getHostPositionOffset () const inline
Definition at line 86 of file MobileHostObstacle.h.
     {
         return hostPositionOffset;
     }
Referenced by getShape(), and maybeInBounds().
getInitialAntennaPositions()
const std::vector<AntennaPosition>& veins::MobileHostObstacle::getInitialAntennaPositions () const inline
Definition at line 74 of file MobileHostObstacle.h.
     {
         return initialAntennaPositions;
     }
getIntersectionPoint()
double MobileHostObstacle::getIntersectionPoint (const Coord & senderPos, const Coord & receiverPos, simtime_t t) const
return closest point (in meters) along (senderPos–receiverPos) where this obstacle overlaps, or NAN if it doesn't
Definition at line 111 of file MobileHostObstacle.cc.
 {
     const double not_a_number = std::numeric_limits<double>::quiet_NaN();
     MobileHostObstacle::Coords shape = getShape(t);
     // shortcut if sender is inside
     bool senderInside = isPointInObstacle(senderPos, shape);
     if (senderInside) return 0;
     // get a list of points (in [0, 1]) along the line between sender and receiver where the beam intersects with this obstacle
     std::multiset<double> intersectAt;
     bool doesIntersect = false;
     MobileHostObstacle::Coords::const_iterator i = shape.begin();
     MobileHostObstacle::Coords::const_iterator j = (shape.rbegin() + 1).base();
     for (; i != shape.end(); j = i++) {
         Coord c1 = *i;
         Coord c2 = *j;
         double inter = segmentsIntersectAt(senderPos, receiverPos, c1, c2);
         if (inter != -1) {
             doesIntersect = true;
             EV << "intersect: " << inter << endl;
             intersectAt.insert(inter);
         }
     }
     // shortcut if no intersections
     if (!doesIntersect) {
         bool receiverInside = isPointInObstacle(receiverPos, shape);
         if (receiverInside) return senderPos.distance(receiverPos);
         return not_a_number;
     }
     return (*intersectAt.begin() * senderPos.distance(receiverPos));
 }
References veins::Coord::distance(), getShape(), anonymous_namespace{MobileHostObstacle.cc}::isPointInObstacle(), and anonymous_namespace{MobileHostObstacle.cc}::segmentsIntersectAt().
getLength()
double veins::MobileHostObstacle::getLength () const inline
Definition at line 82 of file MobileHostObstacle.h.
     {
         return length;
     }
Referenced by getShape(), and maybeInBounds().
getMobility()
const BaseMobility* veins::MobileHostObstacle::getMobility () const inline
Definition at line 78 of file MobileHostObstacle.h.
     {
         return mobility;
     }
Referenced by getShape(), and maybeInBounds().
getShape()
MobileHostObstacle::Coords MobileHostObstacle::getShape (simtime_t t) const
Definition at line 70 of file MobileHostObstacle.cc.
 {
     double l = getLength();
     double o = getHostPositionOffset(); // this is the shift we have to undo in order to (given the OMNeT++ host position) get the car's front bumper position
     double w = getWidth() / 2;
     const BaseMobility* m = getMobility();
     Coord p = m->getPositionAt(t);
     double a = Heading::fromCoord(m->getCurrentOrientation()).getRad();
     Coords shape;
     shape.push_back(p + Coord(-(l - o), -w).rotatedYaw(-a));
     shape.push_back(p + Coord(+o, -w).rotatedYaw(-a));
     shape.push_back(p + Coord(+o, +w).rotatedYaw(-a));
     shape.push_back(p + Coord(-(l - o), +w).rotatedYaw(-a));
     return shape;
 }
References veins::Heading::fromCoord(), veins::BaseMobility::getCurrentOrientation(), getHostPositionOffset(), getLength(), getMobility(), veins::BaseMobility::getPositionAt(), veins::Heading::getRad(), and getWidth().
Referenced by getIntersectionPoint().
getWidth()
double veins::MobileHostObstacle::getWidth () const inline
Definition at line 90 of file MobileHostObstacle.h.
     {
         return width;
     }
Referenced by getShape(), and maybeInBounds().
maybeInBounds()
bool MobileHostObstacle::maybeInBounds (double x1, double y1, double x2, double y2, simtime_t t) const
Definition at line 88 of file MobileHostObstacle.cc.
 {
     double l = getLength();
     double o = getHostPositionOffset(); // this is the shift we have to undo in order to (given the OMNeT++ host position) get the car's front bumper position
     double w = getWidth() / 2;
     const BaseMobility* m = getMobility();
     Coord p = m->getPositionAt(t);
     double lw = std::max(l, w);
     double xx1 = p.x - std::abs(o) - lw;
     double xx2 = p.x + std::abs(o) + lw;
     double yy1 = p.y - std::abs(o) - lw;
     double yy2 = p.y + std::abs(o) + lw;
     if (xx2 < x1) return false;
     if (xx1 > x2) return false;
     if (yy2 < y1) return false;
     if (yy1 > y2) return false;
     return true;
 }
References getHostPositionOffset(), getLength(), getMobility(), veins::BaseMobility::getPositionAt(), getWidth(), veins::Coord::x, and veins::Coord::y.
setHeight()
void veins::MobileHostObstacle::setHeight (double d) inline
Definition at line 69 of file MobileHostObstacle.h.
     {
         this->height = d;
     }
setHostPositionOffset()
void veins::MobileHostObstacle::setHostPositionOffset (double d) inline
Definition at line 61 of file MobileHostObstacle.h.
     {
         this->hostPositionOffset = d;
     }
setLength()
void veins::MobileHostObstacle::setLength (double d) inline
Definition at line 57 of file MobileHostObstacle.h.
     {
         this->length = d;
     }
setMobility()
void veins::MobileHostObstacle::setMobility (BaseMobility * mobility) inline
Definition at line 53 of file MobileHostObstacle.h.
     {
         this->mobility = mobility;
     }
setWidth()
void veins::MobileHostObstacle::setWidth (double d) inline
Definition at line 65 of file MobileHostObstacle.h.
     {
         this->width = d;
     }
Member Data Documentation
height
double veins::MobileHostObstacle::height protected
Definition at line 120 of file MobileHostObstacle.h.
hostPositionOffset
double veins::MobileHostObstacle::hostPositionOffset protected
Definition at line 118 of file MobileHostObstacle.h.
initialAntennaPositions
std::vector<AntennaPosition> veins::MobileHostObstacle::initialAntennaPositions protected
Positions with identiers for all antennas connected to the host of this obstacle.
Used to identify which host this obstacle belongs to. Even works after the host has been destroyed (as AntennaPosition only stores the comonnent id).
Definition at line 115 of file MobileHostObstacle.h.
length
double veins::MobileHostObstacle::length protected
Definition at line 117 of file MobileHostObstacle.h.
mobility
BaseMobility* veins::MobileHostObstacle::mobility protected
Definition at line 116 of file MobileHostObstacle.h.
width
double veins::MobileHostObstacle::width protected
Definition at line 119 of file MobileHostObstacle.h.
The documentation for this class was generated from the following files:
MobileHostObstacle.h
MobileHostObstacle.cc