Veins: veins::BaseWorldUtility Class Reference
veins::BaseWorldUtility Class Reference
Provides information and utility methods for the whole simulation.
#include <BaseWorldUtility.h>
Public Member Functions
BaseWorldUtility ()
void initialize (int stage) override
const Coord * getPgs ()
Returns the playgroundSize.
bool useTorus ()
Returns true if our playground represents a torus (borders are connected)
virtual Coord getRandomPosition ()
Random position somewhere in the playground.
bool use2D ()
Returns true if the world is 2-dimensional.
long getUniqueAirFrameId ()
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Static Public Member Functions
static const double speedOfLight ()
Speed of light in meters per second.
Protected Member Functions
virtual void initializeIfNecessary ()
Initializes all members accessible by other modules.
Protected Attributes
Coord playgroundSize
Size of the area the nodes are in (in meters)
bool useTorusFlag
Should the playground be treated as a torus?
bool use2DFlag
Should the world be 2-dimensional?
long airFrameId
Provides a unique number for AirFrames per simulation.
bool isInitialized
Stores if members are already initialized.
Detailed Description
Provides information and utility methods for the whole simulation.
Definition at line 40 of file BaseWorldUtility.h.
Constructor & Destructor Documentation
BaseWorldUtility()
BaseWorldUtility::BaseWorldUtility ()
Definition at line 35 of file BaseWorldUtility.cc.
     : isInitialized(false)
 {
 }
Member Function Documentation
getPgs()
const Coord* veins::BaseWorldUtility::getPgs () inline
Returns the playgroundSize.
Note: The playground is in the range [0, playground size]. Meaning the upper borders (at pg-size) as well as the lower borders (at 0) are part of the playground.
Definition at line 91 of file BaseWorldUtility.h.
     {
         initializeIfNecessary();
         return &playgroundSize;
     };
Referenced by veins::TraCIScenarioManager::init_traci(), veins::BaseConnectionManager::initialize(), veins::BaseMobility::initialize(), veins::PhyLayer80211p::initializeBreakpointPathlossModel(), veins::PhyLayer80211p::initializeSimpleObstacleShadowing(), veins::PhyLayer80211p::initializeSimplePathlossModel(), veins::PhyLayer80211p::initializeVehicleObstacleShadowing(), veins::BaseMobility::playgroundSizeX(), veins::BaseMobility::playgroundSizeY(), and veins::BaseMobility::playgroundSizeZ().
getRandomPosition()
Coord BaseWorldUtility::getRandomPosition () virtual
Random position somewhere in the playground.
Definition at line 78 of file BaseWorldUtility.cc.
 {
     initializeIfNecessary();
     return Coord(uniform(0, playgroundSize.x), uniform(0, playgroundSize.y), use2DFlag ? 0. : uniform(0, playgroundSize.z));
 }
References initializeIfNecessary(), playgroundSize, use2DFlag, veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by veins::BaseMobility::getRandomPosition(), veins::BaseMobility::initialize(), and veins::BaseMobility::placeRandomlyIfOutside().
getUniqueAirFrameId()
long veins::BaseWorldUtility::getUniqueAirFrameId () inline
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Definition at line 115 of file BaseWorldUtility.h.
     {
         initializeIfNecessary();
         // if counter has done one complete cycle and will be set to a value it already had
         if (airFrameId == -1) {
             // print a warning
             EV << "WARNING: AirFrameId-Counter has done one complete cycle. AirFrameIds are repeating now and may not be unique anymore." << endl;
         }
         return airFrameId++;
     }
Referenced by veins::BasePhyLayer::encapsMsg().
initialize()
void BaseWorldUtility::initialize (int stage) override
Definition at line 40 of file BaseWorldUtility.cc.
 {
     if (stage == 0) {
         initializeIfNecessary();
     }
     else if (stage == 1) {
         // check if necessary modules are there
         // Connection Manager
         if (!FindModule<BaseConnectionManager*>::findGlobalModule()) {
             throw cRuntimeError("Could not find a connection manager module in the network!");
         }
     }
 }
References initializeIfNecessary().
initializeIfNecessary()
void BaseWorldUtility::initializeIfNecessary () protected virtual
Initializes all members accessible by other modules.
Called once the first time another module accesses a member or during initialize stage 0 at the latest.
Definition at line 54 of file BaseWorldUtility.cc.
 {
     if (isInitialized) return;
     use2DFlag = par("use2D");
     playgroundSize = Coord(par("playgroundSizeX").doubleValue(), par("playgroundSizeY").doubleValue(), use2DFlag ? 0. : par("playgroundSizeZ").doubleValue());
     if (playgroundSize.x < 0) {
         throw cRuntimeError("Playground size in X direction is invalid: (%f). Should be greater than or equal to zero.", playgroundSize.x);
     }
     if (playgroundSize.y < 0) {
         throw cRuntimeError("Playground size in Y direction is invalid: (%f). Should be greater than or equal to zero.", playgroundSize.y);
     }
     if (!use2DFlag && playgroundSize.z < 0) {
         throw cRuntimeError("Playground size in Z direction is invalid: (%f). Should be greater than or equal to zero.", playgroundSize.z);
     }
     useTorusFlag = par("useTorus");
     airFrameId = 0;
     isInitialized = true;
 }
References airFrameId, isInitialized, playgroundSize, use2DFlag, useTorusFlag, veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by getRandomPosition(), and initialize().
speedOfLight()
static const double veins::BaseWorldUtility::speedOfLight () inline static
Speed of light in meters per second.
< meters per second
Definition at line 65 of file BaseWorldUtility.h.
     {
         return 299792458.0; ///< meters per second
     }
Referenced by veins::ChannelAccess::calculatePropagationDelay(), veins::SimplePathlossModel::filterSignal(), veins::TwoRayInterferenceModel::filterSignal(), and veins::VehicleObstacleControl::getVehicleAttenuationSingle().
use2D()
bool veins::BaseWorldUtility::use2D () inline
Returns true if the world is 2-dimensional.
Definition at line 108 of file BaseWorldUtility.h.
     {
         initializeIfNecessary();
         return use2DFlag;
     }
Referenced by veins::BaseMobility::checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), veins::PhyLayer80211p::getAnalogueModelFromName(), veins::BaseMobility::goToBorder(), veins::BaseMobility::initialize(), and veins::BaseMobility::updatePosition().
useTorus()
bool veins::BaseWorldUtility::useTorus () inline
Returns true if our playground represents a torus (borders are connected)
Definition at line 98 of file BaseWorldUtility.h.
     {
         initializeIfNecessary();
         return useTorusFlag;
     };
Referenced by veins::BaseConnectionManager::initialize(), veins::PhyLayer80211p::initializeBreakpointPathlossModel(), veins::PhyLayer80211p::initializeSimpleObstacleShadowing(), veins::PhyLayer80211p::initializeSimplePathlossModel(), and veins::PhyLayer80211p::initializeVehicleObstacleShadowing().
Member Data Documentation
airFrameId
long veins::BaseWorldUtility::airFrameId protected
Provides a unique number for AirFrames per simulation.
Definition at line 58 of file BaseWorldUtility.h.
Referenced by initializeIfNecessary().
isInitialized
bool veins::BaseWorldUtility::isInitialized protected
Stores if members are already initialized.
Definition at line 61 of file BaseWorldUtility.h.
Referenced by initializeIfNecessary().
playgroundSize
Coord veins::BaseWorldUtility::playgroundSize protected
Size of the area the nodes are in (in meters)
Note: The playground is in the range [0, playground size]. Meaning the upper borders (at pg-size) as well as the lower borders (at 0) are part of the playground.
Definition at line 49 of file BaseWorldUtility.h.
Referenced by getRandomPosition(), and initializeIfNecessary().
use2DFlag
bool veins::BaseWorldUtility::use2DFlag protected
Should the world be 2-dimensional?
Definition at line 55 of file BaseWorldUtility.h.
Referenced by getRandomPosition(), and initializeIfNecessary().
useTorusFlag
bool veins::BaseWorldUtility::useTorusFlag protected
Should the playground be treated as a torus?
Definition at line 52 of file BaseWorldUtility.h.
Referenced by initializeIfNecessary().
The documentation for this class was generated from the following files:
BaseWorldUtility.h
BaseWorldUtility.cc