Veins: veins::TraCICommandInterface::Poi Class Reference
veins::TraCICommandInterface::Poi Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
Poi (TraCICommandInterface *traci, std::string poiId)
Coord getPosition ()
void remove (int32_t layer)
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string poiId
Detailed Description
Definition at line 435 of file TraCICommandInterface.h.
Constructor & Destructor Documentation
Poi()
veins::TraCICommandInterface::Poi::Poi (TraCICommandInterface * traci, std::string poiId) inline
Definition at line 437 of file TraCICommandInterface.h.
             : traci(traci)
             , poiId(poiId)
         {
             connection = &traci->connection;
         }
References veins::TraCICommandInterface::connection.
Member Function Documentation
getPosition()
Coord veins::TraCICommandInterface::Poi::getPosition ()
Definition at line 1093 of file TraCICommandInterface.cc.
 {
     return traci->genericGetCoord(CMD_GET_POI_VARIABLE, poiId, VAR_POSITION, RESPONSE_GET_POI_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_POI_VARIABLE, veins::TraCIConstants::RESPONSE_GET_POI_VARIABLE, and veins::TraCIConstants::VAR_POSITION.
remove()
void veins::TraCICommandInterface::Poi::remove (int32_t layer)
Definition at line 1098 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     p << static_cast<uint8_t>(REMOVE) << poiId;
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     TraCIBuffer buf = connection->query(CMD_SET_POI_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_POI_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::REMOVE, and veins::TraCIConstants::TYPE_INTEGER.
Referenced by veins::AnnotationManager::hide().
Member Data Documentation
connection
TraCIConnection* veins::TraCICommandInterface::Poi::connection protected
Definition at line 449 of file TraCICommandInterface.h.
poiId
std::string veins::TraCICommandInterface::Poi::poiId protected
Definition at line 450 of file TraCICommandInterface.h.
traci
TraCICommandInterface* veins::TraCICommandInterface::Poi::traci protected
Definition at line 448 of file TraCICommandInterface.h.
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc