Veins: veins::TraCIMobility Class Reference
veins::TraCIMobility Class Reference
Used in modules created by the TraCIScenarioManager.
#include <TraCIMobility.h>
Classes
class Statistics
Public Member Functions
TraCIMobility ()
~TraCIMobility () override
void initialize (int) override
void finish () override
void handleSelfMsg (cMessage *msg) override
Called upon arrival of a self messages.
virtual void preInitialize (std::string external_id, const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan)
virtual void nextPosition (const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan, VehicleSignalSet signals={VehicleSignal::undefined})
virtual void changePosition ()
virtual void changeParkingState (bool)
virtual void collisionOccurred (bool newState)
virtual void setExternalId (std::string external_id)
virtual std::string getExternalId () const
virtual double getHostPositionOffset () const
virtual bool getParkingState () const
virtual std::string getRoadId () const
virtual double getSpeed () const
virtual VehicleSignalSet getSignals () const
virtual Heading getHeading () const
returns heading.
virtual TraCIScenarioManager * getManager () const
virtual TraCICommandInterface * getCommandInterface () const
virtual TraCICommandInterface::Vehicle * getVehicleCommandInterface () const
Coord getHostSpeed () const
Returns the speed of the host (likely 0 if setHostSpeed==false)
Public Member Functions inherited from veins::BaseMobility
BaseMobility ()
BaseMobility (unsigned stacksize)
void handleMessage (cMessage *msg) override
This modules should only receive self-messages.
void initialize (int) override
Initializes mobility model parameters.
void finish () override
Delete dynamically allocated objects.
virtual Coord getPositionAt (simtime_t_cref stWhen) const
Returns the current position at the given simulation time.
virtual Coord getCurrentOrientation () const
virtual Coord getCurrentDirection () const
virtual void setStartPosition (Coord pos)
Overrides start position if called before initialize()
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Static Public Attributes
static const simsignal_t collisionSignal = registerSignal("org_car2x_veins_modules_mobility_collision")
static const simsignal_t parkingStateChangedSignal = registerSignal("org_car2x_veins_modules_mobility_parkingStateChanged")
Static Public Attributes inherited from veins::BaseMobility
static const simsignal_t mobilityStateChangedSignal = registerSignal("org_car2x_veins_base_modules_mobilityStateChanged")
Store the category of HostMove.
Protected Member Functions
void fixIfHostGetsOutside () override
called after each read to check for (and handle) invalid positions
double calculateCO2emission (double v, double a) const
Returns the amount of CO2 emissions in grams/second, calculated for an average Car.
Coord calculateHostPosition (const Coord &vehiclePos) const
Calculates where the OMNeT++ module position of this car should be, given its front bumper position.
Coord getCurrentSpeed () const override
Calling this method on pointers of type TraCIMobility is deprecated in favor of calling either getHostSpeed or getSpeed.
Protected Member Functions inherited from veins::BaseMobility
virtual int iconSizeTagToSize (const char *tag)
Maps the passed icon size tag (is) to an actual size in pixels.
virtual const char * iconSizeToTag (double size)
Maps the passed size in pixels to an appropriate icon size tag (is).
virtual void handleBorderMsg (cMessage *)
Called upon arrival of a border messages.
virtual void makeMove ()
Moves the host.
virtual void updatePosition ()
Update the position information for this node.
double playgroundSizeX () const
Returns the width of the playground.
double playgroundSizeY () const
Returns the height of the playground.
double playgroundSizeZ () const
Returns the height of the playground.
Coord getRandomPosition ()
Random position somewhere in the playground.
bool handleIfOutside (BorderPolicy, Coord &, Coord &, Coord &, double &)
Main border handling function.
BorderHandling checkIfOutside (Coord, Coord &)
Checks whether the host is outside the playground and returns where.
void goToBorder (BorderPolicy, BorderHandling, Coord &, Coord &)
calculate the step to reach the border
void reflectCoordinate (BorderHandling border, Coord &c)
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
void reflectIfOutside (BorderHandling, Coord &, Coord &, Coord &, double &)
Utility function to reflect the node if it goes outside the playground.
void wrapIfOutside (BorderHandling, Coord &, Coord &)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
void placeRandomlyIfOutside (Coord &)
Utility function to place the node randomly if it goes outside the playground.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
int accidentCount
number of accidents
cOutVector currentPosXVec
vector plotting posx
cOutVector currentPosYVec
vector plotting posy
cOutVector currentSpeedVec
vector plotting speed
cOutVector currentAccelerationVec
vector plotting acceleration
cOutVector currentCO2EmissionVec
vector plotting current CO2 emission
Statistics statistics
everything statistics-related
bool isPreInitialized
true if preInitialize() has been called immediately before initialize()
std::string external_id
updated by setExternalId()
double hostPositionOffset
front offset for the antenna on this car
bool setHostSpeed
whether to update the speed of the host (along with its position)
simtime_t lastUpdate
updated by nextPosition()
Coord roadPosition
position of front bumper, updated by nextPosition()
std::string road_id
updated by nextPosition()
double speed
updated by nextPosition()
Heading heading
updated by nextPosition()
VehicleSignalSet signals
updated by nextPosition()
cMessage * startAccidentMsg = nullptr
cMessage * stopAccidentMsg = nullptr
TraCIScenarioManager * manager
TraCICommandInterface * commandInterface
TraCICommandInterface::Vehicle * vehicleCommandInterface
double last_speed
bool isParking
Protected Attributes inherited from veins::BaseMobility
BaseWorldUtility * world
Pointer to BaseWorldUtility – these two must know each other.
Move move
Stores the current position and move pattern of the host.
simtime_t updateInterval
Time interval (in seconds) to update the hosts position.
cMessage * moveMsg
Self message to trigger movement.
bool scaleNodeByDepth
Enable depth dependent scaling of nodes when 3d and tkenv is used.
double playgroundScaleX
Scaling of the playground in X direction.
double playgroundScaleY
Scaling of the playground in Y direction.
double origDisplayWidth
The original width the node is displayed width.
double origDisplayHeight
The original height the node is displayed width.
double origIconSize
The original size of the icon of the node.
bool hasStartPosition
Coord startPosition
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from veins::BaseMobility
enum BorderPolicy { REFLECT , WRAP , PLACERANDOMLY , RAISEERROR }
Selects how a node should behave if it reaches the edge of the playground.
enum BaseMobilityMsgKinds { MOVE_HOST = 21311 , MOVE_TO_BORDER , LAST_BASE_MOBILITY_KIND }
The kind field of messages.
enum BorderHandling {
NOWHERE , X_SMALLER , X_BIGGER , Y_SMALLER ,
Y_BIGGER , Z_SMALLER , Z_BIGGER
}
Specifies which border actually has been reached.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Used in modules created by the TraCIScenarioManager.
This module relies on the TraCIScenarioManager for state updates and can not be used on its own.
TraCI server implementations do not differentiate between the orientation and direction of a vehicle. Thus, TraCIMobility::updatePosition sets the BaseMobility's orientation and direction to the same value. Said value is equivalent to the heading of the vehicle.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff, Luca Bedogni, Bastian Halmos, Stefan Joerer
See also
TraCIScenarioManager
TraCIScenarioManagerLaunchd
Definition at line 59 of file TraCIMobility.h.
Constructor & Destructor Documentation
TraCIMobility()
veins::TraCIMobility::TraCIMobility () inline
Definition at line 80 of file TraCIMobility.h.
         : BaseMobility()
         , isPreInitialized(false)
         , manager(nullptr)
         , commandInterface(nullptr)
         , vehicleCommandInterface(nullptr)
     {
     }
~TraCIMobility()
veins::TraCIMobility::~TraCIMobility () inline override
Definition at line 88 of file TraCIMobility.h.
     {
         delete vehicleCommandInterface;
     }
Member Function Documentation
calculateCO2emission()
double TraCIMobility::calculateCO2emission (double v, double a) const protected
Returns the amount of CO2 emissions in grams/second, calculated for an average Car.
Parameters
v speed in m/s
a acceleration in m/s^2
Returns
emission in g/s
Definition at line 276 of file TraCIMobility.cc.
 {
     // Calculate CO2 emission parameters according to:
     // Cappiello, A. and Chabini, I. and Nam, E.K. and Lue, A. and Abou Zeid, M., "A statistical model of vehicle emissions and fuel consumption," IEEE 5th International Conference on Intelligent Transportation Systems (IEEE ITSC), pp. 801-809, 2002
     double A = 1000 * 0.1326; // W/m/s
     double B = 1000 * 2.7384e-03; // W/(m/s)^2
     double C = 1000 * 1.0843e-03; // W/(m/s)^3
     double M = 1325.0; // kg
     // power in W
     double P_tract = A * v + B * v * v + C * v * v * v + M * a * v; // for sloped roads: +M*g*sin_theta*v
     /*
        // "Category 7 vehicle" (e.g. a '92 Suzuki Swift)
        double alpha = 1.01;
        double beta = 0.0162;
        double delta = 1.90e-06;
        double zeta = 0.252;
        double alpha1 = 0.985;
      */
     // "Category 9 vehicle" (e.g. a '94 Dodge Spirit)
     double alpha = 1.11;
     double beta = 0.0134;
     double delta = 1.98e-06;
     double zeta = 0.241;
     double alpha1 = 0.973;
     if (P_tract <= 0) return alpha1;
     return alpha + beta * v * 3.6 + delta * v * v * v * (3.6 * 3.6 * 3.6) + zeta * a * v;
 }
Referenced by changePosition().
calculateHostPosition()
Coord TraCIMobility::calculateHostPosition (const Coord & vehiclePos) const protected
Calculates where the OMNeT++ module position of this car should be, given its front bumper position.
Definition at line 309 of file TraCIMobility.cc.
 {
     Coord corPos;
     if (hostPositionOffset >= 0.001) {
         // calculate antenna position of vehicle according to antenna offset
         corPos = vehiclePos - (heading.toCoord() * hostPositionOffset);
     }
     else {
         corPos = vehiclePos;
     }
     return corPos;
 }
References heading, hostPositionOffset, and veins::Heading::toCoord().
Referenced by changePosition(), initialize(), and preInitialize().
changeParkingState()
void TraCIMobility::changeParkingState (bool newState) virtual
Definition at line 248 of file TraCIMobility.cc.
 {
     Enter_Method_Silent();
     isParking = newState;
     emit(parkingStateChangedSignal, this);
 }
References isParking, and parkingStateChangedSignal.
changePosition()
void TraCIMobility::changePosition () virtual
Definition at line 190 of file TraCIMobility.cc.
 {
     // ensure we're not called twice in one time step
     ASSERT(lastUpdate != simTime());
     Coord nextPos = calculateHostPosition(roadPosition);
     nextPos.z = move.getStartPosition().z;
     // keep statistics (for current step)
     currentPosXVec.record(nextPos.x);
     currentPosYVec.record(nextPos.y);
     // keep statistics (relative to last step)
     if (statistics.startTime != simTime()) {
         simtime_t updateInterval = simTime() - this->lastUpdate;
         double distance = move.getStartPos().distance(nextPos);
         statistics.totalDistance += distance;
         statistics.totalTime += updateInterval;
         if (speed != -1) {
             statistics.minSpeed = std::min(statistics.minSpeed, speed);
             statistics.maxSpeed = std::max(statistics.maxSpeed, speed);
             currentSpeedVec.record(speed);
             if (last_speed != -1) {
                 double acceleration = (speed - last_speed) / updateInterval;
                 double co2emission = calculateCO2emission(speed, acceleration);
                 currentAccelerationVec.record(acceleration);
                 currentCO2EmissionVec.record(co2emission);
                 statistics.totalCO2Emission += co2emission * updateInterval.dbl();
             }
             last_speed = speed;
         }
         else {
             last_speed = -1;
             speed = -1;
         }
     }
     this->lastUpdate = simTime();
     // Update display string to show node is getting updates
     auto hostMod = getParentModule();
     if (std::string(hostMod->getDisplayString().getTagArg("veins", 0)) == ". ") {
         hostMod->getDisplayString().setTagArg("veins", 0, " .");
     }
     else {
         hostMod->getDisplayString().setTagArg("veins", 0, ". ");
     }
     move.setStart(Coord(nextPos.x, nextPos.y, move.getStartPosition().z)); // keep z position
     move.setDirectionByVector(heading.toCoord());
     move.setOrientationByVector(heading.toCoord());
     if (this->setHostSpeed) {
         move.setSpeed(speed);
     }
     fixIfHostGetsOutside();
     updatePosition();
 }
References calculateCO2emission(), calculateHostPosition(), currentAccelerationVec, currentCO2EmissionVec, currentPosXVec, currentPosYVec, currentSpeedVec, veins::Coord::distance(), fixIfHostGetsOutside(), veins::Move::getStartPos(), veins::Move::getStartPosition(), heading, last_speed, lastUpdate, veins::TraCIMobility::Statistics::maxSpeed, veins::TraCIMobility::Statistics::minSpeed, veins::BaseMobility::move, roadPosition, veins::Move::setDirectionByVector(), setHostSpeed, veins::Move::setOrientationByVector(), veins::Move::setSpeed(), veins::Move::setStart(), speed, veins::TraCIMobility::Statistics::startTime, statistics, veins::Heading::toCoord(), veins::TraCIMobility::Statistics::totalCO2Emission, veins::TraCIMobility::Statistics::totalDistance, veins::TraCIMobility::Statistics::totalTime, veins::BaseMobility::updateInterval, veins::BaseMobility::updatePosition(), veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by nextPosition().
collisionOccurred()
void TraCIMobility::collisionOccurred (bool newState) virtual
Definition at line 255 of file TraCIMobility.cc.
 {
     emit(collisionSignal, newState);
 }
References collisionSignal.
finish()
void TraCIMobility::finish () override
Definition at line 123 of file TraCIMobility.cc.
 {
     statistics.stopTime = simTime();
     statistics.recordScalars(*this);
     cancelAndDelete(startAccidentMsg);
     cancelAndDelete(stopAccidentMsg);
     isPreInitialized = false;
 }
References isPreInitialized, veins::TraCIMobility::Statistics::recordScalars(), startAccidentMsg, statistics, stopAccidentMsg, and veins::TraCIMobility::Statistics::stopTime.
fixIfHostGetsOutside()
void TraCIMobility::fixIfHostGetsOutside () override protected virtual
called after each read to check for (and handle) invalid positions
Reimplemented from veins::BaseMobility.
Definition at line 260 of file TraCIMobility.cc.
 {
     Coord pos = move.getStartPos();
     Coord dummy = Coord::ZERO;
     double dum;
     bool outsideX = (pos.x < 0) || (pos.x >= playgroundSizeX());
     bool outsideY = (pos.y < 0) || (pos.y >= playgroundSizeY());
     bool outsideZ = (!world->use2D()) && ((pos.z < 0) || (pos.z >= playgroundSizeZ()));
     if (outsideX || outsideY || outsideZ) {
         throw cRuntimeError("Tried moving host to (%f, %f) which is outside the playground", pos.x, pos.y);
     }
     handleIfOutside(RAISEERROR, pos, dummy, dummy, dum);
 }
References veins::Move::getStartPos(), veins::BaseMobility::handleIfOutside(), veins::BaseMobility::move, veins::BaseMobility::playgroundSizeX(), veins::BaseMobility::playgroundSizeY(), veins::BaseMobility::playgroundSizeZ(), veins::BaseMobility::RAISEERROR, veins::BaseWorldUtility::use2D(), veins::BaseMobility::world, veins::Coord::x, veins::Coord::y, veins::Coord::z, and veins::Coord::ZERO.
Referenced by changePosition().
getCommandInterface()
virtual TraCICommandInterface* veins::TraCIMobility::getCommandInterface () const inline virtual
Definition at line 146 of file TraCIMobility.h.
     {
         if (!commandInterface) commandInterface = getManager()->getCommandInterface();
         return commandInterface;
     }
Referenced by veins::DemoBaseApplLayer::initialize().
getCurrentSpeed()
Coord veins::TraCIMobility::getCurrentSpeed () const inline override protected virtual
Calling this method on pointers of type TraCIMobility is deprecated in favor of calling either getHostSpeed or getSpeed.
Reimplemented from veins::BaseMobility.
Definition at line 216 of file TraCIMobility.h.
     {
         return BaseMobility::getCurrentSpeed();
     }
References veins::BaseMobility::getCurrentSpeed().
Referenced by veins::DemoBaseApplLayer::handlePositionUpdate().
getExternalId()
virtual std::string veins::TraCIMobility::getExternalId () const inline virtual
Definition at line 105 of file TraCIMobility.h.
     {
         if (external_id == "") throw cRuntimeError("TraCIMobility::getExternalId called with no external_id set yet");
         return external_id;
     }
getHeading()
virtual Heading veins::TraCIMobility::getHeading () const inline virtual
returns heading.
Definition at line 136 of file TraCIMobility.h.
     {
         if (heading.isNan()) throw cRuntimeError("TraCIMobility::getHeading called with no heading set yet");
         return heading;
     }
getHostPositionOffset()
virtual double veins::TraCIMobility::getHostPositionOffset () const inline virtual
Definition at line 110 of file TraCIMobility.h.
     {
         return hostPositionOffset;
     }
getHostSpeed()
Coord veins::TraCIMobility::getHostSpeed () const inline
Returns the speed of the host (likely 0 if setHostSpeed==false)
Definition at line 160 of file TraCIMobility.h.
     {
         return BaseMobility::getCurrentSpeed();
     }
References veins::BaseMobility::getCurrentSpeed().
getManager()
virtual TraCIScenarioManager* veins::TraCIMobility::getManager () const inline virtual
Definition at line 141 of file TraCIMobility.h.
     {
         if (!manager) manager = TraCIScenarioManagerAccess().get();
         return manager;
     }
References veins::TraCIScenarioManagerAccess::get().
getParkingState()
virtual bool veins::TraCIMobility::getParkingState () const inline virtual
Definition at line 114 of file TraCIMobility.h.
     {
         return isParking;
     }
Referenced by veins::DemoBaseApplLayer::handleParkingUpdate().
getRoadId()
virtual std::string veins::TraCIMobility::getRoadId () const inline virtual
Definition at line 118 of file TraCIMobility.h.
     {
         if (road_id == "") throw cRuntimeError("TraCIMobility::getRoadId called with no road_id set yet");
         return road_id;
     }
Referenced by veins::TraCIDemo11p::handlePositionUpdate(), and veins::TraCIDemo11p::onWSM().
getSignals()
virtual VehicleSignalSet veins::TraCIMobility::getSignals () const inline virtual
Definition at line 128 of file TraCIMobility.h.
     {
         if (signals.test(VehicleSignal::undefined)) throw cRuntimeError("TraCIMobility::getSignals called with no signals set yet");
         return signals;
     }
References veins::undefined.
getSpeed()
virtual double veins::TraCIMobility::getSpeed () const inline virtual
Definition at line 123 of file TraCIMobility.h.
     {
         if (speed == -1) throw cRuntimeError("TraCIMobility::getSpeed called with no speed set yet");
         return speed;
     }
Referenced by veins::TraCIDemo11p::handlePositionUpdate().
getVehicleCommandInterface()
virtual TraCICommandInterface::Vehicle* veins::TraCIMobility::getVehicleCommandInterface () const inline virtual
Definition at line 151 of file TraCIMobility.h.
     {
         if (!vehicleCommandInterface) vehicleCommandInterface = new TraCICommandInterface::Vehicle(getCommandInterface()->vehicle(getExternalId()));
         return vehicleCommandInterface;
     }
Referenced by handleSelfMsg(), and veins::DemoBaseApplLayer::initialize().
handleSelfMsg()
void TraCIMobility::handleSelfMsg (cMessage * msg) override virtual
Called upon arrival of a self messages.
The only self message possible is to indicate a new movement. If the host is stationary this function is never called.
every time a self message arrives makeMove is called to handle the movement. Afterward updatePosition updates the position with the display.
Reimplemented from veins::BaseMobility.
Definition at line 135 of file TraCIMobility.cc.
 {
     if (msg == startAccidentMsg) {
         getVehicleCommandInterface()->setSpeed(0);
         simtime_t accidentDuration = par("accidentDuration");
         scheduleAt(simTime() + accidentDuration, stopAccidentMsg);
         accidentCount--;
     }
     else if (msg == stopAccidentMsg) {
         getVehicleCommandInterface()->setSpeed(-1);
         if (accidentCount > 0) {
             simtime_t accidentInterval = par("accidentInterval");
             scheduleAt(simTime() + accidentInterval, startAccidentMsg);
         }
     }
 }
References accidentCount, getVehicleCommandInterface(), veins::TraCICommandInterface::Vehicle::setSpeed(), startAccidentMsg, and stopAccidentMsg.
initialize()
void TraCIMobility::initialize (int stage) override
Definition at line 70 of file TraCIMobility.cc.
 {
     if (stage == 0) {
         BaseMobility::initialize(stage);
         hostPositionOffset = par("hostPositionOffset");
         setHostSpeed = par("setHostSpeed");
         accidentCount = par("accidentCount");
         currentPosXVec.setName("posx");
         currentPosYVec.setName("posy");
         currentSpeedVec.setName("speed");
         currentAccelerationVec.setName("acceleration");
         currentCO2EmissionVec.setName("co2emission");
         statistics.initialize();
         statistics.watch(*this);
         ASSERT(isPreInitialized);
         isPreInitialized = false;
         Coord nextPos = calculateHostPosition(roadPosition);
         nextPos.z = move.getStartPosition().z;
         move.setStart(nextPos);
         move.setDirectionByVector(heading.toCoord());
         move.setOrientationByVector(heading.toCoord());
         if (this->setHostSpeed) {
             move.setSpeed(speed);
         }
         isParking = false;
         startAccidentMsg = nullptr;
         stopAccidentMsg = nullptr;
         manager = nullptr;
         last_speed = -1;
         if (accidentCount > 0) {
             simtime_t accidentStart = par("accidentStart");
             startAccidentMsg = new cMessage("scheduledAccident");
             stopAccidentMsg = new cMessage("scheduledAccidentResolved");
             scheduleAt(simTime() + accidentStart, startAccidentMsg);
         }
     }
     else if (stage == 1) {
         // don't call BaseMobility::initialize(stage) -- our parent will take care to call changePosition later
     }
     else {
         BaseMobility::initialize(stage);
     }
 }
References accidentCount, calculateHostPosition(), currentAccelerationVec, currentCO2EmissionVec, currentPosXVec, currentPosYVec, currentSpeedVec, veins::Move::getStartPosition(), heading, hostPositionOffset, veins::TraCIMobility::Statistics::initialize(), veins::BaseMobility::initialize(), isParking, isPreInitialized, last_speed, manager, veins::BaseMobility::move, roadPosition, veins::Move::setDirectionByVector(), setHostSpeed, veins::Move::setOrientationByVector(), veins::Move::setSpeed(), veins::Move::setStart(), speed, startAccidentMsg, statistics, stopAccidentMsg, veins::Heading::toCoord(), veins::TraCIMobility::Statistics::watch(), and veins::Coord::z.
nextPosition()
void TraCIMobility::nextPosition (const Coord & position, std::string road_id = "", double speed = -1, Heading heading = Heading::nan, VehicleSignalSet signals = {VehicleSignal::undefined}) virtual
Definition at line 176 of file TraCIMobility.cc.
 {
     EV_DEBUG << "nextPosition " << position.x << " " << position.y << " " << road_id << " " << speed << " " << heading << std::endl;
     isPreInitialized = false;
     this->roadPosition = position;
     this->road_id = road_id;
     this->speed = speed;
     this->heading = heading;
     this->signals = signals;
     changePosition();
     ASSERT(getCurrentDirection() == heading.toCoord() and getCurrentDirection() == getCurrentOrientation());
 }
References changePosition(), veins::BaseMobility::getCurrentDirection(), veins::BaseMobility::getCurrentOrientation(), heading, isPreInitialized, road_id, roadPosition, signals, speed, veins::Heading::toCoord(), veins::Coord::x, and veins::Coord::y.
preInitialize()
void TraCIMobility::preInitialize (std::string external_id, const Coord & position, std::string road_id = "", double speed = -1, Heading heading = Heading::nan) virtual
Definition at line 152 of file TraCIMobility.cc.
 {
     this->external_id = external_id;
     this->lastUpdate = 0;
     this->roadPosition = position;
     this->road_id = road_id;
     this->speed = speed;
     this->heading = heading;
     this->hostPositionOffset = par("hostPositionOffset");
     this->setHostSpeed = par("setHostSpeed");
     Coord nextPos = calculateHostPosition(roadPosition);
     nextPos.z = move.getStartPosition().z;
     move.setStart(nextPos);
     move.setDirectionByVector(heading.toCoord());
     move.setOrientationByVector(heading.toCoord());
     if (this->setHostSpeed) {
         move.setSpeed(speed);
     }
     isPreInitialized = true;
 }
References calculateHostPosition(), external_id, veins::Move::getStartPosition(), heading, hostPositionOffset, isPreInitialized, lastUpdate, veins::BaseMobility::move, road_id, roadPosition, veins::Move::setDirectionByVector(), setHostSpeed, veins::Move::setOrientationByVector(), veins::Move::setSpeed(), veins::Move::setStart(), speed, veins::Heading::toCoord(), and veins::Coord::z.
setExternalId()
virtual void veins::TraCIMobility::setExternalId (std::string external_id) inline virtual
Definition at line 101 of file TraCIMobility.h.
     {
         this->external_id = external_id;
     }
Member Data Documentation
accidentCount
int veins::TraCIMobility::accidentCount protected
number of accidents
Definition at line 166 of file TraCIMobility.h.
Referenced by handleSelfMsg(), and initialize().
collisionSignal
const simsignal_t TraCIMobility::collisionSignal = registerSignal("org_car2x_veins_modules_mobility_collision") static
Definition at line 77 of file TraCIMobility.h.
Referenced by collisionOccurred().
commandInterface
TraCICommandInterface* veins::TraCIMobility::commandInterface mutable protected
Definition at line 192 of file TraCIMobility.h.
currentAccelerationVec
cOutVector veins::TraCIMobility::currentAccelerationVec protected
vector plotting acceleration
Definition at line 171 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
currentCO2EmissionVec
cOutVector veins::TraCIMobility::currentCO2EmissionVec protected
vector plotting current CO2 emission
Definition at line 172 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
currentPosXVec
cOutVector veins::TraCIMobility::currentPosXVec protected
vector plotting posx
Definition at line 168 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
currentPosYVec
cOutVector veins::TraCIMobility::currentPosYVec protected
vector plotting posy
Definition at line 169 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
currentSpeedVec
cOutVector veins::TraCIMobility::currentSpeedVec protected
vector plotting speed
Definition at line 170 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
external_id
std::string veins::TraCIMobility::external_id protected
updated by setExternalId()
Definition at line 178 of file TraCIMobility.h.
Referenced by preInitialize().
heading
Heading veins::TraCIMobility::heading protected
updated by nextPosition()
Definition at line 186 of file TraCIMobility.h.
Referenced by calculateHostPosition(), changePosition(), initialize(), nextPosition(), and preInitialize().
hostPositionOffset
double veins::TraCIMobility::hostPositionOffset protected
front offset for the antenna on this car
Definition at line 179 of file TraCIMobility.h.
Referenced by calculateHostPosition(), initialize(), and preInitialize().
isParking
bool veins::TraCIMobility::isParking protected
Definition at line 196 of file TraCIMobility.h.
Referenced by changeParkingState(), and initialize().
isPreInitialized
bool veins::TraCIMobility::isPreInitialized protected
true if preInitialize() has been called immediately before initialize()
Definition at line 176 of file TraCIMobility.h.
Referenced by finish(), initialize(), nextPosition(), and preInitialize().
last_speed
double veins::TraCIMobility::last_speed protected
Definition at line 194 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
lastUpdate
simtime_t veins::TraCIMobility::lastUpdate protected
updated by nextPosition()
Definition at line 182 of file TraCIMobility.h.
Referenced by changePosition(), and preInitialize().
manager
TraCIScenarioManager* veins::TraCIMobility::manager mutable protected
Definition at line 191 of file TraCIMobility.h.
Referenced by initialize().
parkingStateChangedSignal
const simsignal_t TraCIMobility::parkingStateChangedSignal = registerSignal("org_car2x_veins_modules_mobility_parkingStateChanged") static
Definition at line 78 of file TraCIMobility.h.
Referenced by changeParkingState(), veins::DemoBaseApplLayer::initialize(), and veins::DemoBaseApplLayer::receiveSignal().
road_id
std::string veins::TraCIMobility::road_id protected
updated by nextPosition()
Definition at line 184 of file TraCIMobility.h.
Referenced by nextPosition(), and preInitialize().
roadPosition
Coord veins::TraCIMobility::roadPosition protected
position of front bumper, updated by nextPosition()
Definition at line 183 of file TraCIMobility.h.
Referenced by changePosition(), initialize(), nextPosition(), and preInitialize().
setHostSpeed
bool veins::TraCIMobility::setHostSpeed protected
whether to update the speed of the host (along with its position)
Definition at line 180 of file TraCIMobility.h.
Referenced by changePosition(), initialize(), and preInitialize().
signals
VehicleSignalSet veins::TraCIMobility::signals protected
updated by nextPosition()
Definition at line 187 of file TraCIMobility.h.
Referenced by nextPosition().
speed
double veins::TraCIMobility::speed protected
updated by nextPosition()
Definition at line 185 of file TraCIMobility.h.
Referenced by changePosition(), initialize(), nextPosition(), and preInitialize().
startAccidentMsg
cMessage* veins::TraCIMobility::startAccidentMsg = nullptr protected
Definition at line 189 of file TraCIMobility.h.
Referenced by finish(), handleSelfMsg(), and initialize().
statistics
Statistics veins::TraCIMobility::statistics protected
everything statistics-related
Definition at line 174 of file TraCIMobility.h.
Referenced by changePosition(), finish(), and initialize().
stopAccidentMsg
cMessage* veins::TraCIMobility::stopAccidentMsg = nullptr protected
Definition at line 190 of file TraCIMobility.h.
Referenced by finish(), handleSelfMsg(), and initialize().
vehicleCommandInterface
TraCICommandInterface::Vehicle* veins::TraCIMobility::vehicleCommandInterface mutable protected
Definition at line 193 of file TraCIMobility.h.
The documentation for this class was generated from the following files:
TraCIMobility.h
TraCIMobility.cc