Veins: veins::TraCICommandInterface::Lane Class Reference
veins::TraCICommandInterface::Lane Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
Lane (TraCICommandInterface *traci, std::string laneId)
std::list< Coord > getShape ()
std::string getRoadId ()
double getLength ()
double getMaxSpeed ()
double getMeanSpeed ()
double getWidth ()
void setDisallowed (std::list< std::string > disallowedClasses)
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string laneId
Detailed Description
Definition at line 319 of file TraCICommandInterface.h.
Constructor & Destructor Documentation
Lane()
veins::TraCICommandInterface::Lane::Lane (TraCICommandInterface * traci, std::string laneId) inline
Definition at line 321 of file TraCICommandInterface.h.
             : traci(traci)
             , laneId(laneId)
         {
             connection = &traci->connection;
         }
References veins::TraCICommandInterface::connection.
Member Function Documentation
getLength()
double veins::TraCICommandInterface::Lane::getLength ()
Definition at line 1124 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, VAR_LENGTH, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE, and veins::TraCIConstants::VAR_LENGTH.
getMaxSpeed()
double veins::TraCICommandInterface::Lane::getMaxSpeed ()
Definition at line 1129 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, VAR_MAXSPEED, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE, and veins::TraCIConstants::VAR_MAXSPEED.
getMeanSpeed()
double veins::TraCICommandInterface::Lane::getMeanSpeed ()
Definition at line 1134 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, LAST_STEP_MEAN_SPEED, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, veins::TraCIConstants::LAST_STEP_MEAN_SPEED, and veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE.
getRoadId()
std::string veins::TraCICommandInterface::Lane::getRoadId ()
Definition at line 1119 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_LANE_VARIABLE, laneId, LANE_EDGE_ID, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, veins::TraCIConstants::LANE_EDGE_ID, and veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE.
getShape()
std::list< Coord > veins::TraCICommandInterface::Lane::getShape ()
Definition at line 1114 of file TraCICommandInterface.cc.
 {
     return traci->genericGetCoordList(CMD_GET_LANE_VARIABLE, laneId, VAR_SHAPE, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE, and veins::TraCIConstants::VAR_SHAPE.
Referenced by veins::RoadsCanvasVisualizer::initialize().
getWidth()
double veins::TraCICommandInterface::Lane::getWidth ()
Definition at line 1139 of file TraCICommandInterface.cc.
 {
     return traci->genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, VAR_WIDTH, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE, and veins::TraCIConstants::VAR_WIDTH.
setDisallowed()
void veins::TraCICommandInterface::Lane::setDisallowed (std::list< std::string > disallowedClasses)
Definition at line 1144 of file TraCICommandInterface.cc.
 {
     uint8_t variableId = LANE_DISALLOWED;
     uint8_t variableType = TYPE_STRINGLIST;
     TraCIBuffer buf;
     buf << variableId << laneId << variableType << disallowedClasses;
     TraCIBuffer obuf = connection->query(CMD_SET_LANE_VARIABLE, buf);
     ASSERT(obuf.eof());
 }
References veins::TraCIConstants::CMD_SET_LANE_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConstants::LANE_DISALLOWED, veins::TraCIConnection::query(), and veins::TraCIConstants::TYPE_STRINGLIST.
Member Data Documentation
connection
TraCIConnection* veins::TraCICommandInterface::Lane::connection protected
Definition at line 338 of file TraCICommandInterface.h.
laneId
std::string veins::TraCICommandInterface::Lane::laneId protected
Definition at line 339 of file TraCICommandInterface.h.
traci
TraCICommandInterface* veins::TraCICommandInterface::Lane::traci protected
Definition at line 337 of file TraCICommandInterface.h.
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc