Veins: veins::TraCICommandInterface::Trafficlight Class Reference
veins::TraCICommandInterface::Trafficlight Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
Trafficlight (TraCICommandInterface *traci, std::string trafficLightId)
std::string getCurrentState () const
simtime_t getDefaultCurrentPhaseDuration () const
std::list< std::string > getControlledLanes () const
std::list< std::list< TraCITrafficLightLink > > getControlledLinks () const
int32_t getCurrentPhaseIndex () const
std::string getCurrentProgramID () const
TraCITrafficLightProgram getProgramDefinition () const
simtime_t getAssumedNextSwitchTime () const
void setProgram (std::string program)
set/switch to different program
void setPhaseIndex (int32_t index)
set/switch to different phase within the program
void setState (std::string state)
void setPhaseDuration (simtime_t duration)
set remaining duration of current phase
void setProgramDefinition (TraCITrafficLightProgram::Logic program, int32_t programNr)
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string trafficLightId
Detailed Description
Definition at line 348 of file TraCICommandInterface.h.
Constructor & Destructor Documentation
Trafficlight()
veins::TraCICommandInterface::Trafficlight::Trafficlight (TraCICommandInterface * traci, std::string trafficLightId) inline
Definition at line 350 of file TraCICommandInterface.h.
             : traci(traci)
             , trafficLightId(trafficLightId)
         {
             connection = &traci->connection;
         }
References veins::TraCICommandInterface::connection.
Member Function Documentation
getAssumedNextSwitchTime()
simtime_t veins::TraCICommandInterface::Trafficlight::getAssumedNextSwitchTime () const
Definition at line 882 of file TraCICommandInterface.cc.
 {
     return traci->genericGetTime(CMD_GET_TL_VARIABLE, trafficLightId, TL_NEXT_SWITCH, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, and veins::TraCIConstants::TL_NEXT_SWITCH.
Referenced by veins::TraCITrafficLightInterface::initialize(), veins::TraCITrafficLightInterface::setNextSwitch(), and veins::TraCITrafficLightInterface::setRemainingDuration().
getControlledLanes()
std::list< std::string > veins::TraCICommandInterface::Trafficlight::getControlledLanes () const
Definition at line 676 of file TraCICommandInterface.cc.
 {
     return traci->genericGetStringList(CMD_GET_TL_VARIABLE, trafficLightId, TL_CONTROLLED_LANES, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, and veins::TraCIConstants::TL_CONTROLLED_LANES.
getControlledLinks()
std::list< std::list< TraCITrafficLightLink > > veins::TraCICommandInterface::Trafficlight::getControlledLinks () const
Definition at line 681 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_COMPOUND;
     uint8_t commandId = CMD_GET_TL_VARIABLE;
     uint8_t variableId = TL_CONTROLLED_LINKS;
     std::string objectId = trafficLightId;
     uint8_t responseId = RESPONSE_GET_TL_VARIABLE;
     TraCIBuffer buf = connection->query(commandId, TraCIBuffer() << variableId << objectId);
     // generic header
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     int32_t compoundSize;
     buf >> compoundSize; // nr of fields in the compound
     int32_t nrOfSignals = buf.readTypeChecked<int32_t>(TYPE_INTEGER);
     std::list<std::list<TraCITrafficLightLink>> controlledLinks;
     for (int32_t i = 0; i < nrOfSignals; ++i) {
         int32_t nrOfLinks = buf.readTypeChecked<int32_t>(TYPE_INTEGER);
         std::list<TraCITrafficLightLink> linksOfSignal;
         uint8_t stringListType;
         buf >> stringListType;
         ASSERT(stringListType == static_cast<uint8_t>(TYPE_STRINGLIST));
         for (int32_t j = 0; j < nrOfLinks; ++j) {
             int32_t stringCount;
             buf >> stringCount;
             ASSERT(stringCount == 3);
             TraCITrafficLightLink link;
             buf >> link.incoming;
             buf >> link.outgoing;
             buf >> link.internal;
             linksOfSignal.push_back(link);
         }
         controlledLinks.push_back(linksOfSignal);
     }
     return controlledLinks;
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCITrafficLightLink::incoming, veins::TraCITrafficLightLink::internal, veins::TraCITrafficLightLink::outgoing, veins::TraCIConnection::query(), veins::TraCIBuffer::readTypeChecked(), veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, veins::TraCIConstants::TL_CONTROLLED_LINKS, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_INTEGER, and veins::TraCIConstants::TYPE_STRINGLIST.
getCurrentPhaseIndex()
int32_t veins::TraCICommandInterface::Trafficlight::getCurrentPhaseIndex () const
Definition at line 735 of file TraCICommandInterface.cc.
 {
     return traci->genericGetInt(CMD_GET_TL_VARIABLE, trafficLightId, TL_CURRENT_PHASE, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, and veins::TraCIConstants::TL_CURRENT_PHASE.
Referenced by veins::TraCITrafficLightInterface::initialize(), and veins::TraCITrafficLightInterface::setCurrentPhaseByNr().
getCurrentProgramID()
std::string veins::TraCICommandInterface::Trafficlight::getCurrentProgramID () const
Definition at line 740 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_TL_VARIABLE, trafficLightId, TL_CURRENT_PROGRAM, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, and veins::TraCIConstants::TL_CURRENT_PROGRAM.
Referenced by veins::TraCITrafficLightInterface::initialize(), and veins::TraCITrafficLightInterface::setCurrentLogicById().
getCurrentState()
std::string veins::TraCICommandInterface::Trafficlight::getCurrentState () const
Definition at line 666 of file TraCICommandInterface.cc.
 {
     return traci->genericGetString(CMD_GET_TL_VARIABLE, trafficLightId, TL_RED_YELLOW_GREEN_STATE, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, and veins::TraCIConstants::TL_RED_YELLOW_GREEN_STATE.
Referenced by veins::TraCITrafficLightInterface::initialize(), and veins::TraCITrafficLightInterface::setCurrentState().
getDefaultCurrentPhaseDuration()
simtime_t veins::TraCICommandInterface::Trafficlight::getDefaultCurrentPhaseDuration () const
Definition at line 671 of file TraCICommandInterface.cc.
 {
     return traci->genericGetTime(CMD_GET_TL_VARIABLE, trafficLightId, TL_PHASE_DURATION, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, and veins::TraCIConstants::TL_PHASE_DURATION.
getProgramDefinition()
TraCITrafficLightProgram veins::TraCICommandInterface::Trafficlight::getProgramDefinition () const
Definition at line 745 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_COMPOUND;
     TraCITrafficLightProgram program(trafficLightId);
     const auto apiVersion = traci->versionConfig.version;
     if (apiVersion == 15 || apiVersion == 16 || apiVersion == 17 || apiVersion == 18) {
         uint8_t commandId = CMD_GET_TL_VARIABLE;
         uint8_t variableId = TL_COMPLETE_DEFINITION_RYG;
         std::string objectId = trafficLightId;
         uint8_t responseId = RESPONSE_GET_TL_VARIABLE;
         TraCIBuffer buf = connection->query(commandId, TraCIBuffer() << variableId << objectId);
         // generic header
         uint8_t cmdLength;
         buf >> cmdLength;
         if (cmdLength == 0) {
             uint32_t cmdLengthX;
             buf >> cmdLengthX;
         }
         uint8_t commandId_r;
         buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId;
         buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r;
         buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r;
         buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         int32_t compoundSize;
         buf >> compoundSize; // nr of fields in the compound
         int32_t nrOfLogics = buf.readTypeChecked<int32_t>(TYPE_INTEGER); // nr of logics in the compound
         for (int32_t i = 0; i < nrOfLogics; ++i) {
             TraCITrafficLightProgram::Logic logic;
             logic.id = buf.readTypeChecked<std::string>(TYPE_STRING); // program ID
             logic.type = buf.readTypeChecked<int32_t>(TYPE_INTEGER); // (sub)type - currently just a 0
             logic.parameter = buf.readTypeChecked<int32_t>(TYPE_COMPOUND); // (sub)parameter - currently just a 0
             logic.currentPhase = buf.readTypeChecked<int32_t>(TYPE_INTEGER); // phase index
             int32_t nrOfPhases = buf.readTypeChecked<int32_t>(TYPE_INTEGER); // number of phases in this program
             for (int32_t j = 0; j < nrOfPhases; ++j) {
                 TraCITrafficLightProgram::Phase phase;
                 phase.duration = buf.readTypeChecked<simtime_t>(traci->getTimeType()); // default duration of phase
                 phase.minDuration = buf.readTypeChecked<simtime_t>(traci->getTimeType()); // minimum duration of phase
                 phase.maxDuration = buf.readTypeChecked<simtime_t>(traci->getTimeType()); // maximum duration of phase
                 phase.state = buf.readTypeChecked<std::string>(TYPE_STRING); // phase definition (like "[ryg]*")
                 logic.phases.push_back(phase);
             }
             program.addLogic(logic);
         }
     }
     else if (apiVersion == 19 || apiVersion == 20) {
         uint8_t commandId = CMD_GET_TL_VARIABLE;
         uint8_t variableId = TL_COMPLETE_DEFINITION_RYG;
         std::string objectId = trafficLightId;
         uint8_t responseId = RESPONSE_GET_TL_VARIABLE;
         TraCIBuffer buf = connection->query(commandId, TraCIBuffer() << variableId << objectId);
         // generic header
         uint8_t cmdLength;
         buf >> cmdLength;
         if (cmdLength == 0) {
             uint32_t cmdLengthX;
             buf >> cmdLengthX;
         }
         uint8_t commandId_r;
         buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId;
         buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r;
         buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         int32_t nrOfLogics = buf.readTypeChecked<int32_t>(TYPE_COMPOUND); // nr of logics in the compound
         for (int32_t i = 0; i < nrOfLogics; ++i) {
             int32_t nrOfComps = buf.readTypeChecked<int32_t>(TYPE_COMPOUND);
             ASSERT(nrOfComps == 5);
             TraCITrafficLightProgram::Logic logic;
             logic.id = buf.readTypeChecked<std::string>(TYPE_STRING); // program ID
             logic.type = buf.readTypeChecked<int32_t>(TYPE_INTEGER); // (sub)type - currently just a 0
             logic.currentPhase = buf.readTypeChecked<int32_t>(TYPE_INTEGER); // phase index
             int32_t nrOfPhases = buf.readTypeChecked<int32_t>(TYPE_COMPOUND); // number of phases in this program
             for (int32_t j = 0; j < nrOfPhases; ++j) {
                 TraCITrafficLightProgram::Phase phase;
                 int32_t nrOfComps = buf.readTypeChecked<int32_t>(TYPE_COMPOUND);
                 ASSERT((apiVersion == 19 && nrOfComps == 5) || (apiVersion == 20 && nrOfComps == 6));
                 phase.duration = buf.readTypeChecked<simtime_t>(traci->getTimeType()); // default duration of phase
                 phase.state = buf.readTypeChecked<std::string>(TYPE_STRING); // phase definition (like "[ryg]*")
                 phase.minDuration = buf.readTypeChecked<simtime_t>(traci->getTimeType()); // minimum duration of phase
                 phase.maxDuration = buf.readTypeChecked<simtime_t>(traci->getTimeType()); // maximum duration of phase
                 if (apiVersion <= 19) {
                     phase.next = {buf.readTypeChecked<int32_t>(TYPE_INTEGER)};
                 }
                 else {
                     int32_t nextCount = buf.readTypeChecked<int32_t>(TYPE_COMPOUND);
                     phase.next = {};
                     for (int32_t k = 0; k < nextCount; ++k) {
                         phase.next.push_back(buf.readTypeChecked<int32_t>(TYPE_INTEGER));
                     }
                 }
                 if (apiVersion == 20) {
                     phase.name = buf.readTypeChecked<std::string>(TYPE_STRING);
                 }
                 logic.phases.push_back(phase);
             }
             int32_t nrOfSubpars = buf.readTypeChecked<int32_t>(TYPE_COMPOUND); // nr of subparameters
             for (int32_t j = 0; j < nrOfSubpars; ++j) {
                 uint8_t stringListType;
                 buf >> stringListType;
                 ASSERT(stringListType == static_cast<uint8_t>(TYPE_STRINGLIST));
                 std::string s1;
                 buf >> s1; // discard
                 std::string s2;
                 buf >> s2; // discard
             }
             program.addLogic(logic);
         }
     }
     else {
         throw cRuntimeError("Invalid API version used, check your code.");
     }
     return program;
 }
References veins::TraCITrafficLightProgram::addLogic(), veins::TraCIConstants::CMD_GET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCITrafficLightProgram::Logic::currentPhase, veins::TraCITrafficLightProgram::Phase::duration, veins::TraCITrafficLightProgram::Logic::id, veins::TraCITrafficLightProgram::Phase::maxDuration, veins::TraCITrafficLightProgram::Phase::minDuration, veins::TraCITrafficLightProgram::Phase::name, veins::TraCITrafficLightProgram::Phase::next, veins::TraCITrafficLightProgram::Logic::parameter, veins::TraCITrafficLightProgram::Logic::phases, veins::TraCIConnection::query(), veins::TraCIBuffer::readTypeChecked(), veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE, veins::TraCITrafficLightProgram::Phase::state, veins::TraCIConstants::TL_COMPLETE_DEFINITION_RYG, veins::TraCITrafficLightProgram::Logic::type, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_INTEGER, veins::TraCIConstants::TYPE_STRING, and veins::TraCIConstants::TYPE_STRINGLIST.
setPhaseDuration()
void veins::TraCICommandInterface::Trafficlight::setPhaseDuration (simtime_t duration)
set remaining duration of current phase
Definition at line 893 of file TraCICommandInterface.cc.
 {
     TraCIBuffer buf = connection->query(CMD_SET_TL_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(TL_PHASE_DURATION) << trafficLightId << static_cast<uint8_t>(traci->getTimeType()) << duration);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), and veins::TraCIConstants::TL_PHASE_DURATION.
Referenced by veins::TraCITrafficLightInterface::setNextSwitch(), and veins::TraCITrafficLightInterface::setRemainingDuration().
setPhaseIndex()
void veins::TraCICommandInterface::Trafficlight::setPhaseIndex (int32_t index)
set/switch to different phase within the program
Definition at line 1002 of file TraCICommandInterface.cc.
 {
     TraCIBuffer buf = connection->query(CMD_SET_TL_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(TL_PHASE_INDEX) << trafficLightId << static_cast<uint8_t>(TYPE_INTEGER) << index);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TL_PHASE_INDEX, and veins::TraCIConstants::TYPE_INTEGER.
Referenced by veins::TraCITrafficLightInterface::setCurrentPhaseByNr().
setProgram()
void veins::TraCICommandInterface::Trafficlight::setProgram (std::string program)
set/switch to different program
Definition at line 996 of file TraCICommandInterface.cc.
 {
     TraCIBuffer buf = connection->query(CMD_SET_TL_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(TL_PROGRAM) << trafficLightId << static_cast<uint8_t>(TYPE_STRING) << program);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TL_PROGRAM, and veins::TraCIConstants::TYPE_STRING.
Referenced by veins::TraCITrafficLightInterface::setCurrentLogicById().
setProgramDefinition()
void veins::TraCICommandInterface::Trafficlight::setProgramDefinition (TraCITrafficLightProgram::Logic program, int32_t programNr)
Definition at line 899 of file TraCICommandInterface.cc.
 {
     TraCIBuffer inbuf;
     const auto apiVersion = traci->versionConfig.version;
     if (apiVersion == 15 || apiVersion == 16 || apiVersion == 17 || apiVersion == 18) {
         inbuf << static_cast<uint8_t>(TL_COMPLETE_PROGRAM_RYG);
         inbuf << trafficLightId;
         inbuf << static_cast<uint8_t>(TYPE_COMPOUND);
         inbuf << logicNr;
         inbuf << static_cast<uint8_t>(TYPE_STRING);
         inbuf << logic.id;
         inbuf << static_cast<uint8_t>(TYPE_INTEGER); // (sub)type - currently unused
         inbuf << logic.type;
         inbuf << static_cast<uint8_t>(TYPE_COMPOUND); // (sub)parameter - currently unused
         inbuf << logic.parameter;
         inbuf << static_cast<uint8_t>(TYPE_INTEGER);
         inbuf << logic.currentPhase;
         inbuf << static_cast<uint8_t>(TYPE_INTEGER);
         inbuf << static_cast<int32_t>(logic.phases.size());
         for (uint32_t i = 0; i < logic.phases.size(); ++i) {
             TraCITrafficLightProgram::Phase& phase = logic.phases[i];
             inbuf << static_cast<uint8_t>(traci->getTimeType());
             inbuf << phase.duration;
             inbuf << static_cast<uint8_t>(traci->getTimeType());
             inbuf << phase.minDuration;
             inbuf << static_cast<uint8_t>(traci->getTimeType());
             inbuf << phase.maxDuration;
             inbuf << static_cast<uint8_t>(TYPE_STRING);
             inbuf << phase.state;
         }
     }
     else if (apiVersion == 19 || apiVersion == 20) {
         inbuf << static_cast<uint8_t>(TL_COMPLETE_PROGRAM_RYG);
         inbuf << trafficLightId;
         inbuf << static_cast<uint8_t>(TYPE_COMPOUND);
         inbuf << 5;
         inbuf << static_cast<uint8_t>(TYPE_STRING);
         inbuf << logic.id;
         inbuf << static_cast<uint8_t>(TYPE_INTEGER); // (sub)type - currently unused
         inbuf << logic.type;
         inbuf << static_cast<uint8_t>(TYPE_INTEGER);
         inbuf << logic.currentPhase;
         inbuf << static_cast<uint8_t>(TYPE_COMPOUND);
         inbuf << static_cast<int32_t>(logic.phases.size());
         for (uint32_t i = 0; i < logic.phases.size(); ++i) {
             TraCITrafficLightProgram::Phase& phase = logic.phases[i];
             inbuf << static_cast<uint8_t>(TYPE_COMPOUND);
             inbuf << int32_t((apiVersion == 19) ? 5 : 6);
             inbuf << static_cast<uint8_t>(traci->getTimeType());
             inbuf << phase.duration;
             inbuf << static_cast<uint8_t>(TYPE_STRING);
             inbuf << phase.state;
             inbuf << static_cast<uint8_t>(traci->getTimeType());
             inbuf << phase.minDuration;
             inbuf << static_cast<uint8_t>(traci->getTimeType());
             inbuf << phase.maxDuration;
             if (apiVersion <= 19) {
                 inbuf << static_cast<uint8_t>(TYPE_INTEGER);
                 if (phase.next.size() == 0) {
                     inbuf << static_cast<int32_t>(0);
                 }
                 else if (phase.next.size() == 1) {
                     inbuf << static_cast<int32_t>(phase.next[0]);
                 }
                 else {
                     throw cRuntimeError("Setting multiple phase.next requires a newer version of SUMO");
                 }
             }
             else {
                 inbuf << static_cast<uint8_t>(TYPE_COMPOUND);
                 inbuf << static_cast<int32_t>(phase.next.size());
                 for (int32_t next : phase.next) {
                     inbuf << static_cast<uint8_t>(TYPE_INTEGER);
                     inbuf << next;
                 }
             }
             if (apiVersion == 20) {
                 inbuf << static_cast<uint8_t>(TYPE_STRING);
                 inbuf << phase.name;
             }
         }
         // no subparameters
         inbuf << static_cast<uint8_t>(TYPE_COMPOUND);
         inbuf << int32_t(0);
     }
     else {
         throw cRuntimeError("Invalid API version used, check your code.");
     }
     TraCIBuffer obuf = connection->query(CMD_SET_TL_VARIABLE, inbuf);
     ASSERT(obuf.eof());
 }
References veins::TraCIConstants::CMD_SET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCITrafficLightProgram::Logic::currentPhase, veins::TraCITrafficLightProgram::Phase::duration, veins::TraCIBuffer::eof(), veins::TraCITrafficLightProgram::Logic::id, veins::TraCITrafficLightProgram::Phase::maxDuration, veins::TraCITrafficLightProgram::Phase::minDuration, veins::TraCITrafficLightProgram::Phase::name, veins::TraCITrafficLightProgram::Phase::next, veins::TraCITrafficLightProgram::Logic::parameter, veins::TraCITrafficLightProgram::Logic::phases, veins::TraCIConnection::query(), veins::TraCITrafficLightProgram::Phase::state, veins::TraCIConstants::TL_COMPLETE_PROGRAM_RYG, veins::TraCITrafficLightProgram::Logic::type, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_INTEGER, and veins::TraCIConstants::TYPE_STRING.
setState()
void veins::TraCICommandInterface::Trafficlight::setState (std::string state)
Definition at line 887 of file TraCICommandInterface.cc.
 {
     TraCIBuffer buf = connection->query(CMD_SET_TL_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(TL_RED_YELLOW_GREEN_STATE) << trafficLightId << static_cast<uint8_t>(TYPE_STRING) << state);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::CMD_SET_TL_VARIABLE, veins::TraCICommandInterface::connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConstants::TL_RED_YELLOW_GREEN_STATE, and veins::TraCIConstants::TYPE_STRING.
Referenced by veins::TraCITrafficLightInterface::setCurrentState().
Member Data Documentation
connection
TraCIConnection* veins::TraCICommandInterface::Trafficlight::connection protected
Definition at line 374 of file TraCICommandInterface.h.
traci
TraCICommandInterface* veins::TraCICommandInterface::Trafficlight::traci protected
Definition at line 373 of file TraCICommandInterface.h.
trafficLightId
std::string veins::TraCICommandInterface::Trafficlight::trafficLightId protected
Definition at line 375 of file TraCICommandInterface.h.
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc