Veins: veins::RoadsCanvasVisualizer Class Reference
veins::RoadsCanvasVisualizer Class Reference
Simple support module to visualize road network as received via TraCI.
#include <RoadsCanvasVisualizer.h>
Public Member Functions
void initialize (int stage) override
void handleMessage (cMessage *msg) override
void finish () override
Protected Member Functions
cPolylineFigure * createLine (const std::list< veins::Coord > &coords, cFigure::Color color, double width, bool zoom)
Protected Attributes
veins::SignalManager signalManager
cGroupFigure * figures
Detailed Description
Simple support module to visualize road network as received via TraCI.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer
See also
TraCIScenarioManager
Definition at line 43 of file RoadsCanvasVisualizer.h.
Member Function Documentation
createLine()
cPolylineFigure * RoadsCanvasVisualizer::createLine (const std::list< veins::Coord > & coords, cFigure::Color color, double width, bool zoom) protected
Definition at line 81 of file RoadsCanvasVisualizer.cc.
 {
     std::vector<cFigure::Point> points;
     for (auto coord : coords) {
         points.push_back(cFigure::Point(coord.x, coord.y));
     }
     auto* line = new cPolylineFigure();
     line->setPoints(points);
     line->setLineColor(color);
     line->setLineWidth(width);
     line->setZoomLineWidth(zoom);
     return line;
 }
Referenced by initialize().
finish()
void RoadsCanvasVisualizer::finish () override
Definition at line 77 of file RoadsCanvasVisualizer.cc.
 {
 }
handleMessage()
void RoadsCanvasVisualizer::handleMessage (cMessage * msg) override
Definition at line 72 of file RoadsCanvasVisualizer.cc.
 {
     throw cRuntimeError("RoadsCanvasVisualizer does not handle any events");
 }
initialize()
void RoadsCanvasVisualizer::initialize (int stage) override
Definition at line 31 of file RoadsCanvasVisualizer.cc.
 {
     bool enabled = par("enabled");
     if (!enabled) return;
     if (!hasGUI()) return;
     if (stage == 0) {
         TraCIScenarioManager* manager = TraCIScenarioManagerAccess().get();
         ASSERT(manager);
         figures = new cGroupFigure("roads");
         double zindex = par("lineZIndex");
 #if OMNETPP_VERSION >= 0x501
         figures->setZIndex(zindex);
 #endif
         cCanvas* canvas = getParentModule()->getCanvas();
         canvas->addFigure(figures);
         auto onTraciInitialized = [this, manager](veins::SignalPayload<bool> payload) {
             TraCICommandInterface* traci = manager->getCommandInterface();
             ASSERT(traci);
             std::string colorStr = par("lineColor");
             auto color = cFigure::Color(colorStr.c_str());
             double width = par("lineWidth");
             bool zoom = par("lineWidthZoom");
             auto laneIds = traci->getLaneIds();
             for (auto laneId : laneIds) {
                 auto coords = traci->lane(laneId).getShape();
                 auto line = createLine(coords, color, width, zoom);
                 figures->addFigure(line);
             }
         };
         signalManager.subscribeCallback(manager, TraCIScenarioManager::traciInitializedSignal, onTraciInitialized);
     }
 }
References createLine(), figures, veins::TraCIScenarioManagerAccess::get(), veins::TraCIScenarioManager::getCommandInterface(), veins::TraCICommandInterface::getLaneIds(), veins::TraCICommandInterface::Lane::getShape(), veins::TraCICommandInterface::lane(), signalManager, veins::SignalManager::subscribeCallback(), and veins::TraCIScenarioManager::traciInitializedSignal.
Member Data Documentation
figures
cGroupFigure* veins::RoadsCanvasVisualizer::figures protected
Definition at line 51 of file RoadsCanvasVisualizer.h.
Referenced by initialize().
signalManager
veins::SignalManager veins::RoadsCanvasVisualizer::signalManager protected
Definition at line 50 of file RoadsCanvasVisualizer.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
RoadsCanvasVisualizer.h
RoadsCanvasVisualizer.cc