Veins: veins::TraCICommandInterface Class Reference
veins::TraCICommandInterface Class Reference
#include <TraCICommandInterface.h>
Classes
class GuiView
class Junction
class Lane
class LaneAreaDetector
class Poi
class Polygon
class Road
class Route
class Trafficlight
class Vehicle
struct VersionConfig
Public Types
enum DepartTime { DEPART_TIME_TRIGGERED = -1 , DEPART_TIME_CONTAINER_TRIGGERED = -2 , DEPART_TIME_NOW = -3 }
enum DepartSpeed { DEPART_SPEED_RANDOM = -2 , DEPART_SPEED_MAX = -3 }
enum DepartPosition {
DEPART_POSITION_RANDOM = -2 , DEPART_POSITION_FREE = -3 , DEPART_POSITION_BASE = -4 , DEPART_POSITION_LAST = -5 ,
DEPART_POSITION_RANDOM_FREE = -6
}
enum DepartLane {
DEPART_LANE_RANDOM = -2 , DEPART_LANE_FREE = -3 , DEPART_LANE_ALLOWED = -4 , DEPART_LANE_BEST = -5 ,
DEPART_LANE_FIRST = -6
}
Public Member Functions
TraCICommandInterface (cComponent *owner, TraCIConnection &c, bool ignoreGuiCommands)
bool isIgnoringGuiCommands ()
std::pair< uint32_t, std::string > getVersion ()
void setApiVersion (uint32_t apiVersion)
std::pair< double, double > getLonLat (const Coord &)
unsigned getApiVersion () const
uint8_t getTimeType () const
uint8_t getNetBoundaryType () const
uint8_t getTimeStepCmd () const
std::pair< TraCICoord, TraCICoord > initNetworkBoundaries (int margin)
std::tuple< std::string, double, uint8_t > getRoadMapPos (const Coord &coord)
Convert Cartesian coordination to road map position.
double getDistance (const Coord &position1, const Coord &position2, bool returnDrivingDistance)
Get the distance between two arbitrary positions.
bool addVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st=0, double emitPosition=DEPART_POSITION_BASE, double emitSpeed=DEPART_SPEED_MAX, int8_t emitLane=DEPART_LANE_BEST)
Adds a vehicle to the simulation.
Vehicle vehicle (std::string nodeId)
std::list< std::string > getRoadIds ()
Road road (std::string roadId)
std::list< std::string > getLaneIds ()
Lane lane (std::string laneId)
std::list< std::string > getTrafficlightIds ()
Trafficlight trafficlight (std::string trafficLightId)
std::list< std::string > getLaneAreaDetectorIds ()
LaneAreaDetector laneAreaDetector (std::string laneAreaDetectorId)
std::list< std::string > getPolygonIds ()
void addPolygon (std::string polyId, std::string polyType, const TraCIColor &color, bool filled, int32_t layer, const std::list< Coord > &points)
Polygon polygon (std::string polyId)
std::list< std::string > getPoiIds ()
void addPoi (std::string poiId, std::string poiType, const TraCIColor &color, int32_t layer, const Coord &pos)
Poi poi (std::string poiId)
std::list< std::string > getJunctionIds ()
Junction junction (std::string junctionId)
std::list< std::string > getRouteIds ()
void addRoute (std::string routeId, const std::list< std::string > &edges)
Route route (std::string routeId)
std::list< std::string > getVehicleTypeIds ()
double getVehicleTypeMaxSpeed (std::string typeId)
void setVehicleTypeMaxSpeed (std::string typeId, double maxSpeed)
std::list< std::string > getGuiViewIds ()
GuiView guiView (std::string viewId)
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Private Member Functions
std::string genericGetString (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
Coord genericGetCoord (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
double genericGetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
void genericSetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, double value)
simtime_t genericGetTime (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
uint8_t genericGetUnsignedByte (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
int32_t genericGetInt (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
std::list< std::string > genericGetStringList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
std::list< Coord > genericGetCoordList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result *result=nullptr)
Private Attributes
TraCIConnection & connection
bool ignoreGuiCommands
VersionConfig versionConfig
Static Private Attributes
static const std::map< uint32_t, VersionConfig > versionConfigs
Additional Inherited Members
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Definition at line 38 of file TraCICommandInterface.h.
Member Enumeration Documentation
DepartLane
enum veins::TraCICommandInterface::DepartLane
Enumerator
DEPART_LANE_RANDOM
DEPART_LANE_FREE
DEPART_LANE_ALLOWED
DEPART_LANE_BEST
DEPART_LANE_FIRST
Definition at line 62 of file TraCICommandInterface.h.
                     {
         DEPART_LANE_RANDOM = -2, // A random lane
         DEPART_LANE_FREE = -3, // The least occupied lane
         DEPART_LANE_ALLOWED = -4, // The least occupied lane which allows continuation
         DEPART_LANE_BEST = -5, // The least occupied of the best lanes
         DEPART_LANE_FIRST = -6, // The rightmost valid
     };
DepartPosition
enum veins::TraCICommandInterface::DepartPosition
Enumerator
DEPART_POSITION_RANDOM
DEPART_POSITION_FREE
DEPART_POSITION_BASE
DEPART_POSITION_LAST
DEPART_POSITION_RANDOM_FREE
Definition at line 54 of file TraCICommandInterface.h.
{
         DEPART_POSITION_RANDOM = -2,
         DEPART_POSITION_FREE = -3,
         DEPART_POSITION_BASE = -4,
         DEPART_POSITION_LAST = -5,
         DEPART_POSITION_RANDOM_FREE = -6,
     };
DepartSpeed
enum veins::TraCICommandInterface::DepartSpeed
Enumerator
DEPART_SPEED_RANDOM
DEPART_SPEED_MAX
Definition at line 49 of file TraCICommandInterface.h.
                      {
         DEPART_SPEED_RANDOM = -2,
         DEPART_SPEED_MAX = -3,
     };
DepartTime
enum veins::TraCICommandInterface::DepartTime
Enumerator
DEPART_TIME_TRIGGERED
DEPART_TIME_CONTAINER_TRIGGERED
DEPART_TIME_NOW
Definition at line 43 of file TraCICommandInterface.h.
                     {
         DEPART_TIME_TRIGGERED = -1,
         DEPART_TIME_CONTAINER_TRIGGERED = -2,
         DEPART_TIME_NOW = -3, // Not yet documented and fully implemented (Sumo 0.30.0)
     };
Constructor & Destructor Documentation
TraCICommandInterface()
veins::TraCICommandInterface::TraCICommandInterface (cComponent * owner, TraCIConnection & c, bool ignoreGuiCommands)
Definition at line 48 of file TraCICommandInterface.cc.
     : HasLogProxy(owner)
     , connection(c)
     , ignoreGuiCommands(ignoreGuiCommands)
 {
 }
Member Function Documentation
addPoi()
void veins::TraCICommandInterface::addPoi (std::string poiId, std::string poiType, const TraCIColor & color, int32_t layer, const Coord & pos)
Definition at line 1073 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     TraCICoord pos = connection.omnet2traci(pos_);
     p << static_cast<uint8_t>(ADD) << poiId;
     p << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(4);
     p << static_cast<uint8_t>(TYPE_STRING) << poiType;
     p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
 #if (VEINS_VERSION_MAJOR == 5)
     p << pos;
 #else
     p << static_cast<uint8_t>(POSITION_2D) << pos;
 #endif
     TraCIBuffer buf = connection.query(CMD_SET_POI_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::ADD, veins::TraCIColor::alpha, veins::TraCIColor::blue, veins::TraCIConstants::CMD_SET_POI_VARIABLE, connection, veins::TraCIBuffer::eof(), veins::TraCIColor::green, veins::TraCIConnection::omnet2traci(), veins::TraCIConstants::POSITION_2D, veins::TraCIConnection::query(), veins::TraCIColor::red, veins::TraCIConstants::TYPE_COLOR, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_INTEGER, and veins::TraCIConstants::TYPE_STRING.
Referenced by veins::AnnotationManager::show().
addPolygon()
void veins::TraCICommandInterface::addPolygon (std::string polyId, std::string polyType, const TraCIColor & color, bool filled, int32_t layer, const std::list< Coord > & points)
Definition at line 1036 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     p << static_cast<uint8_t>(ADD) << polyId;
     p << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(5);
     p << static_cast<uint8_t>(TYPE_STRING) << polyType;
     p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
     p << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(filled);
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     p << static_cast<uint8_t>(TYPE_POLYGON);
     p.writeByteOrFull<uint32_t>(points.size());
     for (std::list<Coord>::const_iterator i = points.begin(); i != points.end(); ++i) {
         const TraCICoord& pos = connection.omnet2traci(*i);
         p << static_cast<double>(pos.x) << static_cast<double>(pos.y);
     }
     TraCIBuffer buf = connection.query(CMD_SET_POLYGON_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::ADD, veins::TraCIColor::alpha, veins::TraCIColor::blue, veins::TraCIConstants::CMD_SET_POLYGON_VARIABLE, connection, veins::TraCIBuffer::eof(), veins::TraCIColor::green, veins::TraCIConnection::omnet2traci(), veins::TraCIConnection::query(), veins::TraCIColor::red, veins::TraCIConstants::TYPE_COLOR, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_INTEGER, veins::TraCIConstants::TYPE_POLYGON, veins::TraCIConstants::TYPE_STRING, veins::TraCIConstants::TYPE_UBYTE, veins::TraCIBuffer::writeByteOrFull(), veins::TraCICoord::x, and veins::TraCICoord::y.
Referenced by veins::AnnotationManager::show().
addRoute()
void veins::TraCICommandInterface::addRoute (std::string routeId, const std::list< std::string > & edges)
Definition at line 253 of file TraCICommandInterface.cc.
 {
     TraCIBuffer p;
     p << static_cast<uint8_t>(ADD);
     p << routeId;
     p << static_cast<uint8_t>(TYPE_STRINGLIST);
     p << static_cast<int32_t>(edges.size());
     for (const std::string& edge : edges) {
         p << edge;
     }
     TraCIBuffer buf = connection.query(CMD_SET_ROUTE_VARIABLE, p);
     ASSERT(buf.eof());
 }
References veins::TraCIConstants::ADD, veins::TraCIConstants::CMD_SET_ROUTE_VARIABLE, connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), and veins::TraCIConstants::TYPE_STRINGLIST.
addVehicle()
bool veins::TraCICommandInterface::addVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st = 0, double emitPosition = DEPART_POSITION_BASE, double emitSpeed = DEPART_SPEED_MAX, int8_t emitLane = DEPART_LANE_BEST)
Adds a vehicle to the simulation.
Parameters
vehicleId The new vehicle's ID.
vehicleTypeId The new vehicle's type identifier.
routeId Identifier of the new vehicle's route.
emitTime_st Time at which to spawn the new vehicle or a value from DepartTime.
emitPosition Position of the new vehicle on its lane. Valid values are between 0 and 1 (start and end of edge) and special values from DepartPosition.
emitSpeed Speed in meters per second of the new vehicle. Also accepts special values from DepartSpeed.
emitLane The new vehicle's lane. Special Also accepts special values from DepartLane.
Returns
Success indication
Definition at line 1179 of file TraCICommandInterface.cc.
 {
     TraCIConnection::Result result;
     uint8_t variableId = ADD;
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 6;
     int32_t emitTime = (emitTime_st < 0) ? round(emitTime_st.dbl()) : (floor(emitTime_st.dbl() * 1000));
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << vehicleId << variableType << count << (uint8_t) TYPE_STRING << vehicleTypeId << (uint8_t) TYPE_STRING << routeId << (uint8_t) TYPE_INTEGER << emitTime << (uint8_t) TYPE_DOUBLE << emitPosition << (uint8_t) TYPE_DOUBLE << emitSpeed << (uint8_t) TYPE_BYTE << emitLane, &result);
     ASSERT(buf.eof());
     return result.success;
 }
References veins::TraCIConstants::ADD, veins::TraCIConstants::CMD_SET_VEHICLE_VARIABLE, connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, veins::TraCIConstants::TYPE_BYTE, veins::TraCIConstants::TYPE_COMPOUND, veins::TraCIConstants::TYPE_DOUBLE, veins::TraCIConstants::TYPE_INTEGER, and veins::TraCIConstants::TYPE_STRING.
Referenced by veins::TraCIVehicleInserter::insertVehicles().
genericGetCoord()
Coord veins::TraCICommandInterface::genericGetCoord (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1486 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = POSITION_2D;
     double x;
     double y;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return Coord();
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> x;
     buf >> y;
     ASSERT(buf.eof());
     return connection.traci2omnet(TraCICoord(x, y));
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConstants::POSITION_2D, veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, and veins::TraCIConnection::traci2omnet().
genericGetCoordList()
std::list< Coord > veins::TraCICommandInterface::genericGetCoordList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1722 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_POLYGON;
     std::list<Coord> res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return res;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     uint32_t count = buf.readByteOrFull<uint32_t>();
     for (uint32_t i = 0; i < count; i++) {
         double x;
         buf >> x;
         double y;
         buf >> y;
         res.push_back(connection.traci2omnet(TraCICoord(x, y)));
     }
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIBuffer::readByteOrFull(), veins::TraCIConnection::Result::success, veins::TraCIConnection::traci2omnet(), and veins::TraCIConstants::TYPE_POLYGON.
genericGetDouble()
double veins::TraCICommandInterface::genericGetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1525 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_DOUBLE;
     double res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return 0;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, and veins::TraCIConstants::TYPE_DOUBLE.
Referenced by getVehicleTypeMaxSpeed().
genericGetInt()
int32_t veins::TraCICommandInterface::genericGetInt (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1642 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_INTEGER;
     int32_t res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return 0;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, and veins::TraCIConstants::TYPE_INTEGER.
genericGetString()
std::string veins::TraCICommandInterface::genericGetString (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1450 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_STRING;
     std::string res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return res;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, and veins::TraCIConstants::TYPE_STRING.
genericGetStringList()
std::list< std::string > veins::TraCICommandInterface::genericGetStringList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1679 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_STRINGLIST;
     std::list<std::string> res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return res;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     uint32_t count;
     buf >> count;
     for (uint32_t i = 0; i < count; i++) {
         std::string id;
         buf >> id;
         res.push_back(id);
     }
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, and veins::TraCIConstants::TYPE_STRINGLIST.
Referenced by getGuiViewIds(), getJunctionIds(), getLaneAreaDetectorIds(), getLaneIds(), getPoiIds(), getPolygonIds(), getRoadIds(), getRouteIds(), getTrafficlightIds(), and getVehicleTypeIds().
genericGetTime()
simtime_t veins::TraCICommandInterface::genericGetTime (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1569 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = getTimeType();
     simtime_t res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return res;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), getTimeType(), veins::TraCIConnection::query(), and veins::TraCIConnection::Result::success.
genericGetUnsignedByte()
uint8_t veins::TraCICommandInterface::genericGetUnsignedByte (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId, TraCIConnection::Result * result = nullptr) private
Definition at line 1605 of file TraCICommandInterface.cc.
 {
     uint8_t resultTypeId = TYPE_UBYTE;
     int8_t res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId, result);
     if ((result != nullptr) && (!result->success)) {
         return 0;
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r;
     buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId;
     buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r;
     buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r;
     buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), veins::TraCIConnection::Result::success, and veins::TraCIConstants::TYPE_UBYTE.
genericSetDouble()
void veins::TraCICommandInterface::genericSetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, double value) private
Definition at line 1562 of file TraCICommandInterface.cc.
 {
     uint8_t variableType = TYPE_DOUBLE;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId << variableType << value);
     ASSERT(buf.eof());
 }
References connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), and veins::TraCIConstants::TYPE_DOUBLE.
Referenced by setVehicleTypeMaxSpeed().
getApiVersion()
unsigned veins::TraCICommandInterface::getApiVersion () const inline
Definition at line 75 of file TraCICommandInterface.h.
     {
         return versionConfig.version;
     }
getDistance()
double veins::TraCICommandInterface::getDistance (const Coord & position1, const Coord & position2, bool returnDrivingDistance)
Get the distance between two arbitrary positions.
Parameters
position1 OMNeT coordinate of first position
position2 OMNeT coordinate of second position
returnDrivingDistance whether to return the driving distance or the air distance
Returns
the distance between the two positions
Definition at line 495 of file TraCICommandInterface.cc.
 {
     uint8_t variable = DISTANCE_REQUEST;
     std::string simId = "sim0";
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 3;
     uint8_t dType = static_cast<uint8_t>(returnDrivingDistance ? REQUEST_DRIVINGDIST : REQUEST_AIRDIST);
     // query road network boundaries
 #if (VEINS_VERSION_MAJOR == 5)
     TraCIBuffer buf = connection.query(CMD_GET_SIM_VARIABLE, TraCIBuffer() << variable << simId << variableType << count << connection.omnet2traci(p1) << connection.omnet2traci(p2) << dType);
 #else
     TraCIBuffer buf = connection.query(CMD_GET_SIM_VARIABLE, TraCIBuffer() << variable << simId << variableType << count << static_cast<uint8_t>(POSITION_2D) << connection.omnet2traci(p1) << static_cast<uint8_t>(POSITION_2D) << connection.omnet2traci(p2) << dType);
 #endif
     uint8_t cmdLength_resp;
     buf >> cmdLength_resp;
     uint8_t commandId_resp;
     buf >> commandId_resp;
     ASSERT(commandId_resp == RESPONSE_GET_SIM_VARIABLE);
     uint8_t variableId_resp;
     buf >> variableId_resp;
     ASSERT(variableId_resp == variable);
     std::string simId_resp;
     buf >> simId_resp;
     ASSERT(simId_resp == simId);
     uint8_t typeId_resp;
     buf >> typeId_resp;
     ASSERT(typeId_resp == TYPE_DOUBLE);
     double distance;
     buf >> distance;
     ASSERT(buf.eof());
     return distance;
 }
References veins::TraCIConstants::CMD_GET_SIM_VARIABLE, connection, veins::TraCIConstants::DISTANCE_REQUEST, veins::TraCIBuffer::eof(), veins::TraCIConnection::omnet2traci(), veins::TraCIConstants::POSITION_2D, veins::TraCIConnection::query(), veins::TraCIConstants::REQUEST_AIRDIST, veins::TraCIConstants::REQUEST_DRIVINGDIST, veins::TraCIConstants::RESPONSE_GET_SIM_VARIABLE, veins::TraCIConstants::TYPE_COMPOUND, and veins::TraCIConstants::TYPE_DOUBLE.
getGuiViewIds()
std::list< std::string > veins::TraCICommandInterface::getGuiViewIds ()
Definition at line 1332 of file TraCICommandInterface.cc.
 {
     if (ignoreGuiCommands) {
         EV_DEBUG << "Ignoring TraCI GUI command (as instructed by ignoreGuiCommands)" << std::endl;
         return std::list<std::string>();
     }
     return genericGetStringList(CMD_GET_GUI_VARIABLE, "", ID_LIST, RESPONSE_GET_GUI_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_GUI_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, ignoreGuiCommands, and veins::TraCIConstants::RESPONSE_GET_GUI_VARIABLE.
getJunctionIds()
std::list< std::string > veins::TraCICommandInterface::getJunctionIds ()
Definition at line 1164 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_JUNCTION_VARIABLE, "", ID_LIST, RESPONSE_GET_JUNCTION_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_JUNCTION_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_JUNCTION_VARIABLE.
getLaneAreaDetectorIds()
std::list< std::string > veins::TraCICommandInterface::getLaneAreaDetectorIds ()
Definition at line 1154 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_LANEAREA_VARIABLE, "", ID_LIST, RESPONSE_GET_LANEAREA_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANEAREA_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_LANEAREA_VARIABLE.
getLaneIds()
std::list< std::string > veins::TraCICommandInterface::getLaneIds ()
Definition at line 1109 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_LANE_VARIABLE, "", ID_LIST, RESPONSE_GET_LANE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_LANE_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_LANE_VARIABLE.
Referenced by veins::RoadsCanvasVisualizer::initialize().
getLonLat()
std::pair< double, double > veins::TraCICommandInterface::getLonLat (const Coord & coord)
Definition at line 1260 of file TraCICommandInterface.cc.
 {
     TraCIBuffer request;
 #if (VEINS_VERSION_MAJOR == 5)
     request << static_cast<uint8_t>(POSITION_CONVERSION) << std::string("sim0") << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(2) << connection.omnet2traci(coord) << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(POSITION_LON_LAT);
 #else
     request << static_cast<uint8_t>(POSITION_CONVERSION) << std::string("sim0") << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(2) << static_cast<uint8_t>(POSITION_2D) << connection.omnet2traci(coord) << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(POSITION_LON_LAT);
 #endif
     TraCIBuffer response = connection.query(CMD_GET_SIM_VARIABLE, request);
     uint8_t cmdLength;
     response >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         response >> cmdLengthX;
     }
     uint8_t responseId;
     response >> responseId;
     ASSERT(responseId == RESPONSE_GET_SIM_VARIABLE);
     uint8_t variable;
     response >> variable;
     ASSERT(variable == POSITION_CONVERSION);
     std::string id;
     response >> id;
     uint8_t convPosType;
     response >> convPosType;
     ASSERT(convPosType == POSITION_LON_LAT);
     double convPosLon;
     response >> convPosLon;
     double convPosLat;
     response >> convPosLat;
     return std::make_pair(convPosLon, convPosLat);
 }
References veins::TraCIConstants::CMD_GET_SIM_VARIABLE, connection, veins::TraCIConnection::omnet2traci(), veins::TraCIConstants::POSITION_2D, veins::TraCIConstants::POSITION_CONVERSION, veins::TraCIConstants::POSITION_LON_LAT, veins::TraCIConnection::query(), veins::TraCIConstants::RESPONSE_GET_SIM_VARIABLE, veins::TraCIConstants::TYPE_COMPOUND, and veins::TraCIConstants::TYPE_UBYTE.
getNetBoundaryType()
uint8_t veins::TraCICommandInterface::getNetBoundaryType () const inline
Definition at line 83 of file TraCICommandInterface.h.
     {
         return versionConfig.netBoundaryType;
     }
Referenced by initNetworkBoundaries().
getPoiIds()
std::list< std::string > veins::TraCICommandInterface::getPoiIds ()
Definition at line 1068 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_POI_VARIABLE, "", ID_LIST, RESPONSE_GET_POI_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_POI_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_POI_VARIABLE.
getPolygonIds()
std::list< std::string > veins::TraCICommandInterface::getPolygonIds ()
Definition at line 1008 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_POLYGON_VARIABLE, "", ID_LIST, RESPONSE_GET_POLYGON_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_POLYGON_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_POLYGON_VARIABLE.
getRoadIds()
std::list< std::string > veins::TraCICommandInterface::getRoadIds ()
Definition at line 268 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_EDGE_VARIABLE, "", ID_LIST, RESPONSE_GET_EDGE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_EDGE_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_EDGE_VARIABLE.
getRoadMapPos()
std::tuple< std::string, double, uint8_t > veins::TraCICommandInterface::getRoadMapPos (const Coord & coord)
Convert Cartesian coordination to road map position.
Parameters
coord Cartesian coordination
Returns
a tuple of <RoadId, Pos, LaneId> where: RoadId identifies a road segment (edge) Pos describes the position of the node in longitudinal direction (ranging from 0 to the road's length) LaneId identifies the driving lane on the edge.
Definition at line 1295 of file TraCICommandInterface.cc.
 {
     TraCIBuffer request;
 #if (VEINS_VERSION_MAJOR == 5)
     request << static_cast<uint8_t>(POSITION_CONVERSION) << std::string("sim0") << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(2) << connection.omnet2traci(coord) << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(POSITION_ROADMAP);
 #else
     request << static_cast<uint8_t>(POSITION_CONVERSION) << std::string("sim0") << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(2) << static_cast<uint8_t>(POSITION_2D) << connection.omnet2traci(coord) << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(POSITION_ROADMAP);
 #endif
     TraCIBuffer response = connection.query(CMD_GET_SIM_VARIABLE, request);
     uint8_t cmdLength;
     response >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         response >> cmdLengthX;
     }
     uint8_t responseId;
     response >> responseId;
     ASSERT(responseId == RESPONSE_GET_SIM_VARIABLE);
     uint8_t variable;
     response >> variable;
     ASSERT(variable == POSITION_CONVERSION);
     std::string id;
     response >> id;
     uint8_t convPosType;
     response >> convPosType;
     ASSERT(convPosType == POSITION_ROADMAP);
     std::string convRoadId;
     response >> convRoadId;
     double convPos;
     response >> convPos;
     uint8_t convLaneId;
     response >> convLaneId;
     return std::make_tuple(convRoadId, convPos, convLaneId);
 }
References veins::TraCIConstants::CMD_GET_SIM_VARIABLE, connection, veins::TraCIConnection::omnet2traci(), veins::TraCIConstants::POSITION_2D, veins::TraCIConstants::POSITION_CONVERSION, veins::TraCIConstants::POSITION_ROADMAP, veins::TraCIConnection::query(), veins::TraCIConstants::RESPONSE_GET_SIM_VARIABLE, veins::TraCIConstants::TYPE_COMPOUND, and veins::TraCIConstants::TYPE_UBYTE.
getRouteIds()
std::list< std::string > veins::TraCICommandInterface::getRouteIds ()
Definition at line 248 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_ROUTE_VARIABLE, "", ID_LIST, RESPONSE_GET_ROUTE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_ROUTE_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_ROUTE_VARIABLE.
Referenced by veins::TraCIVehicleInserter::receiveSignal().
getTimeStepCmd()
uint8_t veins::TraCICommandInterface::getTimeStepCmd () const inline
Definition at line 87 of file TraCICommandInterface.h.
     {
         return versionConfig.timeStepCmd;
     }
getTimeType()
uint8_t veins::TraCICommandInterface::getTimeType () const inline
Definition at line 79 of file TraCICommandInterface.h.
     {
         return versionConfig.timeType;
     }
Referenced by genericGetTime().
getTrafficlightIds()
std::list< std::string > veins::TraCICommandInterface::getTrafficlightIds ()
Definition at line 661 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_TL_VARIABLE, "", ID_LIST, RESPONSE_GET_TL_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_TL_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_TL_VARIABLE.
getVehicleTypeIds()
std::list< std::string > veins::TraCICommandInterface::getVehicleTypeIds ()
Definition at line 233 of file TraCICommandInterface.cc.
 {
     return genericGetStringList(CMD_GET_VEHICLETYPE_VARIABLE, "", ID_LIST, RESPONSE_GET_VEHICLETYPE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLETYPE_VARIABLE, genericGetStringList(), veins::TraCIConstants::ID_LIST, and veins::TraCIConstants::RESPONSE_GET_VEHICLETYPE_VARIABLE.
Referenced by veins::TraCIVehicleInserter::receiveSignal().
getVehicleTypeMaxSpeed()
double veins::TraCICommandInterface::getVehicleTypeMaxSpeed (std::string typeId)
Definition at line 238 of file TraCICommandInterface.cc.
 {
     return genericGetDouble(CMD_GET_VEHICLETYPE_VARIABLE, typeId, VAR_MAXSPEED, RESPONSE_GET_VEHICLETYPE_VARIABLE);
 }
References veins::TraCIConstants::CMD_GET_VEHICLETYPE_VARIABLE, genericGetDouble(), veins::TraCIConstants::RESPONSE_GET_VEHICLETYPE_VARIABLE, and veins::TraCIConstants::VAR_MAXSPEED.
getVersion()
std::pair< uint32_t, std::string > veins::TraCICommandInterface::getVersion ()
Definition at line 60 of file TraCICommandInterface.cc.
 {
     TraCIConnection::Result result;
     TraCIBuffer buf = connection.query(CMD_GETVERSION, TraCIBuffer(), &result);
     if (!result.success) {
         ASSERT(buf.eof());
         return std::pair<uint32_t, std::string>(0, "(unknown)");
     }
     uint8_t cmdLength;
     buf >> cmdLength;
     uint8_t commandResp;
     buf >> commandResp;
     ASSERT(commandResp == CMD_GETVERSION);
     uint32_t apiVersion;
     buf >> apiVersion;
     std::string serverVersion;
     buf >> serverVersion;
     ASSERT(buf.eof());
     return std::pair<uint32_t, std::string>(apiVersion, serverVersion);
 }
References veins::TraCIConstants::CMD_GETVERSION, connection, veins::TraCIBuffer::eof(), veins::TraCIConnection::query(), and veins::TraCIConnection::Result::success.
guiView()
GuiView veins::TraCICommandInterface::guiView (std::string viewId) inline
Definition at line 539 of file TraCICommandInterface.h.
     {
         return GuiView(this, viewId);
     }
Referenced by veins::TraCIScreenRecorder::handleMessage().
initNetworkBoundaries()
std::pair< TraCICoord, TraCICoord > veins::TraCICommandInterface::initNetworkBoundaries (int margin)
Definition at line 95 of file TraCICommandInterface.cc.
 {
     // query road network boundaries
     TraCIBuffer buf = connection.query(CMD_GET_SIM_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_NET_BOUNDING_BOX) << std::string("sim0"));
     uint8_t cmdLength_resp;
     buf >> cmdLength_resp;
     uint8_t commandId_resp;
     buf >> commandId_resp;
     ASSERT(commandId_resp == RESPONSE_GET_SIM_VARIABLE);
     uint8_t variableId_resp;
     buf >> variableId_resp;
     ASSERT(variableId_resp == VAR_NET_BOUNDING_BOX);
     std::string simId;
     buf >> simId;
     uint8_t typeId_resp;
     buf >> typeId_resp;
     ASSERT(typeId_resp == getNetBoundaryType());
     if (getNetBoundaryType() == TYPE_POLYGON) {
         // Polygons can have an arbitrary number of tuples, so check that it is actually 2
         uint8_t npoints;
         buf >> npoints;
         ASSERT(npoints == 2);
     }
     double x1;
     buf >> x1;
     double y1;
     buf >> y1;
     double x2;
     buf >> x2;
     double y2;
     buf >> y2;
     ASSERT(buf.eof());
     EV_DEBUG << "TraCI reports network boundaries (" << x1 << ", " << y1 << ")-(" << x2 << ", " << y2 << ")" << endl;
     TraCICoord nb1(x1, y1);
     TraCICoord nb2(x2, y2);
     connection.setNetbounds(nb1, nb2, margin);
     return {nb1, nb2};
 }
References veins::TraCIConstants::CMD_GET_SIM_VARIABLE, connection, veins::TraCIBuffer::eof(), getNetBoundaryType(), veins::TraCIConnection::query(), veins::TraCIConstants::RESPONSE_GET_SIM_VARIABLE, veins::TraCIConnection::setNetbounds(), veins::TraCIConstants::TYPE_POLYGON, and veins::TraCIConstants::VAR_NET_BOUNDING_BOX.
isIgnoringGuiCommands()
bool veins::TraCICommandInterface::isIgnoringGuiCommands ()
Definition at line 55 of file TraCICommandInterface.cc.
 {
     return ignoreGuiCommands;
 }
References ignoreGuiCommands.
junction()
Junction veins::TraCICommandInterface::junction (std::string junctionId) inline
Definition at line 476 of file TraCICommandInterface.h.
     {
         return Junction(this, junctionId);
     }
lane()
Lane veins::TraCICommandInterface::lane (std::string laneId) inline
Definition at line 341 of file TraCICommandInterface.h.
     {
         return Lane(this, laneId);
     }
Referenced by veins::RoadsCanvasVisualizer::initialize().
laneAreaDetector()
LaneAreaDetector veins::TraCICommandInterface::laneAreaDetector (std::string laneAreaDetectorId) inline
Definition at line 400 of file TraCICommandInterface.h.
     {
         return LaneAreaDetector(this, laneAreaDetectorId);
     }
poi()
Poi veins::TraCICommandInterface::poi (std::string poiId) inline
Definition at line 452 of file TraCICommandInterface.h.
     {
         return Poi(this, poiId);
     }
Referenced by veins::AnnotationManager::hide().
polygon()
Polygon veins::TraCICommandInterface::polygon (std::string polyId) inline
Definition at line 427 of file TraCICommandInterface.h.
     {
         return Polygon(this, polyId);
     }
Referenced by veins::AnnotationManager::hide().
road()
Road veins::TraCICommandInterface::road (std::string roadId) inline
Definition at line 312 of file TraCICommandInterface.h.
     {
         return Road(this, roadId);
     }
route()
Route veins::TraCICommandInterface::route (std::string routeId) inline
Definition at line 500 of file TraCICommandInterface.h.
     {
         return Route(this, routeId);
     }
setApiVersion()
void veins::TraCICommandInterface::setApiVersion (uint32_t apiVersion)
Definition at line 84 of file TraCICommandInterface.cc.
 {
     try {
         versionConfig = versionConfigs.at(apiVersion);
         TraCIBuffer::setTimeType(versionConfig.timeType);
     }
     catch (std::out_of_range const& exc) {
         throw cRuntimeError("%s", std::string("TraCI server reports unsupported TraCI API version: " + std::to_string(apiVersion) + ". We recommend using Sumo version 1.0.1 or 0.32.0").c_str());
     }
 }
References veins::TraCIBuffer::setTimeType(), veins::TraCICommandInterface::VersionConfig::timeType, versionConfig, and versionConfigs.
setVehicleTypeMaxSpeed()
void veins::TraCICommandInterface::setVehicleTypeMaxSpeed (std::string typeId, double maxSpeed)
Definition at line 243 of file TraCICommandInterface.cc.
 {
     genericSetDouble(CMD_SET_VEHICLETYPE_VARIABLE, typeId, VAR_MAXSPEED, maxSpeed);
 }
References veins::TraCIConstants::CMD_SET_VEHICLETYPE_VARIABLE, genericSetDouble(), and veins::TraCIConstants::VAR_MAXSPEED.
trafficlight()
Trafficlight veins::TraCICommandInterface::trafficlight (std::string trafficLightId) inline
Definition at line 377 of file TraCICommandInterface.h.
     {
         return Trafficlight(this, trafficLightId);
     }
vehicle()
Vehicle veins::TraCICommandInterface::vehicle (std::string nodeId) inline
Definition at line 287 of file TraCICommandInterface.h.
     {
         return Vehicle(this, nodeId);
     }
Member Data Documentation
connection
TraCIConnection& veins::TraCICommandInterface::connection private
Definition at line 552 of file TraCICommandInterface.h.
Referenced by addPoi(), addPolygon(), addRoute(), addVehicle(), veins::TraCICommandInterface::Vehicle::changeRoute(), veins::TraCICommandInterface::Vehicle::changeVehicleRoute(), genericGetCoord(), genericGetCoordList(), genericGetDouble(), genericGetInt(), genericGetString(), genericGetStringList(), genericGetTime(), genericGetUnsignedByte(), genericSetDouble(), veins::TraCICommandInterface::Vehicle::getColor(), veins::TraCICommandInterface::Trafficlight::getControlledLinks(), getDistance(), veins::TraCICommandInterface::Vehicle::getLeader(), getLonLat(), veins::TraCICommandInterface::Vehicle::getNextTls(), veins::TraCICommandInterface::Trafficlight::getProgramDefinition(), getRoadMapPos(), getVersion(), veins::TraCICommandInterface::GuiView::GuiView(), initNetworkBoundaries(), veins::TraCICommandInterface::Junction::Junction(), veins::TraCICommandInterface::Lane::Lane(), veins::TraCICommandInterface::LaneAreaDetector::LaneAreaDetector(), veins::TraCICommandInterface::Vehicle::newRoute(), veins::TraCICommandInterface::Poi::Poi(), veins::TraCICommandInterface::Polygon::Polygon(), veins::TraCICommandInterface::Polygon::remove(), veins::TraCICommandInterface::Poi::remove(), veins::TraCICommandInterface::Road::Road(), veins::TraCICommandInterface::Route::Route(), veins::TraCICommandInterface::GuiView::setBoundary(), veins::TraCICommandInterface::Vehicle::setColor(), veins::TraCICommandInterface::Lane::setDisallowed(), veins::TraCICommandInterface::Trafficlight::setPhaseDuration(), veins::TraCICommandInterface::Trafficlight::setPhaseIndex(), veins::TraCICommandInterface::Trafficlight::setProgram(), veins::TraCICommandInterface::Trafficlight::setProgramDefinition(), veins::TraCICommandInterface::GuiView::setScheme(), veins::TraCICommandInterface::Polygon::setShape(), veins::TraCICommandInterface::Vehicle::setSpeedMode(), veins::TraCICommandInterface::Trafficlight::setState(), veins::TraCICommandInterface::GuiView::setZoom(), veins::TraCICommandInterface::Vehicle::slowDown(), veins::TraCICommandInterface::Vehicle::stopAt(), veins::TraCICommandInterface::GuiView::takeScreenshot(), veins::TraCICommandInterface::GuiView::trackVehicle(), veins::TraCICommandInterface::Trafficlight::Trafficlight(), and veins::TraCICommandInterface::Vehicle::Vehicle().
ignoreGuiCommands
bool veins::TraCICommandInterface::ignoreGuiCommands private
Definition at line 553 of file TraCICommandInterface.h.
Referenced by getGuiViewIds(), and isIgnoringGuiCommands().
versionConfig
VersionConfig veins::TraCICommandInterface::versionConfig private
Definition at line 555 of file TraCICommandInterface.h.
Referenced by setApiVersion().
versionConfigs
const std::map< uint32_t, TraCICommandInterface::VersionConfig > veins::TraCICommandInterface::versionConfigs static private
Initial value:
= {
    {20, {20, TYPE_DOUBLE, TYPE_POLYGON, VAR_TIME}},
    {19, {19, TYPE_DOUBLE, TYPE_POLYGON, VAR_TIME}},
    {18, {18, TYPE_DOUBLE, TYPE_POLYGON, VAR_TIME}},
    {17, {17, TYPE_INTEGER, TYPE_BOUNDINGBOX, VAR_TIME_STEP}},
    {16, {16, TYPE_INTEGER, TYPE_BOUNDINGBOX, VAR_TIME_STEP}},
    {15, {15, TYPE_INTEGER, TYPE_BOUNDINGBOX, VAR_TIME_STEP}},
}
Definition at line 554 of file TraCICommandInterface.h.
Referenced by setApiVersion().
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc