Veins: veins::AnnotationManagerAccess Class Reference
veins::AnnotationManagerAccess Class Reference
#include <AnnotationManager.h>
Public Member Functions
AnnotationManager * getIfExists ()
Detailed Description
Definition at line 177 of file AnnotationManager.h.
Member Function Documentation
getIfExists()
AnnotationManager* veins::AnnotationManagerAccess::getIfExists () inline
Definition at line 179 of file AnnotationManager.h.
     {
         return FindModule<AnnotationManager*>::findGlobalModule();
     };
References veins::FindModule< T >::findGlobalModule().
Referenced by veins::DemoBaseApplLayer::initialize(), veins::TraCIScenarioManager::initialize(), veins::ObstacleControl::initialize(), and veins::VehicleObstacleControl::initialize().
The documentation for this class was generated from the following file:
AnnotationManager.h