Veins: veins::TraCIBuffer Class Reference
veins::TraCIBuffer Class Reference
Byte-buffer that stores values in TraCI byte-order.
#include <TraCIBuffer.h>
Public Member Functions
TraCIBuffer ()
TraCIBuffer (std::string buf)
template<typename T >
T read ()
template<typename T >
void write (T inv)
void readBuffer (unsigned char *buffer, size_t size)
template<typename T >
T read (T &out)
template<typename T >
TraCIBuffer & operator>> (T &out)
template<typename T >
TraCIBuffer & operator<< (const T &inv)
template<typename T >
T readTypeChecked (int expectedTraCIType)
read and check type, then read and return an item from the buffer
template<typename T >
T readByteOrFull ()
first read a Byte.
template<typename T >
void writeByteOrFull (T inv)
write only a Byte if value fits in a Byte.
bool eof () const
void set (std::string buf)
void clear ()
std::string str () const
std::string hexStr () const
template<>
std::vector< std::string > readTypeChecked (int expectedTraCIType)
template<>
void write (std::string inv)
template<>
void write (std::list< std::string > inv)
template<>
std::string read ()
template<>
void write (TraCICoord inv)
template<>
void write (simtime_t o)
Static Public Member Functions
static void setTimeType (uint8_t val)
Private Attributes
std::string buf
size_t buf_index
Static Private Attributes
static bool timeAsDouble = true
Detailed Description
Byte-buffer that stores values in TraCI byte-order.
Definition at line 41 of file TraCIBuffer.h.
Constructor & Destructor Documentation
TraCIBuffer() [1/2]
veins::TraCIBuffer::TraCIBuffer ()
Definition at line 36 of file TraCIBuffer.cc.
     : buf()
 {
     buf_index = 0;
 }
References buf_index.
TraCIBuffer() [2/2]
veins::TraCIBuffer::TraCIBuffer (std::string buf)
Definition at line 42 of file TraCIBuffer.cc.
     : buf(buf)
 {
     buf_index = 0;
 }
References buf_index.
Member Function Documentation
clear()
void veins::TraCIBuffer::clear ()
Definition at line 59 of file TraCIBuffer.cc.
 {
     set("");
 }
References set().
eof()
bool veins::TraCIBuffer::eof () const
Definition at line 48 of file TraCIBuffer.cc.
 {
     return buf_index == buf.length();
 }
References buf, and buf_index.
Referenced by veins::TraCICommandInterface::addPoi(), veins::TraCICommandInterface::addPolygon(), veins::TraCICommandInterface::addRoute(), veins::TraCICommandInterface::addVehicle(), veins::TraCICommandInterface::Vehicle::changeRoute(), veins::TraCICommandInterface::Vehicle::changeTarget(), veins::TraCICommandInterface::Vehicle::changeVehicleRoute(), veins::TraCICommandInterface::genericGetCoord(), veins::TraCICommandInterface::genericGetCoordList(), veins::TraCICommandInterface::genericGetDouble(), veins::TraCICommandInterface::genericGetInt(), veins::TraCICommandInterface::genericGetString(), veins::TraCICommandInterface::genericGetStringList(), veins::TraCICommandInterface::genericGetTime(), veins::TraCICommandInterface::genericGetUnsignedByte(), veins::TraCICommandInterface::genericSetDouble(), veins::TraCICommandInterface::Vehicle::getColor(), veins::TraCICommandInterface::getDistance(), veins::TraCICommandInterface::Vehicle::getLeader(), veins::TraCICommandInterface::Vehicle::getNextTls(), veins::TraCICommandInterface::getVersion(), veins::TraCIScenarioManager::init_traci(), veins::TraCICommandInterface::initNetworkBoundaries(), veins::TraCICommandInterface::Vehicle::newRoute(), veins::TraCICommandInterface::Polygon::remove(), veins::TraCICommandInterface::Poi::remove(), veins::TraCICommandInterface::GuiView::setBoundary(), veins::TraCICommandInterface::Vehicle::setColor(), veins::TraCICommandInterface::Lane::setDisallowed(), veins::TraCICommandInterface::Vehicle::setMaxSpeed(), veins::TraCICommandInterface::Vehicle::setParameter(), veins::TraCICommandInterface::Trafficlight::setPhaseDuration(), veins::TraCICommandInterface::Trafficlight::setPhaseIndex(), veins::TraCICommandInterface::Trafficlight::setProgram(), veins::TraCICommandInterface::Trafficlight::setProgramDefinition(), veins::TraCICommandInterface::GuiView::setScheme(), veins::TraCICommandInterface::Polygon::setShape(), veins::TraCICommandInterface::Vehicle::setSpeed(), veins::TraCICommandInterface::Vehicle::setSpeedMode(), veins::TraCICommandInterface::Trafficlight::setState(), veins::TraCICommandInterface::GuiView::setZoom(), veins::TraCICommandInterface::Vehicle::slowDown(), veins::TraCICommandInterface::Vehicle::stopAt(), veins::TraCIScenarioManager::subscribeToTrafficLightVariables(), veins::TraCIScenarioManager::subscribeToVehicleVariables(), veins::TraCICommandInterface::GuiView::takeScreenshot(), veins::TraCICommandInterface::GuiView::trackVehicle(), veins::TraCIScenarioManager::unsubscribeFromTrafficLightVariables(), and veins::TraCIScenarioManager::unsubscribeFromVehicleVariables().
hexStr()
std::string veins::TraCIBuffer::hexStr () const
Definition at line 83 of file TraCIBuffer.cc.
 {
     std::stringstream ss;
     for (std::string::const_iterator i = buf.begin() + buf_index; i != buf.end(); ++i) {
         if (i != buf.begin()) ss << " ";
         ss << std::hex << std::setw(2) << std::setfill('0') << (int) (uint8_t) *i;
     }
     return ss.str();
 }
References buf, and buf_index.
operator<<()
template<typename T > TraCIBuffer& veins::TraCIBuffer::operator<< (const T & inv) inline
Definition at line 116 of file TraCIBuffer.h.
     {
         write(inv);
         return *this;
     }
operator>>()
template<typename T > TraCIBuffer& veins::TraCIBuffer::operator>> (T & out) inline
Definition at line 109 of file TraCIBuffer.h.
     {
         out = read<T>();
         return *this;
     }
read() [1/3]
template<> simtime_t veins::TraCIBuffer::read ()
Definition at line 112 of file TraCIBuffer.cc.
 {
     uint32_t length = read<uint32_t>();
     if (length == 0) return std::string();
     char obuf[length + 1];
     for (size_t i = 0; i < length; ++i) read<char>(obuf[i]);
     obuf[length] = 0;
     return std::string(obuf, length);
 }
read() [2/3]
template<typename T > T veins::TraCIBuffer::read () inline
Definition at line 47 of file TraCIBuffer.h.
     {
         T buf_to_return;
         unsigned char* p_buf_to_return = reinterpret_cast<unsigned char*>(&buf_to_return);
         if (isBigEndian()) {
             for (size_t i = 0; i < sizeof(buf_to_return); ++i) {
                 if (eof()) throw cRuntimeError("Attempted to read past end of byte buffer");
                 p_buf_to_return[i] = buf[buf_index++];
             }
         }
         else {
             for (size_t i = 0; i < sizeof(buf_to_return); ++i) {
                 if (eof()) throw cRuntimeError("Attempted to read past end of byte buffer");
                 p_buf_to_return[sizeof(buf_to_return) - 1 - i] = buf[buf_index++];
             }
         }
         return buf_to_return;
     }
References veins::isBigEndian().
read() [3/3]
template<typename T > T veins::TraCIBuffer::read (T & out) inline
Definition at line 102 of file TraCIBuffer.h.
     {
         out = read<T>();
         return out;
     }
readBuffer()
void veins::TraCIBuffer::readBuffer (unsigned char * buffer, size_t size) inline
Definition at line 85 of file TraCIBuffer.h.
     {
         if (isBigEndian()) {
             for (size_t i = 0; i < size; ++i) {
                 if (eof()) throw cRuntimeError("Attempted to read past end of byte buffer");
                 buffer[i] = buf[buf_index++];
             }
         }
         else {
             for (size_t i = 0; i < size; ++i) {
                 if (eof()) throw cRuntimeError("Attempted to read past end of byte buffer");
                 buffer[size - 1 - i] = buf[buf_index++];
             }
         }
     }
References veins::isBigEndian().
readByteOrFull()
template<typename T > T veins::TraCIBuffer::readByteOrFull () inline
first read a Byte.
Only if read value is 0 and EOF has not been reached, read requested data type.
Definition at line 139 of file TraCIBuffer.h.
     {
         uint8_t shortBuf = read<uint8_t>();
         if (shortBuf > 0 || eof()) {
             return shortBuf;
         }
         return read<T>();
     }
Referenced by veins::TraCICommandInterface::genericGetCoordList().
readTypeChecked() [1/2]
template<> std::vector< std::string > veins::TraCIBuffer::readTypeChecked (int expectedTraCIType)
Definition at line 70 of file TraCIBuffer.cc.
 {
     ASSERT(read<uint8_t>() == static_cast<uint8_t>(expectedTraCIType));
     int32_t nrOfElements = read<uint8_t>();
     std::vector<std::string> result;
     result.reserve(nrOfElements);
     for (int32_t i = 0; i < nrOfElements; ++i) {
         result.emplace_back(read<std::string>());
     }
     return result;
 }
readTypeChecked() [2/2]
template<typename T > T veins::TraCIBuffer::readTypeChecked (int expectedTraCIType) inline
read and check type, then read and return an item from the buffer
Definition at line 127 of file TraCIBuffer.h.
     {
         uint8_t read_type(read<uint8_t>());
         ASSERT(read_type == static_cast<uint8_t>(expectedTraCIType));
         return read<T>();
     }
Referenced by veins::TraCICommandInterface::Trafficlight::getControlledLinks(), veins::TraCICommandInterface::Trafficlight::getProgramDefinition(), and veins::TraCIScenarioManager::processTrafficLightSubscription().
set()
void veins::TraCIBuffer::set (std::string buf)
Definition at line 53 of file TraCIBuffer.cc.
 {
     this->buf = buf;
     buf_index = 0;
 }
References buf, and buf_index.
Referenced by clear().
setTimeType()
static void veins::TraCIBuffer::setTimeType (uint8_t val) inline static
Definition at line 170 of file TraCIBuffer.h.
     {
         if (val != TraCIConstants::TYPE_INTEGER && val != TraCIConstants::TYPE_DOUBLE) {
             throw cRuntimeError("Invalid time data type");
         }
         timeAsDouble = val == TraCIConstants::TYPE_DOUBLE;
     }
References veins::TraCIConstants::TYPE_DOUBLE, and veins::TraCIConstants::TYPE_INTEGER.
Referenced by veins::TraCICommandInterface::setApiVersion().
str()
std::string veins::TraCIBuffer::str () const
Definition at line 64 of file TraCIBuffer.cc.
 {
     return buf;
 }
References buf.
Referenced by veins::makeTraCICommand(), and veins::TraCIConnection::sendMessage().
write() [1/5]
template<> void veins::TraCIBuffer::write (simtime_t o)
Definition at line 150 of file TraCIBuffer.cc.
 {
     if (timeAsDouble) {
         double d = o.dbl();
         write<double>(d);
     }
     else {
         uint32_t i = o.inUnit(SIMTIME_MS);
         write<uint32_t>(i);
     }
 }
References timeAsDouble.
write() [2/5]
template<> void VEINS_API veins::TraCIBuffer::write (std::list< std::string > inv)
Definition at line 102 of file TraCIBuffer.cc.
 {
     int32_t numElem = inv.size();
     write(numElem);
     for (std::list<std::string>::const_iterator i = inv.begin(); i != inv.end(); ++i) {
         write(static_cast<std::string>(*i));
     }
 }
References write().
write() [3/5]
template<> void VEINS_API veins::TraCIBuffer::write (std::string inv)
Definition at line 94 of file TraCIBuffer.cc.
 {
     uint32_t length = inv.length();
     write<uint32_t>(length);
     for (size_t i = 0; i < length; ++i) write<char>(inv[i]);
 }
write() [4/5]
template<typename T > void veins::TraCIBuffer::write (T inv) inline
Definition at line 69 of file TraCIBuffer.h.
     {
         unsigned char* p_buf_to_send = reinterpret_cast<unsigned char*>(&inv);
         if (isBigEndian()) {
             for (size_t i = 0; i < sizeof(inv); ++i) {
                 buf += p_buf_to_send[i];
             }
         }
         else {
             for (size_t i = 0; i < sizeof(inv); ++i) {
                 buf += p_buf_to_send[sizeof(inv) - 1 - i];
             }
         }
     }
References veins::isBigEndian().
Referenced by write().
write() [5/5]
template<> void veins::TraCIBuffer::write (TraCICoord inv)
Definition at line 125 of file TraCIBuffer.cc.
 {
 #if (VEINS_VERSION_MAJOR == 5)
     write<uint8_t>(POSITION_2D);
 #endif
     write<double>(inv.x);
     write<double>(inv.y);
 }
References veins::TraCIConstants::POSITION_2D, veins::TraCICoord::x, and veins::TraCICoord::y.
writeByteOrFull()
template<typename T > void veins::TraCIBuffer::writeByteOrFull (T inv) inline
write only a Byte if value fits in a Byte.
Otherwise write with requested data type.
Definition at line 153 of file TraCIBuffer.h.
     {
         if (inv < 256) {
             uint8_t shortBuf = inv;
             write(shortBuf);
             return;
         }
         write<uint8_t>(0);
         write(inv);
     }
Referenced by veins::TraCICommandInterface::addPolygon().
Member Data Documentation
buf
std::string veins::TraCIBuffer::buf private
Definition at line 179 of file TraCIBuffer.h.
Referenced by eof(), hexStr(), set(), and str().
buf_index
size_t veins::TraCIBuffer::buf_index private
Definition at line 180 of file TraCIBuffer.h.
Referenced by eof(), hexStr(), set(), and TraCIBuffer().
timeAsDouble
bool veins::TraCIBuffer::timeAsDouble = true static private
Definition at line 181 of file TraCIBuffer.h.
Referenced by write().
The documentation for this class was generated from the following files:
TraCIBuffer.h
TraCIBuffer.cc