Veins: veins::math Namespace Reference
veins::math Namespace Reference
Functions
template<class T >
std::enable_if< std::is_floating_point< T >::value, bool >::type almost_equal (T x, T y, int ulp=1)
Compare two floats for approximate equality.
Function Documentation
almost_equal()
template<class T > std::enable_if<std::is_floating_point<T>::value, bool>::type veins::math::almost_equal (T x, T y, int ulp = 1)
Compare two floats for approximate equality.
Floating point numbers are prone to inequalities. Expressions that logically result in the same values therefore often are not exactly equal, because two representations of very similar values are computed. This function allows comparisons for such cases by allowing for a small error (epsilon), without considering numbers to be unequal.
Parameters
x First comparand
y Second comparand
ulp How many ULP's (Units in the Last Place) we want to tolerate when comparing two numbers. The larger the value, the more error we allow. The maximum floating point error on most platforms is below 0.5 ULP. A 0 value means that two numbers must be exactly the same to be considered equal.
Returns
Indicator whether the lhs and rhs are virtually equal
Definition at line 119 of file FWMath.h.
 {
     const T epsilon = std::numeric_limits<T>::epsilon();
     const T delta = std::abs(x - y);
     return (delta <= epsilon * std::abs(x + y) * ulp) || (delta < std::numeric_limits<T>::min());
 }
Referenced by veins::Move::getPositionAt(), veins::SampledAntenna1D::SampledAntenna1D(), veins::Move::setDirectionByTarget(), and veins::Move::setDirectionByVector().