Veins: veins Namespace Reference
veins Namespace Reference
Veins - The open source vehicular network simulation framework.
Namespaces
math
SignalUtils
TraCIConstants
Classes
class BaseConnectionManager
Module to control the channel and handle all connection related stuff.
class ChannelAccess
Basic class for all physical layers, please don't touch!!
class ConnectionManager
BaseConnectionManager implementation which only defines a specific max interference distance.
class NicEntry
NicEntry is used by ConnectionManager to store the necessary information for each nic.
class NicEntryDebug
NicEntry is used by ConnectionManager to store the necessary information for each nic.
class NicEntryDirect
NicEntry is used by ConnectionManager to store the necessary information for each nic.
class AddressingInterface
Interface for modules which assign L2 and L3 addresses for modules.
class BaseApplLayer
Base class for the application layer.
class DrawAmount
Defines the amount of power drawn by a device from a power source.
class BaseBattery
Base class for any power source.
class BaseLayer
A very simple layer template.
class BaseMacLayer
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses.
class BaseMobility
Base module for all mobility modules.
class BaseModule
Base class for all simple modules of a host.
class BaseWorldUtility
Provides information and utility methods for the whole simulation.
class BatteryAccess
Extends BaseModule by several methods which provide access to the battery module.
class AnalogueModel
Interface for the analogue models of the physical layer.
class Antenna
The Antenna class is the base class of all antenna models.
class BaseDecider
Provides some base functionality for most common deciders.
class BasePhyLayer
The BasePhyLayer represents the physical layer of a nic.
class ChannelInfo
This class is used by the BasePhyLayer to keep track of the AirFrames on the channel.
class DeciderResult
A class to represent the result of a processed packet (that is not noise) by the Decider.
class Decider
The basic Decider class.
class DeciderToPhyInterface
This class is the interface for a Decider to the BasePhyLayer.
class MacToPhyInterface
Defines the methods provided by the phy to the mac layer.
class PhyToMacControlInfo
Controlinfo for packets which are send from Physical layer to the MAC layer.
class Radio
The class that represents the Radio as a state machine.
class Signal
A Signal represents the power measured on a channel.
class Spectrum
class AntennaPosition
Stores the position of the host's antenna along with its speed, so that it can be linearly extrapolated.
class Coord
Class for storing 3D coordinates.
class EnumBitset
class FindModule
Provides method templates to find omnet modules.
class AccessModuleWrap
Finds and returns the pointer to a module of type T.
class FWMath
Support functions for mathematical operations.
class Heading
Stores a Heading in rad, with 0 degrees being east and 90 degrees being north.
class HostState
HostState is published by the battery to announce host failure.
class MacToNetwControlInfo
Stores control information from mac to upper layer.
class Move
Class to store object position and movement.
class NetwToMacControlInfo
Control info to pass next hop L2 addr from netw to MAC layer.
class PassedMessage
class POA
Container class used to attach data to Airframe s which are needed by the receiver for antenna gain calculation (POA is short for position, orientation, antenna).
class LAddress
Layer address handling helper function.
class BreakpointPathlossModel
Basic implementation of a BreakpointPathlossModel.
class NakagamiFading
A simple model to account for fast fading using the Nakagami Distribution.
class PERModel
This class applies a parameterized packet error rate to incoming packets.
class SimpleObstacleShadowing
Basic implementation of a SimpleObstacleShadowing.
class SimplePathlossModel
Basic implementation of a SimplePathlossModel.
class TwoRayInterferenceModel
Extended version of Two-Ray Ground path loss model.
class VehicleObstacleShadowing
Basic implementation of a VehicleObstacleShadowing that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
class DemoBaseApplLayer
Demo application layer base class.
class MyVeinsApp
This is a stub for a typical Veins application layer.
class TraCIDemo11p
A tutorial demo for TraCI.
class TraCIDemoRSU11p
Small RSU Demo using 11p.
class DemoBaseApplLayerToMac1609_4Interface
Interface between DemoBaseApplLayer Layer and Mac1609_4.
class Mac1609_4
class Mac80211pToPhy11pInterface
Interface of PhyLayer80211p exposed to Mac1609_4.
class LinearMobility
Linear movement model.
class ParBuffer
class TraCIBuffer
Byte-buffer that stores values in TraCI byte-order.
class TraCIColor
TraCI compatible color container.
class TraCICommandInterface
struct traci2omnet_functor
class TraCIConnection
struct TraCICoord
Coord equivalent for storing TraCI coordinates.
class TraCICoordinateTransformation
Helper class for converting SUMO coordinates to OMNeT++ Coordinates for a given network.
class TraCILauncher
Launches a program (the TraCI server) when instantiated.
class TraCIMobility
Used in modules created by the TraCIScenarioManager.
class TraCIMobilityAccess
class TraCIRegionOfInterest
Can return whether a given position lies within the simulation's region of interest.
class TraCIScenarioManager
Creates and moves nodes controlled by a TraCI server.
class TraCIScenarioManagerAccess
class TraCIScenarioManagerForker
Extends the TraCIScenarioManager to automatically fork an instance of SUMO when needed.
class TraCIScenarioManagerForkerAccess
class TraCIScenarioManagerLaunchd
Extends the TraCIScenarioManager for use with sumo-launchd.py and SUMO.
class TraCIScenarioManagerLaunchdAccess
class TraCIScreenRecorder
Simple support module to take (a series of) screenshots of a simulation running in the TraCI server.
class TraCIVehicleInserter
Uses the TraCIScenarioManager to programmatically insert new vehicles at the TraCI server.
struct EnumTraits< VehicleSignal >
class MobileHostObstacle
Obstacle for radio waves derived from a mobile host's body.
class Obstacle
stores information about an Obstacle for ObstacleControl
class ObstacleControl
ObstacleControl models obstacles that block radio transmissions.
class ObstacleControlAccess
class VehicleObstacleControl
VehicleObstacleControl models moving obstacles that block radio transmissions.
class VehicleObstacleControlAccess
class Decider80211p
Based on Decider80211.h from Karl Wessel and modifications by Christopher Saloman.
class Decider80211pToPhy80211pInterface
Interface of PhyLayer80211p exposed to Decider80211p.
class DeciderResult80211
Defines an extended DeciderResult for the 80211 protocol which stores the bit-rate of the transmission.
class NistErrorRate
Model the error rate for different modulations and coding schemes.
class PhyLayer80211p
Adaptation of the PhyLayer class for 802.11p.
class SampledAntenna1D
This class represents an antenna whose gain is calculated from given samples in the horizontal plane.
class BBoxLookup
Fast grid-based spatial datastructure to find obstacles (geometric shapes) in a bounding box.
class HasLogProxy
Helper class for logging from classes not derived from cComponent.
struct MacToPhyControlInfo11p
Stores information which is needed by the physical layer when sending a MacPkt.
struct SignalPayload
class SignalCallbackListener
class SignalManager
struct TimerMessage
struct TimerSpecification
A class which specifies a Timer.
class TimerManager
class AnnotationDummy
AnnotationDummy is just a workaround to visualize annotations.
class AnnotationManager
manages annotations on the OMNeT++ canvas.
class AnnotationManagerAccess
class TraCITrafficLightAbstractLogic
Base class to simplify implementation of traffic light logics.
class TraCITrafficLightSimpleLogic
class TraCITrafficLightSimpleLogicAccess
class TraCITrafficLightInterface
class TraCITrafficLightInterfaceAccess
class TraCITrafficLightProgram
struct TraCITrafficLightLink
class RoadsCanvasVisualizer
Simple support module to visualize road network as received via TraCI.
class RoadsOsgVisualizer
Simple support module to visualize road network as received via TraCI.
Typedefs
using ChannelMobilityAccessType = AccessModuleWrap< BaseMobility >
using ChannelMobilityPtrType = ChannelMobilityAccessType::wrapType *
using AnalogueModelList = std::vector< std::unique_ptr< AnalogueModel > >
using OmnetCoord = TraCICoordinateTransformation::OmnetCoord
using OmnetCoordList = TraCICoordinateTransformation::OmnetCoordList
using TraCICoordList = TraCICoordinateTransformation::TraCICoordList
using OmnetHeading = TraCICoordinateTransformation::OmnetHeading
using TraCIHeading = TraCICoordinateTransformation::TraCIHeading
using VehicleSignalSet = EnumBitset< VehicleSignal >
typedef long intval_t
typedef unsigned long uintval_t
Enumerations
enum class VehicleSignal : uint32_t {
blinker_right , blinker_left , blinker_emergency , brakelight ,
frontlight , foglight , highbeam , backdrive ,
wiper , door_open_left , door_open_right , emergency_blue ,
emergency_red , emergency_yellow , undefined
}
enum class Channel {
crit_sol = 172 , sch1 = 174 , sch2 = 176 , cch = 178 ,
sch3 = 180 , sch4 = 182 , hpps = 184
}
Channels as reserved by the FCC.
enum class ChannelType { control = 0 , service }
enum class MCS {
undefined = -1 , ofdm_bpsk_r_1_2 , ofdm_bpsk_r_3_4 , ofdm_qpsk_r_1_2 ,
ofdm_qpsk_r_3_4 , ofdm_qam16_r_1_2 , ofdm_qam16_r_3_4 , ofdm_qam64_r_2_3 ,
ofdm_qam64_r_3_4
}
Modulation and coding scheme to be used for transmission.
enum class Bandwidth { ofdm_5_mhz , ofdm_10_mhz , ofdm_20_mhz }
Available bandwidths.
Functions
std::ostream & operator<< (std::ostream &os, const Signal &s)
simtime_t calculateStart (const Signal &lhs, const Signal &rhs)
simtime_t calculateDuration (const Signal &lhs, const Signal &rhs)
Spectrum::Frequencies normalizeFrequencies (Spectrum::Frequencies freqs)
bool operator== (const Spectrum &lhs, const Spectrum &rhs)
std::ostream & operator<< (std::ostream &os, const Spectrum &s)
std::ostream & operator<< (std::ostream &os, const Coord &coord)
template<typename T >
EnumBitset< T > operator| (T lhs, T rhs)
template<class T >
std::vector< T * > getSubmodulesOfType (cModule *parentModule, bool recurse=false)
Return a vector containing pointers to all submodules of parentModule of type T.
std::ostream & operator<< (std::ostream &os, const Heading &o)
cNEDValue nedf_veins_eval_by_version (cComponent *component, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_veins_eval_by_version, "any veins_eval_by_version(int version, string defaultExpression, int minVersion1, string expression1, ...)", "veins", "Evaluates to expression1 if version >= minVersion1, otherwise evaluates to defaultExpression")
cNEDValue nedf_veins_omnetpp_buildnum (cComponent *component, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_veins_omnetpp_buildnum, "int veins_omnetpp_buildnum()", "veins", "Returns value of C++ OMNETPP_BUILDNUM macro")
bool VEINS_API isBigEndian ()
SOCKET socket (void *ptr)
std::string makeTraCICommand (uint8_t commandId, const TraCIBuffer &buf=TraCIBuffer())
returns byte-buffer containing a TraCI command with optional parameters
uint64_t getOfdmDatarate (MCS mcs, Bandwidth bw)
Given bandwidth and MCS returns datarate in bits per second.
uint32_t getNDBPS (MCS mcs)
returns the number of databits per ofdm symbol
uint64_t getBandwidth (Bandwidth bw)
returns the bandwidth in Hz
MCS getMCS (uint64_t datarate, Bandwidth bw)
returns encoding given datarate
template<typename T , typename ... Args>
std::unique_ptr< T > make_unique (Args &&... args)
User-defined implementation of std::make_unique.
template<typename T >
cModule * findModuleByPath (T modulePath)
Arithmetic operators
Signal operator+ (const Signal &lhs, const Signal &rhs)
Add two signals to each other.
Signal operator+ (const Signal &lhs, double rhs)
Increment a signal's power levels by a constant.
Signal operator+ (double lhs, const Signal &rhs)
Increment a signal's power levels by a constant.
Signal operator- (const Signal &lhs, const Signal &rhs)
Substract two signals from each other.
Signal operator- (const Signal &lhs, double rhs)
Decrement a signal's power levels by a constant.
Signal operator- (double lhs, const Signal &rhs)
Decrement a constant power level by a signal's power levels.
Signal operator* (const Signal &lhs, const Signal &rhs)
Multiply two signals by each other.
Signal operator* (const Signal &lhs, double rhs)
Multiply a signal's power levels by a constant.
Signal operator* (double lhs, const Signal &rhs)
Multiply a signal's power levels by a constant.
Signal operator/ (const Signal &lhs, const Signal &rhs)
Divide two signals by each other.
Signal operator/ (const Signal &lhs, double rhs)
Divide a signal's power levels by a constant.
Signal operator/ (double lhs, const Signal &rhs)
Divide a a constant by a signal's power levels.
Variables
template<typename T >
struct VEINS_API EnumTraits
const uint64_t NUM_BITRATES_80211P = 8
Bit rates for 802.11p.
const uint64_t BITRATES_80211P [] = {3000000, 4500000, 6000000, 9000000, 12000000, 18000000, 24000000, 27000000}
const uint32_t N_DBPS_80211P [] = {24, 36, 48, 72, 96, 144, 192, 216}
Number of Data Bits Per Symbol (N_NBPS) corresponding to bitrates in BITRATES_80211P.
const double T_SYM_80211P = 8e-6
Symbol interval.
const int PHY_HDR_SERVICE_LENGTH = 16
Length (in bits) of SERVICE field in PHY HEADER.
const int PHY_TAIL_LENGTH = 6
Length (in bits) of Tail field in PHY PPDU.
const double PHY_HDR_PREAMBLE_DURATION = 32e-6
Duration of the PLCP Preamble.
const double PHY_HDR_PLCPSIGNAL_DURATION = 8e-6
Duration of the PLCP Signal.
const int PHY_HDR_PLCPSIGNAL_LENGTH = 24
Length of the PLCP Signal.
const uint64_t PHY_HDR_BITRATE = 3000000
Bitrate of the PLCP Signal.
const SimTime SLOTLENGTH_11P = SimTime().setRaw(13000000UL)
Slot Time for 10 MHz channel spacing.
const SimTime SIFS_11P = SimTime().setRaw(32000000UL)
Short interframe space.
const SimTime RADIODELAY_11P = SimTime().setRaw(1000000UL)
Time it takes to switch from Rx to Tx Mode.
const unsigned CWMIN_11P = 15
Contention Window minimal size.
const unsigned CWMAX_11P = 1023
Contention Window maximal size.
const SimTime SWITCHING_INTERVAL_11P = SimTime().setRaw(50000000000UL)
1609.4 slot length
const SimTime GUARD_INTERVAL_11P = SimTime().setRaw(4000000000UL)
1609.4 slot length
const Bandwidth BANDWIDTH_11P = Bandwidth::ofdm_10_mhz
const std::map< Channel, double > IEEE80211ChannelFrequencies
Maps channel identifier to the corresponding center frequency.
Detailed Description
Veins - The open source vehicular network simulation framework.
Typedef Documentation
AnalogueModelList
using veins::AnalogueModelList = typedef std::vector<std::unique_ptr<AnalogueModel> >
Definition at line 82 of file AnalogueModel.h.
ChannelMobilityAccessType
using veins::ChannelMobilityAccessType = typedef AccessModuleWrap<BaseMobility>
Definition at line 43 of file ChannelAccess.h.
ChannelMobilityPtrType
using veins::ChannelMobilityPtrType = typedef ChannelMobilityAccessType::wrapType*
Definition at line 44 of file ChannelAccess.h.
intval_t
typedef long veins::intval_t
Definition at line 102 of file veins.h.
OmnetCoord
using veins::OmnetCoord = typedef TraCICoordinateTransformation::OmnetCoord
Definition at line 27 of file TraCICoordinateTransformation.cc.
OmnetCoordList
using veins::OmnetCoordList = typedef TraCICoordinateTransformation::OmnetCoordList
Definition at line 28 of file TraCICoordinateTransformation.cc.
OmnetHeading
using veins::OmnetHeading = typedef TraCICoordinateTransformation::OmnetHeading
Definition at line 30 of file TraCICoordinateTransformation.cc.
TraCICoordList
using veins::TraCICoordList = typedef TraCICoordinateTransformation::TraCICoordList
Definition at line 29 of file TraCICoordinateTransformation.cc.
TraCIHeading
using veins::TraCIHeading = typedef TraCICoordinateTransformation::TraCIHeading
Definition at line 31 of file TraCICoordinateTransformation.cc.
uintval_t
typedef unsigned long veins::uintval_t
Definition at line 103 of file veins.h.
VehicleSignalSet
using veins::VehicleSignalSet = typedef EnumBitset<VehicleSignal>
Definition at line 54 of file VehicleSignal.h.
Enumeration Type Documentation
Bandwidth
enum veins::Bandwidth strong
Available bandwidths.
Enumerator
ofdm_5_mhz
ofdm_10_mhz
ofdm_20_mhz
Definition at line 47 of file ConstsPhy.h.
                      {
     ofdm_5_mhz,
     ofdm_10_mhz,
     ofdm_20_mhz
 };
Channel
enum veins::Channel strong
Channels as reserved by the FCC.
Enumerator
crit_sol
sch1
sch2
cch
sch3
sch4
hpps
Definition at line 139 of file Consts80211p.h.
                    {
     crit_sol = 172,
     sch1 = 174,
     sch2 = 176,
     cch = 178,
     sch3 = 180,
     sch4 = 182,
     hpps = 184
 };
ChannelType
enum veins::ChannelType strong
Enumerator
control
service
Definition at line 164 of file Consts80211p.h.
{
     control = 0,
     service,
 };
MCS
enum veins::MCS strong
Modulation and coding scheme to be used for transmission.
Enumerator
undefined
ofdm_bpsk_r_1_2
ofdm_bpsk_r_3_4
ofdm_qpsk_r_1_2
ofdm_qpsk_r_3_4
ofdm_qam16_r_1_2
ofdm_qam16_r_3_4
ofdm_qam64_r_2_3
ofdm_qam64_r_3_4
Definition at line 33 of file ConstsPhy.h.
                {
     // use the default MCS
     undefined = -1,
     ofdm_bpsk_r_1_2,
     ofdm_bpsk_r_3_4,
     ofdm_qpsk_r_1_2,
     ofdm_qpsk_r_3_4,
     ofdm_qam16_r_1_2,
     ofdm_qam16_r_3_4,
     ofdm_qam64_r_2_3,
     ofdm_qam64_r_3_4
 };
VehicleSignal
enum veins::VehicleSignal : uint32_t strong
Enumerator
blinker_right
blinker_left
blinker_emergency
brakelight
frontlight
foglight
highbeam
backdrive
wiper
door_open_left
door_open_right
emergency_blue
emergency_red
emergency_yellow
undefined
Definition at line 31 of file VehicleSignal.h.
                          : uint32_t {
     blinker_right,
     blinker_left,
     blinker_emergency,
     brakelight,
     frontlight,
     foglight,
     highbeam,
     backdrive,
     wiper,
     door_open_left,
     door_open_right,
     emergency_blue,
     emergency_red,
     emergency_yellow,
     undefined
 };
Function Documentation
calculateDuration()
simtime_t veins::calculateDuration (const Signal & lhs, const Signal & rhs)
Parameters
lhs the first signal
rhs the second signal
Definition at line 516 of file Signal.cc.
 {
     simtime_t temp = std::min(lhs.sendingStart + lhs.duration, rhs.sendingStart + rhs.duration) - std::max(lhs.sendingStart, rhs.sendingStart);
     return (temp > 0) ? temp : 0;
 }
calculateStart()
simtime_t veins::calculateStart (const Signal & lhs, const Signal & rhs)
their minimum start times.
Parameters
lhs the first signal
rhs the second signal
Definition at line 511 of file Signal.cc.
 {
     return std::max(lhs.sendingStart, rhs.sendingStart);
 }
Define_NED_Function2() [1/2]
veins::Define_NED_Function2 (nedf_veins_eval_by_version , "any veins_eval_by_version(int version, string defaultExpression, int minVersion1, string expression1, ...)" , "veins" , "Evaluates to expression1 if version >= minVersion1, otherwise evaluates to defaultExpression")
Define_NED_Function2() [2/2]
veins::Define_NED_Function2 (nedf_veins_omnetpp_buildnum , "int veins_omnetpp_buildnum()" , "veins" , "Returns value of C++ OMNETPP_BUILDNUM macro")
findModuleByPath()
template<typename T > cModule* veins::findModuleByPath (T modulePath)
Definition at line 87 of file veins.h.
 {
 #if OMNETPP_BUILDNUM < 1506
     try {
         return cSimulation::getActiveSimulation()->getModuleByPath(modulePath);
     }
     catch (cRuntimeError) {
         return nullptr;
     }
 #else
     return cSimulation::getActiveSimulation()->findModuleByPath(modulePath);
 #endif
 }
Referenced by veins::ChannelAccess::getConnectionManager(), veins::ObstacleControlAccess::getIfExists(), and veins::VehicleObstacleControlAccess::getIfExists().
getBandwidth()
uint64_t veins::getBandwidth (Bandwidth bw) inline
returns the bandwidth in Hz
Definition at line 141 of file ConstsPhy.h.
 {
     switch (bw) {
     case Bandwidth::ofdm_5_mhz:
         return 5000000;
         break;
     case Bandwidth::ofdm_10_mhz:
         return 10000000;
         break;
     case Bandwidth::ofdm_20_mhz:
         return 20000000;
         break;
     default:
         ASSERT2(false, "Invalid datarate for required bandwidth");
         return -1;
     }
 }
References ofdm_10_mhz, ofdm_20_mhz, and ofdm_5_mhz.
getMCS()
MCS veins::getMCS (uint64_t datarate, Bandwidth bw) inline
returns encoding given datarate
Definition at line 160 of file ConstsPhy.h.
 {
     if (bw == Bandwidth::ofdm_10_mhz) {
         if (datarate == 3000000) {
             return MCS::ofdm_bpsk_r_1_2;
         }
         if (datarate == 4500000) {
             return MCS::ofdm_bpsk_r_3_4;
         }
         if (datarate == 6000000) {
             return MCS::ofdm_qpsk_r_1_2;
         }
         if (datarate == 9000000) {
             return MCS::ofdm_qpsk_r_3_4;
         }
         if (datarate == 12000000) {
             return MCS::ofdm_qam16_r_1_2;
         }
         if (datarate == 18000000) {
             return MCS::ofdm_qam16_r_3_4;
         }
         if (datarate == 24000000) {
             return MCS::ofdm_qam64_r_2_3;
         }
         if (datarate == 27000000) {
             return MCS::ofdm_qam64_r_3_4;
         }
     }
     if (bw == Bandwidth::ofdm_20_mhz) {
         if (datarate == 6000000) {
             return MCS::ofdm_bpsk_r_1_2;
         }
         if (datarate == 9000000) {
             return MCS::ofdm_bpsk_r_3_4;
         }
         if (datarate == 12000000) {
             return MCS::ofdm_qpsk_r_1_2;
         }
         if (datarate == 18000000) {
             return MCS::ofdm_qpsk_r_3_4;
         }
         if (datarate == 24000000) {
             return MCS::ofdm_qam16_r_1_2;
         }
         if (datarate == 36000000) {
             return MCS::ofdm_qam16_r_3_4;
         }
         if (datarate == 48000000) {
             return MCS::ofdm_qam64_r_2_3;
         }
         if (datarate == 54000000) {
             return MCS::ofdm_qam64_r_3_4;
         }
     }
     if (bw == Bandwidth::ofdm_5_mhz) {
         if (datarate == 1500000) {
             return MCS::ofdm_bpsk_r_1_2;
         }
         if (datarate == 2250000) {
             return MCS::ofdm_bpsk_r_3_4;
         }
         if (datarate == 3000000) {
             return MCS::ofdm_qpsk_r_1_2;
         }
         if (datarate == 4500000) {
             return MCS::ofdm_qpsk_r_3_4;
         }
         if (datarate == 6000000) {
             return MCS::ofdm_qam16_r_1_2;
         }
         if (datarate == 9000000) {
             return MCS::ofdm_qam16_r_3_4;
         }
         if (datarate == 12000000) {
             return MCS::ofdm_qam64_r_2_3;
         }
         if (datarate == 13500000) {
             return MCS::ofdm_qam64_r_3_4;
         }
     }
     ASSERT2(false, "Invalid datarate for required bandwidth");
     return MCS::undefined;
 }
References ofdm_10_mhz, ofdm_20_mhz, ofdm_5_mhz, ofdm_bpsk_r_1_2, ofdm_bpsk_r_3_4, ofdm_qam16_r_1_2, ofdm_qam16_r_3_4, ofdm_qam64_r_2_3, ofdm_qam64_r_3_4, ofdm_qpsk_r_1_2, ofdm_qpsk_r_3_4, and undefined.
Referenced by veins::NistErrorRate::getChunkSuccessRate(), and veins::Mac1609_4::setParametersForBitrate().
getNDBPS()
uint32_t veins::getNDBPS (MCS mcs) inline
returns the number of databits per ofdm symbol
Definition at line 105 of file ConstsPhy.h.
 {
     uint32_t ndbps;
     switch (mcs) {
     case MCS::ofdm_bpsk_r_1_2:
         ndbps = 24;
         break;
     case MCS::ofdm_bpsk_r_3_4:
         ndbps = 36;
         break;
     case MCS::ofdm_qpsk_r_1_2:
         ndbps = 48;
         break;
     case MCS::ofdm_qpsk_r_3_4:
         ndbps = 72;
         break;
     case MCS::ofdm_qam16_r_1_2:
         ndbps = 96;
         break;
     case MCS::ofdm_qam16_r_3_4:
         ndbps = 144;
         break;
     case MCS::ofdm_qam64_r_2_3:
         ndbps = 192;
         break;
     case MCS::ofdm_qam64_r_3_4:
         ndbps = 216;
         break;
     default:
         ndbps = 24;
         break;
     }
     return ndbps;
 }
References ofdm_bpsk_r_1_2, ofdm_bpsk_r_3_4, ofdm_qam16_r_1_2, ofdm_qam16_r_3_4, ofdm_qam64_r_2_3, ofdm_qam64_r_3_4, ofdm_qpsk_r_1_2, and ofdm_qpsk_r_3_4.
Referenced by veins::PhyLayer80211p::getFrameDuration().
getOfdmDatarate()
uint64_t veins::getOfdmDatarate (MCS mcs, Bandwidth bw) inline
Given bandwidth and MCS returns datarate in bits per second.
Definition at line 54 of file ConstsPhy.h.
 {
     // divide datarate by div, depending on bandwidth
     uint64_t div;
     // datarate to be returned
     uint64_t dr;
     switch (bw) {
     case Bandwidth::ofdm_5_mhz:
         div = 4;
         break;
     case Bandwidth::ofdm_10_mhz:
         div = 2;
         break;
     case Bandwidth::ofdm_20_mhz:
     default:
         div = 1;
         break;
     }
     switch (mcs) {
     case MCS::ofdm_bpsk_r_1_2:
         dr = 6000000;
         break;
     case MCS::ofdm_bpsk_r_3_4:
         dr = 9000000;
         break;
     case MCS::ofdm_qpsk_r_1_2:
         dr = 12000000;
         break;
     case MCS::ofdm_qpsk_r_3_4:
         dr = 18000000;
         break;
     case MCS::ofdm_qam16_r_1_2:
         dr = 24000000;
         break;
     case MCS::ofdm_qam16_r_3_4:
         dr = 36000000;
         break;
     case MCS::ofdm_qam64_r_2_3:
         dr = 48000000;
         break;
     case MCS::ofdm_qam64_r_3_4:
         dr = 54000000;
         break;
     default:
         dr = 6000000;
         break;
     }
     return (dr / div);
 }
References ofdm_10_mhz, ofdm_20_mhz, ofdm_5_mhz, ofdm_bpsk_r_1_2, ofdm_bpsk_r_3_4, ofdm_qam16_r_1_2, ofdm_qam16_r_3_4, ofdm_qam64_r_2_3, ofdm_qam64_r_3_4, ofdm_qpsk_r_1_2, and ofdm_qpsk_r_3_4.
Referenced by veins::Decider80211p::checkIfSignalOk().
getSubmodulesOfType()
template<class T > std::vector<T*> veins::getSubmodulesOfType (cModule * parentModule, bool recurse = false)
Return a vector containing pointers to all submodules of parentModule of type T.
Definition at line 155 of file FindModule.h.
 {
     std::vector<T*> result;
     for (cModule::SubmoduleIterator iter(parentModule); !iter.end(); iter++) {
         auto mm = dynamic_cast<T*>(*iter);
         if (mm != nullptr) result.push_back(mm);
         if (recurse) {
             for (auto m : getSubmodulesOfType<T>(*iter, recurse)) {
                 result.emplace_back(m);
             }
         }
     }
     return result;
 }
isBigEndian()
bool VEINS_API veins::isBigEndian ()
Definition at line 177 of file TraCIBuffer.cc.
 {
     short a = 0x0102;
     unsigned char* p_a = reinterpret_cast<unsigned char*>(&a);
     return (p_a[0] == 0x01);
 }
Referenced by veins::TraCIBuffer::read(), veins::TraCIBuffer::readBuffer(), and veins::TraCIBuffer::write().
make_unique()
template<typename T , typename ... Args> std::unique_ptr<T> veins::make_unique (Args &&... args)
User-defined implementation of std::make_unique.
Until Veins builds on C++14, this provides equivalent functionality.
Definition at line 80 of file veins.h.
 {
     return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
 }
makeTraCICommand()
std::string veins::makeTraCICommand (uint8_t commandId, const TraCIBuffer & buf)
returns byte-buffer containing a TraCI command with optional parameters
Definition at line 266 of file TraCIConnection.cc.
 {
     if (sizeof(uint8_t) + sizeof(uint8_t) + buf.str().length() > 0xFF) {
         uint32_t len = sizeof(uint8_t) + sizeof(uint32_t) + sizeof(uint8_t) + buf.str().length();
         return (TraCIBuffer() << static_cast<uint8_t>(0) << len << commandId).str() + buf.str();
     }
     uint8_t len = sizeof(uint8_t) + sizeof(uint8_t) + buf.str().length();
     return (TraCIBuffer() << len << commandId).str() + buf.str();
 }
References veins::TraCIBuffer::str().
Referenced by veins::TraCIScenarioManagerLaunchd::init_traci(), and veins::TraCIConnection::query().
nedf_veins_eval_by_version()
cNEDValue veins::nedf_veins_eval_by_version (cComponent * component, cNEDValue argv[], int argc)
Definition at line 54 of file NedFunctions.cc.
 {
     if (argc < 2) {
         throw cRuntimeError("veins_eval_by_version(): at least 2 arguments expected");
     }
     if (argv[0].getType() != cNEDValue::INT) {
         throw cRuntimeError("veins_eval_by_version(): int argument expected for argument %d", 0);
     }
     if (argv[1].getType() != cNEDValue::STRING) {
         throw cRuntimeError("veins_eval_by_version(): string argument expected for argument %d", 1);
     }
     int ver = (int) argv[0];
     int idx = 0;
     while (idx + 4 <= argc) {
         if (argv[idx + 2].getType() != cNEDValue::INT) {
             throw cRuntimeError("veins_eval_by_version(): int argument expected for argument %d", idx + 2);
         }
         if (argv[idx + 3].getType() != cNEDValue::STRING) {
             throw cRuntimeError("veins_eval_by_version(): string argument expected for argument %d", idx + 3);
         }
         int v = (int) argv[idx + 2];
         if (ver >= v) {
             idx = idx + 2;
         }
         else {
             break;
         }
     }
 #if OMNETPP_VERSION >= 0x600
     return opp_eval(argv[idx + 1].stringValue(), context);
 #elif OMNETPP_BUILDNUM >= 1020
     cExpression::Context context(component);
     return opp_eval(argv[idx + 1].stringValue(), &context);
 #else
     return opp_eval(argv[idx + 1].stringValue(), component);
 #endif
 }
References anonymous_namespace{NedFunctions.cc}::opp_eval().
nedf_veins_omnetpp_buildnum()
cNEDValue veins::nedf_veins_omnetpp_buildnum (cComponent * component, cNEDValue argv[], int argc)
Definition at line 104 of file NedFunctions.cc.
 {
 #if OMNETPP_BUILDNUM > 1525
     return (intval_t) OMNETPP_BUILDNUM;
 #else
     return (int) OMNETPP_BUILDNUM;
 #endif
 }
normalizeFrequencies()
Spectrum::Frequencies veins::normalizeFrequencies (Spectrum::Frequencies freqs)
Definition at line 29 of file Spectrum.cc.
 {
     // sort and deduplicate frequencies first
     std::sort(freqs.begin(), freqs.end());
     freqs.erase(std::unique(freqs.begin(), freqs.end()), freqs.end());
     return freqs;
 }
operator*() [1/3]
Signal VEINS_API veins::operator* (const Signal & lhs, const Signal & rhs)
Multiply two signals by each other.
The resulting signal's power level is the product of each individual signal's power levels.
Parameters
lhs the first signal
rhs the second signal
Definition at line 447 of file Signal.cc.
 {
     Signal result(lhs);
     result *= rhs;
     return result;
 }
operator*() [2/3]
Signal VEINS_API veins::operator* (const Signal & lhs, double rhs)
Multiply a signal's power levels by a constant.
Parameters
lhs the signal to multiply with
rhs power level to multiply by in milliwatt
Definition at line 454 of file Signal.cc.
 {
     Signal result(lhs);
     result *= rhs;
     return result;
 }
operator*() [3/3]
Signal VEINS_API veins::operator* (double lhs, const Signal & rhs)
Multiply a signal's power levels by a constant.
Parameters
lhs power level to multiply by in milliwatt
rhs the signal to multiply with
Definition at line 461 of file Signal.cc.
 {
     Signal result(rhs);
     result *= lhs;
     return result;
 }
operator+() [1/3]
Signal VEINS_API veins::operator+ (const Signal & lhs, const Signal & rhs)
Add two signals to each other.
The resulting signal's power level is the sum of each individual signal's power levels.
Parameters
lhs the first signal
rhs the second signal
Definition at line 407 of file Signal.cc.
 {
     Signal result(lhs);
     result += rhs;
     return result;
 }
operator+() [2/3]
Signal VEINS_API veins::operator+ (const Signal & lhs, double rhs)
Increment a signal's power levels by a constant.
Parameters
lhs the signal to add
rhs power level to add in milliwatt
Definition at line 414 of file Signal.cc.
 {
     Signal result(lhs);
     result += rhs;
     return result;
 }
operator+() [3/3]
Signal VEINS_API veins::operator+ (double lhs, const Signal & rhs)
Increment a signal's power levels by a constant.
Parameters
lhs power level to add in milliwatt
rhs the signal to add
Definition at line 421 of file Signal.cc.
 {
     Signal result(rhs);
     result += lhs;
     return result;
 }
operator-() [1/3]
Signal VEINS_API veins::operator- (const Signal & lhs, const Signal & rhs)
Substract two signals from each other.
The resulting signal's power level is the difference of each individual signal's power levels.
Parameters
lhs the first signal
rhs the second signal
Definition at line 428 of file Signal.cc.
 {
     Signal result(lhs);
     result -= rhs;
     return result;
 }
operator-() [2/3]
Signal VEINS_API veins::operator- (const Signal & lhs, double rhs)
Decrement a signal's power levels by a constant.
Parameters
lhs the signal to substract from
rhs power level to substract in milliwatt
Definition at line 435 of file Signal.cc.
 {
     Signal result(lhs);
     result -= rhs;
     return result;
 }
operator-() [3/3]
Signal VEINS_API veins::operator- (double lhs, const Signal & rhs)
Decrement a constant power level by a signal's power levels.
Parameters
lhs power level to substract from in milliwatt
rhs the signal to substract
Definition at line 442 of file Signal.cc.
 {
     return lhs + (-1 * rhs);
 }
operator/() [1/3]
Signal VEINS_API veins::operator/ (const Signal & lhs, const Signal & rhs)
Divide two signals by each other.
The resulting signal's power level is the division of each individual signal's power levels.
Parameters
lhs the first signal (dividend)
rhs the second signal (divisor)
Definition at line 468 of file Signal.cc.
 {
     Signal result(lhs);
     result /= rhs;
     return result;
 }
operator/() [2/3]
Signal VEINS_API veins::operator/ (const Signal & lhs, double rhs)
Divide a signal's power levels by a constant.
Parameters
lhs the dividend
rhs the constnat divisor in milliwatt
Definition at line 475 of file Signal.cc.
 {
     Signal result(lhs);
     result /= rhs;
     return result;
 }
operator/() [3/3]
Signal VEINS_API veins::operator/ (double lhs, const Signal & rhs)
Divide a a constant by a signal's power levels.
Parameters
rhs the constant dividend in milliwatt
lhs the divisor
Definition at line 482 of file Signal.cc.
 {
     // Create constant signal
     Signal sigLhs(rhs.getSpectrum());
     sigLhs = lhs;
     return sigLhs / rhs;
 }
References veins::Signal::getSpectrum().
operator<<() [1/4]
std::ostream& veins::operator<< (std::ostream & os, const Coord & coord) inline
Definition at line 332 of file Coord.h.
 {
     return os << "(" << coord.x << "," << coord.y << "," << coord.z << ")";
 }
References veins::Coord::x, veins::Coord::y, and veins::Coord::z.
operator<<() [2/4]
std::ostream& veins::operator<< (std::ostream & os, const Heading & o) inline
Definition at line 95 of file Heading.h.
 {
     return os << "(" << o.getRad() << " rad)";
 }
References veins::Heading::getRad().
operator<<() [3/4]
std::ostream& veins::operator<< (std::ostream & os, const Signal & s)
Parameters
os the outputstream to write to
s the signal to convert
Definition at line 490 of file Signal.cc.
 {
     os << "Signal(";
     if (s.timingUsed) {
         os << "interval: (" << s.getReceptionStart() << ", " << s.getReceptionEnd() << "), ";
     }
     os << s.spectrum << ", ";
     std::ostringstream ss;
     for (auto&& value : s.values) {
         if (ss.tellp() != 0) {
             ss << ", ";
         }
         ss << value;
     }
     os << ss.str();
     os << ")";
     return os;
 }
operator<<() [4/4]
std::ostream& veins::operator<< (std::ostream & os, const Spectrum & s)
Definition at line 73 of file Spectrum.cc.
 {
     os << "Spectrum(";
     std::ostringstream ss;
     for (auto&& frequency : s.frequencies) {
         if (ss.tellp() != 0) {
             ss << ", ";
         }
         ss << frequency;
     }
     os << ss.str();
     os << ")";
     return os;
 }
operator==()
bool veins::operator== (const Spectrum & lhs, const Spectrum & rhs)
Definition at line 68 of file Spectrum.cc.
 {
     return lhs.frequencies == rhs.frequencies;
 }
operator|()
template<typename T > EnumBitset<T> veins::operator| (T lhs, T rhs)
Definition at line 140 of file EnumBitset.h.
 {
     return EnumBitset<T>(lhs) | EnumBitset<T>(rhs);
 }
socket()
SOCKET veins::socket (void * ptr)
Definition at line 57 of file TraCIConnection.cc.
 {
     ASSERT(ptr);
     return *static_cast<SOCKET*>(ptr);
 }
Referenced by veins::TraCIConnection::connect(), veins::TraCIScenarioManagerForker::getPortNumber(), veins::TraCIConnection::receiveMessage(), veins::TraCIConnection::sendMessage(), and veins::TraCIConnection::~TraCIConnection().
Variable Documentation
BANDWIDTH_11P
const Bandwidth veins::BANDWIDTH_11P = Bandwidth::ofdm_10_mhz
Definition at line 134 of file Consts80211p.h.
Referenced by veins::Decider80211p::checkIfSignalOk(), and veins::Mac1609_4::setParametersForBitrate().
BITRATES_80211P
const uint64_t veins::BITRATES_80211P[] = {3000000, 4500000, 6000000, 9000000, 12000000, 18000000, 24000000, 27000000}
Definition at line 40 of file Consts80211p.h.
CWMAX_11P
const unsigned veins::CWMAX_11P = 1023
Contention Window maximal size.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 119 of file Consts80211p.h.
Referenced by veins::Mac1609_4::initialize().
CWMIN_11P
const unsigned veins::CWMIN_11P = 15
Contention Window minimal size.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 113 of file Consts80211p.h.
Referenced by veins::Mac1609_4::initialize().
EnumTraits
template<typename T > struct VEINS_API veins::EnumTraits
Definition at line 1 of file EnumBitset.h.
GUARD_INTERVAL_11P
const SimTime veins::GUARD_INTERVAL_11P = SimTime().setRaw(4000000000UL)
1609.4 slot length
as defined in Table H.1 in the IEEE 1609.4-2010 standard It is the sum of SyncTolerance and MaxChSwitchTime as defined in 6.2.5 in the IEEE 1609.4-2010 Standard
Definition at line 132 of file Consts80211p.h.
Referenced by veins::Mac1609_4::guardActive(), and veins::Mac1609_4::timeLeftTillGuardOver().
IEEE80211ChannelFrequencies
const std::map<Channel, double> veins::IEEE80211ChannelFrequencies
Initial value:
= {
    {Channel::crit_sol, 5.86e9},
    {Channel::sch1, 5.87e9},
    {Channel::sch2, 5.88e9},
    {Channel::cch, 5.89e9},
    {Channel::sch3, 5.90e9},
    {Channel::sch4, 5.91e9},
    {Channel::hpps, 5.92e9},
}
Maps channel identifier to the corresponding center frequency.
Note
Not all entries are defined.
Definition at line 154 of file Consts80211p.h.
Referenced by veins::PhyLayer80211p::attachSignal(), veins::PhyLayer80211p::changeListeningChannel(), veins::Mac1609_4::handleSelfMsg(), veins::PhyLayer80211p::initialize(), and veins::Mac1609_4::sendAck().
N_DBPS_80211P
const uint32_t veins::N_DBPS_80211P[] = {24, 36, 48, 72, 96, 144, 192, 216}
Number of Data Bits Per Symbol (N_NBPS) corresponding to bitrates in BITRATES_80211P.
as defined in Table 17-3 in the IEEE 802.11-2007 standard
Definition at line 46 of file Consts80211p.h.
NUM_BITRATES_80211P
const uint64_t veins::NUM_BITRATES_80211P = 8
Bit rates for 802.11p.
as defined in Table 17-14 MIB attribute default values/ranges in the IEEE 802.11-2007 standard
Definition at line 39 of file Consts80211p.h.
PHY_HDR_BITRATE
const uint64_t veins::PHY_HDR_BITRATE = 3000000
Bitrate of the PLCP Signal.
as defined in Table 17.4 Timing-related parameters in the IEEE 802.11-2007 standard 24 bits in 8e-6 seconds
Definition at line 89 of file Consts80211p.h.
PHY_HDR_PLCPSIGNAL_DURATION
const double veins::PHY_HDR_PLCPSIGNAL_DURATION = 8e-6
Duration of the PLCP Signal.
as defined in Table 17.4 Timing-related parameters in the IEEE 802.11-2007 standard
Definition at line 76 of file Consts80211p.h.
Referenced by veins::PhyLayer80211p::getFrameDuration().
PHY_HDR_PLCPSIGNAL_LENGTH
const int veins::PHY_HDR_PLCPSIGNAL_LENGTH = 24
Length of the PLCP Signal.
as defined in Figure 17.1 PPDU frame format in the IEEE 802.11-2007 standard
Definition at line 82 of file Consts80211p.h.
PHY_HDR_PREAMBLE_DURATION
const double veins::PHY_HDR_PREAMBLE_DURATION = 32e-6
Duration of the PLCP Preamble.
as defined in Table 17.4 Timing-related parameters in the IEEE 802.11-2007 standard
Definition at line 70 of file Consts80211p.h.
Referenced by veins::Decider80211p::checkIfSignalOk(), and veins::PhyLayer80211p::getFrameDuration().
PHY_HDR_SERVICE_LENGTH
const int veins::PHY_HDR_SERVICE_LENGTH = 16
Length (in bits) of SERVICE field in PHY HEADER.
as defined in 17.3.2 PLCP frame format in the IEEE 802.11-2007 standard
Definition at line 58 of file Consts80211p.h.
PHY_TAIL_LENGTH
const int veins::PHY_TAIL_LENGTH = 6
Length (in bits) of Tail field in PHY PPDU.
as defined in 17.3.2 PLCP frame format in the IEEE 802.11-2007 standard
Definition at line 64 of file Consts80211p.h.
RADIODELAY_11P
const SimTime veins::RADIODELAY_11P = SimTime().setRaw(1000000UL)
Time it takes to switch from Rx to Tx Mode.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 107 of file Consts80211p.h.
Referenced by veins::Mac1609_4::handleSelfMsg(), veins::Mac1609_4::sendAck(), and veins::Mac1609_4::sendFrame().
SIFS_11P
const SimTime veins::SIFS_11P = SimTime().setRaw(32000000UL)
Short interframe space.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 101 of file Consts80211p.h.
Referenced by veins::Mac1609_4::EDCA::initiateTransmit(), veins::Mac1609_4::sendAck(), veins::Mac1609_4::EDCA::startContent(), and veins::Mac1609_4::EDCA::stopContent().
SLOTLENGTH_11P
const SimTime veins::SLOTLENGTH_11P = SimTime().setRaw(13000000UL)
Slot Time for 10 MHz channel spacing.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 95 of file Consts80211p.h.
Referenced by veins::Mac1609_4::EDCA::initiateTransmit(), veins::Mac1609_4::EDCA::startContent(), and veins::Mac1609_4::EDCA::stopContent().
SWITCHING_INTERVAL_11P
const SimTime veins::SWITCHING_INTERVAL_11P = SimTime().setRaw(50000000000UL)
1609.4 slot length
as defined in Table H.1 in the IEEE 1609.4-2010 standard
Definition at line 125 of file Consts80211p.h.
Referenced by veins::Mac1609_4::getSwitchingInterval(), veins::Mac1609_4::handleSelfMsg(), and veins::Mac1609_4::initialize().
T_SYM_80211P
const double veins::T_SYM_80211P = 8e-6
Symbol interval.
as defined in Table 17-4 in the IEEE 802.11-2007 standard
Definition at line 52 of file Consts80211p.h.
Referenced by veins::PhyLayer80211p::getFrameDuration().