Veins: anonymous_namespace{BBoxLookup.cc} Namespace Reference
anonymous_namespace{BBoxLookup.cc} Namespace Reference
Classes
struct Ray
Helper structure representing a wireless ray from a sender to a receiver.
Typedefs
using Point = veins::BBoxLookup::Point
using Box = veins::BBoxLookup::Box
Functions
Ray makeRay (const Point &sender, const Point &receiver)
Return a Ray struct for fast intersection tests from sender to receiver.
bool intersects (const Ray &ray, const Box &box)
Return whether ray intersects with box.
Typedef Documentation
Box
using anonymous_namespace{BBoxLookup.cc}::Box = typedef veins::BBoxLookup::Box
Definition at line 30 of file BBoxLookup.cc.
Point
using anonymous_namespace{BBoxLookup.cc}::Point = typedef veins::BBoxLookup::Point
Definition at line 29 of file BBoxLookup.cc.
Function Documentation
intersects()
bool anonymous_namespace{BBoxLookup.cc}::intersects (const Ray & ray, const Box & box)
Return whether ray intersects with box.
Based on: Amy Williams, Steve Barrus, R. Keith Morley & Peter Shirley (2005) An Efficient and Robust Ray-Box Intersection Algorithm, Journal of Graphics Tools, 10:1, 49-54, DOI: 10.1080/2151237X.2005.10129188
Definition at line 74 of file BBoxLookup.cc.
 {
     const double x[2]{box.p1.x, box.p2.x};
     const double y[2]{box.p1.y, box.p2.y};
     double tmin = (x[ray.sign.x] - ray.origin.x) * ray.invDirection.x;
     double tmax = (x[1 - ray.sign.x] - ray.origin.x) * ray.invDirection.x;
     double tymin = (y[ray.sign.y] - ray.origin.y) * ray.invDirection.y;
     double tymax = (y[1 - ray.sign.y] - ray.origin.y) * ray.invDirection.y;
     if ((tmin > tymax) || (tymin > tmax)) return false;
     if (tymin > tmin) tmin = tymin;
     if (tymax < tmax) tmax = tymax;
     return (tmin < ray.length) && (tmax > 0);
 }
References anonymous_namespace{BBoxLookup.cc}::Ray::invDirection, anonymous_namespace{BBoxLookup.cc}::Ray::length, anonymous_namespace{BBoxLookup.cc}::Ray::origin, veins::BBoxLookup::Box::p1, veins::BBoxLookup::Box::p2, anonymous_namespace{BBoxLookup.cc}::Ray::sign, anonymous_namespace{BBoxLookup.cc}::Ray::x, veins::BBoxLookup::Point::x, anonymous_namespace{BBoxLookup.cc}::Ray::y, and veins::BBoxLookup::Point::y.
Referenced by veins::ChannelInfo::assertNoIntersections(), veins::Obstacle::containsPoint(), veins::BBoxLookup::findOverlapping(), and anonymous_namespace{MobileHostObstacle.cc}::isPointInObstacle().
makeRay()
Ray anonymous_namespace{BBoxLookup.cc}::makeRay (const Point & sender, const Point & receiver)
Return a Ray struct for fast intersection tests from sender to receiver.
Definition at line 52 of file BBoxLookup.cc.
 {
     const double dir_x = receiver.x - sender.x;
     const double dir_y = receiver.y - sender.y;
     Ray ray;
     ray.origin = sender;
     ray.destination = receiver;
     ray.length = std::sqrt(dir_x * dir_x + dir_y * dir_y);
     ray.direction.x = dir_x / ray.length;
     ray.direction.y = dir_y / ray.length;
     ray.invDirection.x = 1.0 / ray.direction.x;
     ray.invDirection.y = 1.0 / ray.direction.y;
     ray.sign.x = ray.invDirection.x < 0;
     ray.sign.y = ray.invDirection.y < 0;
     return ray;
 }
References anonymous_namespace{BBoxLookup.cc}::Ray::destination, anonymous_namespace{BBoxLookup.cc}::Ray::direction, anonymous_namespace{BBoxLookup.cc}::Ray::invDirection, anonymous_namespace{BBoxLookup.cc}::Ray::length, anonymous_namespace{BBoxLookup.cc}::Ray::origin, anonymous_namespace{BBoxLookup.cc}::Ray::sign, anonymous_namespace{BBoxLookup.cc}::Ray::x, veins::BBoxLookup::Point::x, anonymous_namespace{BBoxLookup.cc}::Ray::y, and veins::BBoxLookup::Point::y.
Referenced by veins::BBoxLookup::findOverlapping().